const wordsEN = [
    // --- 1. หมวดบุคคลและสรรพนาม (People & Pronouns) - 20 คำ ---
    { thai: "ฉัน / ผม", target: "I", reading: "ไอ", lang: "en-US" },
    { thai: "คุณ", target: "You", reading: "ยู", lang: "en-US" },
    { thai: "เขา (ผู้ชาย)", target: "He", reading: "ฮี", lang: "en-US" },
    { thai: "เธอ (ผู้หญิง)", target: "She", reading: "ชี", lang: "en-US" },
    { thai: "พวกเรา", target: "We", reading: "วี", lang: "en-US" },
    { thai: "พวกเขา", target: "They", reading: "เดย์", lang: "en-US" },
    { thai: "มัน", target: "It", reading: "อิท", lang: "en-US" },
    { thai: "ฉัน (กรรม)", target: "Me", reading: "มี", lang: "en-US" },
    { thai: "เขา (กรรม)", target: "Him", reading: "ฮิม", lang: "en-US" },
    { thai: "เธอ (กรรม)", target: "Her", reading: "เฮอร์", lang: "en-US" },
    { thai: "พวกเรา (กรรม)", target: "Us", reading: "อัส", lang: "en-US" },
    { thai: "พวกเขา (กรรม)", target: "Them", reading: "เดม", lang: "en-US" },
    { thai: "ผู้ชาย", target: "Man", reading: "แมน", lang: "en-US" },
    { thai: "ผู้หญิง", target: "Woman", reading: "วูแมน", lang: "en-US" },
    { thai: "เด็กผู้ชาย", target: "Boy", reading: "บอย", lang: "en-US" },
    { thai: "เด็กผู้หญิง", target: "Girl", reading: "เกิร์ล", lang: "en-US" },
    { thai: "เพื่อน", target: "Friend", reading: "เฟรนด์", lang: "en-US" },
    { thai: "ครอบครัว", target: "Family", reading: "แฟมิลี่", lang: "en-US" },
    { thai: "บุคคล (คนเดียว)", target: "Person", reading: "เพอร์ซัน", lang: "en-US" },
    { thai: "ผู้คน (หลายคน)", target: "People", reading: "พีเพิล", lang: "en-US" },

    // --- 2. หมวดร่างกาย (Body Parts) - 20 คำ ---
    { thai: "หัว", target: "Head", reading: "เฮด", lang: "en-US" },
    { thai: "ผม", target: "Hair", reading: "แฮร์", lang: "en-US" },
    { thai: "ตา", target: "Eye", reading: "อาย", lang: "en-US" },
    { thai: "หู", target: "Ear", reading: "เอียร์", lang: "en-US" },
    { thai: "จมูก", target: "Nose", reading: "โนส", lang: "en-US" },
    { thai: "ปาก", target: "Mouth", reading: "เมาท์", lang: "en-US" },
    { thai: "ฟัน", target: "Tooth", reading: "ทูธ", lang: "en-US" },
    { thai: "ใบหน้า", target: "Face", reading: "เฟซ", lang: "en-US" },
    { thai: "คอ", target: "Neck", reading: "เน็ค", lang: "en-US" },
    { thai: "ไหล่", target: "Shoulder", reading: "โชวเดอร์", lang: "en-US" },
    { thai: "แขน", target: "Arm", reading: "อาร์ม", lang: "en-US" },
    { thai: "มือ", target: "Hand", reading: "แฮนด์", lang: "en-US" },
    { thai: "นิ้วมือ", target: "Finger", reading: "ฟิงเกอร์", lang: "en-US" },
    { thai: "ขา", target: "Leg", reading: "เลก", lang: "en-US" },
    { thai: "เท้า", target: "Foot", reading: "ฟุต", lang: "en-US" },
    { thai: "นิ้วเท้า", target: "Toe", reading: "โท", lang: "en-US" },
    { thai: "หลัง", target: "Back", reading: "แบ็ก", lang: "en-US" },
    { thai: "หัวใจ", target: "Heart", reading: "ฮาร์ท", lang: "en-US" },
    { thai: "เลือด", target: "Blood", reading: "บลัด", lang: "en-US" },
    { thai: "กระดูก", target: "Bone", reading: "โบน", lang: "en-US" },

    // --- 3. หมวดครอบครัวและญาติ (Family & Relatives) - 15 คำ ---
    { thai: "พ่อ", target: "Father", reading: "ฟาเธอร์", lang: "en-US" },
    { thai: "แม่", target: "Mother", reading: "มาเธอร์", lang: "en-US" },
    { thai: "ผู้ปกครอง / พ่อแม่", target: "Parent", reading: "พาเรนท์", lang: "en-US" },
    { thai: "ลูกชาย", target: "Son", reading: "ซัน", lang: "en-US" },
    { thai: "ลูกสาว", target: "Daughter", reading: "ดอเทอร์", lang: "en-US" },
    { thai: "พี่ชาย / น้องชาย", target: "Brother", reading: "บราเธอร์", lang: "en-US" },
    { thai: "พี่สาว / น้องสาว", target: "Sister", reading: "ซิสเตอร์", lang: "en-US" },
    { thai: "ปู่ / ตา", target: "Grandfather", reading: "แกรนด์ฟาเธอร์", lang: "en-US" },
    { thai: "ย่า / ยาย", target: "Grandmother", reading: "แกรนด์มาเธอร์", lang: "en-US" },
    { thai: "ลุง / น้าชาย / อาชาย", target: "Uncle", reading: "อังเคิล", lang: "en-US" },
    { thai: "ป้า / น้าหญิง / อาหญิง", target: "Aunt", reading: "อ้านท์", lang: "en-US" },
    { thai: "ลูกพี่ลูกน้อง", target: "Cousin", reading: "คัสซิน", lang: "en-US" },
    { thai: "สามี", target: "Husband", reading: "ฮัสแบนด์", lang: "en-US" },
    { thai: "ภรรยา", target: "Wife", reading: "ไวฟ์", lang: "en-US" },
    { thai: "เด็ก / ลูก", target: "Child", reading: "ไชลด์", lang: "en-US" },

    // --- 4. หมวดเวลา (Time & Calendar) - 20 คำ ---
    { thai: "วินาที", target: "Second", reading: "เซคคันด์", lang: "en-US" },
    { thai: "นาที", target: "Minute", reading: "มินิท", lang: "en-US" },
    { thai: "ชั่วโมง", target: "Hour", reading: "อาวร์", lang: "en-US" },
    { thai: "วัน", target: "Day", reading: "เดย์", lang: "en-US" },
    { thai: "สัปดาห์", target: "Week", reading: "วีค", lang: "en-US" },
    { thai: "เดือน", target: "Month", reading: "มันธ์", lang: "en-US" },
    { thai: "ปี", target: "Year", reading: "เยียร์", lang: "en-US" },
    { thai: "ตอนเช้า", target: "Morning", reading: "มอร์นิ่ง", lang: "en-US" },
    { thai: "ตอนบ่าย", target: "Afternoon", reading: "อาฟเตอร์นูน", lang: "en-US" },
    { thai: "ตอนเย็น / ค่ำ", target: "Evening", reading: "อีฟเวนนิ่ง", lang: "en-US" },
    { thai: "ตอนกลางคืน", target: "Night", reading: "ไนท์", lang: "en-US" },
    { thai: "วันนี้", target: "Today", reading: "ทูเดย์", lang: "en-US" },
    { thai: "พรุ่งนี้", target: "Tomorrow", reading: "ทูมอร์โรว์", lang: "en-US" },
    { thai: "เมื่อวานนี้", target: "Yesterday", reading: "เยสเทอร์เดย์", lang: "en-US" },
    { thai: "ตอนนี้ / ปัจจุบัน", target: "Now", reading: "นาว", lang: "en-US" },
    { thai: "ตอนนั้น / หลังจากนั้น", target: "Then", reading: "เดน", lang: "en-US" },
    { thai: "อนาคต", target: "Future", reading: "ฟิวเจอร์", lang: "en-US" },
    { thai: "อดีต", target: "Past", reading: "พาสท์", lang: "en-US" },
    { thai: "ปัจจุบัน / ของขวัญ", target: "Present", reading: "พรีเซนต์", lang: "en-US" },
    { thai: "เวลา", target: "Time", reading: "ไทม์", lang: "en-US" },

    // --- 5. หมวดธรรมชาติและสิ่งแวดล้อม (Nature & Environment) - 25 คำ ---
    { thai: "ดวงอาทิตย์", target: "Sun", reading: "ซัน", lang: "en-US" },
    { thai: "ดวงจันทร์", target: "Moon", reading: "มูน", lang: "en-US" },
    { thai: "ดาว", target: "Star", reading: "สตาร์", lang: "en-US" },
    { thai: "ท้องฟ้า", target: "Sky", reading: "สกาย", lang: "en-US" },
    { thai: "เมฆ", target: "Cloud", reading: "คลาวด์", lang: "en-US" },
    { thai: "ฝน", target: "Rain", reading: "เรน", lang: "en-US" },
    { thai: "ลม", target: "Wind", reading: "วินด์", lang: "en-US" },
    { thai: "หิมะ", target: "Snow", reading: "สโนว์", lang: "en-US" },
    { thai: "ไฟ", target: "Fire", reading: "ไฟร์", lang: "en-US" },
    { thai: "น้ำ", target: "Water", reading: "วอเทอร์", lang: "en-US" },
    { thai: "โลก (ดาวเคราะห์) / ดิน", target: "Earth", reading: "เอิร์ธ", lang: "en-US" },
    { thai: "โลก (รวมทั้งหมด)", target: "World", reading: "เวิลด์", lang: "en-US" },
    { thai: "ต้นไม้", target: "Tree", reading: "ทรี", lang: "en-US" },
    { thai: "ดอกไม้", target: "Flower", reading: "ฟลาวเวอร์", lang: "en-US" },
    { thai: "หญ้า", target: "Grass", reading: "กราส", lang: "en-US" },
    { thai: "สัตว์", target: "Animal", reading: "แอนิมอล", lang: "en-US" },
    { thai: "นก", target: "Bird", reading: "เบิร์ด", lang: "en-US" },
    { thai: "ปลา", target: "Fish", reading: "ฟิช", lang: "en-US" },
    { thai: "สุนัข", target: "Dog", reading: "ด็อก", lang: "en-US" },
    { thai: "แมว", target: "Cat", reading: "แคท", lang: "en-US" },
    { thai: "ภูเขา", target: "Mountain", reading: "เมาน์เทน", lang: "en-US" },
    { thai: "แม่น้ำ", target: "River", reading: "ริเวอร์", lang: "en-US" },
    { thai: "ทะเล", target: "Sea", reading: "ซี", lang: "en-US" },
    { thai: "หิน", target: "Rock", reading: "ร็อก", lang: "en-US" },
    { thai: "ทราย", target: "Sand", reading: "แซนด์", lang: "en-US" },
	// --- 6. หมวดกริยาและการกระทำ (Common Action Verbs) - 35 คำ ---
    { thai: "กิน", target: "Eat", reading: "อีท", lang: "en-US" },
    { thai: "ดื่ม", target: "Drink", reading: "ดริงก์", lang: "en-US" },
    { thai: "นอน", target: "Sleep", reading: "สลีพ", lang: "en-US" },
    { thai: "วิ่ง", target: "Run", reading: "รัน", lang: "en-US" },
    { thai: "เดิน", target: "Walk", reading: "วอล์ก", lang: "en-US" },
    { thai: "กระโดด", target: "Jump", reading: "จัมพ์", lang: "en-US" },
    { thai: "อ่าน", target: "Read", reading: "รีด", lang: "en-US" },
    { thai: "เขียน", target: "Write", reading: "ไรท์", lang: "en-US" },
    { thai: "ฟัง", target: "Listen", reading: "ลิสเซิน", lang: "en-US" },
    { thai: "พูด", target: "Speak", reading: "สปีค", lang: "en-US" },
    { thai: "ดู / มอง", target: "Look", reading: "ลุค", lang: "en-US" },
    { thai: "คิด", target: "Think", reading: "ธิงก์", lang: "en-US" },
    { thai: "ทำงาน", target: "Work", reading: "เวิร์ก", lang: "en-US" },
    { thai: "เรียน", target: "Learn", reading: "เลิร์น", lang: "en-US" },
    { thai: "สอน", target: "Teach", reading: "ทีช", lang: "en-US" },
    { thai: "ซื้อ", target: "Buy", reading: "บาย", lang: "en-US" },
    { thai: "ขาย", target: "Sell", reading: "เซลล์", lang: "en-US" },
    { thai: "ทำ / สร้าง", target: "Make", reading: "เมค", lang: "en-US" },
    { thai: "ให้", target: "Give", reading: "กิฟ", lang: "en-US" },
    { thai: "รับ", target: "Receive", reading: "รีซีฟ", lang: "en-US" },
    { thai: "ถือ / จับ", target: "Hold", reading: "โฮลด์", lang: "en-US" },
    { thai: "เปิด", target: "Open", reading: "โอเพิน", lang: "en-US" },
    { thai: "ปิด", target: "Close", reading: "โคลส", lang: "en-US" },
    { thai: "ขับรถ", target: "Drive", reading: "ไดรฟ์", lang: "en-US" },
    { thai: "ขี่ / ปั่น", target: "Ride", reading: "ไรด์", lang: "en-US" },
    { thai: "ว่ายน้ำ", target: "Swim", reading: "สวิม", lang: "en-US" },
    { thai: "บิน", target: "Fly", reading: "ฟลาย", lang: "en-US" },
    { thai: "หัวเราะ", target: "Laugh", reading: "ลาฟ", lang: "en-US" },
    { thai: "ร้องไห้", target: "Cry", reading: "คราย", lang: "en-US" },
    { thai: "ยิ้ม", target: "Smile", reading: "สไมล์", lang: "en-US" },
    { thai: "รอ", target: "Wait", reading: "เวท", lang: "en-US" },
    { thai: "หยุด", target: "Stop", reading: "สต็อป", lang: "en-US" },
    { thai: "ช่วย", target: "Help", reading: "เฮลพ์", lang: "en-US" },
    { thai: "เล่น", target: "Play", reading: "เพลย์", lang: "en-US" },
    { thai: "ร้องเพลง", target: "Sing", reading: "ซิง", lang: "en-US" },

    // --- 7. หมวดสีสัน (Colors) - 15 คำ ---
    { thai: "สีแดง", target: "Red", reading: "เรด", lang: "en-US" },
    { thai: "สีน้ำเงิน", target: "Blue", reading: "บลู", lang: "en-US" },
    { thai: "สีเขียว", target: "Green", reading: "กรีน", lang: "en-US" },
    { thai: "สีเหลือง", target: "Yellow", reading: "เยลโล่", lang: "en-US" },
    { thai: "สีดำ", target: "Black", reading: "แบล็ก", lang: "en-US" },
    { thai: "สีขาว", target: "White", reading: "ไวท์", lang: "en-US" },
    { thai: "สีส้ม", target: "Orange", reading: "ออเรนจ์", lang: "en-US" },
    { thai: "สีชมพู", target: "Pink", reading: "พิงก์", lang: "en-US" },
    { thai: "สีม่วง", target: "Purple", reading: "เพอร์เพิล", lang: "en-US" },
    { thai: "สีน้ำตาล", target: "Brown", reading: "บราวน์", lang: "en-US" },
    { thai: "สีเทา", target: "Gray", reading: "เกรย์", lang: "en-US" },
    { thai: "สีทอง", target: "Gold", reading: "โกลด์", lang: "en-US" },
    { thai: "สีเงิน", target: "Silver", reading: "ซิลเวอร์", lang: "en-US" },
    { thai: "สีสัน", target: "Color", reading: "คัลเลอร์", lang: "en-US" },
    { thai: "สว่าง", target: "Bright", reading: "ไบรท์", lang: "en-US" },

    // --- 8. หมวดสิ่งของรอบตัวและในบ้าน (House & Objects) - 30 คำ ---
    { thai: "บ้าน", target: "House", reading: "เฮาส์", lang: "en-US" },
    { thai: "ห้อง", target: "Room", reading: "รูม", lang: "en-US" },
    { thai: "ประตู", target: "Door", reading: "ดอร์", lang: "en-US" },
    { thai: "หน้าต่าง", target: "Window", reading: "วินโดว์", lang: "en-US" },
    { thai: "โต๊ะ", target: "Table", reading: "เทเบิล", lang: "en-US" },
    { thai: "เก้าอี้", target: "Chair", reading: "แชร์", lang: "en-US" },
    { thai: "เตียง", target: "Bed", reading: "เบด", lang: "en-US" },
    { thai: "หมอน", target: "Pillow", reading: "พิลโล่", lang: "en-US" },
    { thai: "ผ้าห่ม", target: "Blanket", reading: "แบล็งเก็ต", lang: "en-US" },
    { thai: "โทรศัพท์", target: "Phone", reading: "โฟน", lang: "en-US" },
    { thai: "คอมพิวเตอร์", target: "Computer", reading: "คอมพิวเตอร์", lang: "en-US" },
    { thai: "หนังสือ", target: "Book", reading: "บุ๊ก", lang: "en-US" },
    { thai: "ปากกา", target: "Pen", reading: "เพน", lang: "en-US" },
    { thai: "กระดาษ", target: "Paper", reading: "เพเพอร์", lang: "en-US" },
    { thai: "กระเป๋า", target: "Bag", reading: "แบ็ก", lang: "en-US" },
    { thai: "กุญแจ", target: "Key", reading: "คี", lang: "en-US" },
    { thai: "เงิน", target: "Money", reading: "มันนี่", lang: "en-US" },
    { thai: "แก้วน้ำ", target: "Glass", reading: "กลาส", lang: "en-US" },
    { thai: "จาน", target: "Plate", reading: "เพลท", lang: "en-US" },
    { thai: "ช้อน", target: "Spoon", reading: "สพูน", lang: "en-US" },
    { thai: "ส้อม", target: "Fork", reading: "ฟอร์ก", lang: "en-US" },
    { thai: "รถยนต์", target: "Car", reading: "คาร์", lang: "en-US" },
    { thai: "จักรยาน", target: "Bicycle", reading: "ไบซิเคิล", lang: "en-US" },
    { thai: "นาฬิกา", target: "Watch", reading: "วอทช์", lang: "en-US" },
    { thai: "เสื้อผ้า", target: "Clothes", reading: "โคลธส์", lang: "en-US" },
    { thai: "รองเท้า", target: "Shoes", reading: "ชูส์", lang: "en-US" },
    { thai: "แว่นตา", target: "Glasses", reading: "กลาสเซส", lang: "en-US" },
    { thai: "ไฟ / หลอดไฟ", target: "Light", reading: "ไลท์", lang: "en-US" },
    { thai: "พัดลม", target: "Fan", reading: "แฟน", lang: "en-US" },
    { thai: "กล่อง", target: "Box", reading: "บ็อกซ์", lang: "en-US" },

    // --- 9. หมวดอาหารและเครื่องดื่ม (Food & Drink) - 20 คำ ---
    { thai: "ข้าว", target: "Rice", reading: "ไรซ์", lang: "en-US" },
    { thai: "ขนมปัง", target: "Bread", reading: "เบรด", lang: "en-US" },
    { thai: "เนื้อสัตว์", target: "Meat", reading: "มีท", lang: "en-US" },
    { thai: "ไก่", target: "Chicken", reading: "ชิกเก็น", lang: "en-US" },
    { thai: "ไข่", target: "Egg", reading: "เอ็ก", lang: "en-US" },
    { thai: "ผัก", target: "Vegetable", reading: "เว็จทะเบิล", lang: "en-US" },
    { thai: "ผลไม้", target: "Fruit", reading: "ฟรุต", lang: "en-US" },
    { thai: "นม", target: "Milk", reading: "มิลค์", lang: "en-US" },
    { thai: "น้ำเปล่า", target: "Water", reading: "วอเทอร์", lang: "en-US" },
    { thai: "กาแฟ", target: "Coffee", reading: "คอฟฟี่", lang: "en-US" },
    { thai: "ชา", target: "Tea", reading: "ที", lang: "en-US" },
    { thai: "น้ำตาล", target: "Sugar", reading: "ชูการ์", lang: "en-US" },
    { thai: "เกลือ", target: "Salt", reading: "ซอลท์", lang: "en-US" },
    { thai: "เผ็ด", target: "Spicy", reading: "สไปซี่", lang: "en-US" },
    { thai: "หวาน", target: "Sweet", reading: "สวีท", lang: "en-US" },
    { thai: "เปรี้ยว", target: "Sour", reading: "เซาว์เออร์", lang: "en-US" },
    { thai: "เค็ม", target: "Salty", reading: "ซอลตี้", lang: "en-US" },
    { thai: "ขม", target: "Bitter", reading: "บิทเทอร์", lang: "en-US" },
    { thai: "ร้อน", target: "Hot", reading: "ฮอท", lang: "en-US" },
    { thai: "เย็น", target: "Cold", reading: "โคลด์", lang: "en-US" },
	// --- 10. หมวดสถานที่และอาคาร (Places & Buildings) - 30 คำ ---
    { thai: "โรงเรียน", target: "School", reading: "สคูล", lang: "en-US" },
    { thai: "โรงพยาบาล", target: "Hospital", reading: "ฮอสปิตัล", lang: "en-US" },
    { thai: "ธนาคาร", target: "Bank", reading: "แบงก์", lang: "en-US" },
    { thai: "ร้านอาหาร", target: "Restaurant", reading: "เรสเตอรองต์", lang: "en-US" },
    { thai: "โรงแรม", target: "Hotel", reading: "โฮเทล", lang: "en-US" },
    { thai: "ตลาด", target: "Market", reading: "มาร์เก็ต", lang: "en-US" },
    { thai: "สำนักงาน / ออฟฟิศ", target: "Office", reading: "ออฟฟิศ", lang: "en-US" },
    { thai: "ร้านค้า", target: "Shop", reading: "ช็อป", lang: "en-US" },
    { thai: "ห้างสรรพสินค้า", target: "Mall", reading: "มอลล์", lang: "en-US" },
    { thai: "สนามบิน", target: "Airport", reading: "แอร์พอร์ต", lang: "en-US" },
    { thai: "สถานี", target: "Station", reading: "สเตชั่น", lang: "en-US" },
    { thai: "สวนสาธารณะ", target: "Park", reading: "พาร์ค", lang: "en-US" },
    { thai: "ห้องสมุด", target: "Library", reading: "ไลบรารี", lang: "en-US" },
    { thai: "วัด", target: "Temple", reading: "เทมเพิล", lang: "en-US" },
    { thai: "เมือง", target: "City", reading: "ซิตี้", lang: "en-US" },
    { thai: "หมู่บ้าน", target: "Village", reading: "วิลเลจ", lang: "en-US" },
    { thai: "ประเทศ", target: "Country", reading: "คันทรี", lang: "en-US" },
    { thai: "ถนน", target: "Road", reading: "โร้ด", lang: "en-US" },
    { thai: "ทางแยก", target: "Intersection", reading: "อินเตอร์เซคชัน", lang: "en-US" },
    { thai: "สะพาน", target: "Bridge", reading: "บริดจ์", lang: "en-US" },
    { thai: "ฟาร์ม", target: "Farm", reading: "ฟาร์ม", lang: "en-US" },
    { thai: "โรงงาน", target: "Factory", reading: "แฟคทอรี", lang: "en-US" },
    { thai: "สวน", target: "Garden", reading: "การ์เดน", lang: "en-US" },
    { thai: "ห้องน้ำ", target: "Restroom", reading: "เรสท์รูม", lang: "en-US" },
    { thai: "ห้องครัว", target: "Kitchen", reading: "คิทเช่น", lang: "en-US" },
    { thai: "ห้องนอน", target: "Bedroom", reading: "เบดรูม", lang: "en-US" },
    { thai: "ชั้นบน", target: "Upstairs", reading: "อัพสแตร์ส", lang: "en-US" },
    { thai: "ชั้นล่าง", target: "Downstairs", reading: "ดาวน์สแตร์ส", lang: "en-US" },
    { thai: "มุม", target: "Corner", reading: "คอร์เนอร์", lang: "en-US" },
    { thai: "ใจกลางเมือง", target: "Downtown", reading: "ดาวน์ทาวน์", lang: "en-US" },

    // --- 11. หมวดการเดินทางและยานพาหนะ (Travel & Vehicles) - 20 คำ ---
    { thai: "เครื่องบิน", target: "Airplane", reading: "แอร์เพลน", lang: "en-US" },
    { thai: "เรือ", target: "Boat", reading: "โบท", lang: "en-US" },
    { thai: "รถไฟ", target: "Train", reading: "เทรน", lang: "en-US" },
    { thai: "รถเมล์ / รถบัส", target: "Bus", reading: "บัส", lang: "en-US" },
    { thai: "มอเตอร์ไซค์", target: "Motorcycle", reading: "มอเตอร์ไซเคิล", lang: "en-US" },
    { thai: "ตั๋ว", target: "Ticket", reading: "ทิคเก็ต", lang: "en-US" },
    { thai: "แผนที่", target: "Map", reading: "แมพ", lang: "en-US" },
    { thai: "สัมภาระ / กระเป๋าเดินทาง", target: "Luggage", reading: "ลักเกจ", lang: "en-US" },
    { thai: "พาสปอร์ต", target: "Passport", reading: "พาสปอร์ต", lang: "en-US" },
    { thai: "เที่ยวบิน", target: "Flight", reading: "ไฟลท์", lang: "en-US" },
    { thai: "โรงแรม", target: "Hotel", reading: "โฮเทล", lang: "en-US" },
    { thai: "ท่องเที่ยว", target: "Tourism", reading: "ทัวริซึม", lang: "en-US" },
    { thai: "ทิศทาง", target: "Direction", reading: "ไดเรคชัน", lang: "en-US" },
    { thai: "ทางเหนือ", target: "North", reading: "นอร์ธ", lang: "en-US" },
    { thai: "ทางใต้", target: "South", reading: "เซาท์", lang: "en-US" },
    { thai: "ทางตะวันออก", target: "East", reading: "อีสต์", lang: "en-US" },
    { thai: "ทางตะวันตก", target: "West", reading: "เวสต์", lang: "en-US" },
    { thai: "ตรงไป", target: "Straight", reading: "สเตรท", lang: "en-US" },
    { thai: "เลี้ยว", target: "Turn", reading: "เทิร์น", lang: "en-US" },
    { thai: "มาถึง", target: "Arrive", reading: "อะไรฟ์", lang: "en-US" },

    // --- 12. หมวดคำคุณศัพท์พื้นฐาน (Basic Adjectives) - 50 คำ ---
    { thai: "ใหญ่", target: "Big", reading: "บิ๊ก", lang: "en-US" },
    { thai: "เล็ก", target: "Small", reading: "สมอลล์", lang: "en-US" },
    { thai: "สูง", target: "High", reading: "ไฮ", lang: "en-US" },
    { thai: "ต่ำ", target: "Low", reading: "โลว์", lang: "en-US" },
    { thai: "ยาว", target: "Long", reading: "ลอง", lang: "en-US" },
    { thai: "สั้น", target: "Short", reading: "ชอร์ต", lang: "en-US" },
    { thai: "กว้าง", target: "Wide", reading: "ไวด์", lang: "en-US" },
    { thai: "แคบ", target: "Narrow", reading: "แนร์โรว์", lang: "en-US" },
    { thai: "หนา", target: "Thick", reading: "ธิค", lang: "en-US" },
    { thai: "บาง", target: "Thin", reading: "ธิน", lang: "en-US" },
    { thai: "หนัก", target: "Heavy", reading: "เฮฟวี", lang: "en-US" },
    { thai: "เบา", target: "Light", reading: "ไลท์", lang: "en-US" },
    { thai: "ยาก", target: "Hard", reading: "ฮาร์ด", lang: "en-US" },
    { thai: "ง่าย", target: "Easy", reading: "อีซี", lang: "en-US" },
    { thai: "ดี", target: "Good", reading: "กู๊ด", lang: "en-US" },
    { thai: "แย่", target: "Bad", reading: "แบด", lang: "en-US" },
    { thai: "สวย", target: "Beautiful", reading: "บิวติฟูล", lang: "en-US" },
    { thai: "น่าเกลียด", target: "Ugly", reading: "อัคลี", lang: "en-US" },
    { thai: "ร้อน", target: "Hot", reading: "ฮอท", lang: "en-US" },
    { thai: "หนาว", target: "Cold", reading: "โคลด์", lang: "en-US" },
    { thai: "เร็ว", target: "Fast", reading: "ฟาสต์", lang: "en-US" },
    { thai: "ช้า", target: "Slow", reading: "สโลว์", lang: "en-US" },
    { thai: "ใหม่", target: "New", reading: "นิว", lang: "en-US" },
    { thai: "เก่า / แก่", target: "Old", reading: "โอลด์", lang: "en-US" },
    { thai: "แพง", target: "Expensive", reading: "เอ็กซ์เพนซีฟ", lang: "en-US" },
    { thai: "ถูก", target: "Cheap", reading: "ชีป", lang: "en-US" },
    { thai: "รวย", target: "Rich", reading: "ริช", lang: "en-US" },
    { thai: "จน", target: "Poor", reading: "พัวร์", lang: "en-US" },
    { thai: "สะอาด", target: "Clean", reading: "คลีน", lang: "en-US" },
    { thai: "สกปรก", target: "Dirty", reading: "เดอร์ตี", lang: "en-US" },
    { thai: "เต็ม", target: "Full", reading: "ฟูล", lang: "en-US" },
    { thai: "ว่างเปล่า", target: "Empty", reading: "เอ็มพ์ตี", lang: "en-US" },
    { thai: "ดัง", target: "Loud", reading: "ลาวด์", lang: "en-US" },
    { thai: "เงียบ", target: "Quiet", reading: "ไควเอท", lang: "en-US" },
    { thai: "มีความสุข", target: "Happy", reading: "แฮปปี", lang: "en-US" },
    { thai: "เศร้า", target: "Sad", reading: "แซด", lang: "en-US" },
    { thai: "โกรธ", target: "Angry", reading: "แองกรี", lang: "en-US" },
    { thai: "หิว", target: "Hungry", reading: "ฮังกรี", lang: "en-US" },
    { thai: "กระหายน้ำ", target: "Thirsty", reading: "เธิร์สที", lang: "en-US" },
    { thai: "เหนื่อย", target: "Tired", reading: "ไทร์ด", lang: "en-US" },
    { thai: "ป่วย", target: "Sick", reading: "ซิค", lang: "en-US" },
    { thai: "แข็งแรง", target: "Strong", reading: "สตรอง", lang: "en-US" },
    { thai: "อ่อนแอ", target: "Weak", reading: "วีค", lang: "en-US" },
    { thai: "ฉลาด", target: "Smart", reading: "สมาร์ท", lang: "en-US" },
    { thai: "โง่", target: "Stupid", reading: "สตูพิด", lang: "en-US" },
    { thai: "ปลอดภัย", target: "Safe", reading: "เซฟ", lang: "en-US" },
    { thai: "อันตราย", target: "Dangerous", reading: "เดนเจอรัส", lang: "en-US" },
    { thai: "น่าสนใจ", target: "Interesting", reading: "อินเทอเรสติ้ง", lang: "en-US" },
    { thai: "น่าเบื่อ", target: "Boring", reading: "บอริ่ง", lang: "en-US" },
    { thai: "สำคัญ", target: "Important", reading: "อิมพอร์แทนท์", lang: "en-US" },
	// --- 13. หมวดอาชีพ (Occupations) - 25 คำ ---
    { thai: "พนักงาน", target: "Employee", reading: "เอ็มพลอยยี", lang: "en-US" },
    { thai: "นายจ้าง / หัวหน้า", target: "Boss", reading: "บอส", lang: "en-US" },
    { thai: "ผู้จัดการ", target: "Manager", reading: "แมนเนเจอร์", lang: "en-US" },
    { thai: "พนักงานขาย", target: "Salesman", reading: "เซลส์แมน", lang: "en-US" },
    { thai: "วิศวกร", target: "Engineer", reading: "เอนจินเนียร์", lang: "en-US" },
    { thai: "หมอ", target: "Doctor", reading: "ด็อกเตอร์", lang: "en-US" },
    { thai: "พยาบาล", target: "Nurse", reading: "เนิร์ส", lang: "en-US" },
    { thai: "ครู", target: "Teacher", reading: "ทีเชอร์", lang: "en-US" },
    { thai: "ตำรวจ", target: "Police", reading: "พะลิส", lang: "en-US" },
    { thai: "ทหาร", target: "Soldier", reading: "โซลเจอร์", lang: "en-US" },
    { thai: "นักบิน", target: "Pilot", reading: "ไพล็อต", lang: "en-US" },
    { thai: "พ่อครัว", target: "Chef", reading: "เชฟ", lang: "en-US" },
    { thai: "พนักงานเสิร์ฟ", target: "Waiter", reading: "เวทเทอร์", lang: "en-US" },
    { thai: "คนขับรถ", target: "Driver", reading: "ไดรเวอร์", lang: "en-US" },
    { thai: "นักเขียน", target: "Writer", reading: "ไรท์เตอร์", lang: "en-US" },
    { thai: "ศิลปิน", target: "Artist", reading: "อาร์ทิสต์", lang: "en-US" },
    { thai: "นักธุรกิจ", target: "Businessman", reading: "บิสเนสแมน", lang: "en-US" },
    { thai: "เลขานุการ", target: "Secretary", reading: "เซคระเทรี", lang: "en-US" },
    { thai: "ช่างภาพ", target: "Photographer", reading: "ฟะทอกระเฟอร์", lang: "en-US" },
    { thai: "นักออกแบบ", target: "Designer", reading: "ดีไซน์เนอร์", lang: "en-US" },
    { thai: "ชาวนา / เกษตรกร", target: "Farmer", reading: "ฟาร์มเมอร์", lang: "en-US" },
    { thai: "นักแสดง", target: "Actor", reading: "แอคเทอร์", lang: "en-US" },
    { thai: "นักดนตรี", target: "Musician", reading: "มิวสิเชียน", lang: "en-US" },
    { thai: "อาชีพ", target: "Career", reading: "คะเรียร์", lang: "en-US" },
    { thai: "งาน", target: "Job", reading: "จ๊อบ", lang: "en-US" },

    // --- 14. หมวดธุรกิจและการตลาด (Business & Marketing) - 40 คำ ---
    { thai: "บริษัท", target: "Company", reading: "คัมพะนี", lang: "en-US" },
    { thai: "ธุรกิจ", target: "Business", reading: "บิสเนส", lang: "en-US" },
    { thai: "ลูกค้า", target: "Customer", reading: "คัสโตเมอร์", lang: "en-US" },
    { thai: "บริการ", target: "Service", reading: "เซอร์วิส", lang: "en-US" },
    { thai: "ผลิตภัณฑ์ / สินค้า", target: "Product", reading: "พรอตักต์", lang: "en-US" },
    { thai: "แบรนด์ / ยี่ห้อ", target: "Brand", reading: "แบรนด์", lang: "en-US" },
    { thai: "ราคา", target: "Price", reading: "ไพรซ์", lang: "en-US" },
    { thai: "ส่วนลด", target: "Discount", reading: "ดิสเคานต์", lang: "en-US" },
    { thai: "โฆษณา", target: "Advertising", reading: "แอดเวอร์ไทซิ่ง", lang: "en-US" },
    { thai: "ยอดขาย", target: "Sales", reading: "เซลส์", lang: "en-US" },
    { thai: "การตลาด", target: "Marketing", reading: "มาร์เก็ตติ้ง", lang: "en-US" },
    { thai: "กำไร", target: "Profit", reading: "พรอฟิต", lang: "en-US" },
    { thai: "ขาดทุน", target: "Loss", reading: "ลอส", lang: "en-US" },
    { thai: "คู่แข่ง", target: "Competitor", reading: "คัมเพททิเทอร์", lang: "en-US" },
    { thai: "กลยุทธ์", target: "Strategy", reading: "สแตรทิจี", lang: "en-US" },
    { thai: "โอกาส", target: "Opportunity", reading: "ออพพอร์ทูนิตี้", lang: "en-US" },
    { thai: "สัญญา", target: "Contract", reading: "คอนแทรคต์", lang: "en-US" },
    { thai: "ข้อตกลง", target: "Agreement", reading: "อะกรีเมนต์", lang: "en-US" },
    { thai: "หุ้น", target: "Stock", reading: "สต็อก", lang: "en-US" },
    { thai: "การลงทุน", target: "Investment", reading: "อินเวสต์เมนต์", lang: "en-US" },
    { thai: "เป้าหมาย", target: "Goal", reading: "โกล", lang: "en-US" },
    { thai: "ความสำเร็จ", target: "Success", reading: "ซัคเซส", lang: "en-US" },
    { thai: "ล้มเหลว", target: "Failure", reading: "เฟลเยอร์", lang: "en-US" },
    { thai: "การเติบโต", target: "Growth", reading: "โกรว์ธ", lang: "en-US" },
    { thai: "คุณภาพ", target: "Quality", reading: "ควอลิตี้", lang: "en-US" },
    { thai: "ปริมาณ", target: "Quantity", reading: "ควอนทิตี้", lang: "en-US" },
    { thai: "ภาษี", target: "Tax", reading: "แทกซ์", lang: "en-US" },
    { thai: "ใบแจ้งหนี้", target: "Invoice", reading: "อินวอยซ์", lang: "en-US" },
    { thai: "ใบเสร็จ", target: "Receipt", reading: "รีซีท", lang: "en-US" },
    { thai: "ธนาคาร", target: "Bank", reading: "แบงก์", lang: "en-US" },
    { thai: "บัญชี", target: "Account", reading: "อะเคานต์", lang: "en-US" },
    { thai: "บัตรเครดิต", target: "Credit card", reading: "เครดิตการ์ด", lang: "en-US" },
    { thai: "เงินสด", target: "Cash", reading: "แคช", lang: "en-US" },
    { thai: "ค่าใช้จ่าย", target: "Expense", reading: "เอ็กซ์เพนส์", lang: "en-US" },
    { thai: "งบประมาณ", target: "Budget", reading: "บัดเจ็ต", lang: "en-US" },
    { thai: "หนี้", target: "Debt", reading: "เดท", lang: "en-US" },
    { thai: "ความมั่งคั่ง", target: "Wealth", reading: "เวลธ์", lang: "en-US" },
    { thai: "เศรษฐกิจ", target: "Economy", reading: "อีคอนโนมี", lang: "en-US" },
    { thai: "ตลาด", target: "Market", reading: "มาร์เก็ต", lang: "en-US" },
    { thai: "อุตสาหกรรม", target: "Industry", reading: "อินดัสทรี", lang: "en-US" },

    // --- 15. หมวดการสื่อสารและอุปกรณ์ในออฟฟิศ (Office & Communication) - 35 คำ ---
    { thai: "การประชุม", target: "Meeting", reading: "มีทติ้ง", lang: "en-US" },
    { thai: "การนำเสนอ", target: "Presentation", reading: "พรีเซนเทชัน", lang: "en-US" },
    { thai: "รายงาน", target: "Report", reading: "รีพอร์ต", lang: "en-US" },
    { thai: "โครงการ", target: "Project", reading: "โปรเจกต์", lang: "en-US" },
    { thai: "กำหนดส่ง", target: "Deadline", reading: "เดดไลน์", lang: "en-US" },
    { thai: "ตารางเวลา", target: "Schedule", reading: "สเกดจูล", lang: "en-US" },
    { thai: "ข้อมูล", target: "Information", reading: "อินฟอร์เมชัน", lang: "en-US" },
    { thai: "อีเมล", target: "Email", reading: "อีเมล", lang: "en-US" },
    { thai: "ข้อความ", target: "Message", reading: "เมสเสจ", lang: "en-US" },
    { thai: "โทรศัพท์", target: "Telephone", reading: "เทลละโฟน", lang: "en-US" },
    { thai: "แล็ปท็อป", target: "Laptop", reading: "แล็ปท็อป", lang: "en-US" },
    { thai: "เครื่องพิมพ์", target: "Printer", reading: "พริ้นเตอร์", lang: "en-US" },
    { thai: "เอกสาร", target: "Document", reading: "ดอคิวเมนต์", lang: "en-US" },
    { thai: "ไฟล์ / แฟ้ม", target: "File", reading: "ไฟล์", lang: "en-US" },
    { thai: "อินเทอร์เน็ต", target: "Internet", reading: "อินเทอร์เน็ต", lang: "en-US" },
    { thai: "รหัสผ่าน", target: "Password", reading: "พาสเวิร์ด", lang: "en-US" },
    { thai: "หน้าจอ", target: "Screen", reading: "สกรีน", lang: "en-US" },
    { thai: "แป้นพิมพ์", target: "Keyboard", reading: "คีย์บอร์ด", lang: "en-US" },
    { thai: "เมาส์", target: "Mouse", reading: "เมาส์", lang: "en-US" },
    { thai: "ซอฟต์แวร์", target: "Software", reading: "ซอฟต์แวร์", lang: "en-US" },
    { thai: "ฮาร์ดแวร์", target: "Hardware", reading: "ฮาร์ดแวร์", lang: "en-US" },
    { thai: "การสื่อสาร", target: "Communication", reading: "คอมมูนิเคชัน", lang: "en-US" },
    { thai: "เครือข่าย", target: "Network", reading: "เน็ตเวิร์ก", lang: "en-US" },
    { thai: "ทีม", target: "Team", reading: "ทีม", lang: "en-US" },
    { thai: "ความร่วมมือ", target: "Collaboration", reading: "คอลลาบอเรชัน", lang: "en-US" },
    { thai: "ความคิดเห็น", target: "Feedback", reading: "ฟีดแบ็ก", lang: "en-US" },
    { thai: "การตัดสินใจ", target: "Decision", reading: "ดีซิชัน", lang: "en-US" },
    { thai: "ปัญหา", target: "Problem", reading: "พรอบเบลม", lang: "en-US" },
    { thai: "วิธีแก้ปัญหา", target: "Solution", reading: "โซลูชัน", lang: "en-US" },
    { thai: "นวัตกรรม", target: "Innovation", reading: "อินโนเวชัน", lang: "en-US" },
    { thai: "ความคิดสร้างสรรค์", target: "Creativity", reading: "ครีเอทิวิตี้", lang: "en-US" },
    { thai: "ทักษะ", target: "Skill", reading: "สกิล", lang: "en-US" },
    { thai: "ประสบการณ์", target: "Experience", reading: "เอ็กซ์พีเรียนซ์", lang: "en-US" },
    { thai: "ความรู้", target: "Knowledge", reading: "นอลเลจ", lang: "en-US" },
    { thai: "เป้าหมาย", target: "Target", reading: "ทาร์เก็ต", lang: "en-US" },
	// --- 16. หมวดเทคโนโลยีและฮาร์ดแวร์ (Technology & Hardware) - 25 คำ ---
    { thai: "เทคโนโลยี", target: "Technology", reading: "เทคโนโลยี", lang: "en-US" },
    { thai: "อุปกรณ์", target: "Device", reading: "ดีไวซ์", lang: "en-US" },
    { thai: "มือถือ", target: "Mobile", reading: "โมบายล์", lang: "en-US" },
    { thai: "เซิร์ฟเวอร์", target: "Server", reading: "เซิร์ฟเวอร์", lang: "en-US" },
    { thai: "หน้าจอ", target: "Screen", reading: "สกรีน", lang: "en-US" },
    { thai: "แบตเตอรี่", target: "Battery", reading: "แบตเตอรี่", lang: "en-US" },
    { thai: "สายเคเบิล", target: "Cable", reading: "เคเบิล", lang: "en-US" },
    { thai: "ไร้สาย", target: "Wireless", reading: "ไวร์เลส", lang: "en-US" },
    { thai: "บลูทูธ", target: "Bluetooth", reading: "บลูทูธ", lang: "en-US" },
    { thai: "เราเตอร์", target: "Router", reading: "เราเตอร์", lang: "en-US" },
    { thai: "สวิตช์", target: "Switch", reading: "สวิตช์", lang: "en-US" },
    { thai: "หน่วยความจำ", target: "Memory", reading: "เมมโมรี", lang: "en-US" },
    { thai: "ตัวประมวลผล", target: "Processor", reading: "โปรเซสเซอร์", lang: "en-US" },
    { thai: "ที่เก็บข้อมูล", target: "Storage", reading: "สตอเรจ", lang: "en-US" },
    { thai: "ระบบคลาวด์", target: "Cloud", reading: "คลาวด์", lang: "en-US" },
    { thai: "เบราว์เซอร์", target: "Browser", reading: "เบราว์เซอร์", lang: "en-US" },
    { thai: "แอปพลิเคชัน", target: "Application", reading: "แอปพลิเคชัน", lang: "en-US" },
    { thai: "ดาวน์โหลด", target: "Download", reading: "ดาวน์โหลด", lang: "en-US" },
    { thai: "อัปโหลด", target: "Upload", reading: "อัปโหลด", lang: "en-US" },
    { thai: "ติดตั้ง", target: "Install", reading: "อินสตอล", lang: "en-US" },
    { thai: "อัปเดต", target: "Update", reading: "อัปเดต", lang: "en-US" },
    { thai: "อัปเกรด", target: "Upgrade", reading: "อัปเกรด", lang: "en-US" },
    { thai: "เวอร์ชัน", target: "Version", reading: "เวอร์ชัน", lang: "en-US" },
    { thai: "ระบบ", target: "System", reading: "ซิสเต็ม", lang: "en-US" },
    { thai: "แพลตฟอร์ม", target: "Platform", reading: "แพลตฟอร์ม", lang: "en-US" },

    // --- 17. หมวดการพัฒนาเว็บและโปรแกรมมิ่ง (Web Development & Programming) - 40 คำ ---
    { thai: "โค้ด / รหัส", target: "Code", reading: "โค้ด", lang: "en-US" },
    { thai: "โปรแกรม", target: "Program", reading: "โปรแกรม", lang: "en-US" },
    { thai: "นักพัฒนา", target: "Developer", reading: "ดีเวลลอปเปอร์", lang: "en-US" },
    { thai: "ฟังก์ชัน", target: "Function", reading: "ฟังก์ชัน", lang: "en-US" },
    { thai: "ตัวแปร", target: "Variable", reading: "แวเรียเบิล", lang: "en-US" },
    { thai: "อาเรย์ / ชุดข้อมูล", target: "Array", reading: "อาเรย์", lang: "en-US" },
    { thai: "อ็อบเจกต์", target: "Object", reading: "อ็อบเจกต์", lang: "en-US" },
    { thai: "ข้อความ (สตริง)", target: "String", reading: "สตริง", lang: "en-US" },
    { thai: "จำนวนเต็ม", target: "Integer", reading: "อินทีเจอร์", lang: "en-US" },
    { thai: "บูลีน (ตรรกะ)", target: "Boolean", reading: "บูลีน", lang: "en-US" },
    { thai: "วนลูป", target: "Loop", reading: "ลูป", lang: "en-US" },
    { thai: "เงื่อนไข", target: "Condition", reading: "คอนดิชัน", lang: "en-US" },
    { thai: "คำสั่ง", target: "Statement", reading: "สเตตเมนต์", lang: "en-US" },
    { thai: "ข้อผิดพลาด", target: "Error", reading: "เออร์เรอร์", lang: "en-US" },
    { thai: "บั๊ก / จุดบกพร่อง", target: "Bug", reading: "บั๊ก", lang: "en-US" },
    { thai: "แก้บั๊ก", target: "Debug", reading: "ดีบั๊ก", lang: "en-US" },
    { thai: "สคริปต์", target: "Script", reading: "สคริปต์", lang: "en-US" },
    { thai: "ระบบหน้าบ้าน", target: "Frontend", reading: "ฟรอนต์เอนด์", lang: "en-US" },
    { thai: "ระบบหลังบ้าน", target: "Backend", reading: "แบ็กเอนด์", lang: "en-US" },
    { thai: "ฐานข้อมูล", target: "Database", reading: "ดาต้าเบส", lang: "en-US" },
    { thai: "คำสืบค้น", target: "Query", reading: "คิวรี", lang: "en-US" },
    { thai: "เอพีไอ", target: "API", reading: "เอพีไอ", lang: "en-US" },
    { thai: "เฟรมเวิร์ก", target: "Framework", reading: "เฟรมเวิร์ก", lang: "en-US" },
    { thai: "ไลบรารี", target: "Library", reading: "ไลบรารี", lang: "en-US" },
    { thai: "คลังเก็บโค้ด", target: "Repository", reading: "รีพอซิทอรี", lang: "en-US" },
    { thai: "บันทึกการเปลี่ยน", target: "Commit", reading: "คอมมิต", lang: "en-US" },
    { thai: "ดันโค้ด", target: "Push", reading: "พุช", lang: "en-US" },
    { thai: "ดึงโค้ด", target: "Pull", reading: "พูล", lang: "en-US" },
    { thai: "สาขา (โค้ด)", target: "Branch", reading: "บรานช์", lang: "en-US" },
    { thai: "รวม (โค้ด)", target: "Merge", reading: "เมิร์จ", lang: "en-US" },
    { thai: "ไวยากรณ์ (โค้ด)", target: "Syntax", reading: "ซินแทกซ์", lang: "en-US" },
    { thai: "แท็ก", target: "Tag", reading: "แท็ก", lang: "en-US" },
    { thai: "คุณลักษณะ", target: "Attribute", reading: "แอตทริบิวต์", lang: "en-US" },
    { thai: "องค์ประกอบ", target: "Element", reading: "เอลิเมนต์", lang: "en-US" },
    { thai: "ปลั๊กอิน", target: "Plugin", reading: "ปลั๊กอิน", lang: "en-US" },
    { thai: "โมดูล", target: "Module", reading: "โมดูล", lang: "en-US" },
    { thai: "ส่วนประกอบ", target: "Component", reading: "คอมโพเนนต์", lang: "en-US" },
    { thai: "แม่แบบ", target: "Template", reading: "เทมเพลต", lang: "en-US" },
    { thai: "โฮสต์", target: "Host", reading: "โฮสต์", lang: "en-US" },
    { thai: "โดเมน", target: "Domain", reading: "โดเมน", lang: "en-US" },

    // --- 18. หมวดข้อมูล, UI/UX และตรรกะ (Data, UI/UX & Logic) - 35 คำ ---
    { thai: "ข้อมูล", target: "Data", reading: "ดาต้า", lang: "en-US" },
    { thai: "ตรรกะ", target: "Logic", reading: "ลอจิก", lang: "en-US" },
    { thai: "อินเทอร์เฟส / หน้าจอ", target: "Interface", reading: "อินเทอร์เฟส", lang: "en-US" },
    { thai: "ผู้ใช้", target: "User", reading: "ยูสเซอร์", lang: "en-US" },
    { thai: "การออกแบบ", target: "Design", reading: "ดีไซน์", lang: "en-US" },
    { thai: "โครงร่าง / เค้าโครง", target: "Layout", reading: "เลย์เอาต์", lang: "en-US" },
    { thai: "การนำทาง", target: "Navigation", reading: "เนวิเกชัน", lang: "en-US" },
    { thai: "ปุ่ม", target: "Button", reading: "บัตทอน", lang: "en-US" },
    { thai: "ลิงก์ / จุดเชื่อมโยง", target: "Link", reading: "ลิงก์", lang: "en-US" },
    { thai: "ไอคอน", target: "Icon", reading: "ไอคอน", lang: "en-US" },
    { thai: "เมนู", target: "Menu", reading: "เมนู", lang: "en-US" },
    { thai: "ค้นหา", target: "Search", reading: "เสิร์ช", lang: "en-US" },
    { thai: "กรอง", target: "Filter", reading: "ฟิลเตอร์", lang: "en-US" },
    { thai: "เรียงลำดับ", target: "Sort", reading: "ซอร์ต", lang: "en-US" },
    { thai: "นำเข้า / ข้อมูลเข้า", target: "Input", reading: "อินพุต", lang: "en-US" },
    { thai: "ส่งออก / ผลลัพธ์", target: "Output", reading: "เอาต์พุต", lang: "en-US" },
    { thai: "คลิก", target: "Click", reading: "คลิก", lang: "en-US" },
    { thai: "เลื่อน (จอ)", target: "Scroll", reading: "สกรอลล์", lang: "en-US" },
    { thai: "ปัด (หน้าจอ)", target: "Swipe", reading: "สไวป์", lang: "en-US" },
    { thai: "วางเมาส์เหนือ", target: "Hover", reading: "โฮเวอร์", lang: "en-US" },
    { thai: "โฟกัส", target: "Focus", reading: "โฟกัส", lang: "en-US" },
    { thai: "ใช้งานอยู่", target: "Active", reading: "แอ็กทีฟ", lang: "en-US" },
    { thai: "ค่าเริ่มต้น", target: "Default", reading: "ดีฟอลต์", lang: "en-US" },
    { thai: "การตั้งค่า", target: "Setting", reading: "เซ็ตติ้ง", lang: "en-US" },
    { thai: "โปรไฟล์", target: "Profile", reading: "โปรไฟล์", lang: "en-US" },
    { thai: "บัญชี", target: "Account", reading: "อะเคานต์", lang: "en-US" },
    { thai: "เข้าสู่ระบบ", target: "Login", reading: "ล็อกอิน", lang: "en-US" },
    { thai: "ออกจากระบบ", target: "Logout", reading: "ล็อกเอาต์", lang: "en-US" },
    { thai: "สมัครสมาชิก", target: "Register", reading: "รีจิสเตอร์", lang: "en-US" },
    { thai: "ความปลอดภัย", target: "Security", reading: "ซีเคียวริตี้", lang: "en-US" },
    { thai: "ความเป็นส่วนตัว", target: "Privacy", reading: "ไพรเวซี", lang: "en-US" },
    { thai: "การเข้าถึง", target: "Access", reading: "แอคเซส", lang: "en-US" },
    { thai: "โทเคน (รหัส)", target: "Token", reading: "โทเคน", lang: "en-US" },
    { thai: "เซสชัน", target: "Session", reading: "เซสชัน", lang: "en-US" },
    { thai: "คุกกี้ (ข้อมูล)", target: "Cookie", reading: "คุกกี้", lang: "en-US" },
	// --- 19. หมวดสุขภาพ โภชนาการ และการดูแลร่างกาย (Health & Nutrition) - 30 คำ ---
    { thai: "สุขภาพ", target: "Health", reading: "เฮลท์", lang: "en-US" },
    { thai: "สุขภาพดี", target: "Healthy", reading: "เฮลตี", lang: "en-US" },
    { thai: "โภชนาการ", target: "Nutrition", reading: "นิวทริชัน", lang: "en-US" },
    { thai: "ระบบเผาผลาญ", target: "Metabolism", reading: "เมตาบอลิซึม", lang: "en-US" },
    { thai: "แคลอรี", target: "Calorie", reading: "แคลอรี", lang: "en-US" },
    { thai: "โปรตีน", target: "Protein", reading: "โปรตีน", lang: "en-US" },
    { thai: "วิตามิน", target: "Vitamin", reading: "ไวตามิน", lang: "en-US" },
    { thai: "แร่ธาตุ", target: "Mineral", reading: "มิเนอรัล", lang: "en-US" },
    { thai: "ไขมัน", target: "Fat", reading: "แฟต", lang: "en-US" },
    { thai: "คาร์โบไฮเดรต", target: "Carbohydrate", reading: "คาร์โบไฮเดรต", lang: "en-US" },
    { thai: "เส้นใยอาหาร", target: "Fiber", reading: "ไฟเบอร์", lang: "en-US" },
    { thai: "กล้ามเนื้อ", target: "Muscle", reading: "มัสเซิล", lang: "en-US" },
    { thai: "น้ำหนัก", target: "Weight", reading: "เวท", lang: "en-US" },
    { thai: "ส่วนสูง", target: "Height", reading: "ไฮท์", lang: "en-US" },
    { thai: "ความสมบูรณ์ของร่างกาย", target: "Fitness", reading: "ฟิตเนส", lang: "en-US" },
    { thai: "โรงยิม", target: "Gym", reading: "ยิม", lang: "en-US" },
    { thai: "ออกกำลังกาย (หนัก)", target: "Workout", reading: "เวิร์กเอาต์", lang: "en-US" },
    { thai: "เหงื่อ", target: "Sweat", reading: "สเวต", lang: "en-US" },
    { thai: "การพักผ่อน", target: "Rest", reading: "เรสต์", lang: "en-US" },
    { thai: "การฟื้นฟู", target: "Recovery", reading: "รีคัฟเวอรี", lang: "en-US" },
    { thai: "โรคภัย", target: "Disease", reading: "ดีซีส", lang: "en-US" },
    { thai: "ยารักษาโรค", target: "Medicine", reading: "เมดิซิน", lang: "en-US" },
    { thai: "คลินิก", target: "Clinic", reading: "คลินิก", lang: "en-US" },
    { thai: "การบำบัด", target: "Therapy", reading: "เทอราพี", lang: "en-US" },
    { thai: "อาหารเสริม", target: "Supplement", reading: "ซัปพลิเมนต์", lang: "en-US" },
    { thai: "การย่อยอาหาร", target: "Digestion", reading: "ไดเจสชัน", lang: "en-US" },
    { thai: "ภูมิคุ้มกัน", target: "Immunity", reading: "อิมมูนิตี", lang: "en-US" },
    { thai: "ออกซิเจน", target: "Oxygen", reading: "ออกซิเจน", lang: "en-US" },
    { thai: "โยเกิร์ต", target: "Yogurt", reading: "โยเกิร์ต", lang: "en-US" },
    { thai: "เมล็ดพืช", target: "Seed", reading: "ซีด", lang: "en-US" },

    // --- 20. หมวดการเงิน การลงทุน และสินทรัพย์ (Finance & Investment) - 40 คำ ---
    { thai: "การเงิน", target: "Finance", reading: "ไฟแนนซ์", lang: "en-US" },
    { thai: "สินทรัพย์", target: "Asset", reading: "แอสเซต", lang: "en-US" },
    { thai: "หนี้สิน", target: "Liability", reading: "ไลอะบิลิตี", lang: "en-US" },
    { thai: "กองทุน", target: "Fund", reading: "ฟันด์", lang: "en-US" },
    { thai: "กองทุนรวม", target: "Mutual fund", reading: "มิวชวลฟันด์", lang: "en-US" },
    { thai: "คริปโตเคอร์เรนซี", target: "Cryptocurrency", reading: "คริปโตเคอร์เรนซี", lang: "en-US" },
    { thai: "บิตคอยน์", target: "Bitcoin", reading: "บิตคอยน์", lang: "en-US" },
    { thai: "เงินปันผล", target: "Dividend", reading: "ดิวิเดนด์", lang: "en-US" },
    { thai: "ดอกเบี้ย", target: "Interest", reading: "อินเทอเรสต์", lang: "en-US" },
    { thai: "อัตรา", target: "Rate", reading: "เรต", lang: "en-US" },
    { thai: "เงินเฟ้อ", target: "Inflation", reading: "อินเฟลชัน", lang: "en-US" },
    { thai: "พอร์ตการลงทุน", target: "Portfolio", reading: "พอร์ตโฟลิโอ", lang: "en-US" },
    { thai: "กระจายความเสี่ยง", target: "Diversify", reading: "ไดเวอร์ซิไฟ", lang: "en-US" },
    { thai: "ผลตอบแทน", target: "Return", reading: "รีเทิร์น", lang: "en-US" },
    { thai: "ทุน / เงินทุน", target: "Capital", reading: "แคปปิตัล", lang: "en-US" },
    { thai: "การเทรด / ซื้อขาย", target: "Trade", reading: "เทรด", lang: "en-US" },
    { thai: "ค่าเฉลี่ย", target: "Average", reading: "แอเวอเรจ", lang: "en-US" },
    { thai: "การเกษียณอายุ", target: "Retirement", reading: "รีไทร์เมนต์", lang: "en-US" },
    { thai: "เงินบำนาญ", target: "Pension", reading: "เพนชัน", lang: "en-US" },
    { thai: "เก็บออม", target: "Save", reading: "เซฟ", lang: "en-US" },
    { thai: "รายได้ (เข้า)", target: "Income", reading: "อินคัม", lang: "en-US" },
    { thai: "รายจ่าย", target: "Expenditure", reading: "เอ็กซ์เพนดิเจอร์", lang: "en-US" },
    { thai: "สกุลเงิน", target: "Currency", reading: "เคอร์เรนซี", lang: "en-US" },
    { thai: "เหรียญ", target: "Coin", reading: "คอยน์", lang: "en-US" },
    { thai: "ตลาดกระทิง (ขาขึ้น)", target: "Bull market", reading: "บูลมาร์เก็ต", lang: "en-US" },
    { thai: "ตลาดหมี (ขาลง)", target: "Bear market", reading: "แบร์มาร์เก็ต", lang: "en-US" },
    { thai: "หุ้นส่วน", target: "Partner", reading: "พาร์ตเนอร์", lang: "en-US" },
    { thai: "เจ้าของ", target: "Owner", reading: "โอเนอร์", lang: "en-US" },
    { thai: "นักลงทุน", target: "Investor", reading: "อินเวสเตอร์", lang: "en-US" },
    { thai: "มูลค่า", target: "Value", reading: "แวลู", lang: "en-US" },
    { thai: "ราคา", target: "Price", reading: "ไพรซ์", lang: "en-US" },
    { thai: "โบรกเกอร์ (นายหน้า)", target: "Broker", reading: "โบรกเกอร์", lang: "en-US" },
    { thai: "ค่าธรรมเนียม", target: "Fee", reading: "ฟี", lang: "en-US" },
    { thai: "ความผันผวน", target: "Volatility", reading: "โวลาทิลิตี", lang: "en-US" },
    { thai: "ส่วนแบ่ง / หุ้น", target: "Share", reading: "แชร์", lang: "en-US" },
    { thai: "สภาพคล่อง", target: "Liquidity", reading: "ลิควิดิตี", lang: "en-US" },
    { thai: "ดัชนี", target: "Index", reading: "อินเด็กซ์", lang: "en-US" },
    { thai: "แนวโน้ม", target: "Trend", reading: "เทรนด์", lang: "en-US" },
    { thai: "ความมั่งคั่ง", target: "Wealth", reading: "เวลธ์", lang: "en-US" },
    { thai: "ความเสี่ยง", target: "Risk", reading: "ริสก์", lang: "en-US" },

    // --- 21. หมวดกลยุทธ์ การแข่งขัน และเกมมิ่ง (Strategy & Gaming) - 30 คำ ---
    { thai: "กลยุทธ์", target: "Strategy", reading: "สแตรทิจี", lang: "en-US" },
    { thai: "ยุทธวิธี", target: "Tactic", reading: "แท็กติก", lang: "en-US" },
    { thai: "เกม", target: "Game", reading: "เกม", lang: "en-US" },
    { thai: "การแข่งขัน", target: "Match", reading: "แมตช์", lang: "en-US" },
    { thai: "การต่อสู้", target: "Battle", reading: "แบทเทิล", lang: "en-US" },
    { thai: "คู่แข่ง / ศัตรู", target: "Opponent", reading: "ออปโปเนนต์", lang: "en-US" },
    { thai: "คู่ปรับ", target: "Rival", reading: "ไรเวิล", lang: "en-US" },
    { thai: "ตัวละคร", target: "Character", reading: "คาแร็กเตอร์", lang: "en-US" },
    { thai: "ระดับ / เลเวล", target: "Level", reading: "เลเวล", lang: "en-US" },
    { thai: "สถิติ / ค่าพลัง", target: "Stat", reading: "สแตต", lang: "en-US" },
    { thai: "พลังชีวิต (HP)", target: "Health point", reading: "เฮลธ์พอยต์", lang: "en-US" },
    { thai: "โจมตี", target: "Attack", reading: "แอทแทก", lang: "en-US" },
    { thai: "ป้องกัน", target: "Defense", reading: "ดีเฟนส์", lang: "en-US" },
    { thai: "ความเร็ว", target: "Speed", reading: "สปีด", lang: "en-US" },
    { thai: "ไอเทม / สิ่งของ", target: "Item", reading: "ไอเทม", lang: "en-US" },
    { thai: "สวมใส่", target: "Equip", reading: "อีควิป", lang: "en-US" },
    { thai: "วิวัฒนาการ", target: "Evolve", reading: "อีโวล์ฟ", lang: "en-US" },
    { thai: "เพาะพันธุ์", target: "Breed", reading: "บรีด", lang: "en-US" },
    { thai: "ธรรมชาติ / นิสัย", target: "Nature", reading: "เนเจอร์", lang: "en-US" },
    { thai: "ความสามารถ", target: "Ability", reading: "อะบิลิตี", lang: "en-US" },
    { thai: "ท่าต่อสู้ / การเคลื่อนไหว", target: "Move", reading: "มูฟ", lang: "en-US" },
    { thai: "ตา / รอบ (การเล่น)", target: "Turn", reading: "เทิร์น", lang: "en-US" },
    { thai: "ชนะ", target: "Win", reading: "วิน", lang: "en-US" },
    { thai: "แพ้", target: "Lose", reading: "ลูส", lang: "en-US" },
    { thai: "เสมอ", target: "Draw", reading: "ดรอว์", lang: "en-US" },
    { thai: "การฝึกฝน", target: "Training", reading: "เทรนนิง", lang: "en-US" },
    { thai: "คะแนน", target: "Score", reading: "สกอร์", lang: "en-US" },
    { thai: "แชมป์", target: "Champion", reading: "แชมเปียน", lang: "en-US" },
    { thai: "ทัวร์นาเมนต์", target: "Tournament", reading: "ทัวร์นาเมนต์", lang: "en-US" },
    { thai: "ความเสียหาย", target: "Damage", reading: "ดาเมจ", lang: "en-US" },
	// --- 22. หมวดอารมณ์และความรู้สึก (Emotions & Feelings) - 20 คำ ---
    { thai: "ความรัก", target: "Love", reading: "เลิฟ", lang: "en-US" },
    { thai: "ความเกลียดชัง", target: "Hate", reading: "เฮท", lang: "en-US" },
    { thai: "ความกลัว", target: "Fear", reading: "เฟียร์", lang: "en-US" },
    { thai: "ความประหลาดใจ", target: "Surprise", reading: "เซอร์ไพรส์", lang: "en-US" },
    { thai: "ความตกใจ", target: "Shock", reading: "ช็อก", lang: "en-US" },
    { thai: "ความตื่นเต้น", target: "Excitement", reading: "เอ็กไซต์เมนต์", lang: "en-US" },
    { thai: "ความเบื่อหน่าย", target: "Boredom", reading: "บอร์ดอม", lang: "en-US" },
    { thai: "ความสับสน", target: "Confusion", reading: "คอนฟิวชัน", lang: "en-US" },
    { thai: "ความหวัง", target: "Hope", reading: "โฮป", lang: "en-US" },
    { thai: "ความสุข / ความปีติ", target: "Joy", reading: "จอย", lang: "en-US" },
    { thai: "ความเศร้า", target: "Sadness", reading: "แซดเนส", lang: "en-US" },
    { thai: "ความเครียด", target: "Stress", reading: "สเตรส", lang: "en-US" },
    { thai: "ผ่อนคลาย", target: "Relax", reading: "รีแลกซ์", lang: "en-US" },
    { thai: "ความกังวล", target: "Worry", reading: "วอร์รี", lang: "en-US" },
    { thai: "ความภาคภูมิใจ", target: "Pride", reading: "ไพรด์", lang: "en-US" },
    { thai: "ความอิจฉา", target: "Jealousy", reading: "เจลลัสซี", lang: "en-US" },
    { thai: "ความเห็นอกเห็นใจ", target: "Sympathy", reading: "ซิมพาธี", lang: "en-US" },
    { thai: "ความรู้สึกผิด", target: "Guilt", reading: "กิลต์", lang: "en-US" },
    { thai: "ความมั่นใจ", target: "Confidence", reading: "คอนฟิเดนซ์", lang: "en-US" },
    { thai: "ความสงสัย", target: "Doubt", reading: "เดาต์", lang: "en-US" },

    // --- 23. หมวดสภาพอากาศและฤดูกาล (Weather & Seasons) - 20 คำ ---
    { thai: "สภาพอากาศ", target: "Weather", reading: "เวเธอร์", lang: "en-US" },
    { thai: "ฤดูกาล", target: "Season", reading: "ซีซัน", lang: "en-US" },
    { thai: "ฤดูร้อน", target: "Summer", reading: "ซัมเมอร์", lang: "en-US" },
    { thai: "ฤดูหนาว", target: "Winter", reading: "วินเทอร์", lang: "en-US" },
    { thai: "ฤดูใบไม้ผลิ", target: "Spring", reading: "สปริง", lang: "en-US" },
    { thai: "ฤดูใบไม้ร่วง", target: "Autumn", reading: "ออทัมน์", lang: "en-US" },
    { thai: "อุณหภูมิ", target: "Temperature", reading: "เทมเพอเรเจอร์", lang: "en-US" },
    { thai: "องศา", target: "Degree", reading: "ดีกรี", lang: "en-US" },
    { thai: "แดดออก", target: "Sunny", reading: "ซันนี", lang: "en-US" },
    { thai: "มีเมฆมาก", target: "Cloudy", reading: "คลาวด์ดี", lang: "en-US" },
    { thai: "ฝนตก", target: "Rainy", reading: "เรนนี", lang: "en-US" },
    { thai: "พายุ", target: "Storm", reading: "สตอร์ม", lang: "en-US" },
    { thai: "ฟ้าแลบ", target: "Lightning", reading: "ไลต์นิง", lang: "en-US" },
    { thai: "ฟ้าร้อง", target: "Thunder", reading: "ธันเดอร์", lang: "en-US" },
    { thai: "มีหมอก", target: "Foggy", reading: "ฟ็อกกี", lang: "en-US" },
    { thai: "น้ำแข็ง", target: "Ice", reading: "ไอซ์", lang: "en-US" },
    { thai: "ละลาย", target: "Melt", reading: "เมลต์", lang: "en-US" },
    { thai: "แช่แข็ง", target: "Freeze", reading: "ฟรีซ", lang: "en-US" },
    { thai: "พยากรณ์", target: "Forecast", reading: "ฟอร์คาสต์", lang: "en-US" },
    { thai: "ร่ม", target: "Umbrella", reading: "อัมเบรลลา", lang: "en-US" },

    // --- 24. หมวดงานอดิเรกและความบันเทิง (Hobbies & Entertainment) - 30 คำ ---
    { thai: "งานอดิเรก", target: "Hobby", reading: "ฮ็อบบี", lang: "en-US" },
    { thai: "ดนตรี", target: "Music", reading: "มิวสิก", lang: "en-US" },
    { thai: "เพลง", target: "Song", reading: "ซอง", lang: "en-US" },
    { thai: "ภาพยนตร์", target: "Movie", reading: "มูฟวี", lang: "en-US" },
    { thai: "โรงภาพยนตร์", target: "Cinema", reading: "ซิเนมา", lang: "en-US" },
    { thai: "ศิลปะ", target: "Art", reading: "อาร์ต", lang: "en-US" },
    { thai: "การวาดภาพ (เส้น)", target: "Drawing", reading: "ดรอวิง", lang: "en-US" },
    { thai: "การทาสี / ภาพจิตรกรรม", target: "Painting", reading: "เพนต์ทิง", lang: "en-US" },
    { thai: "การเต้น", target: "Dance", reading: "แดนซ์", lang: "en-US" },
    { thai: "การถ่ายภาพ", target: "Photography", reading: "ฟะทอกระฟี", lang: "en-US" },
    { thai: "กล้อง", target: "Camera", reading: "คาเมรา", lang: "en-US" },
    { thai: "กีฬา", target: "Sport", reading: "สปอร์ต", lang: "en-US" },
    { thai: "ฟุตบอล", target: "Football", reading: "ฟุตบอล", lang: "en-US" },
    { thai: "บาสเกตบอล", target: "Basketball", reading: "บาสเกตบอล", lang: "en-US" },
    { thai: "ว่ายน้ำ", target: "Swimming", reading: "สวิมมิง", lang: "en-US" },
    { thai: "วิ่ง", target: "Running", reading: "รันนิง", lang: "en-US" },
    { thai: "การอ่าน", target: "Reading", reading: "รีดดิง", lang: "en-US" },
    { thai: "นวนิยาย", target: "Novel", reading: "โนเวล", lang: "en-US" },
    { thai: "หนังสือการ์ตูน", target: "Comic", reading: "คอมิก", lang: "en-US" },
    { thai: "เกม", target: "Game", reading: "เกม", lang: "en-US" },
    { thai: "เครื่องเล่นเกม", target: "Console", reading: "คอนโซล", lang: "en-US" },
    { thai: "ปริศนา", target: "Puzzle", reading: "พัสเซิล", lang: "en-US" },
    { thai: "ของเล่น", target: "Toy", reading: "ทอย", lang: "en-US" },
    { thai: "ปาร์ตี้ / งานเลี้ยง", target: "Party", reading: "ปาร์ตี", lang: "en-US" },
    { thai: "เทศกาล", target: "Festival", reading: "เฟสติวัล", lang: "en-US" },
    { thai: "คอนเสิร์ต", target: "Concert", reading: "คอนเสิร์ต", lang: "en-US" },
    { thai: "ตั๋ว", target: "Ticket", reading: "ทิกเก็ต", lang: "en-US" },
    { thai: "มายากล / เวทมนตร์", target: "Magic", reading: "แมจิก", lang: "en-US" },
    { thai: "ของสะสม", target: "Collection", reading: "คอลเลกชัน", lang: "en-US" },
    { thai: "กีตาร์", target: "Guitar", reading: "กีตาร์", lang: "en-US" },

    // --- 25. หมวดแนวคิดนามธรรมและทิศทาง (Abstract Concepts & Directions) - 30 คำ ---
    { thai: "ความคิด / ไอเดีย", target: "Idea", reading: "ไอเดีย", lang: "en-US" },
    { thai: "ความจริง", target: "Truth", reading: "ทรูธ", lang: "en-US" },
    { thai: "คำโกหก", target: "Lie", reading: "ไล", lang: "en-US" },
    { thai: "เหตุผล", target: "Reason", reading: "รีซัน", lang: "en-US" },
    { thai: "จุดประสงค์", target: "Purpose", reading: "เพอร์โพส", lang: "en-US" },
    { thai: "วิธีการ", target: "Method", reading: "เมธอด", lang: "en-US" },
    { thai: "ผลลัพธ์", target: "Result", reading: "รีซัลต์", lang: "en-US" },
    { thai: "ผลกระทบ", target: "Effect", reading: "เอฟเฟกต์", lang: "en-US" },
    { thai: "สาเหตุ", target: "Cause", reading: "คอส", lang: "en-US" },
    { thai: "ประวัติศาสตร์", target: "History", reading: "ฮิสทอรี", lang: "en-US" },
    { thai: "กฎ / กติกา", target: "Rule", reading: "รูล", lang: "en-US" },
    { thai: "กฎหมาย", target: "Law", reading: "ลอว์", lang: "en-US" },
    { thai: "ความยุติธรรม", target: "Justice", reading: "จัสติส", lang: "en-US" },
    { thai: "อิสรภาพ", target: "Freedom", reading: "ฟรีดอม", lang: "en-US" },
    { thai: "สัญลักษณ์", target: "Symbol", reading: "ซิมโบล", lang: "en-US" },
    { thai: "รูปร่าง", target: "Shape", reading: "เชป", lang: "en-US" },
    { thai: "วงกลม", target: "Circle", reading: "เซอร์เคิล", lang: "en-US" },
    { thai: "สี่เหลี่ยม", target: "Square", reading: "สแควร์", lang: "en-US" },
    { thai: "สามเหลี่ยม", target: "Triangle", reading: "ไทรแองเกิล", lang: "en-US" },
    { thai: "ขนาด", target: "Size", reading: "ไซส์", lang: "en-US" },
    { thai: "พื้นที่ว่าง / อวกาศ", target: "Space", reading: "สเปซ", lang: "en-US" },
    { thai: "ระยะทาง", target: "Distance", reading: "ดิสแทนซ์", lang: "en-US" },
    { thai: "พื้นที่ (ตาราง)", target: "Area", reading: "แอเรีย", lang: "en-US" },
    { thai: "ทิศทาง", target: "Direction", reading: "ไดเรกชัน", lang: "en-US" },
    { thai: "ตำแหน่ง", target: "Position", reading: "โพสิชัน", lang: "en-US" },
    { thai: "ด้านบน", target: "Top", reading: "ท็อป", lang: "en-US" },
    { thai: "ด้านล่าง", target: "Bottom", reading: "บอตทอม", lang: "en-US" },
    { thai: "ตรงกลาง", target: "Middle", reading: "มิดเดิล", lang: "en-US" },
    { thai: "ด้านหน้า", target: "Front", reading: "ฟรอนต์", lang: "en-US" },
    { thai: "ด้านหลัง", target: "Back", reading: "แบ็ก", lang: "en-US" },
	// --- 26. หมวดสัตว์ (Animals) - 30 คำ ---
    { thai: "สิงโต", target: "Lion", reading: "ไลออน", lang: "en-US" },
    { thai: "เสือ", target: "Tiger", reading: "ไทเกอร์", lang: "en-US" },
    { thai: "ช้าง", target: "Elephant", reading: "เอเลเฟนท์", lang: "en-US" },
    { thai: "หมี", target: "Bear", reading: "แบร์", lang: "en-US" },
    { thai: "ลิง", target: "Monkey", reading: "มังกี้", lang: "en-US" },
    { thai: "งู", target: "Snake", reading: "สเนก", lang: "en-US" },
    { thai: "ม้า", target: "Horse", reading: "ฮอร์ส", lang: "en-US" },
    { thai: "วัว", target: "Cow", reading: "คาว", lang: "en-US" },
    { thai: "หมู", target: "Pig", reading: "พิก", lang: "en-US" },
    { thai: "แกะ", target: "Sheep", reading: "ชีป", lang: "en-US" },
    { thai: "แพะ", target: "Goat", reading: "โกท", lang: "en-US" },
    { thai: "เป็ด", target: "Duck", reading: "ดัก", lang: "en-US" },
    { thai: "หนู", target: "Mouse", reading: "เมาส์", lang: "en-US" },
    { thai: "กระต่าย", target: "Rabbit", reading: "แรบบิท", lang: "en-US" },
    { thai: "เต่า", target: "Turtle", reading: "เทอร์เทิล", lang: "en-US" },
    { thai: "กบ", target: "Frog", reading: "ฟร็อก", lang: "en-US" },
    { thai: "แมงมุม", target: "Spider", reading: "สไปเดอร์", lang: "en-US" },
    { thai: "แมลง", target: "Insect", reading: "อินเซกต์", lang: "en-US" },
    { thai: "ผึ้ง", target: "Bee", reading: "บี", lang: "en-US" },
    { thai: "ผีเสื้อ", target: "Butterfly", reading: "บัตเตอร์ฟลาย", lang: "en-US" },
    { thai: "มด", target: "Ant", reading: "แอนท์", lang: "en-US" },
    { thai: "แมลงวัน", target: "Fly", reading: "ฟลาย", lang: "en-US" },
    { thai: "ยุง", target: "Mosquito", reading: "มอสคิโต", lang: "en-US" },
    { thai: "โลมา", target: "Dolphin", reading: "ดอลฟิน", lang: "en-US" },
    { thai: "วาฬ", target: "Whale", reading: "เวล", lang: "en-US" },
    { thai: "ฉลาม", target: "Shark", reading: "ชาร์ก", lang: "en-US" },
    { thai: "เพนกวิน", target: "Penguin", reading: "เพนกวิน", lang: "en-US" },
    { thai: "จิงโจ้", target: "Kangaroo", reading: "แคนการู", lang: "en-US" },
    { thai: "หมาป่า", target: "Wolf", reading: "วูล์ฟ", lang: "en-US" },
    { thai: "จระเข้", target: "Crocodile", reading: "คร็อกโคไดล์", lang: "en-US" },

    // --- 27. หมวดเครื่องแต่งกายและเครื่องประดับ (Clothing & Accessories) - 30 คำ ---
    { thai: "เสื้อเชิ้ต", target: "Shirt", reading: "เชิ้ต", lang: "en-US" },
    { thai: "เสื้อยืด", target: "T-shirt", reading: "ทีเชิ้ต", lang: "en-US" },
    { thai: "กางเกงขายาว", target: "Pants", reading: "แพนทส์", lang: "en-US" },
    { thai: "กางเกงยีนส์", target: "Jeans", reading: "ยีนส์", lang: "en-US" },
    { thai: "กางเกงขาสั้น", target: "Shorts", reading: "ชอร์ตส์", lang: "en-US" },
    { thai: "กระโปรง", target: "Skirt", reading: "สเกิร์ต", lang: "en-US" },
    { thai: "ชุดเดรส", target: "Dress", reading: "เดรส", lang: "en-US" },
    { thai: "ชุดสูท", target: "Suit", reading: "สูท", lang: "en-US" },
    { thai: "เสื้อแจ็คเก็ต", target: "Jacket", reading: "แจ็คเก็ต", lang: "en-US" },
    { thai: "เสื้อโค้ต", target: "Coat", reading: "โค้ต", lang: "en-US" },
    { thai: "เสื้อกันหนาว", target: "Sweater", reading: "สเวตเตอร์", lang: "en-US" },
    { thai: "หมวก (มีปีกรอบ)", target: "Hat", reading: "แฮท", lang: "en-US" },
    { thai: "หมวกแก๊ป", target: "Cap", reading: "แก๊ป", lang: "en-US" },
    { thai: "ถุงเท้า", target: "Socks", reading: "ซ็อกส์", lang: "en-US" },
    { thai: "รองเท้าบูท", target: "Boots", reading: "บูทส์", lang: "en-US" },
    { thai: "รองเท้าผ้าใบ", target: "Sneakers", reading: "สนีกเกอร์ส", lang: "en-US" },
    { thai: "เข็มขัด", target: "Belt", reading: "เบลท์", lang: "en-US" },
    { thai: "เนคไท", target: "Tie", reading: "ไท", lang: "en-US" },
    { thai: "ผ้าพันคอ", target: "Scarf", reading: "สคาร์ฟ", lang: "en-US" },
    { thai: "ถุงมือ", target: "Gloves", reading: "โกลฟส์", lang: "en-US" },
    { thai: "ชุดชั้นใน", target: "Underwear", reading: "อันเดอร์แวร์", lang: "en-US" },
    { thai: "แหวน", target: "Ring", reading: "ริง", lang: "en-US" },
    { thai: "สร้อยคอ", target: "Necklace", reading: "เนคเลซ", lang: "en-US" },
    { thai: "สร้อยข้อมือ", target: "Bracelet", reading: "เบรสเลต", lang: "en-US" },
    { thai: "ต่างหู", target: "Earrings", reading: "เอียร์ริงส์", lang: "en-US" },
    { thai: "กระเป๋าสตางค์", target: "Wallet", reading: "วอลเล็ต", lang: "en-US" },
    { thai: "กระเป๋าถือ (ผู้หญิง)", target: "Purse", reading: "เพิร์ส", lang: "en-US" },
    { thai: "กระเป๋าเป้", target: "Backpack", reading: "แบ็กแพ็ก", lang: "en-US" },
    { thai: "เครื่องแบบ", target: "Uniform", reading: "ยูนิฟอร์ม", lang: "en-US" },
    { thai: "กระเป๋าเสื้อ/กางเกง", target: "Pocket", reading: "พ็อกเก็ต", lang: "en-US" },

    // --- 28. หมวดการศึกษาและโรงเรียน (Education & School) - 40 คำ ---
    { thai: "การศึกษา", target: "Education", reading: "เอดดูเคชัน", lang: "en-US" },
    { thai: "มหาวิทยาลัย", target: "University", reading: "ยูนิเวอร์ซิตี้", lang: "en-US" },
    { thai: "วิทยาลัย", target: "College", reading: "คอลเลจ", lang: "en-US" },
    { thai: "นักเรียน / นักศึกษา", target: "Student", reading: "สติวเดนท์", lang: "en-US" },
    { thai: "ชั้นเรียน", target: "Class", reading: "คลาส", lang: "en-US" },
    { thai: "ห้องเรียน", target: "Classroom", reading: "คลาสรูม", lang: "en-US" },
    { thai: "วิชา", target: "Subject", reading: "ซับเจกต์", lang: "en-US" },
    { thai: "คณิตศาสตร์", target: "Mathematics", reading: "แมทเธเมติกส์", lang: "en-US" },
    { thai: "วิทยาศาสตร์", target: "Science", reading: "ไซเอนซ์", lang: "en-US" },
    { thai: "ภูมิศาสตร์", target: "Geography", reading: "จีโอกราฟฟี", lang: "en-US" },
    { thai: "ภาษา", target: "Language", reading: "แลงกวิจ", lang: "en-US" },
    { thai: "ภาษาอังกฤษ", target: "English", reading: "อิงลิช", lang: "en-US" },
    { thai: "การทดสอบ", target: "Test", reading: "เทสต์", lang: "en-US" },
    { thai: "การสอบ (ทางการ)", target: "Exam", reading: "เอ็กแซม", lang: "en-US" },
    { thai: "แบบทดสอบย่อย", target: "Quiz", reading: "ควิซ", lang: "en-US" },
    { thai: "การบ้าน", target: "Homework", reading: "โฮมเวิร์ก", lang: "en-US" },
    { thai: "ระดับชั้น / เกรด", target: "Grade", reading: "เกรด", lang: "en-US" },
    { thai: "ปริญญา", target: "Degree", reading: "ดีกรี", lang: "en-US" },
    { thai: "ผู้สำเร็จการศึกษา", target: "Graduate", reading: "แกรดูเอต", lang: "en-US" },
    { thai: "ประกาศนียบัตร", target: "Diploma", reading: "ดิพโพลมา", lang: "en-US" },
    { thai: "ทุนการศึกษา", target: "Scholarship", reading: "สกอลาร์ชิป", lang: "en-US" },
    { thai: "บทเรียน", target: "Lesson", reading: "เลสซัน", lang: "en-US" },
    { thai: "บท", target: "Chapter", reading: "แชปเตอร์", lang: "en-US" },
    { thai: "หน้า (หนังสือ)", target: "Page", reading: "เพจ", lang: "en-US" },
    { thai: "คำถาม", target: "Question", reading: "เควสชัน", lang: "en-US" },
    { thai: "คำตอบ", target: "Answer", reading: "แอนเซอร์", lang: "en-US" },
    { thai: "ตัวอย่าง", target: "Example", reading: "เอ็กแซมเพิล", lang: "en-US" },
    { thai: "พจนานุกรม", target: "Dictionary", reading: "ดิกชันนารี", lang: "en-US" },
    { thai: "คำศัพท์", target: "Vocabulary", reading: "โวแคบบิวลารี", lang: "en-US" },
    { thai: "ไวยากรณ์", target: "Grammar", reading: "แกรมมาร์", lang: "en-US" },
    { thai: "ดินสอ", target: "Pencil", reading: "เพนซิล", lang: "en-US" },
    { thai: "ยางลบ", target: "Eraser", reading: "อีเรเซอร์", lang: "en-US" },
    { thai: "ไม้บรรทัด", target: "Ruler", reading: "รูลเลอร์", lang: "en-US" },
    { thai: "กระดานดำ", target: "Blackboard", reading: "แบล็กบอร์ด", lang: "en-US" },
    { thai: "กระดานไวท์บอร์ด", target: "Whiteboard", reading: "ไวท์บอร์ด", lang: "en-US" },
    { thai: "สมุดจด", target: "Notebook", reading: "โน้ตบุ๊ก", lang: "en-US" },
    { thai: "โต๊ะเรียน", target: "Desk", reading: "เดสก์", lang: "en-US" },
    { thai: "ภาคเรียน", target: "Term", reading: "เทอม", lang: "en-US" },
    { thai: "ภาคการศึกษา", target: "Semester", reading: "ซิเมสเตอร์", lang: "en-US" },
    { thai: "เวลาพัก", target: "Break", reading: "เบรก", lang: "en-US" },
	// --- 29. หมวดการเดินทางในเมืองและสถานที่สาธารณะ (City Life & Commute) - 30 คำ ---
    { thai: "ถนน", target: "Street", reading: "สตรีท", lang: "en-US" },
    { thai: "ถนนใหญ่ / อเวนิว", target: "Avenue", reading: "อเวนิว", lang: "en-US" },
    { thai: "ทางหลวง", target: "Highway", reading: "ไฮเวย์", lang: "en-US" },
    { thai: "การจราจร", target: "Traffic", reading: "ทราฟฟิก", lang: "en-US" },
    { thai: "ไฟจราจร", target: "Traffic light", reading: "ทราฟฟิก ไลต์", lang: "en-US" },
    { thai: "ทางเท้า", target: "Sidewalk", reading: "ไซด์วอล์ก", lang: "en-US" },
    { thai: "ทางม้าลาย", target: "Crosswalk", reading: "ครอสวอล์ก", lang: "en-US" },
    { thai: "รถไฟใต้ดิน", target: "Subway", reading: "ซับเวย์", lang: "en-US" },
    { thai: "ชานชาลา", target: "Platform", reading: "แพลตฟอร์ม", lang: "en-US" },
    { thai: "ผู้โดยสาร", target: "Passenger", reading: "พาสเซนเจอร์", lang: "en-US" },
    { thai: "การเดินทาง (ระยะไกล)", target: "Journey", reading: "เจอร์นีย์", lang: "en-US" },
    { thai: "การเดินทาง (ระยะสั้น)", target: "Trip", reading: "ทริป", lang: "en-US" },
    { thai: "การท่องเที่ยว", target: "Tour", reading: "ทัวร์", lang: "en-US" },
    { thai: "คนนำทาง / มัคคุเทศก์", target: "Guide", reading: "ไกด์", lang: "en-US" },
    { thai: "เส้นทาง", target: "Route", reading: "รูต", lang: "en-US" },
    { thai: "ค่าโดยสาร", target: "Fare", reading: "แฟร์", lang: "en-US" },
    { thai: "คิว / แถว", target: "Queue", reading: "คิว", lang: "en-US" },
    { thai: "ความล่าช้า", target: "Delay", reading: "ดีเลย์", lang: "en-US" },
    { thai: "อุบัติเหตุ", target: "Accident", reading: "แอคซิเดนท์", lang: "en-US" },
    { thai: "อันตราย (คำนาม)", target: "Danger", reading: "เดนเจอร์", lang: "en-US" },
    { thai: "ความปลอดภัย", target: "Safety", reading: "เซฟตี้", lang: "en-US" },
    { thai: "ฝูงชน", target: "Crowd", reading: "คราวด์", lang: "en-US" },
    { thai: "อาคาร", target: "Building", reading: "บิลดิง", lang: "en-US" },
    { thai: "ตึกระฟ้า", target: "Skyscraper", reading: "สกายสแครปเปอร์", lang: "en-US" },
    { thai: "อพาร์ตเมนต์", target: "Apartment", reading: "อพาร์ตเมนต์", lang: "en-US" },
    { thai: "ละแวกบ้าน", target: "Neighborhood", reading: "เนเบอร์ฮูด", lang: "en-US" },
    { thai: "เมืองหลวง", target: "Capital", reading: "แคปปิตอล", lang: "en-US" },
    { thai: "อนุสาวรีย์", target: "Monument", reading: "โมนิวเมนต์", lang: "en-US" },
    { thai: "พิพิธภัณฑ์", target: "Museum", reading: "มิวเซียม", lang: "en-US" },
    { thai: "สวนสัตว์", target: "Zoo", reading: "ซู", lang: "en-US" },

    // --- 30. หมวดเครื่องมือ วัสดุ และคุณลักษณะทางกายภาพ (Tools, Materials & Shapes) - 35 คำ ---
    { thai: "เครื่องมือ", target: "Tool", reading: "ทูล", lang: "en-US" },
    { thai: "ค้อน", target: "Hammer", reading: "แฮมเมอร์", lang: "en-US" },
    { thai: "ตะปู", target: "Nail", reading: "เนล", lang: "en-US" },
    { thai: "สกรู", target: "Screw", reading: "สกรู", lang: "en-US" },
    { thai: "ประแจ", target: "Wrench", reading: "เรนช์", lang: "en-US" },
    { thai: "กรรไกร", target: "Scissors", reading: "ซิสเซอร์ส", lang: "en-US" },
    { thai: "มีด", target: "Knife", reading: "ไนฟ์", lang: "en-US" },
    { thai: "ใบมีด", target: "Blade", reading: "เบลด", lang: "en-US" },
    { thai: "เครื่องจักร", target: "Machine", reading: "แมชชีน", lang: "en-US" },
    { thai: "เครื่องยนต์", target: "Engine", reading: "เอนจิน", lang: "en-US" },
    { thai: "มอเตอร์", target: "Motor", reading: "มอเตอร์", lang: "en-US" },
    { thai: "วัสดุ", target: "Material", reading: "แมททีเรียล", lang: "en-US" },
    { thai: "ไม้", target: "Wood", reading: "วูด", lang: "en-US" },
    { thai: "โลหะ", target: "Metal", reading: "เมทัล", lang: "en-US" },
    { thai: "เหล็ก", target: "Iron", reading: "ไอรอน", lang: "en-US" },
    { thai: "เหล็กกล้า", target: "Steel", reading: "สตีล", lang: "en-US" },
    { thai: "ทองแดง", target: "Copper", reading: "คอปเปอร์", lang: "en-US" },
    { thai: "พลาสติก", target: "Plastic", reading: "พลาสติก", lang: "en-US" },
    { thai: "ยาง", target: "Rubber", reading: "รับเบอร์", lang: "en-US" },
    { thai: "ฝ้าย", target: "Cotton", reading: "คอตตอน", lang: "en-US" },
    { thai: "หนัง (วัสดุ)", target: "Leather", reading: "เลเธอร์", lang: "en-US" },
    { thai: "กระดาษแข็ง", target: "Cardboard", reading: "การ์ดบอร์ด", lang: "en-US" },
    { thai: "เชือกหนา", target: "Rope", reading: "โรป", lang: "en-US" },
    { thai: "ลวด / สายไฟ", target: "Wire", reading: "ไวร์", lang: "en-US" },
    { thai: "เส้น", target: "Line", reading: "ไลน์", lang: "en-US" },
    { thai: "ส่วนโค้ง", target: "Curve", reading: "เคิร์ฟ", lang: "en-US" },
    { thai: "มุม", target: "Angle", reading: "แองเกิล", lang: "en-US" },
    { thai: "กลม", target: "Round", reading: "ราวน์", lang: "en-US" },
    { thai: "แบน", target: "Flat", reading: "แฟลต", lang: "en-US" },
    { thai: "แหลม / คม", target: "Sharp", reading: "ชาร์ป", lang: "en-US" },
    { thai: "เรียบ / ลื่น", target: "Smooth", reading: "สมูท", lang: "en-US" },
    { thai: "ขรุขระ", target: "Rough", reading: "รัฟ", lang: "en-US" },
    { thai: "นุ่ม", target: "Soft", reading: "ซอฟต์", lang: "en-US" },
    { thai: "แข็ง (วัสดุ)", target: "Hard", reading: "ฮาร์ด", lang: "en-US" },
    { thai: "ของแข็ง", target: "Solid", reading: "โซลิด", lang: "en-US" },

    // --- 31. หมวดสังคม การปกครอง และกระบวนการยุติธรรม (Society, Government & Justice) - 35 คำ ---
    { thai: "สังคม", target: "Society", reading: "โซไซตี้", lang: "en-US" },
    { thai: "วัฒนธรรม", target: "Culture", reading: "คัลเจอร์", lang: "en-US" },
    { thai: "ประเพณี", target: "Tradition", reading: "ทราดิชัน", lang: "en-US" },
    { thai: "รัฐบาล", target: "Government", reading: "กัฟเวิร์นเมนต์", lang: "en-US" },
    { thai: "การเมือง", target: "Politics", reading: "โพลิทิกส์", lang: "en-US" },
    { thai: "การเลือกตั้ง", target: "Election", reading: "อิเล็กชัน", lang: "en-US" },
    { thai: "ลงคะแนนเสียง", target: "Vote", reading: "โหวต", lang: "en-US" },
    { thai: "ประธานาธิบดี / ประธาน", target: "President", reading: "เพรสซิเดนท์", lang: "en-US" },
    { thai: "ผู้นำ", target: "Leader", reading: "ลีดเดอร์", lang: "en-US" },
    { thai: "พลเมือง", target: "Citizen", reading: "ซิติเซน", lang: "en-US" },
    { thai: "ชาติ / ประเทศ", target: "Nation", reading: "เนชัน", lang: "en-US" },
    { thai: "ชุมชน", target: "Community", reading: "คอมมูนิตี", lang: "en-US" },
    { thai: "นโยบาย", target: "Policy", reading: "โพลิซี", lang: "en-US" },
    { thai: "ข้อบังคับ / ระเบียบ", target: "Regulation", reading: "เรกกิวเลชัน", lang: "en-US" },
    { thai: "สิทธิ", target: "Rights", reading: "ไรตส์", lang: "en-US" },
    { thai: "หน้าที่", target: "Duty", reading: "ดิวตี้", lang: "en-US" },
    { thai: "ศาล", target: "Court", reading: "คอร์ต", lang: "en-US" },
    { thai: "ผู้พิพากษา", target: "Judge", reading: "จัดจ์", lang: "en-US" },
    { thai: "ทนายความ", target: "Lawyer", reading: "ลอว์เยอร์", lang: "en-US" },
    { thai: "เจ้าหน้าที่", target: "Officer", reading: "ออฟฟิสเซอร์", lang: "en-US" },
    { thai: "อาชญากรรม", target: "Crime", reading: "ไครม์", lang: "en-US" },
    { thai: "อาชญากร", target: "Criminal", reading: "คริมินอล", lang: "en-US" },
    { thai: "คุก / เรือนจำ", target: "Prison", reading: "พริซัน", lang: "en-US" },
    { thai: "ขโมย (คน)", target: "Thief", reading: "ธีฟ", lang: "en-US" },
    { thai: "การป้องกัน", target: "Protection", reading: "โพรเทกชัน", lang: "en-US" },
    { thai: "สันติภาพ", target: "Peace", reading: "พีซ", lang: "en-US" },
    { thai: "สงคราม", target: "War", reading: "วอร์", lang: "en-US" },
    { thai: "กองทัพบก", target: "Army", reading: "อาร์มี่", lang: "en-US" },
    { thai: "อาวุธ", target: "Weapon", reading: "เวพอน", lang: "en-US" },
    { thai: "ปืน", target: "Gun", reading: "กัน", lang: "en-US" },
    { thai: "ประชากร", target: "Population", reading: "ป็อปปิวเลชัน", lang: "en-US" },
    { thai: "ชายแดน", target: "Border", reading: "บอร์เดอร์", lang: "en-US" },
    { thai: "ธง", target: "Flag", reading: "แฟลก", lang: "en-US" },
    { thai: "สาธารณะ", target: "Public", reading: "พับลิก", lang: "en-US" },
    { thai: "ส่วนตัว", target: "Private", reading: "ไพรเวต", lang: "en-US" },
	// --- 32. หมวดคำบุพบทและคำเชื่อมประโยค (Prepositions & Conjunctions) - 30 คำ ---
    { thai: "ใน / ข้างใน", target: "In", reading: "อิน", lang: "en-US" },
    { thai: "บน / ข้างบน", target: "On", reading: "ออน", lang: "en-US" },
    { thai: "ที่", target: "At", reading: "แอท", lang: "en-US" },
    { thai: "โดย / ด้วย", target: "By", reading: "บาย", lang: "en-US" },
    { thai: "สำหรับ / เพื่อ", target: "For", reading: "ฟอร์", lang: "en-US" },
    { thai: "กับ / ด้วย", target: "With", reading: "วิธ", lang: "en-US" },
    { thai: "เกี่ยวกับ", target: "About", reading: "อะเบาต์", lang: "en-US" },
    { thai: "ต่อต้าน / แข่งกับ", target: "Against", reading: "อะเกนสต์", lang: "en-US" },
    { thai: "ระหว่าง (สองสิ่ง)", target: "Between", reading: "บีทวีน", lang: "en-US" },
    { thai: "เข้าไปใน", target: "Into", reading: "อินทู", lang: "en-US" },
    { thai: "ทะลุผ่าน", target: "Through", reading: "ธรู", lang: "en-US" },
    { thai: "ระหว่าง (เวลา)", target: "During", reading: "ดูริง", lang: "en-US" },
    { thai: "ก่อน", target: "Before", reading: "บีฟอร์", lang: "en-US" },
    { thai: "หลังจาก", target: "After", reading: "อาฟเตอร์", lang: "en-US" },
    { thai: "เหนือ / สูงกว่า", target: "Above", reading: "อะบัฟ", lang: "en-US" },
    { thai: "ใต้ / ต่ำกว่า", target: "Below", reading: "บีโลว์", lang: "en-US" },
    { thai: "จาก", target: "From", reading: "ฟรอม", lang: "en-US" },
    { thai: "ขึ้น", target: "Up", reading: "อัป", lang: "en-US" },
    { thai: "ลง", target: "Down", reading: "ดาวน์", lang: "en-US" },
    { thai: "ออก / ข้างนอก", target: "Out", reading: "เอาต์", lang: "en-US" },
    { thai: "และ", target: "And", reading: "แอนด์", lang: "en-US" },
    { thai: "แต่", target: "But", reading: "บัต", lang: "en-US" },
    { thai: "หรือ", target: "Or", reading: "ออร์", lang: "en-US" },
    { thai: "เพราะว่า", target: "Because", reading: "บีคอส", lang: "en-US" },
    { thai: "ถ้า / หาก", target: "If", reading: "อีฟ", lang: "en-US" },
    { thai: "ดังนั้น", target: "So", reading: "โซ", lang: "en-US" },
    { thai: "แม้ว่า", target: "Although", reading: "ออลโธ", lang: "en-US" },
    { thai: "จนกระทั่ง", target: "Until", reading: "อันทิล", lang: "en-US" },
    { thai: "เว้นแต่ว่า", target: "Unless", reading: "อันเลส", lang: "en-US" },
    { thai: "ตั้งแต่ / เนื่องจาก", target: "Since", reading: "ซินซ์", lang: "en-US" },

    // --- 33. หมวดคำวิเศษณ์บอกเวลา สถานที่ และความถี่ (Common Adverbs) - 30 คำ ---
    { thai: "เสมอ / ตลอด", target: "Always", reading: "ออลเวย์ส", lang: "en-US" },
    { thai: "มักจะ / เป็นประจำ", target: "Usually", reading: "ยูชวลลี", lang: "en-US" },
    { thai: "บ่อยๆ", target: "Often", reading: "ออฟเทน", lang: "en-US" },
    { thai: "บางครั้ง", target: "Sometimes", reading: "ซัมไทมส์", lang: "en-US" },
    { thai: "ไม่เคย", target: "Never", reading: "เนเวอร์", lang: "en-US" },
    { thai: "มาก", target: "Very", reading: "เวรี", lang: "en-US" },
    { thai: "เกินไป / ก็ด้วย", target: "Too", reading: "ทู", lang: "en-US" },
    { thai: "ค่อนข้าง", target: "Quite", reading: "ไควต์", lang: "en-US" },
    { thai: "จริงๆ / อย่างแท้จริง", target: "Really", reading: "เรียลลี", lang: "en-US" },
    { thai: "อย่างแน่นอน / เป๊ะ", target: "Exactly", reading: "เอ็กแซกต์ลี", lang: "en-US" },
    { thai: "เกือบจะ", target: "Almost", reading: "ออลโมสต์", lang: "en-US" },
    { thai: "เรียบร้อยแล้ว", target: "Already", reading: "ออลเรดี้", lang: "en-US" },
    { thai: "ยังคง", target: "Still", reading: "สติล", lang: "en-US" },
    { thai: "ยัง (รูปปฏิเสธ/คำถาม)", target: "Yet", reading: "เย็ต", lang: "en-US" },
    { thai: "เพิ่งจะ / แค่", target: "Just", reading: "จัสต์", lang: "en-US" },
    { thai: "เท่านั้น / เพียงแค่", target: "Only", reading: "โอนลี", lang: "en-US" },
    { thai: "บางที", target: "Maybe", reading: "เมบี", lang: "en-US" },
    { thai: "อาจจะ", target: "Perhaps", reading: "เพอร์แฮปส์", lang: "en-US" },
    { thai: "ทันทีทันใด", target: "Suddenly", reading: "ซัดเดนลี", lang: "en-US" },
    { thai: "อย่างรวดเร็ว", target: "Quickly", reading: "ควิกลี", lang: "en-US" },
    { thai: "อย่างช้าๆ", target: "Slowly", reading: "สโลว์ลี", lang: "en-US" },
    { thai: "อย่างระมัดระวัง", target: "Carefully", reading: "แคร์ฟูลลี", lang: "en-US" },
    { thai: "อย่างง่ายดาย", target: "Easily", reading: "อีซีลี", lang: "en-US" },
    { thai: "ดี (คำวิเศษณ์)", target: "Well", reading: "เวล", lang: "en-US" },
    { thai: "ที่นี่", target: "Here", reading: "เฮียร์", lang: "en-US" },
    { thai: "ที่นั่น", target: "There", reading: "แดร์", lang: "en-US" },
    { thai: "ทุกที่", target: "Everywhere", reading: "เอฟวรีแวร์", lang: "en-US" },
    { thai: "บางที่", target: "Somewhere", reading: "ซัมแวร์", lang: "en-US" },
    { thai: "ไม่มีที่ไหน", target: "Nowhere", reading: "โนแวร์", lang: "en-US" },
    { thai: "ที่ไหนก็ได้", target: "Anywhere", reading: "เอนีแวร์", lang: "en-US" },

    // --- 34. หมวดปริมาณ ขนาด และการวัด (Quantities & Measurements) - 25 คำ ---
    { thai: "ทั้งหมด", target: "All", reading: "ออล", lang: "en-US" },
    { thai: "บ้าง / บางส่วน", target: "Some", reading: "ซัม", lang: "en-US" },
    { thai: "บ้าง (รูปปฏิเสธ/คำถาม)", target: "Any", reading: "เอนี", lang: "en-US" },
    { thai: "มาก (นับได้)", target: "Many", reading: "เมนี", lang: "en-US" },
    { thai: "มาก (นับไม่ได้)", target: "Much", reading: "มัช", lang: "en-US" },
    { thai: "น้อย (นับได้)", target: "Few", reading: "ฟิว", lang: "en-US" },
    { thai: "น้อย (นับไม่ได้)", target: "Little", reading: "ลิตเทิล", lang: "en-US" },
    { thai: "ชิ้น", target: "Piece", reading: "พีซ", lang: "en-US" },
    { thai: "แผ่น / ชิ้นบางๆ", target: "Slice", reading: "สไลซ์", lang: "en-US" },
    { thai: "หยด", target: "Drop", reading: "ดรอป", lang: "en-US" },
    { thai: "ปอนด์ (น้ำหนัก)", target: "Pound", reading: "พาวนด์", lang: "en-US" },
    { thai: "กิโลกรัม", target: "Kilo", reading: "กิโล", lang: "en-US" },
    { thai: "เมตร", target: "Meter", reading: "มีเตอร์", lang: "en-US" },
    { thai: "ลิตร", target: "Liter", reading: "ลิเทอร์", lang: "en-US" },
    { thai: "โหล (12 ชิ้น)", target: "Dozen", reading: "ดัซเซิน", lang: "en-US" },
    { thai: "ครึ่ง", target: "Half", reading: "ฮาล์ฟ", lang: "en-US" },
    { thai: "หนึ่งในสี่", target: "Quarter", reading: "ควอร์เตอร์", lang: "en-US" },
    { thai: "ยอดรวม", target: "Total", reading: "โททอล", lang: "en-US" },
    { thai: "จำนวน / ปริมาณ (นับไม่ได้)", target: "Amount", reading: "อะเมาต์", lang: "en-US" },
    { thai: "ตัวเลข / จำนวน (นับได้)", target: "Number", reading: "นัมเบอร์", lang: "en-US" },
    { thai: "น้ำหนัก", target: "Weight", reading: "เวท", lang: "en-US" },
    { thai: "ความยาว", target: "Length", reading: "เลงธ์", lang: "en-US" },
    { thai: "ความสูง", target: "Height", reading: "ไฮต์", lang: "en-US" },
    { thai: "ความลึก", target: "Depth", reading: "เดปธ์", lang: "en-US" },
    { thai: "ความกว้าง", target: "Width", reading: "วิดธ์", lang: "en-US" },

    // --- 35. หมวดจักรวาล วิทยาศาสตร์ และธรรมชาติ (Universe & Basic Science) - 15 คำ ---
    { thai: "จักรวาล", target: "Universe", reading: "ยูนิเวิร์ส", lang: "en-US" },
    { thai: "ดาราจักร / กาแล็กซี", target: "Galaxy", reading: "กาแล็กซี", lang: "en-US" },
    { thai: "ดาวเคราะห์", target: "Planet", reading: "แพลเน็ต", lang: "en-US" },
    { thai: "อวกาศ / พื้นที่ว่าง", target: "Space", reading: "สเปซ", lang: "en-US" },
    { thai: "อะตอม", target: "Atom", reading: "อะตอม", lang: "en-US" },
    { thai: "พลังงาน", target: "Energy", reading: "เอเนอร์จี", lang: "en-US" },
    { thai: "แรงโน้มถ่วง", target: "Gravity", reading: "กราวิตี", lang: "en-US" },
    { thai: "ฟิสิกส์", target: "Physics", reading: "ฟิสิกส์", lang: "en-US" },
    { thai: "เคมี", target: "Chemistry", reading: "เคมิสทรี", lang: "en-US" },
    { thai: "ชีววิทยา", target: "Biology", reading: "ไบโอโลจี", lang: "en-US" },
    { thai: "เซลล์", target: "Cell", reading: "เซลล์", lang: "en-US" },
    { thai: "ธรรมชาติ", target: "Nature", reading: "เนเจอร์", lang: "en-US" },
    { thai: "ก๊าซ", target: "Gas", reading: "แก๊ส", lang: "en-US" },
    { thai: "ของเหลว", target: "Liquid", reading: "ลิควิด", lang: "en-US" },
    { thai: "การทดลอง", target: "Experiment", reading: "เอ็กซ์เพอริเมนต์", lang: "en-US" }
]; // สิ้นสุดอาเรย์ ตัวแปร wordsEN สมบูรณ์ 1,000 คำ