const wordsJP = [
    // --- 1. หมวดบุคคลและสรรพนาม (People & Pronouns) - 20 คำ ---
    { thai: "ฉัน / ผม", target: "私", reading: "วาตาชิ", lang: "ja-JP" },
    { thai: "คุณ", target: "あなた", reading: "อานาตะ", lang: "ja-JP" },
    { thai: "เขา (ผู้ชาย)", target: "彼", reading: "คาเระ", lang: "ja-JP" },
    { thai: "เธอ (ผู้หญิง)", target: "彼女", reading: "คาโนโจะ", lang: "ja-JP" },
    { thai: "พวกเรา", target: "私たち", reading: "วาตาชิตาจิ", lang: "ja-JP" },
    { thai: "พวกเขา", target: "彼ら", reading: "คาเระระ", lang: "ja-JP" },
    { thai: "มัน", target: "それ", reading: "โซเระ", lang: "ja-JP" },
    { thai: "ฉัน (กรรม)", target: "私を", reading: "วาตาชิ โอะ", lang: "ja-JP" },
    { thai: "เขา (กรรม)", target: "彼を", reading: "คาเระ โอะ", lang: "ja-JP" },
    { thai: "เธอ (กรรม)", target: "彼女を", reading: "คาโนโจะ โอะ", lang: "ja-JP" },
    { thai: "พวกเรา (กรรม)", target: "私たちを", reading: "วาตาชิตาจิ โอะ", lang: "ja-JP" },
    { thai: "พวกเขา (กรรม)", target: "彼らを", reading: "คาเระระ โอะ", lang: "ja-JP" },
    { thai: "ผู้ชาย", target: "男性", reading: "ดันเซย์", lang: "ja-JP" },
    { thai: "ผู้หญิง", target: "女性", reading: "โจเซย์", lang: "ja-JP" },
    { thai: "เด็กผู้ชาย", target: "男の子", reading: "โอโตโกะ โนะ โกะ", lang: "ja-JP" },
    { thai: "เด็กผู้หญิง", target: "女の子", reading: "อนนะ โนะ โกะ", lang: "ja-JP" },
    { thai: "เพื่อน", target: "友達", reading: "โทโมดาจิ", lang: "ja-JP" },
    { thai: "ครอบครัว", target: "家族", reading: "คาโซกุ", lang: "ja-JP" },
    { thai: "บุคคล (คนเดียว)", target: "人", reading: "ฮิโตะ", lang: "ja-JP" },
    { thai: "ผู้คน (หลายคน)", target: "人々", reading: "ฮิโตบิโตะ", lang: "ja-JP" },

    // --- 2. หมวดร่างกาย (Body Parts) - 20 คำ ---
    { thai: "หัว", target: "頭", reading: "อาตามะ", lang: "ja-JP" },
    { thai: "ผม", target: "髪", reading: "คามิ", lang: "ja-JP" },
    { thai: "ตา", target: "目", reading: "เมะ", lang: "ja-JP" },
    { thai: "หู", target: "耳", reading: "มิมิ", lang: "ja-JP" },
    { thai: "จมูก", target: "鼻", reading: "ฮานะ", lang: "ja-JP" },
    { thai: "ปาก", target: "口", reading: "คุจิ", lang: "ja-JP" },
    { thai: "ฟัน", target: "歯", reading: "ฮะ", lang: "ja-JP" },
    { thai: "ใบหน้า", target: "顔", reading: "คาโอะ", lang: "ja-JP" },
    { thai: "คอ", target: "首", reading: "คุบิ", lang: "ja-JP" },
    { thai: "ไหล่", target: "肩", reading: "คาตะ", lang: "ja-JP" },
    { thai: "แขน", target: "腕", reading: "อุเดะ", lang: "ja-JP" },
    { thai: "มือ", target: "手", reading: "เทะ", lang: "ja-JP" },
    { thai: "นิ้วมือ", target: "指", reading: "ยูบิ", lang: "ja-JP" },
    { thai: "ขา", target: "足", reading: "อาชิ", lang: "ja-JP" },
    { thai: "เท้า", target: "足", reading: "อาชิ", lang: "ja-JP" },
    { thai: "นิ้วเท้า", target: "足の指", reading: "อาชิ โนะ ยูบิ", lang: "ja-JP" },
    { thai: "หลัง", target: "背中", reading: "เซนากะ", lang: "ja-JP" },
    { thai: "หัวใจ", target: "心臓", reading: "ชินโซ", lang: "ja-JP" },
    { thai: "เลือด", target: "血", reading: "จิ", lang: "ja-JP" },
    { thai: "กระดูก", target: "骨", reading: "โฮเนะ", lang: "ja-JP" },

    // --- 3. หมวดครอบครัวและญาติ (Family & Relatives) - 15 คำ ---
    { thai: "พ่อ", target: "父", reading: "จิจิ", lang: "ja-JP" },
    { thai: "แม่", target: "母", reading: "ฮาฮะ", lang: "ja-JP" },
    { thai: "ผู้ปกครอง / พ่อแม่", target: "親", reading: "โอยะ", lang: "ja-JP" },
    { thai: "ลูกชาย", target: "息子", reading: "มุสึโกะ", lang: "ja-JP" },
    { thai: "ลูกสาว", target: "娘", reading: "มุสึเมะ", lang: "ja-JP" },
    { thai: "พี่ชาย / น้องชาย", target: "兄弟", reading: "เคียวได", lang: "ja-JP" },
    { thai: "พี่สาว / น้องสาว", target: "姉妹", reading: "ชิไม", lang: "ja-JP" },
    { thai: "ปู่ / ตา", target: "祖父", reading: "โซฟุ", lang: "ja-JP" },
    { thai: "ย่า / ยาย", target: "祖母", reading: "โซโบะ", lang: "ja-JP" },
    { thai: "ลุง / น้าชาย / อาชาย", target: "叔父", reading: "โอจิ", lang: "ja-JP" },
    { thai: "ป้า / น้าหญิง / อาหญิง", target: "叔母", reading: "โอบะ", lang: "ja-JP" },
    { thai: "ลูกพี่ลูกน้อง", target: "いとこ", reading: "อิโตโกะ", lang: "ja-JP" },
    { thai: "สามี", target: "夫", reading: "อตโตะ", lang: "ja-JP" },
    { thai: "ภรรยา", target: "妻", reading: "สึมะ", lang: "ja-JP" },
    { thai: "เด็ก / ลูก", target: "子供", reading: "โคโดโมะ", lang: "ja-JP" },

    // --- 4. หมวดเวลา (Time & Calendar) - 20 คำ ---
    { thai: "วินาที", target: "秒", reading: "เบียว", lang: "ja-JP" },
    { thai: "นาที", target: "分", reading: "ฟุน", lang: "ja-JP" },
    { thai: "ชั่วโมง", target: "時間", reading: "จิคัง", lang: "ja-JP" },
    { thai: "วัน", target: "日", reading: "ฮิ", lang: "ja-JP" },
    { thai: "สัปดาห์", target: "週", reading: "ชู", lang: "ja-JP" },
    { thai: "เดือน", target: "月", reading: "สึกิ", lang: "ja-JP" },
    { thai: "ปี", target: "年", reading: "โทชิ", lang: "ja-JP" },
    { thai: "ตอนเช้า", target: "朝", reading: "อาสะ", lang: "ja-JP" },
    { thai: "ตอนบ่าย", target: "午後", reading: "โกโกะ", lang: "ja-JP" },
    { thai: "ตอนเย็น / ค่ำ", target: "夕方", reading: "ยูงาตะ", lang: "ja-JP" },
    { thai: "ตอนกลางคืน", target: "夜", reading: "โยรุ", lang: "ja-JP" },
    { thai: "วันนี้", target: "今日", reading: "เคียว", lang: "ja-JP" },
    { thai: "พรุ่งนี้", target: "明日", reading: "อาชิตะ", lang: "ja-JP" },
    { thai: "เมื่อวานนี้", target: "昨日", reading: "คิโน", lang: "ja-JP" },
    { thai: "ตอนนี้ / ปัจจุบัน", target: "今", reading: "อิม่ะ", lang: "ja-JP" },
    { thai: "ตอนนั้น / หลังจากนั้น", target: "その時", reading: "โซโนะ โทกิ", lang: "ja-JP" },
    { thai: "อนาคต", target: "未来", reading: "มิไร", lang: "ja-JP" },
    { thai: "อดีต", target: "過去", reading: "คาโกะ", lang: "ja-JP" },
    { thai: "ปัจจุบัน / ของขวัญ", target: "現在", reading: "เก็นไซ", lang: "ja-JP" },
    { thai: "เวลา", target: "時間", reading: "จิคัง", lang: "ja-JP" },

    // --- 5. หมวดธรรมชาติและสิ่งแวดล้อม (Nature & Environment) - 25 คำ ---
    { thai: "ดวงอาทิตย์", target: "太陽", reading: "ไทโย", lang: "ja-JP" },
    { thai: "ดวงจันทร์", target: "月", reading: "สึกิ", lang: "ja-JP" },
    { thai: "ดาว", target: "星", reading: "โฮชิ", lang: "ja-JP" },
    { thai: "ท้องฟ้า", target: "空", reading: "โซระ", lang: "ja-JP" },
    { thai: "เมฆ", target: "雲", reading: "คุโมะ", lang: "ja-JP" },
    { thai: "ฝน", target: "雨", reading: "อาเมะ", lang: "ja-JP" },
    { thai: "ลม", target: "風", reading: "คาเสะ", lang: "ja-JP" },
    { thai: "หิมะ", target: "雪", reading: "ยูกิ", lang: "ja-JP" },
    { thai: "ไฟ", target: "火", reading: "ฮิ", lang: "ja-JP" },
    { thai: "น้ำ", target: "水", reading: "มิซุ", lang: "ja-JP" },
    { thai: "โลก (ดาวเคราะห์) / ดิน", target: "地球", reading: "จิคิว", lang: "ja-JP" },
    { thai: "โลก (รวมทั้งหมด)", target: "世界", reading: "เซไก", lang: "ja-JP" },
    { thai: "ต้นไม้", target: "木", reading: "คิ", lang: "ja-JP" },
    { thai: "ดอกไม้", target: "花", reading: "ฮานะ", lang: "ja-JP" },
    { thai: "หญ้า", target: "草", reading: "คุซะ", lang: "ja-JP" },
    { thai: "สัตว์", target: "動物", reading: "โดบุตสึ", lang: "ja-JP" },
    { thai: "นก", target: "鳥", reading: "โทริ", lang: "ja-JP" },
    { thai: "ปลา", target: "魚", reading: "ซาคานะ", lang: "ja-JP" },
    { thai: "สุนัข", target: "犬", reading: "อินุ", lang: "ja-JP" },
    { thai: "แมว", target: "猫", reading: "เนโกะ", lang: "ja-JP" },
    { thai: "ภูเขา", target: "山", reading: "ยามะ", lang: "ja-JP" },
    { thai: "แม่น้ำ", target: "川", reading: "คาวะ", lang: "ja-JP" },
    { thai: "ทะเล", target: "海", reading: "อุมิ", lang: "ja-JP" },
    { thai: "หิน", target: "岩", reading: "อิวะ", lang: "ja-JP" },
    { thai: "ทราย", target: "砂", reading: "สึนะ", lang: "ja-JP" },

    // --- 6. หมวดกริยาและการกระทำ (Common Action Verbs) - 35 คำ ---
    { thai: "กิน", target: "食べる", reading: "ทาเบรุ", lang: "ja-JP" },
    { thai: "ดื่ม", target: "飲む", reading: "โนมุ", lang: "ja-JP" },
    { thai: "นอน", target: "寝る", reading: "เนรุ", lang: "ja-JP" },
    { thai: "วิ่ง", target: "走る", reading: "ฮาชิรุ", lang: "ja-JP" },
    { thai: "เดิน", target: "歩く", reading: "อารุกุ", lang: "ja-JP" },
    { thai: "กระโดด", target: "跳ぶ", reading: "โทบุ", lang: "ja-JP" },
    { thai: "อ่าน", target: "読む", reading: "โยมุ", lang: "ja-JP" },
    { thai: "เขียน", target: "書く", reading: "คากุ", lang: "ja-JP" },
    { thai: "ฟัง", target: "聞く", reading: "คิกุ", lang: "ja-JP" },
    { thai: "พูด", target: "話す", reading: "ฮานาสุ", lang: "ja-JP" },
    { thai: "ดู / มอง", target: "見る", reading: "มิรุ", lang: "ja-JP" },
    { thai: "คิด", target: "考える", reading: "คันงาเอรุ", lang: "ja-JP" },
    { thai: "ทำงาน", target: "働く", reading: "ฮาตารากุ", lang: "ja-JP" },
    { thai: "เรียน", target: "学ぶ", reading: "มานาบุ", lang: "ja-JP" },
    { thai: "สอน", target: "教える", reading: "โอชิเอรุ", lang: "ja-JP" },
    { thai: "ซื้อ", target: "買う", reading: "คาอุ", lang: "ja-JP" },
    { thai: "ขาย", target: "売る", reading: "อุรุ", lang: "ja-JP" },
    { thai: "ทำ / สร้าง", target: "作る", reading: "สึคุรุ", lang: "ja-JP" },
    { thai: "ให้", target: "与える", reading: "อาทาเอรุ", lang: "ja-JP" },
    { thai: "รับ", target: "受け取る", reading: "อุเคโตรุ", lang: "ja-JP" },
    { thai: "ถือ / จับ", target: "持つ", reading: "โมตสึ", lang: "ja-JP" },
    { thai: "เปิด", target: "開ける", reading: "อาเครุ", lang: "ja-JP" },
    { thai: "ปิด", target: "閉める", reading: "ชิเมรุ", lang: "ja-JP" },
    { thai: "ขับรถ", target: "運転する", reading: "อุนเต็น สุรุ", lang: "ja-JP" },
    { thai: "ขี่ / ปั่น", target: "乗る", reading: "โนรุ", lang: "ja-JP" },
    { thai: "ว่ายน้ำ", target: "泳ぐ", reading: "โอโยงุ", lang: "ja-JP" },
    { thai: "บิน", target: "飛ぶ", reading: "โทบุ", lang: "ja-JP" },
    { thai: "หัวเราะ", target: "笑う", reading: "วาราอุ", lang: "ja-JP" },
    { thai: "ร้องไห้", target: "泣く", reading: "นากุ", lang: "ja-JP" },
    { thai: "ยิ้ม", target: "微笑む", reading: "โฮโฮเอมุ", lang: "ja-JP" },
    { thai: "รอ", target: "待つ", reading: "มัตสึ", lang: "ja-JP" },
    { thai: "หยุด", target: "止まる", reading: "โทมารุ", lang: "ja-JP" },
    { thai: "ช่วย", target: "助ける", reading: "ทาสุเครุ", lang: "ja-JP" },
    { thai: "เล่น", target: "遊ぶ", reading: "อาโซบุ", lang: "ja-JP" },
    { thai: "ร้องเพลง", target: "歌う", reading: "อุตาอุ", lang: "ja-JP" },

    // --- 7. หมวดสีสัน (Colors) - 15 คำ ---
    { thai: "สีแดง", target: "赤", reading: "อากะ", lang: "ja-JP" },
    { thai: "สีน้ำเงิน", target: "青", reading: "อาโอะ", lang: "ja-JP" },
    { thai: "สีเขียว", target: "緑", reading: "มิโดริ", lang: "ja-JP" },
    { thai: "สีเหลือง", target: "黄色", reading: "คีโระ", lang: "ja-JP" },
    { thai: "สีดำ", target: "黒", reading: "คุโระ", lang: "ja-JP" },
    { thai: "สีขาว", target: "白", reading: "ชิโระ", lang: "ja-JP" },
    { thai: "สีส้ม", target: "オレンジ", reading: "โอเรนจิ", lang: "ja-JP" },
    { thai: "สีชมพู", target: "ピンク", reading: "พิงคุ", lang: "ja-JP" },
    { thai: "สีม่วง", target: "紫", reading: "มุราซากิ", lang: "ja-JP" },
    { thai: "สีน้ำตาล", target: "茶色", reading: "จาอิโระ", lang: "ja-JP" },
    { thai: "สีเทา", target: "灰色", reading: "ไฮอิโระ", lang: "ja-JP" },
    { thai: "สีทอง", target: "金色", reading: "คินอิโระ", lang: "ja-JP" },
    { thai: "สีเงิน", target: "銀色", reading: "กินอิโระ", lang: "ja-JP" },
    { thai: "สีสัน", target: "色", reading: "อิโระ", lang: "ja-JP" },
    { thai: "สว่าง", target: "明るい", reading: "อาคารุย", lang: "ja-JP" },

    // --- 8. หมวดสิ่งของรอบตัวและในบ้าน (House & Objects) - 30 คำ ---
    { thai: "บ้าน", target: "家", reading: "อิเอะ", lang: "ja-JP" },
    { thai: "ห้อง", target: "部屋", reading: "เฮยะ", lang: "ja-JP" },
    { thai: "ประตู", target: "ドア", reading: "ดัว", lang: "ja-JP" },
    { thai: "หน้าต่าง", target: "窓", reading: "มาโดะ", lang: "ja-JP" },
    { thai: "โต๊ะ", target: "テーブル", reading: "เทบุรุ", lang: "ja-JP" },
    { thai: "เก้าอี้", target: "椅子", reading: "อิสุ", lang: "ja-JP" },
    { thai: "เตียง", target: "ベッド", reading: "เบดโดะ", lang: "ja-JP" },
    { thai: "หมอน", target: "枕", reading: "มาคุระ", lang: "ja-JP" },
    { thai: "ผ้าห่ม", target: "毛布", reading: "โมฟุ", lang: "ja-JP" },
    { thai: "โทรศัพท์", target: "電話", reading: "เดนวะ", lang: "ja-JP" },
    { thai: "คอมพิวเตอร์", target: "コンピューター", reading: "คอมพิวตา", lang: "ja-JP" },
    { thai: "หนังสือ", target: "本", reading: "ฮง", lang: "ja-JP" },
    { thai: "ปากกา", target: "ペン", reading: "เพน", lang: "ja-JP" },
    { thai: "กระดาษ", target: "紙", reading: "คามิ", lang: "ja-JP" },
    { thai: "กระเป๋า", target: "バッグ", reading: "บักกุ", lang: "ja-JP" },
    { thai: "กุญแจ", target: "鍵", reading: "คางิ", lang: "ja-JP" },
    { thai: "เงิน", target: "お金", reading: "โอกาเนะ", lang: "ja-JP" },
    { thai: "แก้วน้ำ", target: "グラス", reading: "กุราสุ", lang: "ja-JP" },
    { thai: "จาน", target: "皿", reading: "ซาระ", lang: "ja-JP" },
    { thai: "ช้อน", target: "スプーン", reading: "สุปูน", lang: "ja-JP" },
    { thai: "ส้อม", target: "フォーク", reading: "โฟกุ", lang: "ja-JP" },
    { thai: "รถยนต์", target: "車", reading: "คุรุมะ", lang: "ja-JP" },
    { thai: "จักรยาน", target: "自転車", reading: "จิเตนชะ", lang: "ja-JP" },
    { thai: "นาฬิกา", target: "時計", reading: "โทเค", lang: "ja-JP" },
    { thai: "เสื้อผ้า", target: "服", reading: "ฟุกุ", lang: "ja-JP" },
    { thai: "รองเท้า", target: "靴", reading: "คุตสึ", lang: "ja-JP" },
    { thai: "แว่นตา", target: "眼鏡", reading: "เมกาเนะ", lang: "ja-JP" },
    { thai: "ไฟ / หลอดไฟ", target: "電灯", reading: "เดนโต", lang: "ja-JP" },
    { thai: "พัดลม", target: "扇風機", reading: "เซมปูกิ", lang: "ja-JP" },
    { thai: "กล่อง", target: "箱", reading: "ฮาโกะ", lang: "ja-JP" },

    // --- 9. หมวดอาหารและเครื่องดื่ม (Food & Drink) - 20 คำ ---
    { thai: "ข้าว", target: "ご飯", reading: "โกฮัง", lang: "ja-JP" },
    { thai: "ขนมปัง", target: "パン", reading: "ปัง", lang: "ja-JP" },
    { thai: "เนื้อสัตว์", target: "肉", reading: "นิกุ", lang: "ja-JP" },
    { thai: "ไก่", target: "鶏肉", reading: "โทรินิกุ", lang: "ja-JP" },
    { thai: "ไข่", target: "卵", reading: "ทามาโกะ", lang: "ja-JP" },
    { thai: "ผัก", target: "野菜", reading: "ยาไซ", lang: "ja-JP" },
    { thai: "ผลไม้", target: "果物", reading: "คุดาโมโนะ", lang: "ja-JP" },
    { thai: "นม", target: "牛乳", reading: "กิวนิว", lang: "ja-JP" },
    { thai: "น้ำเปล่า", target: "水", reading: "มิซุ", lang: "ja-JP" },
    { thai: "กาแฟ", target: "コーヒー", reading: "โคฮี", lang: "ja-JP" },
    { thai: "ชา", target: "お茶", reading: "โอจะ", lang: "ja-JP" },
    { thai: "น้ำตาล", target: "砂糖", reading: "ซาโต", lang: "ja-JP" },
    { thai: "เกลือ", target: "塩", reading: "ชิโอะ", lang: "ja-JP" },
    { thai: "เผ็ด", target: "辛い", reading: "คารัย", lang: "ja-JP" },
    { thai: "หวาน", target: "甘い", reading: "อามาย", lang: "ja-JP" },
    { thai: "เปรี้ยว", target: "酸っぱい", reading: "ซุปปาย", lang: "ja-JP" },
    { thai: "เค็ม", target: "しょっぱい", reading: "ชปปาย", lang: "ja-JP" },
    { thai: "ขม", target: "苦い", reading: "นิगाय", lang: "ja-JP" },
    { thai: "ร้อน", target: "熱い", reading: "อาทสึย", lang: "ja-JP" },
    { thai: "เย็น", target: "冷たい", reading: "ทสึเมตาย", lang: "ja-JP" },

    // --- 10. หมวดสถานที่และอาคาร (Places & Buildings) - 30 คำ ---
    { thai: "โรงเรียน", target: "学校", reading: "กักโค", lang: "ja-JP" },
    { thai: "โรงพยาบาล", target: "病院", reading: "เบียวอิน", lang: "ja-JP" },
    { thai: "ธนาคาร", target: "銀行", reading: "กิงโค", lang: "ja-JP" },
    { thai: "ร้านอาหาร", target: "レストラン", reading: "เรสึโตรัน", lang: "ja-JP" },
    { thai: "โรงแรม", target: "ホテル", reading: "โฮเตะรุ", lang: "ja-JP" },
    { thai: "ตลาด", target: "市場", reading: "อิจิบะ", lang: "ja-JP" },
    { thai: "สำนักงาน / ออฟฟิศ", target: "オフィス", reading: "โอฟิสึ", lang: "ja-JP" },
    { thai: "ร้านค้า", target: "店", reading: "มิเสะ", lang: "ja-JP" },
    { thai: "ห้างสรรพสินค้า", target: "ショッピングモール", reading: "ชอปปิงงุมอรุ", lang: "ja-JP" },
    { thai: "สนามบิน", target: "空港", reading: "คูโค", lang: "ja-JP" },
    { thai: "สถานี", target: "駅", reading: "เอกิ", lang: "ja-JP" },
    { thai: "สวนสาธารณะ", target: "公園", reading: "โคเอน", lang: "ja-JP" },
    { thai: "ห้องสมุด", target: "図書館", reading: "โทโชคัง", lang: "ja-JP" },
    { thai: "วัด", target: "お寺", reading: "โอเทระ", lang: "ja-JP" },
    { thai: "เมือง", target: "街", reading: "มาจิ", lang: "ja-JP" },
    { thai: "หมู่บ้าน", target: "村", reading: "มุระ", lang: "ja-JP" },
    { thai: "ประเทศ", target: "国", reading: "คุนิ", lang: "ja-JP" },
    { thai: "ถนน", target: "道", reading: "มิจิ", lang: "ja-JP" },
    { thai: "ทางแยก", target: "交差点", reading: "โคซาเต็น", lang: "ja-JP" },
    { thai: "สะพาน", target: "橋", reading: "ฮาชิ", lang: "ja-JP" },
    { thai: "ฟาร์ม", target: "農場", reading: "โนโจ", lang: "ja-JP" },
    { thai: "โรงงาน", target: "工場", reading: "โคโจ", lang: "ja-JP" },
    { thai: "สวน", target: "庭", reading: "นิวะ", lang: "ja-JP" },
    { thai: "ห้องน้ำ", target: "トイレ", reading: "โทอิเระ", lang: "ja-JP" },
    { thai: "ห้องครัว", target: "キッチン", reading: "คิตชิน", lang: "ja-JP" },
    { thai: "ห้องนอน", target: "寝室", reading: "ชินชิตสึ", lang: "ja-JP" },
    { thai: "ชั้นบน", target: "上の階", reading: "อุเอะ โนะ ไค", lang: "ja-JP" },
    { thai: "ชั้นล่าง", target: "下の階", reading: "ชิตะ โนะ ไค", lang: "ja-JP" },
    { thai: "มุม", target: "角", reading: "คาโดะ", lang: "ja-JP" },
    { thai: "ใจกลางเมือง", target: "都心", reading: "โทชิน", lang: "ja-JP" },
	, // --- 11. หมวดการเดินทางและยานพาหนะ (Travel & Vehicles) - 20 คำ ---
    { thai: "เครื่องบิน", target: "飛行機", reading: "ฮิโคคิ", lang: "ja-JP" },
    { thai: "เรือ", target: "船", reading: "ฟุเนะ", lang: "ja-JP" },
    { thai: "รถไฟ", target: "電車", reading: "เดนชะ", lang: "ja-JP" },
    { thai: "รถเมล์ / รถบัส", target: "バス", reading: "บาสุ", lang: "ja-JP" },
    { thai: "มอเตอร์ไซค์", target: "バイク", reading: "ไบกุ", lang: "ja-JP" },
    { thai: "ตั๋ว", target: "チケット", reading: "จิเกตโตะ", lang: "ja-JP" },
    { thai: "แผนที่", target: "地図", reading: "จิซุ", lang: "ja-JP" },
    { thai: "สัมภาระ / กระเป๋าเดินทาง", target: "荷物", reading: "นิโมตสึ", lang: "ja-JP" },
    { thai: "พาสปอร์ต", target: "パスポート", reading: "พาสุโปโตะ", lang: "ja-JP" },
    { thai: "เที่ยวบิน", target: "フライト", reading: "ฟุไรโตะ", lang: "ja-JP" },
    { thai: "โรงแรม", target: "ホテル", reading: "โฮเตะรุ", lang: "ja-JP" },
    { thai: "ท่องเที่ยว", target: "観光", reading: "คังโค", lang: "ja-JP" },
    { thai: "ทิศทาง", target: "方向", reading: "โฮโค", lang: "ja-JP" },
    { thai: "ทางเหนือ", target: "北", reading: "คิตะ", lang: "ja-JP" },
    { thai: "ทางใต้", target: "南", reading: "มินามิ", lang: "ja-JP" },
    { thai: "ทางตะวันออก", target: "東", reading: "ฮิงาชิ", lang: "ja-JP" },
    { thai: "ทางตะวันตก", target: "西", reading: "นิชิ", lang: "ja-JP" },
    { thai: "ตรงไป", target: "まっすぐ", reading: "มัสซึงุ", lang: "ja-JP" },
    { thai: "เลี้ยว", target: "曲がる", reading: "มางารุ", lang: "ja-JP" },
    { thai: "มาถึง", target: "到着する", reading: "โทจาคุ สุรุ", lang: "ja-JP" },

    // --- 12. หมวดคำคุณศัพท์พื้นฐาน (Basic Adjectives) - 50 คำ ---
    { thai: "ใหญ่", target: "大きい", reading: "โอคี", lang: "ja-JP" },
    { thai: "เล็ก", target: "小さい", reading: "จีไซ", lang: "ja-JP" },
    { thai: "สูง", target: "高い", reading: "ทาไค", lang: "ja-JP" },
    { thai: "ต่ำ", target: "低い", reading: "ฮิคุย", lang: "ja-JP" },
    { thai: "ยาว", target: "長い", reading: "นางาย", lang: "ja-JP" },
    { thai: "สั้น", target: "短い", reading: "มิจิไค", lang: "ja-JP" },
    { thai: "กว้าง", target: "広い", reading: "ฮิรอย", lang: "ja-JP" },
    { thai: "แคบ", target: "狭い", reading: "เซมาย", lang: "ja-JP" },
    { thai: "หนา", target: "厚い", reading: "อัทสึย", lang: "ja-JP" },
    { thai: "บาง", target: "薄い", reading: "อุซุย", lang: "ja-JP" },
    { thai: "หนัก", target: "重い", reading: "โอมอย", lang: "ja-JP" },
    { thai: "เบา", target: "軽い", reading: "คารุย", lang: "ja-JP" },
    { thai: "ยาก", target: "難しい", reading: "มุซึคาชี", lang: "ja-JP" },
    { thai: "ง่าย", target: "簡単", reading: "คันตัน", lang: "ja-JP" },
    { thai: "ดี", target: "良い", reading: "โย่ย", lang: "ja-JP" },
    { thai: "แย่", target: "悪い", reading: "วารุย", lang: "ja-JP" },
    { thai: "สวย", target: "きれい", reading: "คิเร", lang: "ja-JP" },
    { thai: "น่าเกลียด", target: "醜い", reading: "มินิคุย", lang: "ja-JP" },
    { thai: "ร้อน", target: "暑い", reading: "อัทสึย", lang: "ja-JP" },
    { thai: "หนาว", target: "寒い", reading: "ซามุย", lang: "ja-JP" },
    { thai: "เร็ว", target: "速い", reading: "ฮายาย", lang: "ja-JP" },
    { thai: "ช้า", target: "遅い", reading: "โอซอย", lang: "ja-JP" },
    { thai: "ใหม่", target: "新しい", reading: "อาทาราชี", lang: "ja-JP" },
    { thai: "เก่า / แก่", target: "古い", reading: "ฟุรุย", lang: "ja-JP" },
    { thai: "แพง", target: "高い", reading: "ทาไค", lang: "ja-JP" },
    { thai: "ถูก", target: "安い", reading: "ยาสุย", lang: "ja-JP" },
    { thai: "รวย", target: "裕福", reading: "ยูฟุคุ", lang: "ja-JP" },
    { thai: "จน", target: "貧しい", reading: "มาซึชี", lang: "ja-JP" },
    { thai: "สะอาด", target: "清潔", reading: "เซเคตสึ", lang: "ja-JP" },
    { thai: "สกปรก", target: "汚い", reading: "คิตานาย", lang: "ja-JP" },
    { thai: "เต็ม", target: "いっぱい", reading: "อิปปาย", lang: "ja-JP" },
    { thai: "ว่างเปล่า", target: "空", reading: "คาระ", lang: "ja-JP" },
    { thai: "ดัง", target: "うるさい", reading: "อุรุซาย", lang: "ja-JP" },
    { thai: "เงียบ", target: "静か", reading: "ชิซึกะ", lang: "ja-JP" },
    { thai: "มีความสุข", target: "幸せ", reading: "ชิอาวาเสะ", lang: "ja-JP" },
    { thai: "เศร้า", target: "悲しい", reading: "คานาชี", lang: "ja-JP" },
    { thai: "โกรธ", target: "怒る", reading: "โอโครุ", lang: "ja-JP" },
    { thai: "หิว", target: "お腹が空いた", reading: "โอนากะ งะ ซุยตะ", lang: "ja-JP" },
    { thai: "กระหายน้ำ", target: "喉が渇く", reading: "โนโดะ งะ คาวาคุ", lang: "ja-JP" },
    { thai: "เหนื่อย", target: "疲れた", reading: "ทสึคาเรตะ", lang: "ja-JP" },
    { thai: "ป่วย", target: "病気", reading: "เบียวกิ", lang: "ja-JP" },
    { thai: "แข็งแรง", target: "強い", reading: "ทสึโยย", lang: "ja-JP" },
    { thai: "อ่อนแอ", target: "弱い", reading: "โยวาย", lang: "ja-JP" },
    { thai: "ฉลาด", target: "賢い", reading: "คาชิคอย", lang: "ja-JP" },
    { thai: "โง่", target: "馬鹿", reading: "บากะ", lang: "ja-JP" },
    { thai: "ปลอดภัย", target: "安全", reading: "อันเซ็น", lang: "ja-JP" },
    { thai: "อันตราย", target: "危険", reading: "คิเคน", lang: "ja-JP" },
    { thai: "น่าสนใจ", target: "面白い", reading: "โอโมชิรอย", lang: "ja-JP" },
    { thai: "น่าเบื่อ", target: "つまらない", reading: "ทสึมารานาย", lang: "ja-JP" },
    { thai: "สำคัญ", target: "重要", reading: "จูโย", lang: "ja-JP" },

    // --- 13. หมวดอาชีพ (Occupations) - 25 คำ ---
    { thai: "พนักงาน", target: "従業員", reading: "จูเกียวอิน", lang: "ja-JP" },
    { thai: "นายจ้าง / หัวหน้า", target: "上司", reading: "โจชิ", lang: "ja-JP" },
    { thai: "ผู้จัดการ", target: "マネージャー", reading: "มาเนจา", lang: "ja-JP" },
    { thai: "พนักงานขาย", target: "店員", reading: "เต็นอิน", lang: "ja-JP" },
    { thai: "วิศวกร", target: "エンジニア", reading: "เอนจิเนีย", lang: "ja-JP" },
    { thai: "หมอ", target: "医者", reading: "อิชะ", lang: "ja-JP" },
    { thai: "พยาบาล", target: "看護師", reading: "คังโงชิ", lang: "ja-JP" },
    { thai: "ครู", target: "先生", reading: "เซนเซ", lang: "ja-JP" },
    { thai: "ตำรวจ", target: "警察官", reading: "เคซัตสึคัง", lang: "ja-JP" },
    { thai: "ทหาร", target: "兵士", reading: "เฮชิ", lang: "ja-JP" },
    { thai: "นักบิน", target: "パイロット", reading: "ไพรอตโตะ", lang: "ja-JP" },
    { thai: "พ่อครัว", target: "シェフ", reading: "เชฟุ", lang: "ja-JP" },
    { thai: "พนักงานเสิร์ฟ", target: "ウェイター", reading: "เวย์ตา", lang: "ja-JP" },
    { thai: "คนขับรถ", target: "運転手", reading: "อุนเตนชุ", lang: "ja-JP" },
    { thai: "นักเขียน", target: "作家", reading: "ซักกะ", lang: "ja-JP" },
    { thai: "ศิลปิน", target: "芸術家", reading: "เกจุตสึคะ", lang: "ja-JP" },
    { thai: "นักธุรกิจ", target: "ビジネスマン", reading: "บิจิเนสึมัง", lang: "ja-JP" },
    { thai: "เลขานุการ", target: "秘書", reading: "ฮิโชะ", lang: "ja-JP" },
    { thai: "ช่างภาพ", target: "カメラマン", reading: "คาเมรามัง", lang: "ja-JP" },
    { thai: "นักออกแบบ", target: "デザイナー", reading: "ดีไซนา", lang: "ja-JP" },
    { thai: "ชาวนา / เกษตรกร", target: "農家", reading: "โนกะ", lang: "ja-JP" },
    { thai: "นักแสดง", target: "俳優", reading: "ไฮยู", lang: "ja-JP" },
    { thai: "นักดนตรี", target: "音楽家", reading: "องงาคุคะ", lang: "ja-JP" },
    { thai: "อาชีพ", target: "職業", reading: "โชคุเกียว", lang: "ja-JP" },
    { thai: "งาน", target: "仕事", reading: "ชิโกโตะ", lang: "ja-JP" },

    // --- 14. หมวดธุรกิจและการตลาด (Business & Marketing) - 40 คำ ---
    { thai: "บริษัท", target: "会社", reading: "ไคชะ", lang: "ja-JP" },
    { thai: "ธุรกิจ", target: "ビジネス", reading: "บิจิเนสึ", lang: "ja-JP" },
    { thai: "ลูกค้า", target: "お客様", reading: "โอกยาคุซามะ", lang: "ja-JP" },
    { thai: "บริการ", target: "サービス", reading: "ซาบิสึ", lang: "ja-JP" },
    { thai: "ผลิตภัณฑ์ / สินค้า", target: "製品", reading: "เซฮิน", lang: "ja-JP" },
    { thai: "แบรนด์ / ยี่ห้อ", target: "ブランド", reading: "บุรันโดะ", lang: "ja-JP" },
    { thai: "ราคา", target: "価格", reading: "คาคาคุ", lang: "ja-JP" },
    { thai: "ส่วนลด", target: "割引", reading: "วาริบิกิ", lang: "ja-JP" },
    { thai: "โฆษณา", target: "広告", reading: "โคโคคุ", lang: "ja-JP" },
    { thai: "ยอดขาย", target: "売上", reading: "อุริอาเงะ", lang: "ja-JP" },
    { thai: "การตลาด", target: "マーケティング", reading: "มาเกตติงงุ", lang: "ja-JP" },
    { thai: "กำไร", target: "利益", reading: "ริเอกิ", lang: "ja-JP" },
    { thai: "ขาดทุน", target: "損失", reading: "ซนชิตสึ", lang: "ja-JP" },
    { thai: "คู่แข่ง", target: "ライバル", reading: "ไรบารุ", lang: "ja-JP" },
    { thai: "กลยุทธ์", target: "戦略", reading: "เซนเรียคุ", lang: "ja-JP" },
    { thai: "โอกาส", target: "チャンス", reading: "จันสุ", lang: "ja-JP" },
    { thai: "สัญญา", target: "契約", reading: "เคยาคุ", lang: "ja-JP" },
    { thai: "ข้อตกลง", target: "合意", reading: "โกอิ", lang: "ja-JP" },
    { thai: "หุ้น", target: "株", reading: "คาบุ", lang: "ja-JP" },
    { thai: "การลงทุน", target: "投資", reading: "โทชิ", lang: "ja-JP" },
    { thai: "เป้าหมาย", target: "目標", reading: "โมคุเฮียว", lang: "ja-JP" },
    { thai: "ความสำเร็จ", target: "成功", reading: "เซโค", lang: "ja-JP" },
    { thai: "ล้มเหลว", target: "失敗", reading: "ชิปปาย", lang: "ja-JP" },
    { thai: "การเติบโต", target: "成長", reading: "เซโจ", lang: "ja-JP" },
    { thai: "คุณภาพ", target: "品質", reading: "ฮินชิตสึ", lang: "ja-JP" },
    { thai: "ปริมาณ", target: "数量", reading: "ซูเรียว", lang: "ja-JP" },
    { thai: "ภาษี", target: "税金", reading: "เซคิน", lang: "ja-JP" },
    { thai: "ใบแจ้งหนี้", target: "請求書", reading: "เซคิวโชะ", lang: "ja-JP" },
    { thai: "ใบเสร็จ", target: "領収書", reading: "เรียวชูโชะ", lang: "ja-JP" },
    { thai: "ธนาคาร", target: "銀行", reading: "กิงโค", lang: "ja-JP" },
    { thai: "บัญชี", target: "口座", reading: "โคซะ", lang: "ja-JP" },
    { thai: "บัตรเครดิต", target: "クレジットカード", reading: "คุเรจิตโตะ คาโดะ", lang: "ja-JP" },
    { thai: "เงินสด", target: "現金", reading: "เกงคิน", lang: "ja-JP" },
    { thai: "ค่าใช้จ่าย", target: "費用", reading: "ฮิโย", lang: "ja-JP" },
    { thai: "งบประมาณ", target: "予算", reading: "โยซัง", lang: "ja-JP" },
    { thai: "หนี้", target: "借金", reading: "ชักคิน", lang: "ja-JP" },
    { thai: "ความมั่งคั่ง", target: "富", reading: "โทมิ", lang: "ja-JP" },
    { thai: "เศรษฐกิจ", target: "経済", reading: "เคไซ", lang: "ja-JP" },
    { thai: "ตลาด", target: "市場", reading: "ชิโจ", lang: "ja-JP" },
    { thai: "อุตสาหกรรม", target: "産業", reading: "ซังเกียว", lang: "ja-JP" },

    // --- 15. หมวดการสื่อสารและอุปกรณ์ในออฟฟิศ (Office & Communication) - 35 คำ ---
    { thai: "การประชุม", target: "会議", reading: "ไคงิ", lang: "ja-JP" },
    { thai: "การนำเสนอ", target: "プレゼンテーション", reading: "พุเรเซนเตชง", lang: "ja-JP" },
    { thai: "รายงาน", target: "レポート", reading: "เรโปโตะ", lang: "ja-JP" },
    { thai: "โครงการ", target: "プロジェクト", reading: "พุโรเจกโตะ", lang: "ja-JP" },
    { thai: "กำหนดส่ง", target: "締め切り", reading: "ชิเมคิริ", lang: "ja-JP" },
    { thai: "ตารางเวลา", target: "スケジュール", reading: "สุเคจูรุ", lang: "ja-JP" },
    { thai: "ข้อมูล", target: "情報", reading: "โจโฮ", lang: "ja-JP" },
    { thai: "อีเมล", target: "メール", reading: "เมรุ", lang: "ja-JP" },
    { thai: "ข้อความ", target: "メッセージ", reading: "เมสเสจิ", lang: "ja-JP" },
    { thai: "โทรศัพท์", target: "電話", reading: "เดนวะ", lang: "ja-JP" },
    { thai: "แล็ปท็อป", target: "ノートパソコン", reading: "โนโตะ พาโซคง", lang: "ja-JP" },
    { thai: "เครื่องพิมพ์", target: "プリンター", reading: "พุรินตา", lang: "ja-JP" },
    { thai: "เอกสาร", target: "書類", reading: "โชรุย", lang: "ja-JP" },
    { thai: "ไฟล์ / แฟ้ม", target: "ファイル", reading: "ไฟรุ", lang: "ja-JP" },
    { thai: "อินเทอร์เน็ต", target: "インターネット", reading: "อินตาเนตโตะ", lang: "ja-JP" },
    { thai: "รหัสผ่าน", target: "パスワード", reading: "พาสุวาโดะ", lang: "ja-JP" },
    { thai: "หน้าจอ", target: "画面", reading: "กาเมน", lang: "ja-JP" },
    { thai: "แป้นพิมพ์", target: "キーボード", reading: "คีโบโดะ", lang: "ja-JP" },
    { thai: "เมาส์", target: "マウス", reading: "เมาซึ", lang: "ja-JP" },
    { thai: "ซอฟต์แวร์", target: "ソフトウェア", reading: "โซฟุโตะแวอะ", lang: "ja-JP" },
    { thai: "ฮาร์ดแวร์", target: "ハードウェア", reading: "ฮาโดะแวอะ", lang: "ja-JP" },
    { thai: "การสื่อสาร", target: "コミュニケーション", reading: "โคมิวนิเคชง", lang: "ja-JP" },
    { thai: "เครือข่าย", target: "ネットワーク", reading: "เนตโตะวากุ", lang: "ja-JP" },
    { thai: "ทีม", target: "チーム", reading: "จีมุ", lang: "ja-JP" },
    { thai: "ความร่วมมือ", target: "協力", reading: "เคียวเรียคุ", lang: "ja-JP" },
    { thai: "ความคิดเห็น", target: "フィードバック", reading: "ฟีโดะบักกุ", lang: "ja-JP" },
    { thai: "การตัดสินใจ", target: "決定", reading: "เคตเต", lang: "ja-JP" },
    { thai: "ปัญหา", target: "問題", reading: "มนได", lang: "ja-JP" },
    { thai: "วิธีแก้ปัญหา", target: "解決策", reading: "ไคเคตสึซาคุ", lang: "ja-JP" },
    { thai: "นวัตกรรม", target: "イノベーション", reading: "อิโนเบชง", lang: "ja-JP" },
    { thai: "ความคิดสร้างสรรค์", target: "創造性", reading: "โซโซเซ", lang: "ja-JP" },
    { thai: "ทักษะ", target: "スキル", reading: "สุกิรุ", lang: "ja-JP" },
    { thai: "ประสบการณ์", target: "経験", reading: "เคเคน", lang: "ja-JP" },
    { thai: "ความรู้", target: "知識", reading: "จิชิกิ", lang: "ja-JP" },
    { thai: "เป้าหมาย", target: "ターゲット", reading: "ทาเกตโตะ", lang: "ja-JP" },

    // --- 16. หมวดเทคโนโลยีและฮาร์ดแวร์ (Technology & Hardware) - 25 คำ ---
    { thai: "เทคโนโลยี", target: "テクノロジー", reading: "เทคุโนโรจี", lang: "ja-JP" },
    { thai: "อุปกรณ์", target: "デバイス", reading: "เดไบซึ", lang: "ja-JP" },
    { thai: "มือถือ", target: "モバイル", reading: "โมไบรุ", lang: "ja-JP" },
    { thai: "เซิร์ฟเวอร์", target: "サーバー", reading: "ซาบา", lang: "ja-JP" },
    { thai: "หน้าจอ", target: "スクリーン", reading: "สุกุรีน", lang: "ja-JP" },
    { thai: "แบตเตอรี่", target: "バッテリー", reading: "บัตเตอรี", lang: "ja-JP" },
    { thai: "สายเคเบิล", target: "ケーブル", reading: "เคบุรุ", lang: "ja-JP" },
    { thai: "ไร้สาย", target: "ワイヤレス", reading: "ไวยาเรซึ", lang: "ja-JP" },
    { thai: "บลูทูธ", target: "ブルートゥース", reading: "บูรูตูซึ", lang: "ja-JP" },
    { thai: "เราเตอร์", target: "ルーター", reading: "รูตา", lang: "ja-JP" },
    { thai: "สวิตช์", target: "スイッチ", reading: "สุอิจจิ", lang: "ja-JP" },
    { thai: "หน่วยความจำ", target: "メモリ", reading: "เมโมริ", lang: "ja-JP" },
    { thai: "ตัวประมวลผล", target: "プロセッサ", reading: "พุโรเซสซะ", lang: "ja-JP" },
    { thai: "ที่เก็บข้อมูล", target: "ストレージ", reading: "สุโตเรจิ", lang: "ja-JP" },
    { thai: "ระบบคลาวด์", target: "クラウド", reading: "คุเราโดะ", lang: "ja-JP" },
    { thai: "เบราว์เซอร์", target: "ブラウザ", reading: "บุเราซะ", lang: "ja-JP" },
    { thai: "แอปพลิเคชัน", target: "アプリケーション", reading: "อาพุริเคชง", lang: "ja-JP" },
    { thai: "ดาวน์โหลด", target: "ダウンロード", reading: "ดาวนโรโดะ", lang: "ja-JP" },
    { thai: "อัปโหลด", target: "アップロード", reading: "อัปปุโรโดะ", lang: "ja-JP" },
    { thai: "ติดตั้ง", target: "インストール", reading: "อินสุโตรุ", lang: "ja-JP" },
    { thai: "อัปเดต", target: "アップデート", reading: "อัปปุเดโตะ", lang: "ja-JP" },
    { thai: "อัปเกรด", target: "アップグレード", reading: "อัปปุเกรโดะ", lang: "ja-JP" },
    { thai: "เวอร์ชัน", target: "バージョン", reading: "บาจง", lang: "ja-JP" },
    { thai: "ระบบ", target: "システム", reading: "ชิซุเตมุ", lang: "ja-JP" },
    { thai: "แพลตฟอร์ม", target: "プラットフォーム", reading: "พุรัตโตะโฟมุ", lang: "ja-JP" },

    // --- 17. หมวดการพัฒนาเว็บและโปรแกรมมิ่ง (Web Development & Programming) - 40 คำ ---
    { thai: "โค้ด / รหัส", target: "コード", reading: "โคโดะ", lang: "ja-JP" },
    { thai: "โปรแกรม", target: "プログラム", reading: "พุโรกุรามุ", lang: "ja-JP" },
    { thai: "นักพัฒนา", target: "開発者", reading: "ไคฮัตสึชะ", lang: "ja-JP" },
    { thai: "ฟังก์ชัน", target: "関数", reading: "คันซู", lang: "ja-JP" },
    { thai: "ตัวแปร", target: "変数", reading: "เฮนซู", lang: "ja-JP" },
    { thai: "อาเรย์ / ชุดข้อมูล", target: "配列", reading: "ไฮเรตสึ", lang: "ja-JP" },
    { thai: "อ็อบเจกต์", target: "オブジェクト", reading: "โอบุเจกโตะ", lang: "ja-JP" },
    { thai: "ข้อความ (สตริง)", target: "文字列", reading: "โมจิเรตสึ", lang: "ja-JP" },
    { thai: "จำนวนเต็ม", target: "整数", reading: "เซซู", lang: "ja-JP" },
    { thai: "บูลีน (ตรรกะ)", target: "真偽値", reading: "ชินงิจิ", lang: "ja-JP" },
    { thai: "วนลูป", target: "ループ", reading: "รูปุ", lang: "ja-JP" },
    { thai: "เงื่อนไข", target: "条件", reading: "โจเคน", lang: "ja-JP" },
    { thai: "คำสั่ง", target: "文", reading: "บุน", lang: "ja-JP" },
    { thai: "ข้อผิดพลาด", target: "エラー", reading: "เอรา", lang: "ja-JP" },
    { thai: "บั๊ก / จุดบกพร่อง", target: "バグ", reading: "บากุ", lang: "ja-JP" },
    { thai: "แก้บั๊ก", target: "デバッグ", reading: "เดบักกุ", lang: "ja-JP" },
    { thai: "สคริปต์", target: "スクリプト", reading: "สุคุริปุโตะ", lang: "ja-JP" },
    { thai: "ระบบหน้าบ้าน", target: "フロントエンド", reading: "ฟุรอนโตะเอนโดะ", lang: "ja-JP" },
    { thai: "ระบบหลังบ้าน", target: "バックエンド", reading: "บักคุเอนโดะ", lang: "ja-JP" },
    { thai: "ฐานข้อมูล", target: "データベース", reading: "เดตาเบซึ", lang: "ja-JP" },
    { thai: "คำสืบค้น", target: "クエリ", reading: "คุเอริ", lang: "ja-JP" },
    { thai: "เอพีไอ", target: "API", reading: "เอพีไอ", lang: "ja-JP" },
    { thai: "เฟรมเวิร์ก", target: "フレームワーク", reading: "ฟุเรมุวากุ", lang: "ja-JP" },
    { thai: "ไลบรารี", target: "ライブラリ", reading: "ไรบุราริ", lang: "ja-JP" },
    { thai: "คลังเก็บโค้ด", target: "リポジトリ", reading: "ริโพจิโตริ", lang: "ja-JP" },
    { thai: "บันทึกการเปลี่ยน", target: "コミット", reading: "โคมิตโตะ", lang: "ja-JP" },
    { thai: "ดันโค้ด", target: "プッシュ", reading: "พุชชุ", lang: "ja-JP" },
    { thai: "ดึงโค้ด", target: "プル", reading: "พุรุ", lang: "ja-JP" },
    { thai: "สาขา (โค้ด)", target: "ブランチ", reading: "บุรันจิ", lang: "ja-JP" },
    { thai: "รวม (โค้ด)", target: "マージ", reading: "มาจิ", lang: "ja-JP" },
    { thai: "ไวยากรณ์ (โค้ด)", target: "構文", reading: "โคบุน", lang: "ja-JP" },
    { thai: "แท็ก", target: "タグ", reading: "ทากุ", lang: "ja-JP" },
    { thai: "คุณลักษณะ", target: "属性", reading: "โซคุเซ", lang: "ja-JP" },
    { thai: "องค์ประกอบ", target: "要素", reading: "โยโซะ", lang: "ja-JP" },
    { thai: "ปลั๊กอิน", target: "プラグイン", reading: "พุรากุอิน", lang: "ja-JP" },
    { thai: "โมดูล", target: "モジュール", reading: "โมจูรุ", lang: "ja-JP" },
    { thai: "ส่วนประกอบ", target: "コンポーネント", reading: "คอมโปเนนโตะ", lang: "ja-JP" },
    { thai: "แม่แบบ", target: "テンプレート", reading: "เทมพุเรโตะ", lang: "ja-JP" },
    { thai: "โฮสต์", target: "ホスト", reading: "โฮสุโตะ", lang: "ja-JP" },
    { thai: "โดเมน", target: "ドメイン", reading: "โดเมน", lang: "ja-JP" },

    // --- 18. หมวดข้อมูล, UI/UX และตรรกะ (Data, UI/UX & Logic) - 35 คำ ---
    { thai: "ข้อมูล", target: "データ", reading: "เดตา", lang: "ja-JP" },
    { thai: "ตรรกะ", target: "ロジック", reading: "โรจิกกุ", lang: "ja-JP" },
    { thai: "อินเทอร์เฟส / หน้าจอ", target: "インターフェース", reading: "อินทาเฟซึ", lang: "ja-JP" },
    { thai: "ผู้ใช้", target: "ユーザー", reading: "ยูซา", lang: "ja-JP" },
    { thai: "การออกแบบ", target: "デザイン", reading: "ดีไซน", lang: "ja-JP" },
    { thai: "โครงร่าง / เค้าโครง", target: "レイアウト", reading: "เรเอาโตะ", lang: "ja-JP" },
    { thai: "การนำทาง", target: "ナビゲーション", reading: "นาบิเงชง", lang: "ja-JP" },
    { thai: "ปุ่ม", target: "ボタン", reading: "โบตัง", lang: "ja-JP" },
    { thai: "ลิงก์ / จุดเชื่อมโยง", target: "リンク", reading: "ริงคุ", lang: "ja-JP" },
    { thai: "ไอคอน", target: "アイコン", reading: "ไอคง", lang: "ja-JP" },
    { thai: "เมนู", target: "メニュー", reading: "เมนิว", lang: "ja-JP" },
    { thai: "ค้นหา", target: "検索", reading: "เคนซาคุ", lang: "ja-JP" },
    { thai: "กรอง", target: "フィルター", reading: "ฟิรุตา", lang: "ja-JP" },
    { thai: "เรียงลำดับ", target: "ソート", reading: "โซโตะ", lang: "ja-JP" },
    { thai: "นำเข้า / ข้อมูลเข้า", target: "入力", reading: "นิวเรียวคุ", lang: "ja-JP" },
    { thai: "ส่งออก / ผลลัพธ์", target: "出力", reading: "ชุตสึเรียวคุ", lang: "ja-JP" },
    { thai: "คลิก", target: "クリック", reading: "คุริกกุ", lang: "ja-JP" },
    { thai: "เลื่อน (จอ)", target: "スクロール", reading: "สุคุโรรุ", lang: "ja-JP" },
    { thai: "ปัด (หน้าจอ)", target: "スワイプ", reading: "สุไวพุ", lang: "ja-JP" },
    { thai: "วางเมาส์เหนือ", target: "ホバー", reading: "โฮบา", lang: "ja-JP" },
    { thai: "โฟกัส", target: "フォーカス", reading: "โฟกาสุ", lang: "ja-JP" },
    { thai: "ใช้งานอยู่", target: "アクティブ", reading: "อาคุติบุ", lang: "ja-JP" },
    { thai: "ค่าเริ่มต้น", target: "デフォルト", reading: "เดโฟรุโตะ", lang: "ja-JP" },
    { thai: "การตั้งค่า", target: "設定", reading: "เซตเต", lang: "ja-JP" },
    { thai: "โปรไฟล์", target: "プロフィール", reading: "พุโรฟีรุ", lang: "ja-JP" },
    { thai: "บัญชี", target: "アカウント", reading: "อะเคาน์โตะ", lang: "ja-JP" },
    { thai: "เข้าสู่ระบบ", target: "ログイン", reading: "โรกุอิน", lang: "ja-JP" },
    { thai: "ออกจากระบบ", target: "ログアウト", reading: "โรกุเอาโตะ", lang: "ja-JP" },
    { thai: "สมัครสมาชิก", target: "登録", reading: "โทโรคุ", lang: "ja-JP" },
    { thai: "ความปลอดภัย", target: "セキュリティ", reading: "เซคิวริตี", lang: "ja-JP" },
    { thai: "ความเป็นส่วนตัว", target: "プライバシー", reading: "พุไรบาชี", lang: "ja-JP" },
    { thai: "การเข้าถึง", target: "アクセス", reading: "อาคุเซซึ", lang: "ja-JP" },
    { thai: "โทเคน (รหัส)", target: "トークン", reading: "โทคุน", lang: "ja-JP" },
    { thai: "เซสชัน", target: "セッション", reading: "เซสชง", lang: "ja-JP" },
    { thai: "คุกกี้ (ข้อมูล)", target: "クッキー", reading: "คุกคี", lang: "ja-JP" },
	, // --- 19. หมวดสุขภาพ โภชนาการ และการดูแลร่างกาย (Health & Nutrition) - 30 คำ ---
    { thai: "สุขภาพ", target: "健康", reading: "เคนโค", lang: "ja-JP" },
    { thai: "สุขภาพดี", target: "健康的", reading: "เคนโคเทกิ", lang: "ja-JP" },
    { thai: "โภชนาการ", target: "栄養", reading: "เอย์โย", lang: "ja-JP" },
    { thai: "ระบบเผาผลาญ", target: "代謝", reading: "ไทชะ", lang: "ja-JP" },
    { thai: "แคลอรี", target: "カロリー", reading: "คาโรรี", lang: "ja-JP" },
    { thai: "โปรตีน", target: "タンパク質", reading: "ทัมปาคุชิตสึ", lang: "ja-JP" },
    { thai: "วิตามิน", target: "ビタミン", reading: "บิตามิน", lang: "ja-JP" },
    { thai: "แร่ธาตุ", target: "ミネラル", reading: "มิเนรารุ", lang: "ja-JP" },
    { thai: "ไขมัน", target: "脂肪", reading: "ชิโบ", lang: "ja-JP" },
    { thai: "คาร์โบไฮเดรต", target: "炭水化物", reading: "ทันซุยคาบุตสึ", lang: "ja-JP" },
    { thai: "เส้นใยอาหาร", target: "食物繊維", reading: "โชคุมตสึเซ็นอิ", lang: "ja-JP" },
    { thai: "กล้ามเนื้อ", target: "筋肉", reading: "คินนิกุ", lang: "ja-JP" },
    { thai: "น้ำหนัก", target: "体重", reading: "ไทจู", lang: "ja-JP" },
    { thai: "ส่วนสูง", target: "身長", reading: "ชินโจ", lang: "ja-JP" },
    { thai: "ความสมบูรณ์ของร่างกาย", target: "フィットネス", reading: "ฟิตโตะเนสึ", lang: "ja-JP" },
    { thai: "โรงยิม", target: "ジム", reading: "จิมุ", lang: "ja-JP" },
    { thai: "ออกกำลังกาย (หนัก)", target: "ワークアウト", reading: "วากุเอาโตะ", lang: "ja-JP" },
    { thai: "เหงื่อ", target: "汗", reading: "อาเสะ", lang: "ja-JP" },
    { thai: "การพักผ่อน", target: "休息", reading: "คิวโซคุ", lang: "ja-JP" },
    { thai: "การฟื้นฟู", target: "回復", reading: "ไคฟุคุ", lang: "ja-JP" },
    { thai: "โรคภัย", target: "病気", reading: "เบียวกิ", lang: "ja-JP" },
    { thai: "ยารักษาโรค", target: "薬", reading: "คุซุริ", lang: "ja-JP" },
    { thai: "คลินิก", target: "クリニック", reading: "คุรินิกกุ", lang: "ja-JP" },
    { thai: "การบำบัด", target: "セラピー", reading: "เซราพี", lang: "ja-JP" },
    { thai: "อาหารเสริม", target: "サプリメント", reading: "ซาปุริเมนโตะ", lang: "ja-JP" },
    { thai: "การย่อยอาหาร", target: "消化", reading: "โชกะ", lang: "ja-JP" },
    { thai: "ภูมิคุ้มกัน", target: "免疫", reading: "เมนเอกิ", lang: "ja-JP" },
    { thai: "ออกซิเจน", target: "酸素", reading: "ซันโซะ", lang: "ja-JP" },
    { thai: "โยเกิร์ต", target: "ヨーグルト", reading: "โยงุรุโตะ", lang: "ja-JP" },
    { thai: "เมล็ดพืช", target: "種", reading: "ทาเนะ", lang: "ja-JP" },

    // --- 20. หมวดการเงิน การลงทุน และสินทรัพย์ (Finance & Investment) - 40 คำ ---
    { thai: "การเงิน", target: "金融", reading: "คินยู", lang: "ja-JP" },
    { thai: "สินทรัพย์", target: "資産", reading: "ชิซัง", lang: "ja-JP" },
    { thai: "หนี้สิน", target: "負債", reading: "ฟุไซ", lang: "ja-JP" },
    { thai: "กองทุน", target: "ファンド", reading: "ฟันโดะ", lang: "ja-JP" },
    { thai: "กองทุนรวม", target: "投資信託", reading: "โทชิชินตาคุ", lang: "ja-JP" },
    { thai: "คริปโตเคอร์เรนซี", target: "暗号資産", reading: "อันโกชิซัง", lang: "ja-JP" },
    { thai: "บิตคอยน์", target: "ビットコイン", reading: "บิตโตะคอยน์", lang: "ja-JP" },
    { thai: "เงินปันผล", target: "配当", reading: "ไฮโต", lang: "ja-JP" },
    { thai: "ดอกเบี้ย", target: "利子", reading: "ริชิ", lang: "ja-JP" },
    { thai: "อัตรา", target: "レート", reading: "เรโตะ", lang: "ja-JP" },
    { thai: "เงินเฟ้อ", target: "インフレ", reading: "อินฟุเระ", lang: "ja-JP" },
    { thai: "พอร์ตการลงทุน", target: "ポートフォリオ", reading: "โพโตะฟอริโอ", lang: "ja-JP" },
    { thai: "กระจายความเสี่ยง", target: "分散", reading: "บุนซัง", lang: "ja-JP" },
    { thai: "ผลตอบแทน", target: "リターン", reading: "ริตัง", lang: "ja-JP" },
    { thai: "ทุน / เงินทุน", target: "資本", reading: "ชิฮง", lang: "ja-JP" },
    { thai: "การเทรด / ซื้อขาย", target: "トレード", reading: "โทเรโดะ", lang: "ja-JP" },
    { thai: "ค่าเฉลี่ย", target: "平均", reading: "เฮคิน", lang: "ja-JP" },
    { thai: "การเกษียณอายุ", target: "退職", reading: "ไทโชคุ", lang: "ja-JP" },
    { thai: "เงินบำนาญ", target: "年金", reading: "เนนคิน", lang: "ja-JP" },
    { thai: "เก็บออม", target: "貯金する", reading: "โจคิน สุรุ", lang: "ja-JP" },
    { thai: "รายได้ (เข้า)", target: "収入", reading: "ชูนิว", lang: "ja-JP" },
    { thai: "รายจ่าย", target: "支出", reading: "ชิชุตสึ", lang: "ja-JP" },
    { thai: "สกุลเงิน", target: "通貨", reading: "สึกะ", lang: "ja-JP" },
    { thai: "เหรียญ", target: "コイン", reading: "คอยน์", lang: "ja-JP" },
    { thai: "ตลาดกระทิง (ขาขึ้น)", target: "強気相場", reading: "ทสึโยกิโซบะ", lang: "ja-JP" },
    { thai: "ตลาดหมี (ขาลง)", target: "弱気相場", reading: "โยวากิโซบะ", lang: "ja-JP" },
    { thai: "หุ้นส่วน", target: "パートナー", reading: "พาโตะนา", lang: "ja-JP" },
    { thai: "เจ้าของ", target: "オーナー", reading: "โอนา", lang: "ja-JP" },
    { thai: "นักลงทุน", target: "投資家", reading: "โทชิกะ", lang: "ja-JP" },
    { thai: "มูลค่า", target: "価値", reading: "คาจิ", lang: "ja-JP" },
    { thai: "ราคา", target: "価格", reading: "คาคาคุ", lang: "ja-JP" },
    { thai: "โบรกเกอร์ (นายหน้า)", target: "ブローカー", reading: "บุโรคา", lang: "ja-JP" },
    { thai: "ค่าธรรมเนียม", target: "手数料", reading: "เทซูเรียว", lang: "ja-JP" },
    { thai: "ความผันผวน", target: "ボラティリティ", reading: "โบราทิริตี", lang: "ja-JP" },
    { thai: "ส่วนแบ่ง / หุ้น", target: "シェア", reading: "เชีย", lang: "ja-JP" },
    { thai: "สภาพคล่อง", target: "流動性", reading: "ริวโดเซย์", lang: "ja-JP" },
    { thai: "ดัชนี", target: "インデックス", reading: "อินเดกคุซึ", lang: "ja-JP" },
    { thai: "แนวโน้ม", target: "トレンド", reading: "โทเรนโดะ", lang: "ja-JP" },
    { thai: "ความมั่งคั่ง", target: "富", reading: "โทมิ", lang: "ja-JP" },
    { thai: "ความเสี่ยง", target: "リスク", reading: "ริสุคุ", lang: "ja-JP" },

    // --- 21. หมวดกลยุทธ์ การแข่งขัน และเกมมิ่ง (Strategy & Gaming) - 30 คำ ---
    { thai: "กลยุทธ์", target: "戦略", reading: "เซนเรียคุ", lang: "ja-JP" },
    { thai: "ยุทธวิธี", target: "戦術", reading: "เซนจุตสึ", lang: "ja-JP" },
    { thai: "เกม", target: "ゲーム", reading: "เกมุ", lang: "ja-JP" },
    { thai: "การแข่งขัน", target: "試合", reading: "ชิไอ", lang: "ja-JP" },
    { thai: "การต่อสู้", target: "バトル", reading: "บาโตรุ", lang: "ja-JP" },
    { thai: "คู่แข่ง / ศัตรู", target: "敵", reading: "เทกิ", lang: "ja-JP" },
    { thai: "คู่ปรับ", target: "ライバル", reading: "ไรบารุ", lang: "ja-JP" },
    { thai: "ตัวละคร", target: "キャラクター", reading: "คยารัคตา", lang: "ja-JP" },
    { thai: "ระดับ / เลเวล", target: "レベル", reading: "เรเบบุ", lang: "ja-JP" },
    { thai: "สถิติ / ค่าพลัง", target: "ステータス", reading: "สุเตตาสึ", lang: "ja-JP" },
    { thai: "พลังชีวิต (HP)", target: "体力", reading: "ไทเรียวคุ", lang: "ja-JP" },
    { thai: "โจมตี", target: "攻撃", reading: "โคเงคิ", lang: "ja-JP" },
    { thai: "ป้องกัน", target: "防御", reading: "โบเกียว", lang: "ja-JP" },
    { thai: "ความเร็ว", target: "スピード", reading: "สุปีโดะ", lang: "ja-JP" },
    { thai: "ไอเทม / สิ่งของ", target: "アイテム", reading: "ไอเทมุ", lang: "ja-JP" },
    { thai: "สวมใส่", target: "装備", reading: "โซบิ", lang: "ja-JP" },
    { thai: "วิวัฒนาการ", target: "進化", reading: "ชินกะ", lang: "ja-JP" },
    { thai: "เพาะพันธุ์", target: "育成", reading: "อิคึเซ", lang: "ja-JP" },
    { thai: "ธรรมชาติ / นิสัย", target: "性格", reading: "เซย์คาคุ", lang: "ja-JP" },
    { thai: "ความสามารถ", target: "能力", reading: "โนเรียวคุ", lang: "ja-JP" },
    { thai: "ท่าต่อสู้ / การเคลื่อนไหว", target: "技", reading: "วาซะ", lang: "ja-JP" },
    { thai: "ตา / รอบ (การเล่น)", target: "ターン", reading: "ตัง", lang: "ja-JP" },
    { thai: "ชนะ", target: "勝つ", reading: "คัตสึ", lang: "ja-JP" },
    { thai: "แพ้", target: "負ける", reading: "มาเครุ", lang: "ja-JP" },
    { thai: "เสมอ", target: "引き分け", reading: "ฮิคิวาเคะ", lang: "ja-JP" },
    { thai: "การฝึกฝน", target: "トレーニング", reading: "โทเรนิงงุ", lang: "ja-JP" },
    { thai: "คะแนน", target: "スコア", reading: "สุโคอะ", lang: "ja-JP" },
    { thai: "แชมป์", target: "チャンピオン", reading: "จัมปิอง", lang: "ja-JP" },
    { thai: "ทัวร์นาเมนต์", target: "トーナメント", reading: "โทนาเมนโตะ", lang: "ja-JP" },
    { thai: "ความเสียหาย", target: "ダメージ", reading: "ดาเมจิ", lang: "ja-JP" },

    // --- 22. หมวดอารมณ์และความรู้สึก (Emotions & Feelings) - 20 คำ ---
    { thai: "ความรัก", target: "愛", reading: "ไอ", lang: "ja-JP" },
    { thai: "ความเกลียดชัง", target: "憎しみ", reading: "นิคุชิมิ", lang: "ja-JP" },
    { thai: "ความกลัว", target: "恐怖", reading: "เคียวฟุ", lang: "ja-JP" },
    { thai: "ความประหลาดใจ", target: "驚き", reading: "โอโดโรกิ", lang: "ja-JP" },
    { thai: "ความตกใจ", target: "ショック", reading: "ช็อกคุ", lang: "ja-JP" },
    { thai: "ความตื่นเต้น", target: "興奮", reading: "โคฟุน", lang: "ja-JP" },
    { thai: "ความเบื่อหน่าย", target: "退屈", reading: "ไทคุตสึ", lang: "ja-JP" },
    { thai: "ความสับสน", target: "混乱", reading: "คอนรัน", lang: "ja-JP" },
    { thai: "ความหวัง", target: "希望", reading: "คิโบ", lang: "ja-JP" },
    { thai: "ความสุข / ความปีติ", target: "喜び", reading: "โยโรโคบิ", lang: "ja-JP" },
    { thai: "ความเศร้า", target: "悲しみ", reading: "คานาชิมิ", lang: "ja-JP" },
    { thai: "ความเครียด", target: "ストレス", reading: "สุโตเรซึ", lang: "ja-JP" },
    { thai: "ผ่อนคลาย", target: "リラックス", reading: "ริรักคุซึ", lang: "ja-JP" },
    { thai: "ความกังวล", target: "心配", reading: "ชินไป", lang: "ja-JP" },
    { thai: "ความภาคภูมิใจ", target: "誇り", reading: "โฮโคริ", lang: "ja-JP" },
    { thai: "ความอิจฉา", target: "嫉妬", reading: "ชิตโตะ", lang: "ja-JP" },
    { thai: "ความเห็นอกเห็นใจ", target: "同情", reading: "โดโจ", lang: "ja-JP" },
    { thai: "ความรู้สึกผิด", target: "罪悪感", reading: "ไซอัคคุคัง", lang: "ja-JP" },
    { thai: "ความมั่นใจ", target: "自信", reading: "จิชิน", lang: "ja-JP" },
    { thai: "ความสงสัย", target: "疑い", reading: "อุตางาย", lang: "ja-JP" },

    // --- 23. หมวดสภาพอากาศและฤดูกาล (Weather & Seasons) - 20 คำ ---
    { thai: "สภาพอากาศ", target: "天気", reading: "เทนกิ", lang: "ja-JP" },
    { thai: "ฤดูกาล", target: "季節", reading: "คิเซตสึ", lang: "ja-JP" },
    { thai: "ฤดูร้อน", target: "夏", reading: "นัตสึ", lang: "ja-JP" },
    { thai: "ฤดูหนาว", target: "冬", reading: "ฟุยึ", lang: "ja-JP" },
    { thai: "ฤดูใบไม้ผลิ", target: "春", reading: "ฮารุ", lang: "ja-JP" },
    { thai: "ฤดูใบไม้ร่วง", target: "秋", reading: "อากิ", lang: "ja-JP" },
    { thai: "อุณหภูมิ", target: "気温", reading: "คิอง", lang: "ja-JP" },
    { thai: "องศา", target: "度", reading: "โดะ", lang: "ja-JP" },
    { thai: "แดดออก", target: "晴れ", reading: "ฮาเระ", lang: "ja-JP" },
    { thai: "มีเมฆมาก", target: "曇り", reading: "คุโมริ", lang: "ja-JP" },
    { thai: "ฝนตก", target: "雨", reading: "อาเมะ", lang: "ja-JP" },
    { thai: "พายุ", target: "嵐", reading: "อาราชิ", lang: "ja-JP" },
    { thai: "ฟ้าแลบ", target: "稲妻", reading: "อินาซึมะ", lang: "ja-JP" },
    { thai: "ฟ้าร้อง", target: "雷", reading: "คามินาริ", lang: "ja-JP" },
    { thai: "มีหมอก", target: "霧", reading: "คิริ", lang: "ja-JP" },
    { thai: "น้ำแข็ง", target: "氷", reading: "โคริ", lang: "ja-JP" },
    { thai: "ละลาย", target: "溶ける", reading: "โทเครุ", lang: "ja-JP" },
    { thai: "แช่แข็ง", target: "凍る", reading: "โครุ", lang: "ja-JP" },
    { thai: "พยากรณ์", target: "予報", reading: "โยโห", lang: "ja-JP" },
    { thai: "ร่ม", target: "傘", reading: "คาสะ", lang: "ja-JP" },

    // --- 24. หมวดงานอดิเรกและความบันเทิง (Hobbies & Entertainment) - 30 คำ ---
    { thai: "งานอดิเรก", target: "趣味", reading: "ชุมิ", lang: "ja-JP" },
    { thai: "ดนตรี", target: "音楽", reading: "องงาคุ", lang: "ja-JP" },
    { thai: "เพลง", target: "歌", reading: "อุตะ", lang: "ja-JP" },
    { thai: "ภาพยนตร์", target: "映画", reading: "เอกะ", lang: "ja-JP" },
    { thai: "โรงภาพยนตร์", target: "映画館", reading: "เอกากัง", lang: "ja-JP" },
    { thai: "ศิลปะ", target: "芸術", reading: "เกจุตสึ", lang: "ja-JP" },
    { thai: "การวาดภาพ (เส้น)", target: "描画", reading: "เบียวงะ", lang: "ja-JP" },
    { thai: "การทาสี / ภาพจิตรกรรม", target: "絵画", reading: "ไคงะ", lang: "ja-JP" },
    { thai: "การเต้น", target: "ダンス", reading: "ดันซึ", lang: "ja-JP" },
    { thai: "การถ่ายภาพ", target: "写真撮影", reading: "ชาชิน ซัตสึเอ", lang: "ja-JP" },
    { thai: "กล้อง", target: "カメラ", reading: "คาเมระ", lang: "ja-JP" },
    { thai: "กีฬา", target: "スポーツ", reading: "สุโปตสึ", lang: "ja-JP" },
    { thai: "ฟุตบอล", target: "サッカー", reading: "ซักกา", lang: "ja-JP" },
    { thai: "บาสเกตบอล", target: "バスケットボール", reading: "บาสุเกตโตะโบรุ", lang: "ja-JP" },
    { thai: "ว่ายน้ำ", target: "水泳", reading: "ซุยเอ", lang: "ja-JP" },
    { thai: "วิ่ง", target: "ランニング", reading: "รันนิงงุ", lang: "ja-JP" },
    { thai: "การอ่าน", target: "読書", reading: "ดกโชะ", lang: "ja-JP" },
    { thai: "นวนิยาย", target: "小説", reading: "โชเซตสึ", lang: "ja-JP" },
    { thai: "หนังสือการ์ตูน", target: "漫画", reading: "มังงะ", lang: "ja-JP" },
    { thai: "เกม", target: "ゲーム", reading: "เกมุ", lang: "ja-JP" },
    { thai: "เครื่องเล่นเกม", target: "ゲーム機", reading: "เกมุกิ", lang: "ja-JP" },
    { thai: "ปริศนา", target: "パズル", reading: "พาซุรุ", lang: "ja-JP" },
    { thai: "ของเล่น", target: "おもちゃ", reading: "โอโมจะ", lang: "ja-JP" },
    { thai: "ปาร์ตี้ / งานเลี้ยง", target: "パーティー", reading: "พาตี", lang: "ja-JP" },
    { thai: "เทศกาล", target: "お祭り", reading: "โอมัตสึริ", lang: "ja-JP" },
    { thai: "คอนเสิร์ต", target: "コンサート", reading: "คอนซาโตะ", lang: "ja-JP" },
    { thai: "ตั๋ว", target: "チケット", reading: "จิเกตโตะ", lang: "ja-JP" },
    { thai: "มายากล / เวทมนตร์", target: "マジック", reading: "มาจิกกุ", lang: "ja-JP" },
    { thai: "ของสะสม", target: "コレクション", reading: "โคเรคชง", lang: "ja-JP" },
    { thai: "กีตาร์", target: "ギター", reading: "กีตา", lang: "ja-JP" },

    // --- 25. หมวดแนวคิดนามธรรมและทิศทาง (Abstract Concepts & Directions) - 30 คำ ---
    { thai: "ความคิด / ไอเดีย", target: "アイデア", reading: "ไอเดีย", lang: "ja-JP" },
    { thai: "ความจริง", target: "真実", reading: "ชินจิตสึ", lang: "ja-JP" },
    { thai: "คำโกหก", target: "嘘", reading: "อุโซะ", lang: "ja-JP" },
    { thai: "เหตุผล", target: "理由", reading: "ริยู", lang: "ja-JP" },
    { thai: "จุดประสงค์", target: "目的", reading: "โมคุเทกิ", lang: "ja-JP" },
    { thai: "วิธีการ", target: "方法", reading: "โฮโฮ", lang: "ja-JP" },
    { thai: "ผลลัพธ์", target: "結果", reading: "เคกคะ", lang: "ja-JP" },
    { thai: "ผลกระทบ", target: "影響", reading: "เอเคียว", lang: "ja-JP" },
    { thai: "สาเหตุ", target: "原因", reading: "เกนอิน", lang: "ja-JP" },
    { thai: "ประวัติศาสตร์", target: "歴史", reading: "เรคิชิ", lang: "ja-JP" },
    { thai: "กฎ / กติกา", target: "ルール", reading: "รูรุ", lang: "ja-JP" },
    { thai: "กฎหมาย", target: "法律", reading: "โฮริตสึ", lang: "ja-JP" },
    { thai: "ความยุติธรรม", target: "正義", reading: "เซงิ", lang: "ja-JP" },
    { thai: "อิสรภาพ", target: "自由", reading: "จิยู", lang: "ja-JP" },
    { thai: "สัญลักษณ์", target: "シンボル", reading: "ชินโบรุ", lang: "ja-JP" },
    { thai: "รูปร่าง", target: "形", reading: "คาตาจิ", lang: "ja-JP" },
    { thai: "วงกลม", target: "円", reading: "เอน", lang: "ja-JP" },
    { thai: "สี่เหลี่ยม", target: "四角", reading: "ชิคาคุ", lang: "ja-JP" },
    { thai: "สามเหลี่ยม", target: "三角", reading: "ซันคาคุ", lang: "ja-JP" },
    { thai: "ขนาด", target: "サイズ", reading: "ไซซึ", lang: "ja-JP" },
    { thai: "พื้นที่ว่าง / อวกาศ", target: "空間", reading: "คูคัง", lang: "ja-JP" },
    { thai: "ระยะทาง", target: "距離", reading: "เคียวริ", lang: "ja-JP" },
    { thai: "พื้นที่ (ตาราง)", target: "面積", reading: "เมนเซกิ", lang: "ja-JP" },
    { thai: "ทิศทาง", target: "方向", reading: "โฮโค", lang: "ja-JP" },
    { thai: "ตำแหน่ง", target: "位置", reading: "อิจิ", lang: "ja-JP" },
    { thai: "ด้านบน", target: "上", reading: "อุเอะ", lang: "ja-JP" },
    { thai: "ด้านล่าง", target: "下", reading: "ชิตะ", lang: "ja-JP" },
    { thai: "ตรงกลาง", target: "真ん中", reading: "มันนากะ", lang: "ja-JP" },
    { thai: "ด้านหน้า", target: "前", reading: "มาเอะ", lang: "ja-JP" },
    { thai: "ด้านหลัง", target: "後ろ", reading: "อุชิโระ", lang: "ja-JP" },
	, // --- 26. หมวดสัตว์ (Animals) - 30 คำ ---
    { thai: "สิงโต", target: "ライオン", reading: "ไรอง", lang: "ja-JP" },
    { thai: "เสือ", target: "トラ", reading: "โทระ", lang: "ja-JP" },
    { thai: "ช้าง", target: "ゾウ", reading: "โซ", lang: "ja-JP" },
    { thai: "หมี", target: "クマ", reading: "คุมะ", lang: "ja-JP" },
    { thai: "ลิง", target: "サル", reading: "ซารุ", lang: "ja-JP" },
    { thai: "งู", target: "ヘビ", reading: "เฮบิ", lang: "ja-JP" },
    { thai: "ม้า", target: "ウマ", reading: "อุมะ", lang: "ja-JP" },
    { thai: "วัว", target: "ウシ", reading: "อุชิ", lang: "ja-JP" },
    { thai: "หมู", target: "ブタ", reading: "บุตะ", lang: "ja-JP" },
    { thai: "แกะ", target: "ヒツジ", reading: "ฮิตสึจิ", lang: "ja-JP" },
    { thai: "แพะ", target: "ヤギ", reading: "ยากิ", lang: "ja-JP" },
    { thai: "เป็ด", target: "アヒル", reading: "อาฮิรุ", lang: "ja-JP" },
    { thai: "หนู", target: "ネズミ", reading: "เนซึมิ", lang: "ja-JP" },
    { thai: "กระต่าย", target: "ウサギ", reading: "อุซางิ", lang: "ja-JP" },
    { thai: "เต่า", target: "カメ", reading: "คาเมะ", lang: "ja-JP" },
    { thai: "กบ", target: "カエル", reading: "คาเอรุ", lang: "ja-JP" },
    { thai: "แมงมุม", target: "クモ", reading: "คุโมะ", lang: "ja-JP" },
    { thai: "แมลง", target: "虫", reading: "มุชิ", lang: "ja-JP" },
    { thai: "ผึ้ง", target: "ハチ", reading: "ฮาจิ", lang: "ja-JP" },
    { thai: "ผีเสื้อ", target: "チョウ", reading: "โจ", lang: "ja-JP" },
    { thai: "มด", target: "アリ", reading: "อาริ", lang: "ja-JP" },
    { thai: "แมลงวัน", target: "ハエ", reading: "ฮาเอะ", lang: "ja-JP" },
    { thai: "ยุง", target: "カ", reading: "กะ", lang: "ja-JP" },
    { thai: "โลมา", target: "イルカ", reading: "อิรุกะ", lang: "ja-JP" },
    { thai: "วาฬ", target: "クジラ", reading: "คุจิระ", lang: "ja-JP" },
    { thai: "ฉลาม", target: "サメ", reading: "ซาเมะ", lang: "ja-JP" },
    { thai: "เพนกวิน", target: "ペンギン", reading: "เพนกิน", lang: "ja-JP" },
    { thai: "จิงโจ้", target: "カンガルー", reading: "คังการู", lang: "ja-JP" },
    { thai: "หมาป่า", target: "オオカミ", reading: "โอคามิ", lang: "ja-JP" },
    { thai: "จระเข้", target: "ワニ", reading: "วานิ", lang: "ja-JP" },

    // --- 27. หมวดเครื่องแต่งกายและเครื่องประดับ (Clothing & Accessories) - 30 คำ ---
    { thai: "เสื้อเชิ้ต", target: "シャツ", reading: "ชาตสึ", lang: "ja-JP" },
    { thai: "เสื้อยืด", target: "Tシャツ", reading: "ทีชาตสึ", lang: "ja-JP" },
    { thai: "กางเกงขายาว", target: "ズボン", reading: "ซุบง", lang: "ja-JP" },
    { thai: "กางเกงยีนส์", target: "ジーンズ", reading: "จีนซึ", lang: "ja-JP" },
    { thai: "กางเกงขาสั้น", target: "半ズボン", reading: "ฮันซุบง", lang: "ja-JP" },
    { thai: "กระโปรง", target: "スカート", reading: "สุกาโตะ", lang: "ja-JP" },
    { thai: "ชุดเดรส", target: "ワンピース", reading: "วันพีซึ", lang: "ja-JP" },
    { thai: "ชุดสูท", target: "スーツ", reading: "ซูตสึ", lang: "ja-JP" },
    { thai: "เสื้อแจ็คเก็ต", target: "ジャケット", reading: "จาเกตโตะ", lang: "ja-JP" },
    { thai: "เสื้อโค้ต", target: "コート", reading: "โคโตะ", lang: "ja-JP" },
    { thai: "เสื้อกันหนาว", target: "セーター", reading: "เซตา", lang: "ja-JP" },
    { thai: "หมวก (มีปีกรอบ)", target: "帽子", reading: "โบชิ", lang: "ja-JP" },
    { thai: "หมวกแก๊ป", target: "キャップ", reading: "แคปปุ", lang: "ja-JP" },
    { thai: "ถุงเท้า", target: "靴下", reading: "คุตสึชิตะ", lang: "ja-JP" },
    { thai: "รองเท้าบูท", target: "ブーツ", reading: "บูตสึ", lang: "ja-JP" },
    { thai: "รองเท้าผ้าใบ", target: "スニーカー", reading: "ซุนีกา", lang: "ja-JP" },
    { thai: "เข็มขัด", target: "ベルト", reading: "เบรุโตะ", lang: "ja-JP" },
    { thai: "เนคไท", target: "ネクタイ", reading: "เนคุไท", lang: "ja-JP" },
    { thai: "ผ้าพันคอ", target: "マフラー", reading: "มาฟุระ", lang: "ja-JP" },
    { thai: "ถุงมือ", target: "手袋", reading: "เทบุคุโระ", lang: "ja-JP" },
    { thai: "ชุดชั้นใน", target: "下着", reading: "ชิตางิ", lang: "ja-JP" },
    { thai: "แหวน", target: "指輪", reading: "ยูบิวะ", lang: "ja-JP" },
    { thai: "สร้อยคอ", target: "ネックレス", reading: "เนคคุเรซึ", lang: "ja-JP" },
    { thai: "สร้อยข้อมือ", target: "ブレスレット", reading: "บุเรซึเรตโตะ", lang: "ja-JP" },
    { thai: "ต่างหู", target: "イヤリング", reading: "อิยาริงงุ", lang: "ja-JP" },
    { thai: "กระเป๋าสตางค์", target: "財布", reading: "ไซฟุ", lang: "ja-JP" },
    { thai: "กระเป๋าถือ (ผู้หญิง)", target: "ハンドバッグ", reading: "ฮันโดะบักกุ", lang: "ja-JP" },
    { thai: "กระเป๋าเป้", target: "リュック", reading: "ริวกกุ", lang: "ja-JP" },
    { thai: "เครื่องแบบ", target: "制服", reading: "เซฟุคุ", lang: "ja-JP" },
    { thai: "กระเป๋าเสื้อ/กางเกง", target: "ポケット", reading: "โพเกตโตะ", lang: "ja-JP" },

    // --- 28. หมวดการศึกษาและโรงเรียน (Education & School) - 40 คำ ---
    { thai: "การศึกษา", target: "教育", reading: "เคียวอิคุ", lang: "ja-JP" },
    { thai: "มหาวิทยาลัย", target: "大学", reading: "ไดงาคุ", lang: "ja-JP" },
    { thai: "วิทยาลัย", target: "カレッジ", reading: "คาเรจจิ", lang: "ja-JP" },
    { thai: "นักเรียน / นักศึกษา", target: "学生", reading: "กักเซย์", lang: "ja-JP" },
    { thai: "ชั้นเรียน", target: "クラス", reading: "คุราซึ", lang: "ja-JP" },
    { thai: "ห้องเรียน", target: "教室", reading: "เคียวชิตสึ", lang: "ja-JP" },
    { thai: "วิชา", target: "科目", reading: "คาโมคุ", lang: "ja-JP" },
    { thai: "คณิตศาสตร์", target: "数学", reading: "ซูงาคุ", lang: "ja-JP" },
    { thai: "วิทยาศาสตร์", target: "科学", reading: "คางาคุ", lang: "ja-JP" },
    { thai: "ภูมิศาสตร์", target: "地理", reading: "จิริ", lang: "ja-JP" },
    { thai: "ภาษา", target: "言語", reading: "เกนโงะ", lang: "ja-JP" },
    { thai: "ภาษาอังกฤษ", target: "英語", reading: "เอโงะ", lang: "ja-JP" },
    { thai: "การทดสอบ", target: "テスト", reading: "เทซึโตะ", lang: "ja-JP" },
    { thai: "การสอบ (ทางการ)", target: "試験", reading: "ชิเคน", lang: "ja-JP" },
    { thai: "แบบทดสอบย่อย", target: "小テスト", reading: "โชเทซึโตะ", lang: "ja-JP" },
    { thai: "การบ้าน", target: "宿題", reading: "ชุคุได", lang: "ja-JP" },
    { thai: "ระดับชั้น / เกรด", target: "成績", reading: "เซเซคิ", lang: "ja-JP" },
    { thai: "ปริญญา", target: "学位", reading: "กาคุอิ", lang: "ja-JP" },
    { thai: "ผู้สำเร็จการศึกษา", target: "卒業生", reading: "ซตสึเงียวเซย์", lang: "ja-JP" },
    { thai: "ประกาศนียบัตร", target: "卒業証書", reading: "ซตสึเงียวโชโชะ", lang: "ja-JP" },
    { thai: "ทุนการศึกษา", target: "奨学金", reading: "โชงาคุคิน", lang: "ja-JP" },
    { thai: "บทเรียน", target: "授業", reading: "จูเงียว", lang: "ja-JP" },
    { thai: "บท", target: "章", reading: "โช", lang: "ja-JP" },
    { thai: "หน้า (หนังสือ)", target: "ページ", reading: "เพจิ", lang: "ja-JP" },
    { thai: "คำถาม", target: "質問", reading: "ชิตสึมง", lang: "ja-JP" },
    { thai: "คำตอบ", target: "答え", reading: "โคทาเอะ", lang: "ja-JP" },
    { thai: "ตัวอย่าง", target: "例", reading: "เรย์", lang: "ja-JP" },
    { thai: "พจนานุกรม", target: "辞書", reading: "จิโชะ", lang: "ja-JP" },
    { thai: "คำศัพท์", target: "語彙", reading: "โกอิ", lang: "ja-JP" },
    { thai: "ไวยากรณ์", target: "文法", reading: "บุมโป", lang: "ja-JP" },
    { thai: "ดินสอ", target: "鉛筆", reading: "เอมปิตสึ", lang: "ja-JP" },
    { thai: "ยางลบ", target: "消しゴム", reading: "เคชิโกมุ", lang: "ja-JP" },
    { thai: "ไม้บรรทัด", target: "定規", reading: "โจงิ", lang: "ja-JP" },
    { thai: "กระดานดำ", target: "黒板", reading: "โคคุบัง", lang: "ja-JP" },
    { thai: "กระดานไวท์บอร์ด", target: "ホワイトボード", reading: "โฮไวโตะโบโดะ", lang: "ja-JP" },
    { thai: "สมุดจด", target: "ノート", reading: "โนโตะ", lang: "ja-JP" },
    { thai: "โต๊ะเรียน", target: "机", reading: "ทสึคุเอะ", lang: "ja-JP" },
    { thai: "ภาคเรียน", target: "学期", reading: "กักคิ", lang: "ja-JP" },
    { thai: "ภาคการศึกษา", target: "セメスター", reading: "เซเมสึตา", lang: "ja-JP" },
    { thai: "เวลาพัก", target: "休み時間", reading: "ยาสุมิจิคัง", lang: "ja-JP" },

    // --- 29. หมวดการเดินทางในเมืองและสถานที่สาธารณะ (City Life & Commute) - 30 คำ ---
    { thai: "ถนน", target: "通り", reading: "โทริ", lang: "ja-JP" },
    { thai: "ถนนใหญ่ / อเวนิว", target: "大通り", reading: "โอโดริ", lang: "ja-JP" },
    { thai: "ทางหลวง", target: "高速道路", reading: "โคโซคุโดโระ", lang: "ja-JP" },
    { thai: "การจราจร", target: "交通", reading: "โคทซู", lang: "ja-JP" },
    { thai: "ไฟจราจร", target: "信号", reading: "ชินโก", lang: "ja-JP" },
    { thai: "ทางเท้า", target: "歩道", reading: "โฮโด", lang: "ja-JP" },
    { thai: "ทางม้าลาย", target: "横断歩道", reading: "โอดันโฮโด", lang: "ja-JP" },
    { thai: "รถไฟใต้ดิน", target: "地下鉄", reading: "จิกาเตตสึ", lang: "ja-JP" },
    { thai: "ชานชาลา", target: "ホーム", reading: "โฮมุ", lang: "ja-JP" },
    { thai: "ผู้โดยสาร", target: "乗客", reading: "โจคยาคุ", lang: "ja-JP" },
    { thai: "การเดินทาง (ระยะไกล)", target: "旅", reading: "ทาบิ", lang: "ja-JP" },
    { thai: "การเดินทาง (ระยะสั้น)", target: "旅行", reading: "เรียวโค", lang: "ja-JP" },
    { thai: "การท่องเที่ยว", target: "ツアー", reading: "ทสึอา", lang: "ja-JP" },
    { thai: "คนนำทาง / มัคคุเทศก์", target: "ガイド", reading: "ไกโดะ", lang: "ja-JP" },
    { thai: "เส้นทาง", target: "ルート", reading: "รูโตะ", lang: "ja-JP" },
    { thai: "ค่าโดยสาร", target: "運賃", reading: "อุนจิน", lang: "ja-JP" },
    { thai: "คิว / แถว", target: "列", reading: "เรตสึ", lang: "ja-JP" },
    { thai: "ความล่าช้า", target: "遅れ", reading: "โอคุเระ", lang: "ja-JP" },
    { thai: "อุบัติเหตุ", target: "事故", reading: "จิโกะ", lang: "ja-JP" },
    { thai: "อันตราย (คำนาม)", target: "危険", reading: "คิเคน", lang: "ja-JP" },
    { thai: "ความปลอดภัย", target: "安全", reading: "อันเซ็น", lang: "ja-JP" },
    { thai: "ฝูงชน", target: "人込み", reading: "ฮิโตโกมิ", lang: "ja-JP" },
    { thai: "อาคาร", target: "建物", reading: "ทาเตโมโนะ", lang: "ja-JP" },
    { thai: "ตึกระฟ้า", target: "超高層ビル", reading: "โชโคโซบิรุ", lang: "ja-JP" },
    { thai: "อพาร์ตเมนต์", target: "アパート", reading: "อาปาโตะ", lang: "ja-JP" },
    { thai: "ละแวกบ้าน", target: "近所", reading: "คินโจะ", lang: "ja-JP" },
    { thai: "เมืองหลวง", target: "首都", reading: "ชุโตะ", lang: "ja-JP" },
    { thai: "อนุสาวรีย์", target: "記念碑", reading: "คิเนนฮิ", lang: "ja-JP" },
    { thai: "พิพิธภัณฑ์", target: "博物館", reading: "ฮาคุบุตสึคัง", lang: "ja-JP" },
    { thai: "สวนสัตว์", target: "動物園", reading: "โดบุตสึเอน", lang: "ja-JP" },

    // --- 30. หมวดเครื่องมือ วัสดุ และคุณลักษณะทางกายภาพ (Tools, Materials & Shapes) - 35 คำ ---
    { thai: "เครื่องมือ", target: "道具", reading: "โดงุ", lang: "ja-JP" },
    { thai: "ค้อน", target: "ハンマー", reading: "ฮัมมา", lang: "ja-JP" },
    { thai: "ตะปู", target: "釘", reading: "คุงิ", lang: "ja-JP" },
    { thai: "สกรู", target: "ネジ", reading: "เนจิ", lang: "ja-JP" },
    { thai: "ประแจ", target: "レンチ", reading: "เรนจิ", lang: "ja-JP" },
    { thai: "กรรไกร", target: "はさみ", reading: "ฮาซามิ", lang: "ja-JP" },
    { thai: "มีด", target: "包丁", reading: "โฮโจ", lang: "ja-JP" },
    { thai: "ใบมีด", target: "刃", reading: "ฮะ", lang: "ja-JP" },
    { thai: "เครื่องจักร", target: "機械", reading: "คิไค", lang: "ja-JP" },
    { thai: "เครื่องยนต์", target: "エンジン", reading: "เอนจิน", lang: "ja-JP" },
    { thai: "มอเตอร์", target: "モーター", reading: "โมตา", lang: "ja-JP" },
    { thai: "วัสดุ", target: "材料", reading: "ไซเรียว", lang: "ja-JP" },
    { thai: "ไม้", target: "木材", reading: "โมคุไซ", lang: "ja-JP" },
    { thai: "โลหะ", target: "金属", reading: "คินโซคุ", lang: "ja-JP" },
    { thai: "เหล็ก", target: "鉄", reading: "เทตสึ", lang: "ja-JP" },
    { thai: "เหล็กกล้า", target: "鋼", reading: "ฮางาเนะ", lang: "ja-JP" },
    { thai: "ทองแดง", target: "銅", reading: "โด", lang: "ja-JP" },
    { thai: "พลาสติก", target: "プラスチック", reading: "พุราซึจิกกุ", lang: "ja-JP" },
    { thai: "ยาง", target: "ゴム", reading: "โกมุ", lang: "ja-JP" },
    { thai: "ฝ้าย", target: "綿", reading: "เมน", lang: "ja-JP" },
    { thai: "หนัง (วัสดุ)", target: "革", reading: "คาวะ", lang: "ja-JP" },
    { thai: "กระดาษแข็ง", target: "段ボール", reading: "ดันโบรุ", lang: "ja-JP" },
    { thai: "เชือกหนา", target: "ロープ", reading: "โรปุ", lang: "ja-JP" },
    { thai: "ลวด / สายไฟ", target: "針金", reading: "ฮาริงาเนะ", lang: "ja-JP" },
    { thai: "เส้น", target: "線", reading: "เซน", lang: "ja-JP" },
    { thai: "ส่วนโค้ง", target: "曲線", reading: "เคียวคุเซน", lang: "ja-JP" },
    { thai: "มุม", target: "角度", reading: "คาคุโดะ", lang: "ja-JP" },
    { thai: "กลม", target: "丸い", reading: "มารุย", lang: "ja-JP" },
    { thai: "แบน", target: "平ら", reading: "ไทระ", lang: "ja-JP" },
    { thai: "แหลม / คม", target: "鋭い", reading: "ซุรุดอย", lang: "ja-JP" },
    { thai: "เรียบ / ลื่น", target: "滑らか", reading: "นาเมรากะ", lang: "ja-JP" },
    { thai: "ขรุขระ", target: "粗い", reading: "อาราย", lang: "ja-JP" },
    { thai: "นุ่ม", target: "柔らかい", reading: "ยาวารากาย", lang: "ja-JP" },
    { thai: "แข็ง (วัสดุ)", target: "硬い", reading: "คาตาย", lang: "ja-JP" },
    { thai: "ของแข็ง", target: "固体", reading: "โคไต", lang: "ja-JP" },

    // --- 31. หมวดสังคม การปกครอง และกระบวนการยุติธรรม (Society, Government & Justice) - 35 คำ ---
    { thai: "สังคม", target: "社会", reading: "ชาไก", lang: "ja-JP" },
    { thai: "วัฒนธรรม", target: "文化", reading: "บุนกะ", lang: "ja-JP" },
    { thai: "ประเพณี", target: "伝統", reading: "เดนโต", lang: "ja-JP" },
    { thai: "รัฐบาล", target: "政府", reading: "เซฟุ", lang: "ja-JP" },
    { thai: "การเมือง", target: "政治", reading: "เซจิ", lang: "ja-JP" },
    { thai: "การเลือกตั้ง", target: "選挙", reading: "เซนเคียว", lang: "ja-JP" },
    { thai: "ลงคะแนนเสียง", target: "投票", reading: "โทเฮียว", lang: "ja-JP" },
    { thai: "ประธานาธิบดี / ประธาน", target: "大統領", reading: "ไดโทเรียว", lang: "ja-JP" },
    { thai: "ผู้นำ", target: "リーダー", reading: "รีดา", lang: "ja-JP" },
    { thai: "พลเมือง", target: "市民", reading: "ชิมิน", lang: "ja-JP" },
    { thai: "ชาติ / ประเทศ", target: "国家", reading: "คกคะ", lang: "ja-JP" },
    { thai: "ชุมชน", target: "コミュニティ", reading: "โคมิวนิตี", lang: "ja-JP" },
    { thai: "นโยบาย", target: "政策", reading: "เซซาคุ", lang: "ja-JP" },
    { thai: "ข้อบังคับ / ระเบียบ", target: "規制", reading: "คิเซย์", lang: "ja-JP" },
    { thai: "สิทธิ", target: "権利", reading: "เคนริ", lang: "ja-JP" },
    { thai: "หน้าที่", target: "義務", reading: "กิมุ", lang: "ja-JP" },
    { thai: "ศาล", target: "裁判所", reading: "ไซบันโชะ", lang: "ja-JP" },
    { thai: "ผู้พิพากษา", target: "裁判官", reading: "ไซบันคัง", lang: "ja-JP" },
    { thai: "ทนายความ", target: "弁護士", reading: "เบนโกชิ", lang: "ja-JP" },
    { thai: "เจ้าหน้าที่", target: "警察官", reading: "เคซัตสึคัง", lang: "ja-JP" },
    { thai: "อาชญากรรม", target: "犯罪", reading: "ฮันไซ", lang: "ja-JP" },
    { thai: "อาชญากร", target: "犯罪者", reading: "ฮันไซชะ", lang: "ja-JP" },
    { thai: "คุก / เรือนจำ", target: "刑務所", reading: "เคมุโชะ", lang: "ja-JP" },
    { thai: "ขโมย (คน)", target: "泥棒", reading: "โดโรโบ", lang: "ja-JP" },
    { thai: "การป้องกัน", target: "保護", reading: "โฮโกะ", lang: "ja-JP" },
    { thai: "สันติภาพ", target: "平和", reading: "เฮวะ", lang: "ja-JP" },
    { thai: "สงคราม", target: "戦争", reading: "เซนโซ", lang: "ja-JP" },
    { thai: "กองทัพบก", target: "軍隊", reading: "กุนไต", lang: "ja-JP" },
    { thai: "อาวุธ", target: "武器", reading: "บุคิ", lang: "ja-JP" },
    { thai: "ปืน", target: "銃", reading: "จู", lang: "ja-JP" },
    { thai: "ประชากร", target: "人口", reading: "จินโค", lang: "ja-JP" },
    { thai: "ชายแดน", target: "国境", reading: "คกเคียว", lang: "ja-JP" },
    { thai: "ธง", target: "旗", reading: "ฮาตะ", lang: "ja-JP" },
    { thai: "สาธารณะ", target: "公共", reading: "โคเคียว", lang: "ja-JP" },
    { thai: "ส่วนตัว", target: "プライベート", reading: "พุไรเบโตะ", lang: "ja-JP" },

    // --- 32. หมวดคำบุพบทและคำเชื่อมประโยค (Prepositions & Conjunctions) - 30 คำ ---
    { thai: "ใน / ข้างใน", target: "中に", reading: "นากะ นิ", lang: "ja-JP" },
    { thai: "บน / ข้างบน", target: "上に", reading: "อุเอะ นิ", lang: "ja-JP" },
    { thai: "ที่", target: "〜で", reading: "เดะ", lang: "ja-JP" },
    { thai: "โดย / ด้วย", target: "〜によって", reading: "นิ ยตเตะ", lang: "ja-JP" },
    { thai: "สำหรับ / เพื่อ", target: "〜のために", reading: "โนะ ทาเมะ นิ", lang: "ja-JP" },
    { thai: "กับ / ด้วย", target: "〜と一緒に", reading: "โตะ อิชโชะ นิ", lang: "ja-JP" },
    { thai: "เกี่ยวกับ", target: "〜について", reading: "นิ ทสึอิเตะ", lang: "ja-JP" },
    { thai: "ต่อต้าน / แข่งกับ", target: "〜に対して", reading: "นิ ไทชิเตะ", lang: "ja-JP" },
    { thai: "ระหว่าง (สองสิ่ง)", target: "間に", reading: "ไอดะ นิ", lang: "ja-JP" },
    { thai: "เข้าไปใน", target: "中へ", reading: "นากะ เอะ", lang: "ja-JP" },
    { thai: "ทะลุผ่าน", target: "通って", reading: "ทตเตะ", lang: "ja-JP" },
    { thai: "ระหว่าง (เวลา)", target: "〜の間に", reading: "โนะ ไอดะ นิ", lang: "ja-JP" },
    { thai: "ก่อน", target: "前に", reading: "มาเอะ นิ", lang: "ja-JP" },
    { thai: "หลังจาก", target: "後に", reading: "อาโตะ นิ", lang: "ja-JP" },
    { thai: "เหนือ / สูงกว่า", target: "〜の上に", reading: "โนะ อุเอะ นิ", lang: "ja-JP" },
    { thai: "ใต้ / ต่ำกว่า", target: "〜の下に", reading: "โนะ ชิตะ นิ", lang: "ja-JP" },
    { thai: "จาก", target: "〜から", reading: "คาระ", lang: "ja-JP" },
    { thai: "ขึ้น", target: "上へ", reading: "อุเอะ เอะ", lang: "ja-JP" },
    { thai: "ลง", target: "下へ", reading: "ชิตะ เอะ", lang: "ja-JP" },
    { thai: "ออก / ข้างนอก", target: "外へ", reading: "โซโตะ เอะ", lang: "ja-JP" },
    { thai: "และ", target: "そして", reading: "โซชิเตะ", lang: "ja-JP" },
    { thai: "แต่", target: "しかし", reading: "ชิกาชิ", lang: "ja-JP" },
    { thai: "หรือ", target: "または", reading: "มาทาวะ", lang: "ja-JP" },
    { thai: "เพราะว่า", target: "なぜなら", reading: "นาเซนาระ", lang: "ja-JP" },
    { thai: "ถ้า / หาก", target: "もし", reading: "โมชิ", lang: "ja-JP" },
    { thai: "ดังนั้น", target: "だから", reading: "ดากะระ", lang: "ja-JP" },
    { thai: "แม้ว่า", target: "〜だけれども", reading: "ดาเคเรโดโมะ", lang: "ja-JP" },
    { thai: "จนกระทั่ง", target: "〜まで", reading: "มาเดะ", lang: "ja-JP" },
    { thai: "เว้นแต่ว่า", target: "〜しない限り", reading: "ชินาย คางิริ", lang: "ja-JP" },
    { thai: "ตั้งแต่ / เนื่องจาก", target: "〜以来", reading: "อิไร", lang: "ja-JP" },

    // --- 33. หมวดคำวิเศษณ์บอกเวลา สถานที่ และความถี่ (Common Adverbs) - 30 คำ ---
    { thai: "เสมอ / ตลอด", target: "いつも", reading: "อิตสึโมะ", lang: "ja-JP" },
    { thai: "มักจะ / เป็นประจำ", target: "たいてい", reading: "ไทเท", lang: "ja-JP" },
    { thai: "บ่อยๆ", target: "よく", reading: "โยคุ", lang: "ja-JP" },
    { thai: "บางครั้ง", target: "時々", reading: "โทคิโดคิ", lang: "ja-JP" },
    { thai: "ไม่เคย", target: "決して〜ない", reading: "เคสชิเตะ...นาย", lang: "ja-JP" },
    { thai: "มาก", target: "とても", reading: "โทเตโมะ", lang: "ja-JP" },
    { thai: "เกินไป / ก็ด้วย", target: "〜すぎる", reading: "ซุงิรุ", lang: "ja-JP" },
    { thai: "ค่อนข้าง", target: "かなり", reading: "คานาริ", lang: "ja-JP" },
    { thai: "จริงๆ / อย่างแท้จริง", target: "本当に", reading: "ฮนโต นิ", lang: "ja-JP" },
    { thai: "อย่างแน่นอน / เป๊ะ", target: "正確に", reading: "เซคาคุ นิ", lang: "ja-JP" },
    { thai: "เกือบจะ", target: "ほとんど", reading: "โฮตนโดะ", lang: "ja-JP" },
    { thai: "เรียบร้อยแล้ว", target: "すでに", reading: "ซุเดนิ", lang: "ja-JP" },
    { thai: "ยังคง", target: "まだ", reading: "มาดะ", lang: "ja-JP" },
    { thai: "ยัง (รูปปฏิเสธ/คำถาม)", target: "まだ〜ない", reading: "มาดะ...นาย", lang: "ja-JP" },
    { thai: "เพิ่งจะ / แค่", target: "ちょうど", reading: "โจโดะ", lang: "ja-JP" },
    { thai: "เท่านั้น / เพียงแค่", target: "〜だけ", reading: "ดาเคะ", lang: "ja-JP" },
    { thai: "บางที", target: "たぶん", reading: "ทาบุน", lang: "ja-JP" },
    { thai: "อาจจะ", target: "もしかすると", reading: "โมชิกาสุรุโตะ", lang: "ja-JP" },
    { thai: "ทันทีทันใด", target: "突然", reading: "ทตสึเซน", lang: "ja-JP" },
    { thai: "อย่างรวดเร็ว", target: "早く", reading: "ฮายาคุ", lang: "ja-JP" },
    { thai: "อย่างช้าๆ", target: "ゆっくり", reading: "ยุคคุริ", lang: "ja-JP" },
    { thai: "อย่างระมัดระวัง", target: "注意深く", reading: "จูอิบุคาคุ", lang: "ja-JP" },
    { thai: "อย่างง่ายดาย", target: "簡単に", reading: "คันตัน นิ", lang: "ja-JP" },
    { thai: "ดี (คำวิเศษณ์)", target: "上手に", reading: "โจซึ นิ", lang: "ja-JP" },
    { thai: "ที่นี่", target: "ここ", reading: "โคโค", lang: "ja-JP" },
    { thai: "ที่นั่น", target: "そこ", reading: "โซโค", lang: "ja-JP" },
    { thai: "ทุกที่", target: "どこでも", reading: "โดโคเดโมะ", lang: "ja-JP" },
    { thai: "บางที่", target: "どこか", reading: "โดโคกะ", lang: "ja-JP" },
    { thai: "ไม่มีที่ไหน", target: "どこにも〜ない", reading: "โดโคนิโมะ...นาย", lang: "ja-JP" },
    { thai: "ที่ไหนก็ได้", target: "どこでも", reading: "โดโคเดโมะ", lang: "ja-JP" },

    // --- 34. หมวดปริมาณ ขนาด และการวัด (Quantities & Measurements) - 25 คำ ---
    { thai: "ทั้งหมด", target: "全て", reading: "ซุเบเตะ", lang: "ja-JP" },
    { thai: "บ้าง / บางส่วน", target: "いくつか", reading: "อิคุตสึคะ", lang: "ja-JP" },
    { thai: "บ้าง (รูปปฏิเสธ/คำถาม)", target: "何か", reading: "นานิกะ", lang: "ja-JP" },
    { thai: "มาก (นับได้)", target: "多く", reading: "โอคุ", lang: "ja-JP" },
    { thai: "มาก (นับไม่ได้)", target: "たくさん", reading: "ทาคุซัง", lang: "ja-JP" },
    { thai: "น้อย (นับได้)", target: "少ない", reading: "ซุคุนาย", lang: "ja-JP" },
    { thai: "น้อย (นับไม่ได้)", target: "少し", reading: "ซุโคชิ", lang: "ja-JP" },
    { thai: "ชิ้น", target: "一つ", reading: "ฮิตตสึ", lang: "ja-JP" },
    { thai: "แผ่น / ชิ้นบางๆ", target: "一切れ", reading: "ฮิโตคิเระ", lang: "ja-JP" },
    { thai: "หยด", target: "一滴", reading: "อิตเตคิ", lang: "ja-JP" },
    { thai: "ปอนด์ (น้ำหนัก)", target: "ポンド", reading: "ปนโดะ", lang: "ja-JP" },
    { thai: "กิโลกรัม", target: "キロ", reading: "คิโระ", lang: "ja-JP" },
    { thai: "เมตร", target: "メートル", reading: "เมโตรุ", lang: "ja-JP" },
    { thai: "ลิตร", target: "リットル", reading: "ริตโตรุ", lang: "ja-JP" },
    { thai: "โหล (12 ชิ้น)", target: "ダース", reading: "ดาซึ", lang: "ja-JP" },
    { thai: "ครึ่ง", target: "半分", reading: "ฮัมบุน", lang: "ja-JP" },
    { thai: "หนึ่งในสี่", target: "4分の1", reading: "ยนมุน โนะ อิจิ", lang: "ja-JP" },
    { thai: "ยอดรวม", target: "合計", reading: "โกเค", lang: "ja-JP" },
    { thai: "จำนวน / ปริมาณ (นับไม่ได้)", target: "量", reading: "เรียว", lang: "ja-JP" },
    { thai: "ตัวเลข / จำนวน (นับได้)", target: "数", reading: "คาซึ", lang: "ja-JP" },
    { thai: "น้ำหนัก", target: "重さ", reading: "โอโมซะ", lang: "ja-JP" },
    { thai: "ความยาว", target: "長さ", reading: "นางาซะ", lang: "ja-JP" },
    { thai: "ความสูง", target: "高さ", reading: "ทาคาสะ", lang: "ja-JP" },
    { thai: "ความลึก", target: "深さ", reading: "ฟุคาสะ", lang: "ja-JP" },
    { thai: "ความกว้าง", target: "幅", reading: "ฮาบะ", lang: "ja-JP" },

    // --- 35. หมวดจักรวาล วิทยาศาสตร์ และธรรมชาติ (Universe & Basic Science) - 15 คำ ---
    { thai: "จักรวาล", target: "宇宙", reading: "อุจู", lang: "ja-JP" },
    { thai: "ดาราจักร / กาแล็กซี", target: "銀河", reading: "กินงะ", lang: "ja-JP" },
    { thai: "ดาวเคราะห์", target: "惑星", reading: "วาคุเซย์", lang: "ja-JP" },
    { thai: "อวกาศ / พื้นที่ว่าง", target: "空間", reading: "คูคัง", lang: "ja-JP" },
    { thai: "อะตอม", target: "原子", reading: "เกนชิ", lang: "ja-JP" },
    { thai: "พลังงาน", target: "エネルギー", reading: "เอเนรุงี", lang: "ja-JP" },
    { thai: "แรงโน้มถ่วง", target: "重力", reading: "จูเรียวคุ", lang: "ja-JP" },
    { thai: "ฟิสิกส์", target: "物理学", reading: "บุตสึริงาคุ", lang: "ja-JP" },
    { thai: "เคมี", target: "化学", reading: "คางาคุ", lang: "ja-JP" },
    { thai: "ชีววิทยา", target: "生物学", reading: "เซบุตสึงาคุ", lang: "ja-JP" },
    { thai: "เซลล์", target: "細胞", reading: "ไซโบ", lang: "ja-JP" },
    { thai: "ธรรมชาติ", target: "自然", reading: "ชิเซน", lang: "ja-JP" },
    { thai: "ก๊าซ", target: "気体", reading: "คิไต", lang: "ja-JP" },
    { thai: "ของเหลว", target: "液体", reading: "เอคิไต", lang: "ja-JP" },
    { thai: "การทดลอง", target: "実験", reading: "จิกเคน", lang: "ja-JP" }
]; // สิ้นสุดอาเรย์ ตัวแปร wordsJP สมบูรณ์ 1,000 คำ