const wordsCN = [
    // --- 1. หมวดบุคคลและสรรพนาม (People & Pronouns) - 20 คำ ---
    { thai: "ฉัน / ผม", target: "我", reading: "หว่อ", lang: "zh-CN" },
    { thai: "คุณ", target: "你", reading: "หนี่", lang: "zh-CN" },
    { thai: "เขา (ผู้ชาย)", target: "他", reading: "ทา", lang: "zh-CN" },
    { thai: "เธอ (ผู้หญิง)", target: "她", reading: "ทา", lang: "zh-CN" },
    { thai: "พวกเรา", target: "我们", reading: "หว่อเมิน", lang: "zh-CN" },
    { thai: "พวกเขา", target: "他们", reading: "ทาเมิน", lang: "zh-CN" },
    { thai: "มัน", target: "它", reading: "ทา", lang: "zh-CN" },
    { thai: "ฉัน (กรรม)", target: "我", reading: "หว่อ", lang: "zh-CN" },
    { thai: "เขา (กรรม)", target: "他", reading: "ทา", lang: "zh-CN" },
    { thai: "เธอ (กรรม)", target: "她", reading: "ทา", lang: "zh-CN" },
    { thai: "พวกเรา (กรรม)", target: "我们", reading: "หว่อเมิน", lang: "zh-CN" },
    { thai: "พวกเขา (กรรม)", target: "他们", reading: "ทาเมิน", lang: "zh-CN" },
    { thai: "ผู้ชาย", target: "男人", reading: "หนานเหริน", lang: "zh-CN" },
    { thai: "ผู้หญิง", target: "女人", reading: "นวี่เหริน", lang: "zh-CN" },
    { thai: "เด็กผู้ชาย", target: "男孩", reading: "หนานไห", lang: "zh-CN" },
    { thai: "เด็กผู้หญิง", target: "女孩", reading: "นวี่ไห", lang: "zh-CN" },
    { thai: "เพื่อน", target: "朋友", reading: "เผิงโหย่ว", lang: "zh-CN" },
    { thai: "ครอบครัว", target: "家人", reading: "เจียเหริน", lang: "zh-CN" },
    { thai: "บุคคล (คนเดียว)", target: "人", reading: "เหริน", lang: "zh-CN" },
    { thai: "ผู้คน (หลายคน)", target: "人们", reading: "เหรินเมิน", lang: "zh-CN" },

    // --- 2. หมวดร่างกาย (Body Parts) - 20 คำ ---
    { thai: "หัว", target: "头", reading: "โถว", lang: "zh-CN" },
    { thai: "ผม", target: "头发", reading: "โถวฝะ", lang: "zh-CN" },
    { thai: "ตา", target: "眼睛", reading: "เหยี่ยนจิง", lang: "zh-CN" },
    { thai: "หู", target: "耳朵", reading: "เอ๋อร์ตัว", lang: "zh-CN" },
    { thai: "จมูก", target: "鼻子", reading: "ปี๋จึ", lang: "zh-CN" },
    { thai: "ปาก", target: "嘴巴", reading: "จุ่ยปา", lang: "zh-CN" },
    { thai: "ฟัน", target: "牙齿", reading: "หย่าฉื่อ", lang: "zh-CN" },
    { thai: "ใบหน้า", target: "脸", reading: "เหลี่ยน", lang: "zh-CN" },
    { thai: "คอ", target: "脖子", reading: "ป๋อจึ", lang: "zh-CN" },
    { thai: "ไหล่", target: "肩膀", reading: "เจียนปั่ง", lang: "zh-CN" },
    { thai: "แขน", target: "手臂", reading: "โส่วปี้", lang: "zh-CN" },
    { thai: "มือ", target: "手", reading: "โส่ว", lang: "zh-CN" },
    { thai: "นิ้วมือ", target: "手指", reading: "โส่วจื่อ", lang: "zh-CN" },
    { thai: "ขา", target: "腿", reading: "ทุ่ย", lang: "zh-CN" },
    { thai: "เท้า", target: "脚", reading: "เจี่ยว", lang: "zh-CN" },
    { thai: "นิ้วเท้า", target: "脚趾", reading: "เจี่ยวจื่อ", lang: "zh-CN" },
    { thai: "หลัง", target: "背", reading: "เป้ย", lang: "zh-CN" },
    { thai: "หัวใจ", target: "心", reading: "ซิน", lang: "zh-CN" },
    { thai: "เลือด", target: "血", reading: "เซวี่ย", lang: "zh-CN" },
    { thai: "กระดูก", target: "骨头", reading: "กู่โถว", lang: "zh-CN" },

    // --- 3. หมวดครอบครัวและญาติ (Family & Relatives) - 15 คำ ---
    { thai: "พ่อ", target: "爸爸", reading: "ป้าปะ", lang: "zh-CN" },
    { thai: "แม่", target: "妈妈", reading: "ม่ามะ", lang: "zh-CN" },
    { thai: "ผู้ปกครอง / พ่อแม่", target: "父母", reading: "ฟู่หมู่", lang: "zh-CN" },
    { thai: "ลูกชาย", target: "儿子", reading: "เอ๋อร์จึ", lang: "zh-CN" },
    { thai: "ลูกสาว", target: "女儿", reading: "นวี่เอ๋อร์", lang: "zh-CN" },
    { thai: "พี่ชาย / น้องชาย", target: "兄弟", reading: "ซยงตี้", lang: "zh-CN" },
    { thai: "พี่สาว / น้องสาว", target: "姐妹", reading: "เจี่ยเม่ย", lang: "zh-CN" },
    { thai: "ปู่ / ตา", target: "爷爷", reading: "เหยียเยะ", lang: "zh-CN" },
    { thai: "ย่า / ยาย", target: "奶奶", reading: "หน่ายนาย", lang: "zh-CN" },
    { thai: "ลุง / น้าชาย / อาชาย", target: "叔叔", reading: "ซูซุ", lang: "zh-CN" },
    { thai: "ป้า / น้าหญิง / อาหญิง", target: "阿姨", reading: "อาอี๋", lang: "zh-CN" },
    { thai: "ลูกพี่ลูกน้อง", target: "表亲", reading: "เปี่ยวชิน", lang: "zh-CN" },
    { thai: "สามี", target: "丈夫", reading: "จั้งฟุ", lang: "zh-CN" },
    { thai: "ภรรยา", target: "妻子", reading: "ชีจึ", lang: "zh-CN" },
    { thai: "เด็ก / ลูก", target: "孩子", reading: "ไหจึ", lang: "zh-CN" },

    // --- 4. หมวดเวลา (Time & Calendar) - 20 คำ ---
    { thai: "วินาที", target: "秒", reading: "เหมี่ยว", lang: "zh-CN" },
    { thai: "นาที", target: "分钟", reading: "เฟินจง", lang: "zh-CN" },
    { thai: "ชั่วโมง", target: "小时", reading: "เสี่ยวสือ", lang: "zh-CN" },
    { thai: "วัน", target: "天", reading: "เทียน", lang: "zh-CN" },
    { thai: "สัปดาห์", target: "星期", reading: "ซิงชี", lang: "zh-CN" },
    { thai: "เดือน", target: "月", reading: "เยวี่ย", lang: "zh-CN" },
    { thai: "ปี", target: "年", reading: "เหนียน", lang: "zh-CN" },
    { thai: "ตอนเช้า", target: "早上", reading: "เจ่าซ่าง", lang: "zh-CN" },
    { thai: "ตอนบ่าย", target: "下午", reading: "เซี่ยอู่", lang: "zh-CN" },
    { thai: "ตอนเย็น / ค่ำ", target: "晚上", reading: "หว่านซ่าง", lang: "zh-CN" },
    { thai: "ตอนกลางคืน", target: "夜晚", reading: "เยี่ยหว่าน", lang: "zh-CN" },
    { thai: "วันนี้", target: "今天", reading: "จินเทียน", lang: "zh-CN" },
    { thai: "พรุ่งนี้", target: "明天", reading: "หมิงเทียน", lang: "zh-CN" },
    { thai: "เมื่อวานนี้", target: "昨天", reading: "จั๋วเทียน", lang: "zh-CN" },
    { thai: "ตอนนี้ / ปัจจุบัน", target: "现在", reading: "เซี้ยนจ้าย", lang: "zh-CN" },
    { thai: "ตอนนั้น / หลังจากนั้น", target: "那时", reading: "น่าสือ", lang: "zh-CN" },
    { thai: "อนาคต", target: "未来", reading: "เว่ยไหล", lang: "zh-CN" },
    { thai: "อดีต", target: "过去", reading: "กั้วชวี่", lang: "zh-CN" },
    { thai: "ปัจจุบัน / ของขวัญ", target: "目前", reading: "มู่เฉียน", lang: "zh-CN" },
    { thai: "เวลา", target: "时间", reading: "สือเจียน", lang: "zh-CN" },

    // --- 5. หมวดธรรมชาติและสิ่งแวดล้อม (Nature & Environment) - 25 คำ ---
    { thai: "ดวงอาทิตย์", target: "太阳", reading: "ไท่หยาง", lang: "zh-CN" },
    { thai: "ดวงจันทร์", target: "月亮", reading: "เยวี่ยเลี่ยง", lang: "zh-CN" },
    { thai: "ดาว", target: "星星", reading: "ซิงซิง", lang: "zh-CN" },
    { thai: "ท้องฟ้า", target: "天空", reading: "เทียนคง", lang: "zh-CN" },
    { thai: "เมฆ", target: "云", reading: "หยุน", lang: "zh-CN" },
    { thai: "ฝน", target: "雨", reading: "หวี่", lang: "zh-CN" },
    { thai: "ลม", target: "风", reading: "เฟิง", lang: "zh-CN" },
    { thai: "หิมะ", target: "雪", reading: "เสวี่ย", lang: "zh-CN" },
    { thai: "ไฟ", target: "火", reading: "หั่ว", lang: "zh-CN" },
    { thai: "น้ำ", target: "水", reading: "สุ่ย", lang: "zh-CN" },
    { thai: "โลก (ดาวเคราะห์) / ดิน", target: "地球", reading: "ตี้ฉิว", lang: "zh-CN" },
    { thai: "โลก (รวมทั้งหมด)", target: "世界", reading: "ซื่อเจี้ย", lang: "zh-CN" },
    { thai: "ต้นไม้", target: "树", reading: "ซู่", lang: "zh-CN" },
    { thai: "ดอกไม้", target: "花", reading: "ฮวา", lang: "zh-CN" },
    { thai: "หญ้า", target: "草", reading: "เฉ่า", lang: "zh-CN" },
    { thai: "สัตว์", target: "动物", reading: "ต้งอู้", lang: "zh-CN" },
    { thai: "นก", target: "鸟", reading: "เหนี่ยว", lang: "zh-CN" },
    { thai: "ปลา", target: "鱼", reading: "อวี๋", lang: "zh-CN" },
    { thai: "สุนัข", target: "狗", reading: "โก่ว", lang: "zh-CN" },
    { thai: "แมว", target: "猫", reading: "เมา", lang: "zh-CN" },
    { thai: "ภูเขา", target: "山", reading: "ซาน", lang: "zh-CN" },
    { thai: "แม่น้ำ", target: "河", reading: "เหอ", lang: "zh-CN" },
    { thai: "ทะเล", target: "海", reading: "ไห่", lang: "zh-CN" },
    { thai: "หิน", target: "石头", reading: "สือโถว", lang: "zh-CN" },
    { thai: "ทราย", target: "沙子", reading: "ซาจึ", lang: "zh-CN" },

    // --- 6. หมวดกริยาและการกระทำ (Common Action Verbs) - 35 คำ ---
    { thai: "กิน", target: "吃", reading: "ชือ", lang: "zh-CN" },
    { thai: "ดื่ม", target: "喝", reading: "เฮอ", lang: "zh-CN" },
    { thai: "นอน", target: "睡觉", reading: "ซุ่ยเจี้ยว", lang: "zh-CN" },
    { thai: "วิ่ง", target: "跑", reading: "เผ่า", lang: "zh-CN" },
    { thai: "เดิน", target: "走", reading: "โจ่ว", lang: "zh-CN" },
    { thai: "กระโดด", target: "跳", reading: "เที่ยว", lang: "zh-CN" },
    { thai: "อ่าน", target: "读", reading: "ตู๋", lang: "zh-CN" },
    { thai: "เขียน", target: "写", reading: "เสี่ย", lang: "zh-CN" },
    { thai: "ฟัง", target: "听", reading: "ทิง", lang: "zh-CN" },
    { thai: "พูด", target: "说", reading: "ซัว", lang: "zh-CN" },
    { thai: "ดู / มอง", target: "看", reading: "คั่น", lang: "zh-CN" },
    { thai: "คิด", target: "想", reading: "เสี่ยง", lang: "zh-CN" },
    { thai: "ทำงาน", target: "工作", reading: "กงจั้ว", lang: "zh-CN" },
    { thai: "เรียน", target: "学习", reading: "สวีสี", lang: "zh-CN" },
    { thai: "สอน", target: "教", reading: "เจียว", lang: "zh-CN" },
    { thai: "ซื้อ", target: "买", reading: "หม่าย", lang: "zh-CN" },
    { thai: "ขาย", target: "卖", reading: "ม่าย", lang: "zh-CN" },
    { thai: "ทำ / สร้าง", target: "做", reading: "จั้ว", lang: "zh-CN" },
    { thai: "ให้", target: "给", reading: "เก่ย", lang: "zh-CN" },
    { thai: "รับ", target: "收到", reading: "โซวเต้า", lang: "zh-CN" },
    { thai: "ถือ / จับ", target: "拿", reading: "หนา", lang: "zh-CN" },
    { thai: "เปิด", target: "开", reading: "ไค", lang: "zh-CN" },
    { thai: "ปิด", target: "关", reading: "กวน", lang: "zh-CN" },
    { thai: "ขับรถ", target: "开车", reading: "ไคเชอ", lang: "zh-CN" },
    { thai: "ขี่ / ปั่น", target: "骑", reading: "ฉี", lang: "zh-CN" },
    { thai: "ว่ายน้ำ", target: "游泳", reading: "โหยวหย่ง", lang: "zh-CN" },
    { thai: "บิน", target: "飞", reading: "เฟย", lang: "zh-CN" },
    { thai: "หัวเราะ", target: "笑", reading: "เสี้ยว", lang: "zh-CN" },
    { thai: "ร้องไห้", target: "哭", reading: "คู", lang: "zh-CN" },
    { thai: "ยิ้ม", target: "微笑", reading: "เวยเสี้ยว", lang: "zh-CN" },
    { thai: "รอ", target: "等", reading: "เติ่ง", lang: "zh-CN" },
    { thai: "หยุด", target: "停", reading: "ถิง", lang: "zh-CN" },
    { thai: "ช่วย", target: "帮助", reading: "ปางจู้", lang: "zh-CN" },
    { thai: "เล่น", target: "玩", reading: "หวาน", lang: "zh-CN" },
    { thai: "ร้องเพลง", target: "唱歌", reading: "ช่างเกอ", lang: "zh-CN" },

    // --- 7. หมวดสีสัน (Colors) - 15 คำ ---
    { thai: "สีแดง", target: "红色", reading: "หงเซ่อ", lang: "zh-CN" },
    { thai: "สีน้ำเงิน", target: "蓝色", reading: "หลานเซ่อ", lang: "zh-CN" },
    { thai: "สีเขียว", target: "绿色", reading: "ลวี่เซ่อ", lang: "zh-CN" },
    { thai: "สีเหลือง", target: "黄色", reading: "หวงเซ่อ", lang: "zh-CN" },
    { thai: "สีดำ", target: "黑色", reading: "เฮยเซ่อ", lang: "zh-CN" },
    { thai: "สีขาว", target: "白色", reading: "ป๋ายเซ่อ", lang: "zh-CN" },
    { thai: "สีส้ม", target: "橙色", reading: "เฉิงเซ่อ", lang: "zh-CN" },
    { thai: "สีชมพู", target: "粉色", reading: "เฝิ่นเซ่อ", lang: "zh-CN" },
    { thai: "สีม่วง", target: "紫色", reading: "จื่อเซ่อ", lang: "zh-CN" },
    { thai: "สีน้ำตาล", target: "棕色", reading: "จงเซ่อ", lang: "zh-CN" },
    { thai: "สีเทา", target: "灰色", reading: "ฮุยเซ่อ", lang: "zh-CN" },
    { thai: "สีทอง", target: "金色", reading: "จินเซ่อ", lang: "zh-CN" },
    { thai: "สีเงิน", target: "银色", reading: "อิ๋นเซ่อ", lang: "zh-CN" },
    { thai: "สีสัน", target: "颜色", reading: "เหยียนเซ่อ", lang: "zh-CN" },
    { thai: "สว่าง", target: "明亮", reading: "หมิงเลี่ยง", lang: "zh-CN" },

    // --- 8. หมวดสิ่งของรอบตัวและในบ้าน (House & Objects) - 30 คำ ---
    { thai: "บ้าน", target: "房子", reading: "ฝางจึ", lang: "zh-CN" },
    { thai: "ห้อง", target: "房间", reading: "ฝางเจียน", lang: "zh-CN" },
    { thai: "ประตู", target: "门", reading: "เหมิน", lang: "zh-CN" },
    { thai: "หน้าต่าง", target: "窗户", reading: "ชวงหุ", lang: "zh-CN" },
    { thai: "โต๊ะ", target: "桌子", reading: "จัวจึ", lang: "zh-CN" },
    { thai: "เก้าอี้", target: "椅子", reading: "อี่จึ", lang: "zh-CN" },
    { thai: "เตียง", target: "床", reading: "ฉวง", lang: "zh-CN" },
    { thai: "หมอน", target: "枕头", reading: "เจิ่นโถว", lang: "zh-CN" },
    { thai: "ผ้าห่ม", target: "被子", reading: "เป้ยจึ", lang: "zh-CN" },
    { thai: "โทรศัพท์", target: "电话", reading: "เตี้ยนฮว่า", lang: "zh-CN" },
    { thai: "คอมพิวเตอร์", target: "电脑", reading: "เตี้ยนเหน่า", lang: "zh-CN" },
    { thai: "หนังสือ", target: "书", reading: "ซู", lang: "zh-CN" },
    { thai: "ปากกา", target: "笔", reading: "ปี่", lang: "zh-CN" },
    { thai: "กระดาษ", target: "纸", reading: "จื่อ", lang: "zh-CN" },
    { thai: "กระเป๋า", target: "包", reading: "เปา", lang: "zh-CN" },
    { thai: "กุญแจ", target: "钥匙", reading: "เย่าสึ", lang: "zh-CN" },
    { thai: "เงิน", target: "钱", reading: "เฉียน", lang: "zh-CN" },
    { thai: "แก้วน้ำ", target: "杯子", reading: "เปยจึ", lang: "zh-CN" },
    { thai: "จาน", target: "盘子", reading: "ผานจึ", lang: "zh-CN" },
    { thai: "ช้อน", target: "勺子", reading: "เสาจึ", lang: "zh-CN" },
    { thai: "ส้อม", target: "叉子", reading: "ชาจึ", lang: "zh-CN" },
    { thai: "รถยนต์", target: "汽车", reading: "ชี่เชอ", lang: "zh-CN" },
    { thai: "จักรยาน", target: "自行车", reading: "จื้อสิงเชอ", lang: "zh-CN" },
    { thai: "นาฬิกา", target: "手表", reading: "โส่วเปี่ยว", lang: "zh-CN" },
    { thai: "เสื้อผ้า", target: "衣服", reading: "อีฝุ", lang: "zh-CN" },
    { thai: "รองเท้า", target: "鞋子", reading: "เสียจึ", lang: "zh-CN" },
    { thai: "แว่นตา", target: "眼镜", reading: "เหยี่ยนจิ้ง", lang: "zh-CN" },
    { thai: "ไฟ / หลอดไฟ", target: "灯", reading: "เติง", lang: "zh-CN" },
    { thai: "พัดลม", target: "风扇", reading: "เฟิงซั่น", lang: "zh-CN" },
    { thai: "กล่อง", target: "盒子", reading: "เหอจึ", lang: "zh-CN" },

    // --- 9. หมวดอาหารและเครื่องดื่ม (Food & Drink) - 20 คำ ---
    { thai: "ข้าว", target: "米饭", reading: "หมี่ฟ่าน", lang: "zh-CN" },
    { thai: "ขนมปัง", target: "面包", reading: "เมี่ยนเปา", lang: "zh-CN" },
    { thai: "เนื้อสัตว์", target: "肉", reading: "โร่ว", lang: "zh-CN" },
    { thai: "ไก่", target: "鸡肉", reading: "จีโร่ว", lang: "zh-CN" },
    { thai: "ไข่", target: "鸡蛋", reading: "จีต้าน", lang: "zh-CN" },
    { thai: "ผัก", target: "蔬菜", reading: "ซูไช่", lang: "zh-CN" },
    { thai: "ผลไม้", target: "水果", reading: "สุยกั่ว", lang: "zh-CN" },
    { thai: "นม", target: "牛奶", reading: "หนิวหน่าย", lang: "zh-CN" },
    { thai: "น้ำเปล่า", target: "水", reading: "สุ่ย", lang: "zh-CN" },
    { thai: "กาแฟ", target: "咖啡", reading: "คาเฟย", lang: "zh-CN" },
    { thai: "ชา", target: "茶", reading: "ฉา", lang: "zh-CN" },
    { thai: "น้ำตาล", target: "糖", reading: "ถาง", lang: "zh-CN" },
    { thai: "เกลือ", target: "盐", reading: "หยาน", lang: "zh-CN" },
    { thai: "เผ็ด", target: "辣", reading: "ล่า", lang: "zh-CN" },
    { thai: "หวาน", target: "甜", reading: "เถียน", lang: "zh-CN" },
    { thai: "เปรี้ยว", target: "酸", reading: "ซวน", lang: "zh-CN" },
    { thai: "เค็ม", target: "咸", reading: "เสียน", lang: "zh-CN" },
    { thai: "ขม", target: "苦", reading: "ขู่", lang: "zh-CN" },
    { thai: "ร้อน", target: "热", reading: "เร่อ", lang: "zh-CN" },
    { thai: "เย็น", target: "冷", reading: "เหลิ่ง", lang: "zh-CN" },

    // --- 10. หมวดสถานที่และอาคาร (Places & Buildings) - 30 คำ ---
    { thai: "โรงเรียน", target: "学校", reading: "เสวียเสี้ยว", lang: "zh-CN" },
    { thai: "โรงพยาบาล", target: "医院", reading: "อีเยี่ยน", lang: "zh-CN" },
    { thai: "ธนาคาร", target: "银行", reading: "อิ๋นหาง", lang: "zh-CN" },
    { thai: "ร้านอาหาร", target: "餐厅", reading: "ชานทิง", lang: "zh-CN" },
    { thai: "โรงแรม", target: "酒店", reading: "จิ่วเตี้ยน", lang: "zh-CN" },
    { thai: "ตลาด", target: "市场", reading: "ซื่อฉ่าง", lang: "zh-CN" },
    { thai: "สำนักงาน / ออฟฟิศ", target: "办公室", reading: "ป้านกงซื่อ", lang: "zh-CN" },
    { thai: "ร้านค้า", target: "商店", reading: "ซางเตี้ยน", lang: "zh-CN" },
    { thai: "ห้างสรรพสินค้า", target: "商场", reading: "ซางฉ่าง", lang: "zh-CN" },
    { thai: "สนามบิน", target: "机场", reading: "จีฉ่าง", lang: "zh-CN" },
    { thai: "สถานี", target: "车站", reading: "เชอจ้าน", lang: "zh-CN" },
    { thai: "สวนสาธารณะ", target: "公园", reading: "กงหยวน", lang: "zh-CN" },
    { thai: "ห้องสมุด", target: "图书馆", reading: "ถูซูก่วน", lang: "zh-CN" },
    { thai: "วัด", target: "寺庙", reading: "ซื่อเมี้ยว", lang: "zh-CN" },
    { thai: "เมือง", target: "城市", reading: "เฉิงซื่อ", lang: "zh-CN" },
    { thai: "หมู่บ้าน", target: "村庄", reading: "ชุนจวง", lang: "zh-CN" },
    { thai: "ประเทศ", target: "国家", reading: "กั๋วเจีย", lang: "zh-CN" },
    { thai: "ถนน", target: "道路", reading: "เต้าลู่", lang: "zh-CN" },
    { thai: "ทางแยก", target: "十字路口", reading: "สือจื้อ ลู่โข่ว", lang: "zh-CN" },
    { thai: "สะพาน", target: "桥", reading: "เฉียว", lang: "zh-CN" },
    { thai: "ฟาร์ม", target: "农场", reading: "หนงฉ่าง", lang: "zh-CN" },
    { thai: "โรงงาน", target: "工厂", reading: "กงฉ่าง", lang: "zh-CN" },
    { thai: "สวน", target: "花园", reading: "ฮวาหยวน", lang: "zh-CN" },
    { thai: "ห้องน้ำ", target: "洗手间", reading: "สีโส่วเจียน", lang: "zh-CN" },
    { thai: "ห้องครัว", target: "厨房", reading: "ฉูฝาง", lang: "zh-CN" },
    { thai: "ห้องนอน", target: "卧室", reading: "ว่อซื่อ", lang: "zh-CN" },
    { thai: "ชั้นบน", target: "楼上", reading: "โหลวซ่าง", lang: "zh-CN" },
    { thai: "ชั้นล่าง", target: "楼下", reading: "โหลวเซี่ย", lang: "zh-CN" },
    { thai: "มุม", target: "角落", reading: "เจี่ยวลั่ว", lang: "zh-CN" },
    { thai: "ใจกลางเมือง", target: "市中心", reading: "ซื่อ จงซิน", lang: "zh-CN" },
	, // --- 11. หมวดการเดินทางและยานพาหนะ (Travel & Vehicles) - 20 คำ ---
    { thai: "เครื่องบิน", target: "飞机", reading: "เฟยจี", lang: "zh-CN" },
    { thai: "เรือ", target: "船", reading: "ฉวน", lang: "zh-CN" },
    { thai: "รถไฟ", target: "火车", reading: "หั่วเชอ", lang: "zh-CN" },
    { thai: "รถเมล์ / รถบัส", target: "公交车", reading: "กงเจียวเชอ", lang: "zh-CN" },
    { thai: "มอเตอร์ไซค์", target: "摩托车", reading: "หมัวทัวเชอ", lang: "zh-CN" },
    { thai: "ตั๋ว", target: "票", reading: "เพี่ยว", lang: "zh-CN" },
    { thai: "แผนที่", target: "地图", reading: "ตี้ถู", lang: "zh-CN" },
    { thai: "สัมภาระ / กระเป๋าเดินทาง", target: "行李", reading: "สิงหลี่", lang: "zh-CN" },
    { thai: "พาสปอร์ต", target: "护照", reading: "ฮู้จ้าว", lang: "zh-CN" },
    { thai: "เที่ยวบิน", target: "航班", reading: "หางปาน", lang: "zh-CN" },
    { thai: "โรงแรม", target: "酒店", reading: "จิ่วเตี้ยน", lang: "zh-CN" },
    { thai: "ท่องเที่ยว", target: "旅游", reading: "ลวี่โหยว", lang: "zh-CN" },
    { thai: "ทิศทาง", target: "方向", reading: "ฟางเซี่ยง", lang: "zh-CN" },
    { thai: "ทางเหนือ", target: "北", reading: "เป่ย", lang: "zh-CN" },
    { thai: "ทางใต้", target: "南", reading: "หนาน", lang: "zh-CN" },
    { thai: "ทางตะวันออก", target: "东", reading: "ตง", lang: "zh-CN" },
    { thai: "ทางตะวันตก", target: "西", reading: "ซี", lang: "zh-CN" },
    { thai: "ตรงไป", target: "直走", reading: "จื๋อโจ่ว", lang: "zh-CN" },
    { thai: "เลี้ยว", target: "转", reading: "จ่วน", lang: "zh-CN" },
    { thai: "มาถึง", target: "到达", reading: "เต้าต๋า", lang: "zh-CN" },

    // --- 12. หมวดคำคุณศัพท์พื้นฐาน (Basic Adjectives) - 50 คำ ---
    { thai: "ใหญ่", target: "大", reading: "ต้า", lang: "zh-CN" },
    { thai: "เล็ก", target: "小", reading: "เสี่ยว", lang: "zh-CN" },
    { thai: "สูง", target: "高", reading: "เกา", lang: "zh-CN" },
    { thai: "ต่ำ", target: "低", reading: "ตี", lang: "zh-CN" },
    { thai: "ยาว", target: "长", reading: "ฉาง", lang: "zh-CN" },
    { thai: "สั้น", target: "短", reading: "ต่วน", lang: "zh-CN" },
    { thai: "กว้าง", target: "宽", reading: "ควน", lang: "zh-CN" },
    { thai: "แคบ", target: "窄", reading: "ไจ่", lang: "zh-CN" },
    { thai: "หนา", target: "厚", reading: "โฮ่ว", lang: "zh-CN" },
    { thai: "บาง", target: "薄", reading: "เป๋า", lang: "zh-CN" },
    { thai: "หนัก", target: "重", reading: "จ้ง", lang: "zh-CN" },
    { thai: "เบา", target: "轻", reading: "ชิง", lang: "zh-CN" },
    { thai: "ยาก", target: "难", reading: "หนาน", lang: "zh-CN" },
    { thai: "ง่าย", target: "容易", reading: "หรงอี้", lang: "zh-CN" },
    { thai: "ดี", target: "好", reading: "ห่าว", lang: "zh-CN" },
    { thai: "แย่", target: "坏", reading: "ห้วย", lang: "zh-CN" },
    { thai: "สวย", target: "美丽", reading: "เหม่ยลี่", lang: "zh-CN" },
    { thai: "น่าเกลียด", target: "丑", reading: "โฉ่ว", lang: "zh-CN" },
    { thai: "ร้อน", target: "热", reading: "เร่อ", lang: "zh-CN" },
    { thai: "หนาว", target: "冷", reading: "เหลิ่ง", lang: "zh-CN" },
    { thai: "เร็ว", target: "快", reading: "ไขว้", lang: "zh-CN" },
    { thai: "ช้า", target: "慢", reading: "มั่น", lang: "zh-CN" },
    { thai: "ใหม่", target: "新", reading: "ซิน", lang: "zh-CN" },
    { thai: "เก่า / แก่", target: "旧", reading: "จิ้ว", lang: "zh-CN" },
    { thai: "แพง", target: "贵", reading: "กุ้ย", lang: "zh-CN" },
    { thai: "ถูก", target: "便宜", reading: "เพียนอี้", lang: "zh-CN" },
    { thai: "รวย", target: "富有", reading: "ฟู่โหย่ว", lang: "zh-CN" },
    { thai: "จน", target: "穷", reading: "ฉยง", lang: "zh-CN" },
    { thai: "สะอาด", target: "干净", reading: "กานจิ้ง", lang: "zh-CN" },
    { thai: "สกปรก", target: "脏", reading: "จาง", lang: "zh-CN" },
    { thai: "เต็ม", target: "满", reading: "หม่าน", lang: "zh-CN" },
    { thai: "ว่างเปล่า", target: "空", reading: "คง", lang: "zh-CN" },
    { thai: "ดัง", target: "吵", reading: "เฉ่า", lang: "zh-CN" },
    { thai: "เงียบ", target: "安静", reading: "อานจิ้ง", lang: "zh-CN" },
    { thai: "มีความสุข", target: "快乐", reading: "ไขว้เล่อ", lang: "zh-CN" },
    { thai: "เศร้า", target: "伤心", reading: "ซางซิน", lang: "zh-CN" },
    { thai: "โกรธ", target: "生气", reading: "เซิงชี่", lang: "zh-CN" },
    { thai: "หิว", target: "饿", reading: "เอ้อ", lang: "zh-CN" },
    { thai: "กระหายน้ำ", target: "渴", reading: "เข่อ", lang: "zh-CN" },
    { thai: "เหนื่อย", target: "累", reading: "เล่ย", lang: "zh-CN" },
    { thai: "ป่วย", target: "病", reading: "ปิ้ง", lang: "zh-CN" },
    { thai: "แข็งแรง", target: "强壮", reading: "เฉียงจ้วง", lang: "zh-CN" },
    { thai: "อ่อนแอ", target: "弱", reading: "ร่วก", lang: "zh-CN" },
    { thai: "ฉลาด", target: "聪明", reading: "ชงหมิง", lang: "zh-CN" },
    { thai: "โง่", target: "笨", reading: "เปิ้น", lang: "zh-CN" },
    { thai: "ปลอดภัย", target: "安全", reading: "อานฉวน", lang: "zh-CN" },
    { thai: "อันตราย", target: "危险", reading: "เวยเสี่ยน", lang: "zh-CN" },
    { thai: "น่าสนใจ", target: "有趣", reading: "โหย่วชวี่", lang: "zh-CN" },
    { thai: "น่าเบื่อ", target: "无聊", reading: "อู๋เหลียว", lang: "zh-CN" },
    { thai: "สำคัญ", target: "重要", reading: "จ้งเย่า", lang: "zh-CN" },

    // --- 13. หมวดอาชีพ (Occupations) - 25 คำ ---
    { thai: "พนักงาน", target: "员工", reading: "หยวนกง", lang: "zh-CN" },
    { thai: "นายจ้าง / หัวหน้า", target: "老板", reading: "เหลาป่าน", lang: "zh-CN" },
    { thai: "ผู้จัดการ", target: "经理", reading: "จิงหลี่", lang: "zh-CN" },
    { thai: "พนักงานขาย", target: "推销员", reading: "ทุยเซียวหยวน", lang: "zh-CN" },
    { thai: "วิศวกร", target: "工程师", reading: "กงเฉิงซือ", lang: "zh-CN" },
    { thai: "หมอ", target: "医生", reading: "อีเซิง", lang: "zh-CN" },
    { thai: "พยาบาล", target: "护士", reading: "ฮู้สึ", lang: "zh-CN" },
    { thai: "ครู", target: "老师", reading: "เหล่าซือ", lang: "zh-CN" },
    { thai: "ตำรวจ", target: "警察", reading: "จิ่งฉา", lang: "zh-CN" },
    { thai: "ทหาร", target: "士兵", reading: "ซื่อปิง", lang: "zh-CN" },
    { thai: "นักบิน", target: "飞行员", reading: "เฟยสิงหยวน", lang: "zh-CN" },
    { thai: "พ่อครัว", target: "厨师", reading: "ฉูซือ", lang: "zh-CN" },
    { thai: "พนักงานเสิร์ฟ", target: "服务员", reading: "ฝูอู้หยวน", lang: "zh-CN" },
    { thai: "คนขับรถ", target: "司机", reading: "ซือจี", lang: "zh-CN" },
    { thai: "นักเขียน", target: "作家", reading: "จั้วเจีย", lang: "zh-CN" },
    { thai: "ศิลปิน", target: "艺术家", reading: "อี้ซู่เจีย", lang: "zh-CN" },
    { thai: "นักธุรกิจ", target: "商人", reading: "ซางเหริน", lang: "zh-CN" },
    { thai: "เลขานุการ", target: "秘书", reading: "มี่ซู", lang: "zh-CN" },
    { thai: "ช่างภาพ", target: "摄影师", reading: "เซ่อยิ่งซือ", lang: "zh-CN" },
    { thai: "นักออกแบบ", target: "设计师", reading: "เซ่อจี้ซือ", lang: "zh-CN" },
    { thai: "ชาวนา / เกษตรกร", target: "农民", reading: "หนงหมิน", lang: "zh-CN" },
    { thai: "นักแสดง", target: "演员", reading: "เหยี่ยนหยวน", lang: "zh-CN" },
    { thai: "นักดนตรี", target: "音乐家", reading: "อินเยวี่ยเจีย", lang: "zh-CN" },
    { thai: "อาชีพ", target: "职业", reading: "จื๋อเยี่ย", lang: "zh-CN" },
    { thai: "งาน", target: "工作", reading: "กงจั้ว", lang: "zh-CN" },

    // --- 14. หมวดธุรกิจและการตลาด (Business & Marketing) - 40 คำ ---
    { thai: "บริษัท", target: "公司", reading: "กงซือ", lang: "zh-CN" },
    { thai: "ธุรกิจ", target: "生意", reading: "เซิงอี้", lang: "zh-CN" },
    { thai: "ลูกค้า", target: "顾客", reading: "กู้เค่อ", lang: "zh-CN" },
    { thai: "บริการ", target: "服务", reading: "ฝูอู้", lang: "zh-CN" },
    { thai: "ผลิตภัณฑ์ / สินค้า", target: "产品", reading: "ฉ่านผิ่น", lang: "zh-CN" },
    { thai: "แบรนด์ / ยี่ห้อ", target: "品牌", reading: "ผิ่นไผ", lang: "zh-CN" },
    { thai: "ราคา", target: "价格", reading: "เจี้ยเก๋อ", lang: "zh-CN" },
    { thai: "ส่วนลด", target: "折扣", reading: "เจ๋อโค่ว", lang: "zh-CN" },
    { thai: "โฆษณา", target: "广告", reading: "กวั่งเก้า", lang: "zh-CN" },
    { thai: "ยอดขาย", target: "销售", reading: "เซียวโซ่ว", lang: "zh-CN" },
    { thai: "การตลาด", target: "营销", reading: "อิ๋งเซียว", lang: "zh-CN" },
    { thai: "กำไร", target: "利润", reading: "ลี่รุ่น", lang: "zh-CN" },
    { thai: "ขาดทุน", target: "损失", reading: "สุ่นซือ", lang: "zh-CN" },
    { thai: "คู่แข่ง", target: "竞争者", reading: "จิ้งเจิงเจ่อ", lang: "zh-CN" },
    { thai: "กลยุทธ์", target: "战略", reading: "จ้านเลวี่ย", lang: "zh-CN" },
    { thai: "โอกาส", target: "机会", reading: "จีฮุ่ย", lang: "zh-CN" },
    { thai: "สัญญา", target: "合同", reading: "เหอถง", lang: "zh-CN" },
    { thai: "ข้อตกลง", target: "协议", reading: "เสียอี้", lang: "zh-CN" },
    { thai: "หุ้น", target: "股票", reading: "กู่เพี่ยว", lang: "zh-CN" },
    { thai: "การลงทุน", target: "投资", reading: "โถวจือ", lang: "zh-CN" },
    { thai: "เป้าหมาย", target: "目标", reading: "มู่เปียว", lang: "zh-CN" },
    { thai: "ความสำเร็จ", target: "成功", reading: "เฉิงกง", lang: "zh-CN" },
    { thai: "ล้มเหลว", target: "失败", reading: "ซือป้าย", lang: "zh-CN" },
    { thai: "การเติบโต", target: "增长", reading: "เจิงจ่าง", lang: "zh-CN" },
    { thai: "คุณภาพ", target: "质量", reading: "จื้อเลี่ยง", lang: "zh-CN" },
    { thai: "ปริมาณ", target: "数量", reading: "ซู่เลี่ยง", lang: "zh-CN" },
    { thai: "ภาษี", target: "税", reading: "ซุ่ย", lang: "zh-CN" },
    { thai: "ใบแจ้งหนี้", target: "发票", reading: "ฟาเพี่ยว", lang: "zh-CN" },
    { thai: "ใบเสร็จ", target: "收据", reading: "โซวจู้", lang: "zh-CN" },
    { thai: "ธนาคาร", target: "银行", reading: "อิ๋นหาง", lang: "zh-CN" },
    { thai: "บัญชี", target: "账户", reading: "จั้งฮู้", lang: "zh-CN" },
    { thai: "บัตรเครดิต", target: "信用卡", reading: "ซิ่นย่งข่า", lang: "zh-CN" },
    { thai: "เงินสด", target: "现金", reading: "เสี้ยนจิน", lang: "zh-CN" },
    { thai: "ค่าใช้จ่าย", target: "费用", reading: "เฟ่ยย่ง", lang: "zh-CN" },
    { thai: "งบประมาณ", target: "预算", reading: "อวี้ซ่วน", lang: "zh-CN" },
    { thai: "หนี้", target: "债务", reading: "ไจ้อู้", lang: "zh-CN" },
    { thai: "ความมั่งคั่ง", target: "财富", reading: "ไฉฟู่", lang: "zh-CN" },
    { thai: "เศรษฐกิจ", target: "经济", reading: "จิงจี้", lang: "zh-CN" },
    { thai: "ตลาด", target: "市场", reading: "ซื่อฉ่าง", lang: "zh-CN" },
    { thai: "อุตสาหกรรม", target: "行业", reading: "หางเยี่ย", lang: "zh-CN" },

    // --- 15. หมวดการสื่อสารและอุปกรณ์ในออฟฟิศ (Office & Communication) - 35 คำ ---
    { thai: "การประชุม", target: "会议", reading: "ฮุ่ยอี้", lang: "zh-CN" },
    { thai: "การนำเสนอ", target: "演示", reading: "เหยี่ยนซื่อ", lang: "zh-CN" },
    { thai: "รายงาน", target: "报告", reading: "เป้าเก้า", lang: "zh-CN" },
    { thai: "โครงการ", target: "项目", reading: "เซี่ยงมู่", lang: "zh-CN" },
    { thai: "กำหนดส่ง", target: "截止日期", reading: "เจี๋ยจื่อรื่อชี", lang: "zh-CN" },
    { thai: "ตารางเวลา", target: "日程表", reading: "รื่อเฉิงเปี่ยว", lang: "zh-CN" },
    { thai: "ข้อมูล", target: "信息", reading: "ซิ่นซี", lang: "zh-CN" },
    { thai: "อีเมล", target: "电子邮件", reading: "เตี้ยนจื่อโหยวเจี้ยน", lang: "zh-CN" },
    { thai: "ข้อความ", target: "消息", reading: "เซียวซิ", lang: "zh-CN" },
    { thai: "โทรศัพท์", target: "电话", reading: "เตี้ยนฮว่า", lang: "zh-CN" },
    { thai: "แล็ปท็อป", target: "笔记本电脑", reading: "ปี่จี้เปิ่นเตี้ยนเหน่า", lang: "zh-CN" },
    { thai: "เครื่องพิมพ์", target: "打印机", reading: "ต่าอิ้นจี", lang: "zh-CN" },
    { thai: "เอกสาร", target: "文件", reading: "เหวินเจี้ยน", lang: "zh-CN" },
    { thai: "ไฟล์ / แฟ้ม", target: "档案", reading: "ตั่งอ้าน", lang: "zh-CN" },
    { thai: "อินเทอร์เน็ต", target: "互联网", reading: "ฮู่เหลียนหวั่ง", lang: "zh-CN" },
    { thai: "รหัสผ่าน", target: "密码", reading: "มี่หม่า", lang: "zh-CN" },
    { thai: "หน้าจอ", target: "屏幕", reading: "ผิงมู่", lang: "zh-CN" },
    { thai: "แป้นพิมพ์", target: "键盘", reading: "เจี้ยนผาน", lang: "zh-CN" },
    { thai: "เมาส์", target: "鼠标", reading: "สู่เปียว", lang: "zh-CN" },
    { thai: "ซอฟต์แวร์", target: "软件", reading: "ร่วนเจี้ยน", lang: "zh-CN" },
    { thai: "ฮาร์ดแวร์", target: "硬件", reading: "อิ้งเจี้ยน", lang: "zh-CN" },
    { thai: "การสื่อสาร", target: "沟通", reading: "โกวทง", lang: "zh-CN" },
    { thai: "เครือข่าย", target: "网络", reading: "หวั่งลั่ว", lang: "zh-CN" },
    { thai: "ทีม", target: "团队", reading: "ถวนตุ้ย", lang: "zh-CN" },
    { thai: "ความร่วมมือ", target: "合作", reading: "เหอจั้ว", lang: "zh-CN" },
    { thai: "ความคิดเห็น", target: "反馈", reading: "ฝ่านคุ่ย", lang: "zh-CN" },
    { thai: "การตัดสินใจ", target: "决定", reading: "เจวี๋ยติ้ง", lang: "zh-CN" },
    { thai: "ปัญหา", target: "问题", reading: "เวิ่นถี", lang: "zh-CN" },
    { thai: "วิธีแก้ปัญหา", target: "解决方案", reading: "เจี่ยเจวี๋ยฟางอ้าน", lang: "zh-CN" },
    { thai: "นวัตกรรม", target: "创新", reading: "ชวงซิน", lang: "zh-CN" },
    { thai: "ความคิดสร้างสรรค์", target: "创造力", reading: "ชวงจ้าวลี่", lang: "zh-CN" },
    { thai: "ทักษะ", target: "技能", reading: "จี้เหนิง", lang: "zh-CN" },
    { thai: "ประสบการณ์", target: "经验", reading: "จิงเยี่ยน", lang: "zh-CN" },
    { thai: "ความรู้", target: "知识", reading: "จือสึ", lang: "zh-CN" },
    { thai: "เป้าหมาย", target: "目标", reading: "มู่เปียว", lang: "zh-CN" },

    // --- 16. หมวดเทคโนโลยีและฮาร์ดแวร์ (Technology & Hardware) - 25 คำ ---
    { thai: "เทคโนโลยี", target: "技术", reading: "จี้ซู่", lang: "zh-CN" },
    { thai: "อุปกรณ์", target: "设备", reading: "เซ่อเป้ย", lang: "zh-CN" },
    { thai: "มือถือ", target: "手机", reading: "โส่วจี", lang: "zh-CN" },
    { thai: "เซิร์ฟเวอร์", target: "服务器", reading: "ฝูอู้ชี่", lang: "zh-CN" },
    { thai: "หน้าจอ (อุปกรณ์)", target: "显示器", reading: "เสี่ยนซื่อชี่", lang: "zh-CN" },
    { thai: "แบตเตอรี่", target: "电池", reading: "เตี้ยนฉือ", lang: "zh-CN" },
    { thai: "สายเคเบิล", target: "电缆", reading: "เตี้ยนหล่าน", lang: "zh-CN" },
    { thai: "ไร้สาย", target: "无线", reading: "อู๋เซี้ยน", lang: "zh-CN" },
    { thai: "บลูทูธ", target: "蓝牙", reading: "หลานหยา", lang: "zh-CN" },
    { thai: "เราเตอร์", target: "路由器", reading: "ลู่โหยวชี่", lang: "zh-CN" },
    { thai: "สวิตช์", target: "交换机", reading: "เจียวฮ่วนจี", lang: "zh-CN" },
    { thai: "หน่วยความจำ", target: "内存", reading: "เน่ยฉุน", lang: "zh-CN" },
    { thai: "ตัวประมวลผล", target: "处理器", reading: "ฉู่หลี่ชี่", lang: "zh-CN" },
    { thai: "ที่เก็บข้อมูล", target: "存储", reading: "ฉุนฉู่", lang: "zh-CN" },
    { thai: "ระบบคลาวด์", target: "云", reading: "หยุน", lang: "zh-CN" },
    { thai: "เบราว์เซอร์", target: "浏览器", reading: "หลิวหลั่นชี่", lang: "zh-CN" },
    { thai: "แอปพลิเคชัน", target: "应用程序", reading: "อิ้งย่งเฉิงซวี่", lang: "zh-CN" },
    { thai: "ดาวน์โหลด", target: "下载", reading: "เซี่ยจ่าย", lang: "zh-CN" },
    { thai: "อัปโหลด", target: "上传", reading: "ซ่างฉวน", lang: "zh-CN" },
    { thai: "ติดตั้ง", target: "安装", reading: "อานจวง", lang: "zh-CN" },
    { thai: "อัปเดต", target: "更新", reading: "เกิงซิน", lang: "zh-CN" },
    { thai: "อัปเกรด", target: "升级", reading: "เซิงจี", lang: "zh-CN" },
    { thai: "เวอร์ชัน", target: "版本", reading: "ป่านเปิ่น", lang: "zh-CN" },
    { thai: "ระบบ", target: "系统", reading: "ซี่ถ่ง", lang: "zh-CN" },
    { thai: "แพลตฟอร์ม", target: "平台", reading: "ผิงไถ", lang: "zh-CN" },

    // --- 17. หมวดการพัฒนาเว็บและโปรแกรมมิ่ง (Web Development & Programming) - 40 คำ ---
    { thai: "โค้ด / รหัส", target: "代码", reading: "ไต้หม่า", lang: "zh-CN" },
    { thai: "โปรแกรม", target: "程序", reading: "เฉิงซวี่", lang: "zh-CN" },
    { thai: "นักพัฒนา", target: "开发者", reading: "ไคฟาเจ่อ", lang: "zh-CN" },
    { thai: "ฟังก์ชัน", target: "函数", reading: "หานซู่", lang: "zh-CN" },
    { thai: "ตัวแปร", target: "变量", reading: "เปี้ยนเลี่ยง", lang: "zh-CN" },
    { thai: "อาเรย์ / ชุดข้อมูล", target: "数组", reading: "ซู่จู่", lang: "zh-CN" },
    { thai: "อ็อบเจกต์", target: "对象", reading: "ตุ้ยเซี่ยง", lang: "zh-CN" },
    { thai: "ข้อความ (สตริง)", target: "字符串", reading: "จื้อฝูช่วน", lang: "zh-CN" },
    { thai: "จำนวนเต็ม", target: "整数", reading: "เจิ่งซู่", lang: "zh-CN" },
    { thai: "บูลีน (ตรรกะ)", target: "布尔值", reading: "ปู้เอ๋อร์จื๋อ", lang: "zh-CN" },
    { thai: "วนลูป", target: "循环", reading: "สวินหวน", lang: "zh-CN" },
    { thai: "เงื่อนไข", target: "条件", reading: "เถียวเจี้ยน", lang: "zh-CN" },
    { thai: "คำสั่ง", target: "语句", reading: "อวี่จู้", lang: "zh-CN" },
    { thai: "ข้อผิดพลาด", target: "错误", reading: "ชั่วอู้", lang: "zh-CN" },
    { thai: "บั๊ก / จุดบกพร่อง", target: "漏洞", reading: "ลู่ต้ง", lang: "zh-CN" },
    { thai: "แก้บั๊ก", target: "调试", reading: "เถียวซื่อ", lang: "zh-CN" },
    { thai: "สคริปต์", target: "脚本", reading: "เจี่ยวเปิ่น", lang: "zh-CN" },
    { thai: "ระบบหน้าบ้าน", target: "前端", reading: "เฉียนตวน", lang: "zh-CN" },
    { thai: "ระบบหลังบ้าน", target: "后端", reading: "โฮ่วตวน", lang: "zh-CN" },
    { thai: "ฐานข้อมูล", target: "数据库", reading: "ซู่จู้คู้", lang: "zh-CN" },
    { thai: "คำสืบค้น", target: "查询", reading: "ฉาสวิน", lang: "zh-CN" },
    { thai: "เอพีไอ", target: "接口", reading: "เจียโข่ว", lang: "zh-CN" },
    { thai: "เฟรมเวิร์ก", target: "框架", reading: "ควงเจี้ย", lang: "zh-CN" },
    { thai: "ไลบรารี", target: "库", reading: "คู้", lang: "zh-CN" },
    { thai: "คลังเก็บโค้ด", target: "仓库", reading: "ชางคู้", lang: "zh-CN" },
    { thai: "บันทึกการเปลี่ยน", target: "提交", reading: "ถีเจียว", lang: "zh-CN" },
    { thai: "ดันโค้ด", target: "推送", reading: "ทุยซ่ง", lang: "zh-CN" },
    { thai: "ดึงโค้ด", target: "拉取", reading: "ลาชวี่", lang: "zh-CN" },
    { thai: "สาขา (โค้ด)", target: "分支", reading: "เฟินจือ", lang: "zh-CN" },
    { thai: "รวม (โค้ด)", target: "合并", reading: "เหอปิ้ง", lang: "zh-CN" },
    { thai: "ไวยากรณ์ (โค้ด)", target: "语法", reading: "อวี่ฝ่า", lang: "zh-CN" },
    { thai: "แท็ก", target: "标签", reading: "เปียวเชียน", lang: "zh-CN" },
    { thai: "คุณลักษณะ", target: "属性", reading: "สู่ซิ่ง", lang: "zh-CN" },
    { thai: "องค์ประกอบ", target: "元素", reading: "หยวนซู่", lang: "zh-CN" },
    { thai: "ปลั๊กอิน", target: "插件", reading: "ชาเจี้ยน", lang: "zh-CN" },
    { thai: "โมดูล", target: "模块", reading: "หมัวไขว้", lang: "zh-CN" },
    { thai: "ส่วนประกอบ", target: "组件", reading: "จู่เจี้ยน", lang: "zh-CN" },
    { thai: "แม่แบบ", target: "模板", reading: "หมัวป่าน", lang: "zh-CN" },
    { thai: "โฮสต์", target: "主机", reading: "จู่จี", lang: "zh-CN" },
    { thai: "โดเมน", target: "域名", reading: "อวี้หมิง", lang: "zh-CN" },

    // --- 18. หมวดข้อมูล, UI/UX และตรรกะ (Data, UI/UX & Logic) - 35 คำ ---
    { thai: "ข้อมูล", target: "数据", reading: "ซู่จู้", lang: "zh-CN" },
    { thai: "ตรรกะ", target: "逻辑", reading: "หลัวจี", lang: "zh-CN" },
    { thai: "อินเทอร์เฟส / หน้าจอ", target: "界面", reading: "เจี้ยเมี่ยน", lang: "zh-CN" },
    { thai: "ผู้ใช้", target: "用户", reading: "ย่งฮู้", lang: "zh-CN" },
    { thai: "การออกแบบ", target: "设计", reading: "เซ่อจี้", lang: "zh-CN" },
    { thai: "โครงร่าง / เค้าโครง", target: "布局", reading: "ปู้จวี๋", lang: "zh-CN" },
    { thai: "การนำทาง", target: "导航", reading: "เต่าหาง", lang: "zh-CN" },
    { thai: "ปุ่ม", target: "按钮", reading: "อ้านหนิ่ว", lang: "zh-CN" },
    { thai: "ลิงก์ / จุดเชื่อมโยง", target: "链接", reading: "เลี่ยนเจีย", lang: "zh-CN" },
    { thai: "ไอคอน", target: "图标", reading: "ถูปียว", lang: "zh-CN" },
    { thai: "เมนู", target: "菜单", reading: "ไช่ตาน", lang: "zh-CN" },
    { thai: "ค้นหา", target: "搜索", reading: "โซวสั่ว", lang: "zh-CN" },
    { thai: "กรอง", target: "筛选", reading: "ซายเสวี่ยน", lang: "zh-CN" },
    { thai: "เรียงลำดับ", target: "排序", reading: "ไผซวี่", lang: "zh-CN" },
    { thai: "นำเข้า / ข้อมูลเข้า", target: "输入", reading: "ซูรู่", lang: "zh-CN" },
    { thai: "ส่งออก / ผลลัพธ์", target: "输出", reading: "ซูชู", lang: "zh-CN" },
    { thai: "คลิก", target: "点击", reading: "เตี่ยนจี", lang: "zh-CN" },
    { thai: "เลื่อน (จอ)", target: "滚动", reading: "กุ่นต้ง", lang: "zh-CN" },
    { thai: "ปัด (หน้าจอ)", target: "滑动", reading: "หฺวาต้ง", lang: "zh-CN" },
    { thai: "วางเมาส์เหนือ", target: "悬停", reading: "เสวียนถิง", lang: "zh-CN" },
    { thai: "โฟกัส", target: "焦点", reading: "เจียวเตี่ยน", lang: "zh-CN" },
    { thai: "ใช้งานอยู่", target: "激活", reading: "จีฮัว", lang: "zh-CN" },
    { thai: "ค่าเริ่มต้น", target: "默认", reading: "มั่วเริ่น", lang: "zh-CN" },
    { thai: "การตั้งค่า", target: "设置", reading: "เซ่อจี้", lang: "zh-CN" },
    { thai: "โปรไฟล์", target: "个人资料", reading: "เก้อเหริน จือเลี้ยว", lang: "zh-CN" },
    { thai: "บัญชี", target: "账户", reading: "จั้งฮู้", lang: "zh-CN" },
    { thai: "เข้าสู่ระบบ", target: "登录", reading: "เติงลู่", lang: "zh-CN" },
    { thai: "ออกจากระบบ", target: "登出", reading: "เติงชู", lang: "zh-CN" },
    { thai: "สมัครสมาชิก", target: "注册", reading: "จู้เช่อ", lang: "zh-CN" },
    { thai: "ความปลอดภัย", target: "安全", reading: "อานฉวน", lang: "zh-CN" },
    { thai: "ความเป็นส่วนตัว", target: "隐私", reading: "อิ่นซือ", lang: "zh-CN" },
    { thai: "การเข้าถึง", target: "访问", reading: "ฝั่งเวิ่น", lang: "zh-CN" },
    { thai: "โทเคน (รหัส)", target: "令牌", reading: "ลิ่งไผ", lang: "zh-CN" },
    { thai: "เซสชัน", target: "会话", reading: "ฮุ่ยฮว่า", lang: "zh-CN" },
    { thai: "คุกกี้ (ข้อมูล)", target: "Cookie", reading: "คุกกี้", lang: "zh-CN" },
	, // --- 19. หมวดสุขภาพ โภชนาการ และการดูแลร่างกาย (Health & Nutrition) - 30 คำ ---
    { thai: "สุขภาพ", target: "健康", reading: "เจี้ยนคัง", lang: "zh-CN" },
    { thai: "สุขภาพดี", target: "健康的", reading: "เจี้ยนคังเตอะ", lang: "zh-CN" },
    { thai: "โภชนาการ", target: "营养", reading: "อิ๋งหยั่ง", lang: "zh-CN" },
    { thai: "ระบบเผาผลาญ", target: "新陈代谢", reading: "ซินเฉินไต้เซี่ย", lang: "zh-CN" },
    { thai: "แคลอรี", target: "卡路里", reading: "ข่าลู่หลี่", lang: "zh-CN" },
    { thai: "โปรตีน", target: "蛋白质", reading: "ต้านป๋ายจื้อ", lang: "zh-CN" },
    { thai: "วิตามิน", target: "维生素", reading: "เหวยเซิงซู่", lang: "zh-CN" },
    { thai: "แร่ธาตุ", target: "矿物质", reading: "คว่างอู้จื้อ", lang: "zh-CN" },
    { thai: "ไขมัน", target: "脂肪", reading: "จือฝาง", lang: "zh-CN" },
    { thai: "คาร์โบไฮเดรต", target: "碳水化合物", reading: "ทั่นสุ่ยฮว่าเหออู้", lang: "zh-CN" },
    { thai: "เส้นใยอาหาร", target: "纤维", reading: "เซียนเหวย", lang: "zh-CN" },
    { thai: "กล้ามเนื้อ", target: "肌肉", reading: "จีโร่ว", lang: "zh-CN" },
    { thai: "น้ำหนัก", target: "体重", reading: "ถี่จ้ง", lang: "zh-CN" },
    { thai: "ส่วนสูง", target: "身高", reading: "เซินเกา", lang: "zh-CN" },
    { thai: "ความสมบูรณ์ของร่างกาย", target: "健身", reading: "เจี้ยนเซิน", lang: "zh-CN" },
    { thai: "โรงยิม", target: "健身房", reading: "เจี้ยนเซินฝาง", lang: "zh-CN" },
    { thai: "ออกกำลังกาย (หนัก)", target: "锻炼", reading: "ต้วนเลี่ยน", lang: "zh-CN" },
    { thai: "เหงื่อ", target: "汗", reading: "ฮั่น", lang: "zh-CN" },
    { thai: "การพักผ่อน", target: "休息", reading: "ซิวซิ", lang: "zh-CN" },
    { thai: "การฟื้นฟู", target: "恢复", reading: "ฮุยฟู่", lang: "zh-CN" },
    { thai: "โรคภัย", target: "疾病", reading: "จี๋ปิ้ง", lang: "zh-CN" },
    { thai: "ยารักษาโรค", target: "药", reading: "เย่า", lang: "zh-CN" },
    { thai: "คลินิก", target: "诊所", reading: "เจิ่นสั่ว", lang: "zh-CN" },
    { thai: "การบำบัด", target: "治疗", reading: "จื้อเหลียว", lang: "zh-CN" },
    { thai: "อาหารเสริม", target: "补充剂", reading: "ปู่ชงจี้", lang: "zh-CN" },
    { thai: "การย่อยอาหาร", target: "消化", reading: "เซียวฮว่า", lang: "zh-CN" },
    { thai: "ภูมิคุ้มกัน", target: "免疫", reading: "เหมี่ยนอี้", lang: "zh-CN" },
    { thai: "ออกซิเจน", target: "氧气", reading: "หยั่งชี่", lang: "zh-CN" },
    { thai: "โยเกิร์ต", target: "酸奶", reading: "ซวนหน่าย", lang: "zh-CN" },
    { thai: "เมล็ดพืช", target: "种子", reading: "จ่งจึ", lang: "zh-CN" },

    // --- 20. หมวดการเงิน การลงทุน และสินทรัพย์ (Finance & Investment) - 40 คำ ---
    { thai: "การเงิน", target: "金融", reading: "จินหรง", lang: "zh-CN" },
    { thai: "สินทรัพย์", target: "资产", reading: "จือฉ่าน", lang: "zh-CN" },
    { thai: "หนี้สิน", target: "负债", reading: "ฟู่ไจ้", lang: "zh-CN" },
    { thai: "กองทุน", target: "基金", reading: "จีจิน", lang: "zh-CN" },
    { thai: "กองทุนรวม", target: "共同基金", reading: "ก้งถงจีจิน", lang: "zh-CN" },
    { thai: "คริปโตเคอร์เรนซี", target: "加密货币", reading: "เจียมีฮั่วปี้", lang: "zh-CN" },
    { thai: "บิตคอยน์", target: "比特币", reading: "ปี่เท่อปี้", lang: "zh-CN" },
    { thai: "เงินปันผล", target: "股息", reading: "กู่ซี", lang: "zh-CN" },
    { thai: "ดอกเบี้ย", target: "利息", reading: "ลี่ซี", lang: "zh-CN" },
    { thai: "อัตรา", target: "比率", reading: "ปี่ลวี่", lang: "zh-CN" },
    { thai: "เงินเฟ้อ", target: "通货膨胀", reading: "ทงฮั่วเผิงจั้ง", lang: "zh-CN" },
    { thai: "พอร์ตการลงทุน", target: "投资组合", reading: "โถวจือจู่เหอ", lang: "zh-CN" },
    { thai: "กระจายความเสี่ยง", target: "分散投资", reading: "เฟินซ่านโถวจือ", lang: "zh-CN" },
    { thai: "ผลตอบแทน", target: "回报", reading: "หุยเป้า", lang: "zh-CN" },
    { thai: "ทุน / เงินทุน", target: "资本", reading: "จือเปิ่น", lang: "zh-CN" },
    { thai: "การเทรด / ซื้อขาย", target: "交易", reading: "เจียวยี้", lang: "zh-CN" },
    { thai: "ค่าเฉลี่ย", target: "平均", reading: "ผิงจวิน", lang: "zh-CN" },
    { thai: "การเกษียณอายุ", target: "退休", reading: "ทุ่ยซิว", lang: "zh-CN" },
    { thai: "เงินบำนาญ", target: "养老金", reading: "หยั่งเหล่าจิน", lang: "zh-CN" },
    { thai: "เก็บออม", target: "存款", reading: "ฉุนข่วน", lang: "zh-CN" },
    { thai: "รายได้ (เข้า)", target: "收入", reading: "โซวรู่", lang: "zh-CN" },
    { thai: "รายจ่าย", target: "支出", reading: "จือชู", lang: "zh-CN" },
    { thai: "สกุลเงิน", target: "货币", reading: "ฮั่วปี้", lang: "zh-CN" },
    { thai: "เหรียญ", target: "硬币", reading: "อิ้งปี้", lang: "zh-CN" },
    { thai: "ตลาดกระทิง (ขาขึ้น)", target: "牛市", reading: "หนิวซื่อ", lang: "zh-CN" },
    { thai: "ตลาดหมี (ขาลง)", target: "熊市", reading: "สยงซื่อ", lang: "zh-CN" },
    { thai: "หุ้นส่วน", target: "合伙人", reading: "เหอฮั่วเหริน", lang: "zh-CN" },
    { thai: "เจ้าของ", target: "所有者", reading: "สัวโหย่วเจ่อ", lang: "zh-CN" },
    { thai: "นักลงทุน", target: "投资者", reading: "โถวจือเจ่อ", lang: "zh-CN" },
    { thai: "มูลค่า", target: "价值", reading: "เจี้ยจื๋อ", lang: "zh-CN" },
    { thai: "ราคา", target: "价格", reading: "เจี้ยเก๋อ", lang: "zh-CN" },
    { thai: "โบรกเกอร์ (นายหน้า)", target: "经纪人", reading: "จิงจี้เหริน", lang: "zh-CN" },
    { thai: "ค่าธรรมเนียม", target: "费用", reading: "เฟ่ยย่ง", lang: "zh-CN" },
    { thai: "ความผันผวน", target: "波动", reading: "ปัวต้ง", lang: "zh-CN" },
    { thai: "ส่วนแบ่ง / หุ้น", target: "股份", reading: "กู่เฟิ่น", lang: "zh-CN" },
    { thai: "สภาพคล่อง", target: "流动性", reading: "หลิวต้งซิ่ง", lang: "zh-CN" },
    { thai: "ดัชนี", target: "指数", reading: "จื่อซู่", lang: "zh-CN" },
    { thai: "แนวโน้ม", target: "趋势", reading: "ชวีซื่อ", lang: "zh-CN" },
    { thai: "ความมั่งคั่ง", target: "财富", reading: "ไฉฟู่", lang: "zh-CN" },
    { thai: "ความเสี่ยง", target: "风险", reading: "เฟิงเสี่ยน", lang: "zh-CN" },

    // --- 21. หมวดกลยุทธ์ การแข่งขัน และเกมมิ่ง (Strategy & Gaming) - 30 คำ ---
    { thai: "กลยุทธ์", target: "策略", reading: "เช่อเลวี่ย", lang: "zh-CN" },
    { thai: "ยุทธวิธี", target: "战术", reading: "จ้านซู่", lang: "zh-CN" },
    { thai: "เกม", target: "游戏", reading: "โหยวซี่", lang: "zh-CN" },
    { thai: "การแข่งขัน", target: "比赛", reading: "ปี่ไซ้", lang: "zh-CN" },
    { thai: "การต่อสู้", target: "战斗", reading: "จ้านโต้ว", lang: "zh-CN" },
    { thai: "คู่แข่ง / ศัตรู", target: "敌人", reading: "ตี๋เหริน", lang: "zh-CN" },
    { thai: "คู่ปรับ", target: "对手", reading: "ตุ้ยโส่ว", lang: "zh-CN" },
    { thai: "ตัวละคร", target: "角色", reading: "เจวี๋ยเซ่อ", lang: "zh-CN" },
    { thai: "ระดับ / เลเวล", target: "等级", reading: "เติ่งจี๋", lang: "zh-CN" },
    { thai: "สถิติ / ค่าพลัง", target: "属性", reading: "สู่ซิ่ง", lang: "zh-CN" },
    { thai: "พลังชีวิต (HP)", target: "生命值", reading: "เซิงมิ่งจื๋อ", lang: "zh-CN" },
    { thai: "โจมตี", target: "攻击", reading: "กงจี", lang: "zh-CN" },
    { thai: "ป้องกัน", target: "防御", reading: "ฝางอวี้", lang: "zh-CN" },
    { thai: "ความเร็ว", target: "速度", reading: "ซู่ตู้", lang: "zh-CN" },
    { thai: "ไอเทม / สิ่งของ", target: "道具", reading: "เต้าจู้", lang: "zh-CN" },
    { thai: "สวมใส่", target: "装备", reading: "จวงเป้ย", lang: "zh-CN" },
    { thai: "วิวัฒนาการ", target: "进化", reading: "จิ้นฮว่า", lang: "zh-CN" },
    { thai: "เพาะพันธุ์", target: "繁殖", reading: "ฝานจื๋อ", lang: "zh-CN" },
    { thai: "ธรรมชาติ / นิสัย", target: "性格", reading: "ซิ่งเก๋อ", lang: "zh-CN" },
    { thai: "ความสามารถ", target: "能力", reading: "เหนิงลี่", lang: "zh-CN" },
    { thai: "ท่าต่อสู้ / การเคลื่อนไหว", target: "招式", reading: "เจาซื่อ", lang: "zh-CN" },
    { thai: "ตา / รอบ (การเล่น)", target: "回合", reading: "หุยเหอ", lang: "zh-CN" },
    { thai: "ชนะ", target: "赢", reading: "อิ๋ง", lang: "zh-CN" },
    { thai: "แพ้", target: "输", reading: "ซู", lang: "zh-CN" },
    { thai: "เสมอ", target: "平局", reading: "ผิงจวี๋", lang: "zh-CN" },
    { thai: "การฝึกฝน", target: "训练", reading: "ซวิ่นเลี่ยน", lang: "zh-CN" },
    { thai: "คะแนน", target: "分数", reading: "เฟินซู่", lang: "zh-CN" },
    { thai: "แชมป์", target: "冠军", reading: "กว้านจวิน", lang: "zh-CN" },
    { thai: "ทัวร์นาเมนต์", target: "锦标赛", reading: "จิ่นเปียวไซ้", lang: "zh-CN" },
    { thai: "ความเสียหาย", target: "伤害", reading: "ซางไฮ่", lang: "zh-CN" },

    // --- 22. หมวดอารมณ์และความรู้สึก (Emotions & Feelings) - 20 คำ ---
    { thai: "ความรัก", target: "爱", reading: "อ้าย", lang: "zh-CN" },
    { thai: "ความเกลียดชัง", target: "恨", reading: "เฮิ้น", lang: "zh-CN" },
    { thai: "ความกลัว", target: "恐惧", reading: "ข่งจู้", lang: "zh-CN" },
    { thai: "ความประหลาดใจ", target: "惊讶", reading: "จิงย่า", lang: "zh-CN" },
    { thai: "ความตกใจ", target: "震惊", reading: "เจิ้นจิง", lang: "zh-CN" },
    { thai: "ความตื่นเต้น", target: "兴奋", reading: "ซิงเฟิ่น", lang: "zh-CN" },
    { thai: "ความเบื่อหน่าย", target: "无聊", reading: "อู๋เหลียว", lang: "zh-CN" },
    { thai: "ความสับสน", target: "困惑", reading: "คุ่นฮั่ว", lang: "zh-CN" },
    { thai: "ความหวัง", target: "希望", reading: "ซีว่าง", lang: "zh-CN" },
    { thai: "ความสุข / ความปีติ", target: "喜悦", reading: "สี่เยวี่ย", lang: "zh-CN" },
    { thai: "ความเศร้า", target: "悲伤", reading: "เปยซาง", lang: "zh-CN" },
    { thai: "ความเครียด", target: "压力", reading: "ยาลี่", lang: "zh-CN" },
    { thai: "ผ่อนคลาย", target: "放松", reading: "ฟ่างซง", lang: "zh-CN" },
    { thai: "ความกังวล", target: "担心", reading: "ตานซิน", lang: "zh-CN" },
    { thai: "ความภาคภูมิใจ", target: "骄傲", reading: "เจียวเอ้า", lang: "zh-CN" },
    { thai: "ความอิจฉา", target: "嫉妒", reading: "จี๋ตู้", lang: "zh-CN" },
    { thai: "ความเห็นอกเห็นใจ", target: "同情", reading: "ถงฉิง", lang: "zh-CN" },
    { thai: "ความรู้สึกผิด", target: "内疚", reading: "เน่ยจิ้ว", lang: "zh-CN" },
    { thai: "ความมั่นใจ", target: "自信", reading: "จื้อซิ่น", lang: "zh-CN" },
    { thai: "ความสงสัย", target: "怀疑", reading: "หวายอี๋", lang: "zh-CN" },

    // --- 23. หมวดสภาพอากาศและฤดูกาล (Weather & Seasons) - 20 คำ ---
    { thai: "สภาพอากาศ", target: "天气", reading: "เทียนชี่", lang: "zh-CN" },
    { thai: "ฤดูกาล", target: "季节", reading: "จี้เจี๋ย", lang: "zh-CN" },
    { thai: "ฤดูร้อน", target: "夏天", reading: "เซี่ยเทียน", lang: "zh-CN" },
    { thai: "ฤดูหนาว", target: "冬天", reading: "ตงเทียน", lang: "zh-CN" },
    { thai: "ฤดูใบไม้ผลิ", target: "春天", reading: "ชุนเทียน", lang: "zh-CN" },
    { thai: "ฤดูใบไม้ร่วง", target: "秋天", reading: "ชิวเทียน", lang: "zh-CN" },
    { thai: "อุณหภูมิ", target: "温度", reading: "เวินตู้", lang: "zh-CN" },
    { thai: "องศา", target: "度", reading: "ตู้", lang: "zh-CN" },
    { thai: "แดดออก", target: "晴天", reading: "ฉิงเทียน", lang: "zh-CN" },
    { thai: "มีเมฆมาก", target: "多云", reading: "ตั๋วหยุน", lang: "zh-CN" },
    { thai: "ฝนตก", target: "下雨", reading: "เซี่ยหวี่", lang: "zh-CN" },
    { thai: "พายุ", target: "风暴", reading: "เฟิงเป้า", lang: "zh-CN" },
    { thai: "ฟ้าแลบ", target: "闪电", reading: "สั่นเตี้ยน", lang: "zh-CN" },
    { thai: "ฟ้าร้อง", target: "雷", reading: "เหลย", lang: "zh-CN" },
    { thai: "มีหมอก", target: "有雾", reading: "โหย่วอู้", lang: "zh-CN" },
    { thai: "น้ำแข็ง", target: "冰", reading: "ปิง", lang: "zh-CN" },
    { thai: "ละลาย", target: "融化", reading: "หรงฮว่า", lang: "zh-CN" },
    { thai: "แช่แข็ง", target: "结冰", reading: "เจี๋ยปิง", lang: "zh-CN" },
    { thai: "พยากรณ์", target: "预报", reading: "อวี้เป้า", lang: "zh-CN" },
    { thai: "ร่ม", target: "雨伞", reading: "หวี่สั่น", lang: "zh-CN" },

    // --- 24. หมวดงานอดิเรกและความบันเทิง (Hobbies & Entertainment) - 30 คำ ---
    { thai: "งานอดิเรก", target: "爱好", reading: "อ้ายเฮ้า", lang: "zh-CN" },
    { thai: "ดนตรี", target: "音乐", reading: "อินเยวี่ย", lang: "zh-CN" },
    { thai: "เพลง", target: "歌曲", reading: "เกอฉวี่", lang: "zh-CN" },
    { thai: "ภาพยนตร์", target: "电影", reading: "เตี้ยนอิ่ง", lang: "zh-CN" },
    { thai: "โรงภาพยนตร์", target: "电影院", reading: "เตี้ยนอิ่งย่วน", lang: "zh-CN" },
    { thai: "ศิลปะ", target: "艺术", reading: "อี้ซู่", lang: "zh-CN" },
    { thai: "การวาดภาพ (เส้น)", target: "画画", reading: "ฮว่าฮว่า", lang: "zh-CN" },
    { thai: "การทาสี / ภาพจิตรกรรม", target: "绘画", reading: "ฮุ่ยฮว่า", lang: "zh-CN" },
    { thai: "การเต้น", target: "跳舞", reading: "เที่ยวอู่", lang: "zh-CN" },
    { thai: "การถ่ายภาพ", target: "摄影", reading: "เซ่อยิ่ง", lang: "zh-CN" },
    { thai: "กล้อง", target: "相机", reading: "เซี่ยงจี", lang: "zh-CN" },
    { thai: "กีฬา", target: "运动", reading: "ยวิ่นต้ง", lang: "zh-CN" },
    { thai: "ฟุตบอล", target: "足球", reading: "จู๋ฉิว", lang: "zh-CN" },
    { thai: "บาสเกตบอล", target: "篮球", reading: "หลานฉิว", lang: "zh-CN" },
    { thai: "ว่ายน้ำ", target: "游泳", reading: "โหยวหย่ง", lang: "zh-CN" },
    { thai: "วิ่ง", target: "跑步", reading: "เผ่าปู้", lang: "zh-CN" },
    { thai: "การอ่าน", target: "阅读", reading: "เยวี่ยตู๋", lang: "zh-CN" },
    { thai: "นวนิยาย", target: "小说", reading: "เสี่ยวซัว", lang: "zh-CN" },
    { thai: "หนังสือการ์ตูน", target: "漫画", reading: "ม่านฮว่า", lang: "zh-CN" },
    { thai: "เกม", target: "游戏", reading: "โหยวซี่", lang: "zh-CN" },
    { thai: "เครื่องเล่นเกม", target: "游戏机", reading: "โหยวซี่จี", lang: "zh-CN" },
    { thai: "ปริศนา", target: "拼图", reading: "พินถู", lang: "zh-CN" },
    { thai: "ของเล่น", target: "玩具", reading: "หวานจู้", lang: "zh-CN" },
    { thai: "ปาร์ตี้ / งานเลี้ยง", target: "派对", reading: "ไพ่ตุ้ย", lang: "zh-CN" },
    { thai: "เทศกาล", target: "节日", reading: "เจี๋ยรื้", lang: "zh-CN" },
    { thai: "คอนเสิร์ต", target: "音乐会", reading: "อินเยวี่ยฮุ่ย", lang: "zh-CN" },
    { thai: "ตั๋ว", target: "门票", reading: "เหมินเพี่ยว", lang: "zh-CN" },
    { thai: "มายากล / เวทมนตร์", target: "魔术", reading: "หมัวซู่", lang: "zh-CN" },
    { thai: "ของสะสม", target: "收藏品", reading: "โซวฉางผิ่น", lang: "zh-CN" },
    { thai: "กีตาร์", target: "吉他", reading: "จี๋ทา", lang: "zh-CN" },

    // --- 25. หมวดแนวคิดนามธรรมและทิศทาง (Abstract Concepts & Directions) - 30 คำ ---
    { thai: "ความคิด / ไอเดีย", target: "想法", reading: "เสี่ยงฝ่า", lang: "zh-CN" },
    { thai: "ความจริง", target: "真相", reading: "เจินเซี่ยง", lang: "zh-CN" },
    { thai: "คำโกหก", target: "谎言", reading: "ห่วงหยาน", lang: "zh-CN" },
    { thai: "เหตุผล", target: "理由", reading: "หลี่โหยว", lang: "zh-CN" },
    { thai: "จุดประสงค์", target: "目的", reading: "มู่ตี้", lang: "zh-CN" },
    { thai: "วิธีการ", target: "方法", reading: "ฟางฝ่า", lang: "zh-CN" },
    { thai: "ผลลัพธ์", target: "结果", reading: "เจี๋ยกั่ว", lang: "zh-CN" },
    { thai: "ผลกระทบ", target: "影响", reading: "อิ่งเสี่ยง", lang: "zh-CN" },
    { thai: "สาเหตุ", target: "原因", reading: "หยวนอิน", lang: "zh-CN" },
    { thai: "ประวัติศาสตร์", target: "历史", reading: "ลี่สือ", lang: "zh-CN" },
    { thai: "กฎ / กติกา", target: "规则", reading: "กุยเจ๋อ", lang: "zh-CN" },
    { thai: "กฎหมาย", target: "法律", reading: "ฝ่าลวี่", lang: "zh-CN" },
    { thai: "ความยุติธรรม", target: "正义", reading: "เจิ้งยี้", lang: "zh-CN" },
    { thai: "อิสรภาพ", target: "自由", reading: "จื้อโหยว", lang: "zh-CN" },
    { thai: "สัญลักษณ์", target: "象征", reading: "เซี่ยงเจิง", lang: "zh-CN" },
    { thai: "รูปร่าง", target: "形状", reading: "สิงจ้วง", lang: "zh-CN" },
    { thai: "วงกลม", target: "圆形", reading: "หยวนสิง", lang: "zh-CN" },
    { thai: "สี่เหลี่ยม", target: "正方形", reading: "เจิ้งฟางสิง", lang: "zh-CN" },
    { thai: "สามเหลี่ยม", target: "三角形", reading: "ซานเจี่ยวสิง", lang: "zh-CN" },
    { thai: "ขนาด", target: "尺寸", reading: "ฉื่อชุ่น", lang: "zh-CN" },
    { thai: "พื้นที่ว่าง / อวกาศ", target: "空间", reading: "คงเจียน", lang: "zh-CN" },
    { thai: "ระยะทาง", target: "距离", reading: "จู้หลี", lang: "zh-CN" },
    { thai: "พื้นที่ (ตาราง)", target: "面积", reading: "เมี่ยนจี", lang: "zh-CN" },
    { thai: "ทิศทาง", target: "方向", reading: "ฟางเซี่ยง", lang: "zh-CN" },
    { thai: "ตำแหน่ง", target: "位置", reading: "เว่ยจื้อ", lang: "zh-CN" },
    { thai: "ด้านบน", target: "上面", reading: "ซ่างเมี่ยน", lang: "zh-CN" },
    { thai: "ด้านล่าง", target: "下面", reading: "เซี่ยเมี่ยน", lang: "zh-CN" },
    { thai: "ตรงกลาง", target: "中间", reading: "จงเจียน", lang: "zh-CN" },
    { thai: "ด้านหน้า", target: "前面", reading: "เฉียนเมี่ยน", lang: "zh-CN" },
    { thai: "ด้านหลัง", target: "后面", reading: "โฮ่วเมี่ยน", lang: "zh-CN" },
	, // --- 26. หมวดสัตว์ (Animals) - 30 คำ ---
    { thai: "สิงโต", target: "狮子", reading: "ซือจึ", lang: "zh-CN" },
    { thai: "เสือ", target: "老虎", reading: "เหลาหู่", lang: "zh-CN" },
    { thai: "ช้าง", target: "大象", reading: "ต้าเซี่ยง", lang: "zh-CN" },
    { thai: "หมี", target: "熊", reading: "สยง", lang: "zh-CN" },
    { thai: "ลิง", target: "猴子", reading: "โหวจึ", lang: "zh-CN" },
    { thai: "งู", target: "蛇", reading: "เสอ", lang: "zh-CN" },
    { thai: "ม้า", target: "马", reading: "หม่า", lang: "zh-CN" },
    { thai: "วัว", target: "牛", reading: "หนิว", lang: "zh-CN" },
    { thai: "หมู", target: "猪", reading: "จู", lang: "zh-CN" },
    { thai: "แกะ", target: "羊", reading: "หยาง", lang: "zh-CN" },
    { thai: "แพะ", target: "山羊", reading: "ซานหยาง", lang: "zh-CN" },
    { thai: "เป็ด", target: "鸭子", reading: "ยาจึ", lang: "zh-CN" },
    { thai: "หนู", target: "老鼠", reading: "เหลาสู่", lang: "zh-CN" },
    { thai: "กระต่าย", target: "兔子", reading: "ทู่จึ", lang: "zh-CN" },
    { thai: "เต่า", target: "乌龟", reading: "อูกุย", lang: "zh-CN" },
    { thai: "กบ", target: "青蛙", reading: "ชิงวา", lang: "zh-CN" },
    { thai: "แมงมุม", target: "蜘蛛", reading: "จือจู", lang: "zh-CN" },
    { thai: "แมลง", target: "昆虫", reading: "คุนฉง", lang: "zh-CN" },
    { thai: "ผึ้ง", target: "蜜蜂", reading: "มี่เฟิง", lang: "zh-CN" },
    { thai: "ผีเสื้อ", target: "蝴蝶", reading: "หูเตี๋ย", lang: "zh-CN" },
    { thai: "มด", target: "蚂蚁", reading: "หม่ายี่", lang: "zh-CN" },
    { thai: "แมลงวัน", target: "苍蝇", reading: "ชางหยิง", lang: "zh-CN" },
    { thai: "ยุง", target: "蚊子", reading: "เหวินจึ", lang: "zh-CN" },
    { thai: "โลมา", target: "海豚", reading: "ไห่ถุน", lang: "zh-CN" },
    { thai: "วาฬ", target: "鲸鱼", reading: "จิงอวี๋", lang: "zh-CN" },
    { thai: "ฉลาม", target: "鲨鱼", reading: "ซายวี๋", lang: "zh-CN" },
    { thai: "เพนกวิน", target: "企鹅", reading: "ฉี่เอ๋อ", lang: "zh-CN" },
    { thai: "จิงโจ้", target: "袋鼠", reading: "ไต้สู่", lang: "zh-CN" },
    { thai: "หมาป่า", target: "狼", reading: "หลาง", lang: "zh-CN" },
    { thai: "จระเข้", target: "鳄鱼", reading: "เอ้ออวี๋", lang: "zh-CN" },

    // --- 27. หมวดเครื่องแต่งกายและเครื่องประดับ (Clothing & Accessories) - 30 คำ ---
    { thai: "เสื้อเชิ้ต", target: "衬衫", reading: "เชิ่นซาน", lang: "zh-CN" },
    { thai: "เสื้อยืด", target: "T恤", reading: "ทีซวี่", lang: "zh-CN" },
    { thai: "กางเกงขายาว", target: "裤子", reading: "คู่จึ", lang: "zh-CN" },
    { thai: "กางเกงยีนส์", target: "牛仔裤", reading: "หนิวไจ่คู่", lang: "zh-CN" },
    { thai: "กางเกงขาสั้น", target: "短裤", reading: "ต่วนคู่", lang: "zh-CN" },
    { thai: "กระโปรง", target: "裙子", reading: "ฉวินจึ", lang: "zh-CN" },
    { thai: "ชุดเดรส", target: "连衣裙", reading: "เหลียนอีฉวิน", lang: "zh-CN" },
    { thai: "ชุดสูท", target: "西装", reading: "ซีจวง", lang: "zh-CN" },
    { thai: "เสื้อแจ็คเก็ต", target: "外套", reading: "ว่ายเท้า", lang: "zh-CN" },
    { thai: "เสื้อโค้ต", target: "大衣", reading: "ต้าอี", lang: "zh-CN" },
    { thai: "เสื้อกันหนาว", target: "毛衣", reading: "เหมาอี", lang: "zh-CN" },
    { thai: "หมวก (มีปีกรอบ)", target: "帽子", reading: "เม่าจึ", lang: "zh-CN" },
    { thai: "หมวกแก๊ป", target: "鸭舌帽", reading: "ยาเส่อเม่า", lang: "zh-CN" },
    { thai: "ถุงเท้า", target: "袜子", reading: "ว่าจึ", lang: "zh-CN" },
    { thai: "รองเท้าบูท", target: "靴子", reading: "เสวียจึ", lang: "zh-CN" },
    { thai: "รองเท้าผ้าใบ", target: "运动鞋", reading: "ยวิ่นต้งเสีย", lang: "zh-CN" },
    { thai: "เข็มขัด", target: "皮带", reading: "ผีไต้", lang: "zh-CN" },
    { thai: "เนคไท", target: "领带", reading: "หลิ่งไต้", lang: "zh-CN" },
    { thai: "ผ้าพันคอ", target: "围巾", reading: "เหวยจิน", lang: "zh-CN" },
    { thai: "ถุงมือ", target: "手套", reading: "โส่วเท้า", lang: "zh-CN" },
    { thai: "ชุดชั้นใน", target: "内衣", reading: "เน่ยอี", lang: "zh-CN" },
    { thai: "แหวน", target: "戒指", reading: "เจี้ยจื่อ", lang: "zh-CN" },
    { thai: "สร้อยคอ", target: "项链", reading: "เซี่ยงเลี่ยน", lang: "zh-CN" },
    { thai: "สร้อยข้อมือ", target: "手链", reading: "โส่วเลี่ยน", lang: "zh-CN" },
    { thai: "ต่างหู", target: "耳环", reading: "เอ่อร์หวน", lang: "zh-CN" },
    { thai: "กระเป๋าสตางค์", target: "钱包", reading: "เชียนเปา", lang: "zh-CN" },
    { thai: "กระเป๋าถือ (ผู้หญิง)", target: "手提包", reading: "โส่วถีเปา", lang: "zh-CN" },
    { thai: "กระเป๋าเป้", target: "背包", reading: "เปยเปา", lang: "zh-CN" },
    { thai: "เครื่องแบบ", target: "制服", reading: "จื้อฝู", lang: "zh-CN" },
    { thai: "กระเป๋าเสื้อ/กางเกง", target: "口袋", reading: "โข่วไต้", lang: "zh-CN" },

    // --- 28. หมวดการศึกษาและโรงเรียน (Education & School) - 40 คำ ---
    { thai: "การศึกษา", target: "教育", reading: "เจี้ยวอวี้", lang: "zh-CN" },
    { thai: "มหาวิทยาลัย", target: "大学", reading: "ต้าเสวีย", lang: "zh-CN" },
    { thai: "วิทยาลัย", target: "学院", reading: "เสวียย่วน", lang: "zh-CN" },
    { thai: "นักเรียน / นักศึกษา", target: "学生", reading: "เสวียเซิง", lang: "zh-CN" },
    { thai: "ชั้นเรียน", target: "班级", reading: "ปานจี๋", lang: "zh-CN" },
    { thai: "ห้องเรียน", target: "教室", reading: "เจี้ยวซื่อ", lang: "zh-CN" },
    { thai: "วิชา", target: "科目", reading: "เคอมู่", lang: "zh-CN" },
    { thai: "คณิตศาสตร์", target: "数学", reading: "ซู่เสวีย", lang: "zh-CN" },
    { thai: "วิทยาศาสตร์", target: "科学", reading: "เคอเสวีย", lang: "zh-CN" },
    { thai: "ภูมิศาสตร์", target: "地理", reading: "ตี้หลี่", lang: "zh-CN" },
    { thai: "ภาษา", target: "语言", reading: "อวี่หยาน", lang: "zh-CN" },
    { thai: "ภาษาอังกฤษ", target: "英语", reading: "อิงอวี่", lang: "zh-CN" },
    { thai: "การทดสอบ", target: "测试", reading: "เช่อซื่อ", lang: "zh-CN" },
    { thai: "การสอบ (ทางการ)", target: "考试", reading: "เข่าซื่อ", lang: "zh-CN" },
    { thai: "แบบทดสอบย่อย", target: "测验", reading: "เช่อเยี่ยน", lang: "zh-CN" },
    { thai: "การบ้าน", target: "作业", reading: "จั้วเยี่ย", lang: "zh-CN" },
    { thai: "ระดับชั้น / เกรด", target: "年级", reading: "เหนียนจี๋", lang: "zh-CN" },
    { thai: "ปริญญา", target: "学位", reading: "เสวียเว่ย", lang: "zh-CN" },
    { thai: "ผู้สำเร็จการศึกษา", target: "毕业生", reading: "ปี้เยี่ยเซิง", lang: "zh-CN" },
    { thai: "ประกาศนียบัตร", target: "文凭", reading: "เหวินผิง", lang: "zh-CN" },
    { thai: "ทุนการศึกษา", target: "奖学金", reading: "เจี่ยงเสวียจิน", lang: "zh-CN" },
    { thai: "บทเรียน", target: "课", reading: "เค่อ", lang: "zh-CN" },
    { thai: "บท", target: "章", reading: "จาง", lang: "zh-CN" },
    { thai: "หน้า (หนังสือ)", target: "页", reading: "เยี่ย", lang: "zh-CN" },
    { thai: "คำถาม", target: "问题", reading: "เวิ่นถี", lang: "zh-CN" },
    { thai: "คำตอบ", target: "答案", reading: "ต๋าอ้าน", lang: "zh-CN" },
    { thai: "ตัวอย่าง", target: "例子", reading: "ลี่จึ", lang: "zh-CN" },
    { thai: "พจนานุกรม", target: "字典", reading: "จื้อเตี่ยน", lang: "zh-CN" },
    { thai: "คำศัพท์", target: "词汇", reading: "ถือฮุ่ย", lang: "zh-CN" },
    { thai: "ไวยากรณ์", target: "语法", reading: "อวี่ฝ่า", lang: "zh-CN" },
    { thai: "ดินสอ", target: "铅笔", reading: "เชียนปี่", lang: "zh-CN" },
    { thai: "ยางลบ", target: "橡皮", reading: "เซี่ยงผี", lang: "zh-CN" },
    { thai: "ไม้บรรทัด", target: "尺子", reading: "ฉื่อจึ", lang: "zh-CN" },
    { thai: "กระดานดำ", target: "黑板", reading: "เฮยป่าน", lang: "zh-CN" },
    { thai: "กระดานไวท์บอร์ด", target: "白板", reading: "ป๋ายป่าน", lang: "zh-CN" },
    { thai: "สมุดจด", target: "笔记本", reading: "ปี่จี้เปิ่น", lang: "zh-CN" },
    { thai: "โต๊ะเรียน", target: "书桌", reading: "ซูจัว", lang: "zh-CN" },
    { thai: "ภาคเรียน", target: "学期", reading: "เสวียชี", lang: "zh-CN" },
    { thai: "ภาคการศึกษา", target: "学期", reading: "เสวียชี", lang: "zh-CN" },
    { thai: "เวลาพัก", target: "休息时间", reading: "ซิวซิ สือเจียน", lang: "zh-CN" },

    // --- 29. หมวดการเดินทางในเมืองและสถานที่สาธารณะ (City Life & Commute) - 30 คำ ---
    { thai: "ถนน", target: "街道", reading: "เจียเต้า", lang: "zh-CN" },
    { thai: "ถนนใหญ่ / อเวนิว", target: "大道", reading: "ต้าเต้า", lang: "zh-CN" },
    { thai: "ทางหลวง", target: "高速公路", reading: "เกาซู่กงลู่", lang: "zh-CN" },
    { thai: "การจราจร", target: "交通", reading: "เจียวทง", lang: "zh-CN" },
    { thai: "ไฟจราจร", target: "红绿灯", reading: "หงลวี่เติง", lang: "zh-CN" },
    { thai: "ทางเท้า", target: "人行道", reading: "เหรินสิงเต้า", lang: "zh-CN" },
    { thai: "ทางม้าลาย", target: "斑马线", reading: "ปานหม่าเสี้ยน", lang: "zh-CN" },
    { thai: "รถไฟใต้ดิน", target: "地铁", reading: "ตี้เถี่ย", lang: "zh-CN" },
    { thai: "ชานชาลา", target: "站台", reading: "จ้านไถ", lang: "zh-CN" },
    { thai: "ผู้โดยสาร", target: "乘客", reading: "เฉิงเค่อ", lang: "zh-CN" },
    { thai: "การเดินทาง (ระยะไกล)", target: "旅行", reading: "ลวี่สิง", lang: "zh-CN" },
    { thai: "การเดินทาง (ระยะสั้น)", target: "旅程", reading: "ลวี่เฉิง", lang: "zh-CN" },
    { thai: "การท่องเที่ยว", target: "旅游", reading: "ลวี่โหยว", lang: "zh-CN" },
    { thai: "คนนำทาง / มัคคุเทศก์", target: "导游", reading: "เต่าโหยว", lang: "zh-CN" },
    { thai: "เส้นทาง", target: "路线", reading: "ลู่เสี้ยน", lang: "zh-CN" },
    { thai: "ค่าโดยสาร", target: "车费", reading: "เชอเฟ่ย", lang: "zh-CN" },
    { thai: "คิว / แถว", target: "排队", reading: "ไผตุ้ย", lang: "zh-CN" },
    { thai: "ความล่าช้า", target: "延迟", reading: "เหยียนฉือ", lang: "zh-CN" },
    { thai: "อุบัติเหตุ", target: "事故", reading: "ซื่อกู้", lang: "zh-CN" },
    { thai: "อันตราย (คำนาม)", target: "危险", reading: "เวยเสี่ยน", lang: "zh-CN" },
    { thai: "ความปลอดภัย", target: "安全", reading: "อานฉวน", lang: "zh-CN" },
    { thai: "ฝูงชน", target: "人群", reading: "เหรินฉวิน", lang: "zh-CN" },
    { thai: "อาคาร", target: "建筑", reading: "เจี้ยนจู้", lang: "zh-CN" },
    { thai: "ตึกระฟ้า", target: "摩天大楼", reading: "หมัวเทียนต้าโหลว", lang: "zh-CN" },
    { thai: "อพาร์ตเมนต์", target: "公寓", reading: "กงอวี้", lang: "zh-CN" },
    { thai: "ละแวกบ้าน", target: "社区", reading: "เซ่อชวี่", lang: "zh-CN" },
    { thai: "เมืองหลวง", target: "首都", reading: "โส่วตู", lang: "zh-CN" },
    { thai: "อนุสาวรีย์", target: "纪念碑", reading: "จี้เนี่ยนเปย", lang: "zh-CN" },
    { thai: "พิพิธภัณฑ์", target: "博物馆", reading: "ปั๋วอู้ก่วน", lang: "zh-CN" },
    { thai: "สวนสัตว์", target: "动物园", reading: "ต้งอู้หยวน", lang: "zh-CN" },

    // --- 30. หมวดเครื่องมือ วัสดุ และคุณลักษณะทางกายภาพ (Tools, Materials & Shapes) - 35 คำ ---
    { thai: "เครื่องมือ", target: "工具", reading: "กงจู้", lang: "zh-CN" },
    { thai: "ค้อน", target: "锤子", reading: "ฉุยจึ", lang: "zh-CN" },
    { thai: "ตะปู", target: "钉子", reading: "ติงจึ", lang: "zh-CN" },
    { thai: "สกรู", target: "螺丝", reading: "หลัวซือ", lang: "zh-CN" },
    { thai: "ประแจ", target: "扳手", reading: "ปานโส่ว", lang: "zh-CN" },
    { thai: "กรรไกร", target: "剪刀", reading: "เจี่ยนเตา", lang: "zh-CN" },
    { thai: "มีด", target: "刀", reading: "เตา", lang: "zh-CN" },
    { thai: "ใบมีด", target: "刀片", reading: "เตาเพี่ยน", lang: "zh-CN" },
    { thai: "เครื่องจักร", target: "机器", reading: "จีชี่", lang: "zh-CN" },
    { thai: "เครื่องยนต์", target: "引擎", reading: "อิ่นฉิง", lang: "zh-CN" },
    { thai: "มอเตอร์", target: "马达", reading: "หม่าต๋า", lang: "zh-CN" },
    { thai: "วัสดุ", target: "材料", reading: "ไฉเลี้ยว", lang: "zh-CN" },
    { thai: "ไม้", target: "木材", reading: "มู่ไฉ", lang: "zh-CN" },
    { thai: "โลหะ", target: "金属", reading: "จินสู่", lang: "zh-CN" },
    { thai: "เหล็ก", target: "铁", reading: "เถี่ย", lang: "zh-CN" },
    { thai: "เหล็กกล้า", target: "钢", reading: "กัง", lang: "zh-CN" },
    { thai: "ทองแดง", target: "铜", reading: "ถง", lang: "zh-CN" },
    { thai: "พลาสติก", target: "塑料", reading: "ซู่เลี้ยว", lang: "zh-CN" },
    { thai: "ยาง", target: "橡胶", reading: "เซี่ยงเจียว", lang: "zh-CN" },
    { thai: "ฝ้าย", target: "棉花", reading: "เหมียนฮวา", lang: "zh-CN" },
    { thai: "หนัง (วัสดุ)", target: "皮革", reading: "ผีเก๋อ", lang: "zh-CN" },
    { thai: "กระดาษแข็ง", target: "纸板", reading: "จื่อป่าน", lang: "zh-CN" },
    { thai: "เชือกหนา", target: "绳子", reading: "เสิงจึ", lang: "zh-CN" },
    { thai: "ลวด / สายไฟ", target: "电线", reading: "เตี้ยนเสี้ยน", lang: "zh-CN" },
    { thai: "เส้น", target: "线", reading: "เสี้ยน", lang: "zh-CN" },
    { thai: "ส่วนโค้ง", target: "曲线", reading: "ชวีเสี้ยน", lang: "zh-CN" },
    { thai: "มุม", target: "角度", reading: "เจี่ยวตู้", lang: "zh-CN" },
    { thai: "กลม", target: "圆形", reading: "หยวนสิง", lang: "zh-CN" },
    { thai: "แบน", target: "平坦", reading: "ผิงถ่าน", lang: "zh-CN" },
    { thai: "แหลม / คม", target: "锋利", reading: "เฟิงลี่", lang: "zh-CN" },
    { thai: "เรียบ / ลื่น", target: "光滑", reading: "กวงหวาม", lang: "zh-CN" },
    { thai: "ขรุขระ", target: "粗糙", reading: "ชูเชา", lang: "zh-CN" },
    { thai: "นุ่ม", target: "柔软", reading: "หรัวหร่วน", lang: "zh-CN" },
    { thai: "แข็ง (วัสดุ)", target: "坚硬", reading: "เจียนอิ้ง", lang: "zh-CN" },
    { thai: "ของแข็ง", target: "固体", reading: "กู้ถี", lang: "zh-CN" },

    // --- 31. หมวดสังคม การปกครอง และกระบวนการยุติธรรม (Society, Government & Justice) - 35 คำ ---
    { thai: "สังคม", target: "社会", reading: "เซ่อฮุ่ย", lang: "zh-CN" },
    { thai: "วัฒนธรรม", target: "文化", reading: "เหวินฮว่า", lang: "zh-CN" },
    { thai: "ประเพณี", target: "传统", reading: "ฉวนถ่ง", lang: "zh-CN" },
    { thai: "รัฐบาล", target: "政府", reading: "เจิ้งฝู่", lang: "zh-CN" },
    { thai: "การเมือง", target: "政治", reading: "เจิ้งจื้อ", lang: "zh-CN" },
    { thai: "การเลือกตั้ง", target: "选举", reading: "เสวียนจวี่", lang: "zh-CN" },
    { thai: "ลงคะแนนเสียง", target: "投票", reading: "โถวเพี่ยว", lang: "zh-CN" },
    { thai: "ประธานาธิบดี / ประธาน", target: "总统", reading: "จ๋งถ่ง", lang: "zh-CN" },
    { thai: "ผู้นำ", target: "领导者", reading: "หลิ่งเต่าเจ่อ", lang: "zh-CN" },
    { thai: "พลเมือง", target: "公民", reading: "กงหมิน", lang: "zh-CN" },
    { thai: "ชาติ / ประเทศ", target: "国家", reading: "กั๋วเจีย", lang: "zh-CN" },
    { thai: "ชุมชน", target: "社区", reading: "เซ่อชวี่", lang: "zh-CN" },
    { thai: "นโยบาย", target: "政策", reading: "เจิ้งเช่อ", lang: "zh-CN" },
    { thai: "ข้อบังคับ / ระเบียบ", target: "规定", reading: "กุยติ้ง", lang: "zh-CN" },
    { thai: "สิทธิ", target: "权利", reading: "ฉวนลี่", lang: "zh-CN" },
    { thai: "หน้าที่", target: "责任", reading: "เจ๋อเริ่น", lang: "zh-CN" },
    { thai: "ศาล", target: "法院", reading: "ฝ่าหย่วน", lang: "zh-CN" },
    { thai: "ผู้พิพากษา", target: "法官", reading: "ฝากวน", lang: "zh-CN" },
    { thai: "ทนายความ", target: "律师", reading: "ลวี่ซือ", lang: "zh-CN" },
    { thai: "เจ้าหน้าที่", target: "警察", reading: "จิ่งฉา", lang: "zh-CN" },
    { thai: "อาชญากรรม", target: "犯罪", reading: "ฝ่านจุ้ย", lang: "zh-CN" },
    { thai: "อาชญากร", target: "罪犯", reading: "จุ้ยฝ่าน", lang: "zh-CN" },
    { thai: "คุก / เรือนจำ", target: "监狱", reading: "เจียนอวี้", lang: "zh-CN" },
    { thai: "ขโมย (คน)", target: "小偷", reading: "เสี่ยวโทว", lang: "zh-CN" },
    { thai: "การป้องกัน", target: "保护", reading: "ป่าวฮู้", lang: "zh-CN" },
    { thai: "สันติภาพ", target: "和平", reading: "เหอผิง", lang: "zh-CN" },
    { thai: "สงคราม", target: "战争", reading: "จ้านเจิง", lang: "zh-CN" },
    { thai: "กองทัพบก", target: "军队", reading: "จวินตุ้ย", lang: "zh-CN" },
    { thai: "อาวุธ", target: "武器", reading: "อู่ชี่", lang: "zh-CN" },
    { thai: "ปืน", target: "枪", reading: "เชียง", lang: "zh-CN" },
    { thai: "ประชากร", target: "人口", reading: "เหรินโข่ว", lang: "zh-CN" },
    { thai: "ชายแดน", target: "边界", reading: "เปียนเจี้ย", lang: "zh-CN" },
    { thai: "ธง", target: "国旗", reading: "กั๋วฉี", lang: "zh-CN" },
    { thai: "สาธารณะ", target: "公共", reading: "กงก้ง", lang: "zh-CN" },
    { thai: "ส่วนตัว", target: "私人", reading: "ซือเหริน", lang: "zh-CN" },

    // --- 32. หมวดคำบุพบทและคำเชื่อมประโยค (Prepositions & Conjunctions) - 30 คำ ---
    { thai: "ใน / ข้างใน", target: "里面", reading: "หลี่เมี่ยน", lang: "zh-CN" },
    { thai: "บน / ข้างบน", target: "上面", reading: "ซ่างเมี่ยน", lang: "zh-CN" },
    { thai: "ที่", target: "在", reading: "จ้าย", lang: "zh-CN" },
    { thai: "โดย / ด้วย", target: "被", reading: "เป้ย", lang: "zh-CN" },
    { thai: "สำหรับ / เพื่อ", target: "为", reading: "เว่ย", lang: "zh-CN" },
    { thai: "กับ / ด้วย", target: "和", reading: "เหอ", lang: "zh-CN" },
    { thai: "เกี่ยวกับ", target: "关于", reading: "กวนอวี้", lang: "zh-CN" },
    { thai: "ต่อต้าน / แข่งกับ", target: "反对", reading: "ฝ่านตุ้ย", lang: "zh-CN" },
    { thai: "ระหว่าง (สองสิ่ง)", target: "之间", reading: "จือเจียน", lang: "zh-CN" },
    { thai: "เข้าไปใน", target: "进入", reading: "จิ้นรู่", lang: "zh-CN" },
    { thai: "ทะลุผ่าน", target: "穿过", reading: "ชวนกั้ว", lang: "zh-CN" },
    { thai: "ระหว่าง (เวลา)", target: "在...期间", reading: "จ้าย...ชีเจียน", lang: "zh-CN" },
    { thai: "ก่อน", target: "之前", reading: "จือเฉียน", lang: "zh-CN" },
    { thai: "หลังจาก", target: "之后", reading: "จือโฮ่ว", lang: "zh-CN" },
    { thai: "เหนือ / สูงกว่า", target: "在...之上", reading: "จ้าย...จือซ่าง", lang: "zh-CN" },
    { thai: "ใต้ / ต่ำกว่า", target: "在...之下", reading: "จ้าย...จือเซี่ย", lang: "zh-CN" },
    { thai: "จาก", target: "从", reading: "ฉง", lang: "zh-CN" },
    { thai: "ขึ้น", target: "向上", reading: "เซี่ยงซ่าง", lang: "zh-CN" },
    { thai: "ลง", target: "向下", reading: "เซี่ยงเซี่ย", lang: "zh-CN" },
    { thai: "ออก / ข้างนอก", target: "出去", reading: "ชูชวี่", lang: "zh-CN" },
    { thai: "และ", target: "和", reading: "เหอ", lang: "zh-CN" },
    { thai: "แต่", target: "但是", reading: "ต้านซื่อ", lang: "zh-CN" },
    { thai: "หรือ", target: "或者", reading: "ฮั่วเจ่อ", lang: "zh-CN" },
    { thai: "เพราะว่า", target: "因为", reading: "อินเวย", lang: "zh-CN" },
    { thai: "ถ้า / หาก", target: "如果", reading: "รูกั่ว", lang: "zh-CN" },
    { thai: "ดังนั้น", target: "所以", reading: "สัวอี่", lang: "zh-CN" },
    { thai: "แม้ว่า", target: "虽然", reading: "ซุยหราน", lang: "zh-CN" },
    { thai: "จนกระทั่ง", target: "直到", reading: "จื๋อเต้า", lang: "zh-CN" },
    { thai: "เว้นแต่ว่า", target: "除非", reading: "ฉูเฟย", lang: "zh-CN" },
    { thai: "ตั้งแต่ / เนื่องจาก", target: "自从", reading: "จื้อฉง", lang: "zh-CN" },

    // --- 33. หมวดคำวิเศษณ์บอกเวลา สถานที่ และความถี่ (Common Adverbs) - 30 คำ ---
    { thai: "เสมอ / ตลอด", target: "总是", reading: "จ่งซื่อ", lang: "zh-CN" },
    { thai: "มักจะ / เป็นประจำ", target: "通常", reading: "ทงฉาง", lang: "zh-CN" },
    { thai: "บ่อยๆ", target: "经常", reading: "จิงฉาง", lang: "zh-CN" },
    { thai: "บางครั้ง", target: "有时", reading: "โหย่วสือ", lang: "zh-CN" },
    { thai: "ไม่เคย", target: "从不", reading: "ฉงปู้", lang: "zh-CN" },
    { thai: "มาก", target: "很", reading: "เหิ่น", lang: "zh-CN" },
    { thai: "เกินไป / ก็ด้วย", target: "太", reading: "ไท่", lang: "zh-CN" },
    { thai: "ค่อนข้าง", target: "相当", reading: "เซียงตัง", lang: "zh-CN" },
    { thai: "จริงๆ / อย่างแท้จริง", target: "真的", reading: "เจินเตอะ", lang: "zh-CN" },
    { thai: "อย่างแน่นอน / เป๊ะ", target: "确切地", reading: "เควี่ยเชี่ยตี้", lang: "zh-CN" },
    { thai: "เกือบจะ", target: "几乎", reading: "จีฮู", lang: "zh-CN" },
    { thai: "เรียบร้อยแล้ว", target: "已经", reading: "อี่จิง", lang: "zh-CN" },
    { thai: "ยังคง", target: "仍然", reading: "เหรงหราน", lang: "zh-CN" },
    { thai: "ยัง (รูปปฏิเสธ/คำถาม)", target: "还", reading: "ไห", lang: "zh-CN" },
    { thai: "เพิ่งจะ / แค่", target: "刚刚", reading: "กังกัง", lang: "zh-CN" },
    { thai: "เท่านั้น / เพียงแค่", target: "只有", reading: "จือโหย่ว", lang: "zh-CN" },
    { thai: "บางที", target: "也许", reading: "เหยี่ยสวี่", lang: "zh-CN" },
    { thai: "อาจจะ", target: "可能", reading: "เข่อเหนิง", lang: "zh-CN" },
    { thai: "ทันทีทันใด", target: "突然", reading: "ทูหราน", lang: "zh-CN" },
    { thai: "อย่างรวดเร็ว", target: "很快", reading: "เหิ่นไขว้", lang: "zh-CN" },
    { thai: "อย่างช้าๆ", target: "慢慢地", reading: "มั่นมั่นตี้", lang: "zh-CN" },
    { thai: "อย่างระมัดระวัง", target: "小心地", reading: "เสี่ยวซินตี้", lang: "zh-CN" },
    { thai: "อย่างง่ายดาย", target: "容易地", reading: "หรงอี้ตี้", lang: "zh-CN" },
    { thai: "ดี (คำวิเศษณ์)", target: "很好地", reading: "เหิ่นห่าวตี้", lang: "zh-CN" },
    { thai: "ที่นี่", target: "这里", reading: "เจ้อหลี่", lang: "zh-CN" },
    { thai: "ที่นั่น", target: "那里", reading: "น่าหลี่", lang: "zh-CN" },
    { thai: "ทุกที่", target: "到处", reading: "เต้าชู่", lang: "zh-CN" },
    { thai: "บางที่", target: "某处", reading: "โหม่วชู่", lang: "zh-CN" },
    { thai: "ไม่มีที่ไหน", target: "无处", reading: "อู๋ชู่", lang: "zh-CN" },
    { thai: "ที่ไหนก็ได้", target: "任何地方", reading: "เริ่นเหอตี้ฟาง", lang: "zh-CN" },

    // --- 34. หมวดปริมาณ ขนาด และการวัด (Quantities & Measurements) - 25 คำ ---
    { thai: "ทั้งหมด", target: "全部", reading: "ฉวนปู้", lang: "zh-CN" },
    { thai: "บ้าง / บางส่วน", target: "一些", reading: "อี้เซีย", lang: "zh-CN" },
    { thai: "บ้าง (รูปปฏิเสธ/คำถาม)", target: "任何", reading: "เริ่นเหอ", lang: "zh-CN" },
    { thai: "มาก (นับได้)", target: "很多", reading: "เหิ่นตัว", lang: "zh-CN" },
    { thai: "มาก (นับไม่ได้)", target: "很多", reading: "เหิ่นตัว", lang: "zh-CN" },
    { thai: "น้อย (นับได้)", target: "很少", reading: "เหิ่นเส่า", lang: "zh-CN" },
    { thai: "น้อย (นับไม่ได้)", target: "很少", reading: "เหิ่นเส่า", lang: "zh-CN" },
    { thai: "ชิ้น", target: "件", reading: "เจี้ยน", lang: "zh-CN" },
    { thai: "แผ่น / ชิ้นบางๆ", target: "片", reading: "เพี่ยน", lang: "zh-CN" },
    { thai: "หยด", target: "滴", reading: "ตี", lang: "zh-CN" },
    { thai: "ปอนด์ (น้ำหนัก)", target: "磅", reading: "ปั้ง", lang: "zh-CN" },
    { thai: "กิโลกรัม", target: "公斤", reading: "กงจิน", lang: "zh-CN" },
    { thai: "เมตร", target: "米", reading: "หมี่", lang: "zh-CN" },
    { thai: "ลิตร", target: "升", reading: "เซิง", lang: "zh-CN" },
    { thai: "โหล (12 ชิ้น)", target: "打", reading: "ต๋า", lang: "zh-CN" },
    { thai: "ครึ่ง", target: "一半", reading: "อี๋ปั้น", lang: "zh-CN" },
    { thai: "หนึ่งในสี่", target: "四分之一", reading: "ซื่อเฟินจืออี", lang: "zh-CN" },
    { thai: "ยอดรวม", target: "总计", reading: "จ๋งจี้", lang: "zh-CN" },
    { thai: "จำนวน / ปริมาณ (นับไม่ได้)", target: "数量", reading: "ซู่เลี่ยง", lang: "zh-CN" },
    { thai: "ตัวเลข / จำนวน (นับได้)", target: "数字", reading: "ซู่จื้อ", lang: "zh-CN" },
    { thai: "น้ำหนัก", target: "重量", reading: "จ้งเลี่ยง", lang: "zh-CN" },
    { thai: "ความยาว", target: "长度", reading: "ฉางตู้", lang: "zh-CN" },
    { thai: "ความสูง", target: "高度", reading: "เกาตู้", lang: "zh-CN" },
    { thai: "ความลึก", target: "深度", reading: "เซินตู้", lang: "zh-CN" },
    { thai: "ความกว้าง", target: "宽度", reading: "ควนตู้", lang: "zh-CN" },

    // --- 35. หมวดจักรวาล วิทยาศาสตร์ และธรรมชาติ (Universe & Basic Science) - 15 คำ ---
    { thai: "จักรวาล", target: "宇宙", reading: "อวี่โจ้ว", lang: "zh-CN" },
    { thai: "ดาราจักร / กาแล็กซี", target: "星系", reading: "ซิงซี่", lang: "zh-CN" },
    { thai: "ดาวเคราะห์", target: "行星", reading: "สิงซิง", lang: "zh-CN" },
    { thai: "อวกาศ / พื้นที่ว่าง", target: "太空", reading: "ไท่คง", lang: "zh-CN" },
    { thai: "อะตอม", target: "原子", reading: "หยวนจึ", lang: "zh-CN" },
    { thai: "พลังงาน", target: "能量", reading: "เหนิงเลี่ยง", lang: "zh-CN" },
    { thai: "แรงโน้มถ่วง", target: "重力", reading: "จ้งลี่", lang: "zh-CN" },
    { thai: "ฟิสิกส์", target: "物理学", reading: "อู้หลี่เสวีย", lang: "zh-CN" },
    { thai: "เคมี", target: "化学", reading: "ฮว่าเสวีย", lang: "zh-CN" },
    { thai: "ชีววิทยา", target: "生物学", reading: "เซิงอู้เสวีย", lang: "zh-CN" },
    { thai: "เซลล์", target: "细胞", reading: "ซีเปา", lang: "zh-CN" },
    { thai: "ธรรมชาติ", target: "自然", reading: "จื้อหราน", lang: "zh-CN" },
    { thai: "ก๊าซ", target: "气体", reading: "ชี่ถี", lang: "zh-CN" },
    { thai: "ของเหลว", target: "液体", reading: "เยี่ยถี", lang: "zh-CN" },
    { thai: "การทดลอง", target: "实验", reading: "สือเยี่ยน", lang: "zh-CN" }
]; // สิ้นสุดอาเรย์ ตัวแปร wordsCN สมบูรณ์ 1,000 คำ