const wordsKR = [
    // --- 1. หมวดบุคคลและสรรพนาม (People & Pronouns) - 20 คำ ---
    { thai: "ฉัน / ผม", target: "나 / 저", reading: "นา / ชอ", lang: "ko-KR" },
    { thai: "คุณ", target: "너 / 당신", reading: "นอ / ทังชิน", lang: "ko-KR" },
    { thai: "เขา (ผู้ชาย)", target: "그", reading: "คือ", lang: "ko-KR" },
    { thai: "เธอ (ผู้หญิง)", target: "그녀", reading: "คือนยอ", lang: "ko-KR" },
    { thai: "พวกเรา", target: "우리", reading: "อูรี", lang: "ko-KR" },
    { thai: "พวกเขา", target: "그들", reading: "คือดึล", lang: "ko-KR" },
    { thai: "มัน", target: "그것", reading: "คือก็อด", lang: "ko-KR" },
    { thai: "ฉัน (กรรม)", target: "나를 / 저를", reading: "นารึล / ชอรึล", lang: "ko-KR" },
    { thai: "เขา (กรรม)", target: "그를", reading: "คือรึล", lang: "ko-KR" },
    { thai: "เธอ (กรรม)", target: "그녀를", reading: "คือนยอรึล", lang: "ko-KR" },
    { thai: "พวกเรา (กรรม)", target: "우리를", reading: "อูรีรึล", lang: "ko-KR" },
    { thai: "พวกเขา (กรรม)", target: "그들을", reading: "คือดึลอึล", lang: "ko-KR" },
    { thai: "ผู้ชาย", target: "남자", reading: "นัมจา", lang: "ko-KR" },
    { thai: "ผู้หญิง", target: "여자", reading: "ยอจา", lang: "ko-KR" },
    { thai: "เด็กผู้ชาย", target: "남자아이", reading: "นัมจาอาอี", lang: "ko-KR" },
    { thai: "เด็กผู้หญิง", target: "여자아이", reading: "ยอจาอาอี", lang: "ko-KR" },
    { thai: "เพื่อน", target: "친구", reading: "ชินกู", lang: "ko-KR" },
    { thai: "ครอบครัว", target: "가족", reading: "คาจก", lang: "ko-KR" },
    { thai: "บุคคล (คนเดียว)", target: "사람", reading: "ซารัม", lang: "ko-KR" },
    { thai: "ผู้คน (หลายคน)", target: "사람들", reading: "ซารัมดึล", lang: "ko-KR" },

    // --- 2. หมวดร่างกาย (Body Parts) - 20 คำ ---
    { thai: "หัว", target: "머리", reading: "มอรี", lang: "ko-KR" },
    { thai: "ผม", target: "머리카락", reading: "มอรีคารัก", lang: "ko-KR" },
    { thai: "ตา", target: "눈", reading: "นุน", lang: "ko-KR" },
    { thai: "หู", target: "귀", reading: "ควี", lang: "ko-KR" },
    { thai: "จมูก", target: "코", reading: "โค", lang: "ko-KR" },
    { thai: "ปาก", target: "입", reading: "อิบ", lang: "ko-KR" },
    { thai: "ฟัน", target: "이 / 이빨", reading: "อี / อีปัล", lang: "ko-KR" },
    { thai: "ใบหน้า", target: "얼굴", reading: "ออลกุล", lang: "ko-KR" },
    { thai: "คอ", target: "목", reading: "มก", lang: "ko-KR" },
    { thai: "ไหล่", target: "어깨", reading: "ออแก", lang: "ko-KR" },
    { thai: "แขน", target: "팔", reading: "พัล", lang: "ko-KR" },
    { thai: "มือ", target: "손", reading: "ซน", lang: "ko-KR" },
    { thai: "นิ้วมือ", target: "손가락", reading: "ซนการัก", lang: "ko-KR" },
    { thai: "ขา", target: "다리", reading: "ทารี", lang: "ko-KR" },
    { thai: "เท้า", target: "발", reading: "พัล", lang: "ko-KR" },
    { thai: "นิ้วเท้า", target: "발가락", reading: "พัลการัก", lang: "ko-KR" },
    { thai: "หลัง", target: "등", reading: "ทึง", lang: "ko-KR" },
    { thai: "หัวใจ", target: "심장", reading: "ชิมจัง", lang: "ko-KR" },
    { thai: "เลือด", target: "피", reading: "พี", lang: "ko-KR" },
    { thai: "กระดูก", target: "뼈", reading: "ปยอ", lang: "ko-KR" },

    // --- 3. หมวดครอบครัวและญาติ (Family & Relatives) - 15 คำ ---
    { thai: "พ่อ", target: "아빠 / 아버지", reading: "อาปา / อาบอจี", lang: "ko-KR" },
    { thai: "แม่", target: "엄마 / 어머니", reading: "ออมมา / ออมอนี", lang: "ko-KR" },
    { thai: "ผู้ปกครอง / พ่อแม่", target: "부모님", reading: "พูโมนิม", lang: "ko-KR" },
    { thai: "ลูกชาย", target: "아들", reading: "อาดึล", lang: "ko-KR" },
    { thai: "ลูกสาว", target: "딸", reading: "ตัล", lang: "ko-KR" },
    { thai: "พี่ชาย / น้องชาย", target: "형제", reading: "ฮยองเจ", lang: "ko-KR" },
    { thai: "พี่สาว / น้องสาว", target: "자매", reading: "ชาแม", lang: "ko-KR" },
    { thai: "ปู่ / ตา", target: "할아버지", reading: "ฮาราบอจี", lang: "ko-KR" },
    { thai: "ย่า / ยาย", target: "할머니", reading: "ฮัลมอนี", lang: "ko-KR" },
    { thai: "ลุง / น้าชาย / อาชาย", target: "삼촌 / 아저씨", reading: "ซัมชน / อาจอชี่", lang: "ko-KR" },
    { thai: "ป้า / น้าหญิง / อาหญิง", target: "이모 / 아주머니", reading: "อีโม / อาจูมอนี", lang: "ko-KR" },
    { thai: "ลูกพี่ลูกน้อง", target: "사촌", reading: "ซาชน", lang: "ko-KR" },
    { thai: "สามี", target: "남편", reading: "นัมพยอน", lang: "ko-KR" },
    { thai: "ภรรยา", target: "아내", reading: "อาแน", lang: "ko-KR" },
    { thai: "เด็ก / ลูก", target: "아이", reading: "อาอี", lang: "ko-KR" },

    // --- 4. หมวดเวลา (Time & Calendar) - 20 คำ ---
    { thai: "วินาที", target: "초", reading: "โช", lang: "ko-KR" },
    { thai: "นาที", target: "분", reading: "บุน", lang: "ko-KR" },
    { thai: "ชั่วโมง", target: "시간", reading: "ชีกัน", lang: "ko-KR" },
    { thai: "วัน", target: "일 / 하루", reading: "อิล / ฮารู", lang: "ko-KR" },
    { thai: "สัปดาห์", target: "주 / 일주일", reading: "ชู / อิลจูอิล", lang: "ko-KR" },
    { thai: "เดือน", target: "월 / 달", reading: "วอล / ทัล", lang: "ko-KR" },
    { thai: "ปี", target: "년 / 해", reading: "นยอน / แฮ", lang: "ko-KR" },
    { thai: "ตอนเช้า", target: "아침", reading: "อาชิม", lang: "ko-KR" },
    { thai: "ตอนบ่าย", target: "오후", reading: "โอฮู", lang: "ko-KR" },
    { thai: "ตอนเย็น / ค่ำ", target: "저녁", reading: "ชอนย็อก", lang: "ko-KR" },
    { thai: "ตอนกลางคืน", target: "밤", reading: "พัม", lang: "ko-KR" },
    { thai: "วันนี้", target: "오늘", reading: "โอนึล", lang: "ko-KR" },
    { thai: "พรุ่งนี้", target: "내일", reading: "แนอิล", lang: "ko-KR" },
    { thai: "เมื่อวานนี้", target: "어제", reading: "ออเจ", lang: "ko-KR" },
    { thai: "ตอนนี้ / ปัจจุบัน", target: "지금", reading: "ชีกึม", lang: "ko-KR" },
    { thai: "ตอนนั้น / หลังจากนั้น", target: "그때 / 나중에", reading: "คือแต / นาจุงเง", lang: "ko-KR" },
    { thai: "อนาคต", target: "미래", reading: "มีแร", lang: "ko-KR" },
    { thai: "อดีต", target: "과거", reading: "ควากอ", lang: "ko-KR" },
    { thai: "ปัจจุบัน / ของขวัญ", target: "현재 / 선물", reading: "ฮยอนแจ / ซอนมุล", lang: "ko-KR" },
    { thai: "เวลา", target: "시간", reading: "ชีกัน", lang: "ko-KR" },

    // --- 5. หมวดธรรมชาติและสิ่งแวดล้อม (Nature & Environment) - 25 คำ ---
    { thai: "ดวงอาทิตย์", target: "태양 / 해", reading: "แทยัง / แฮ", lang: "ko-KR" },
    { thai: "ดวงจันทร์", target: "달", reading: "ทัล", lang: "ko-KR" },
    { thai: "ดาว", target: "별", reading: "พย็อล", lang: "ko-KR" },
    { thai: "ท้องฟ้า", target: "하늘", reading: "ฮานึล", lang: "ko-KR" },
    { thai: "เมฆ", target: "구름", reading: "คูรึม", lang: "ko-KR" },
    { thai: "ฝน", target: "비", reading: "พี", lang: "ko-KR" },
    { thai: "ลม", target: "바람", reading: "พารัม", lang: "ko-KR" },
    { thai: "หิมะ", target: "눈", reading: "นุน", lang: "ko-KR" },
    { thai: "ไฟ", target: "불", reading: "พุล", lang: "ko-KR" },
    { thai: "น้ำ", target: "물", reading: "มุล", lang: "ko-KR" },
    { thai: "โลก (ดาวเคราะห์) / ดิน", target: "지구 / 흙", reading: "ชีกู / ฮึก", lang: "ko-KR" },
    { thai: "โลก (รวมทั้งหมด)", target: "세계", reading: "เซกเย", lang: "ko-KR" },
    { thai: "ต้นไม้", target: "나무", reading: "นามู", lang: "ko-KR" },
    { thai: "ดอกไม้", target: "꽃", reading: "กช", lang: "ko-KR" },
    { thai: "หญ้า", target: "풀 / 잔디", reading: "พุล / ชันดี", lang: "ko-KR" },
    { thai: "สัตว์", target: "동물", reading: "ทงมุล", lang: "ko-KR" },
    { thai: "นก", target: "새", reading: "แซ", lang: "ko-KR" },
    { thai: "ปลา", target: "물고기 / 생선", reading: "มุลโกกี / แซงซ็อน", lang: "ko-KR" },
    { thai: "สุนัข", target: "개", reading: "แค", lang: "ko-KR" },
    { thai: "แมว", target: "고양이", reading: "โคยังงี", lang: "ko-KR" },
    { thai: "ภูเขา", target: "산", reading: "ซาน", lang: "ko-KR" },
    { thai: "แม่น้ำ", target: "강", reading: "คัง", lang: "ko-KR" },
    { thai: "ทะเล", target: "바다", reading: "พาดา", lang: "ko-KR" },
    { thai: "หิน", target: "돌 / 바위", reading: "ทล / พาวี", lang: "ko-KR" },
    { thai: "ทราย", target: "모래", reading: "โมแร", lang: "ko-KR" },

    // --- 6. หมวดกริยาและการกระทำ (Common Action Verbs) - 35 คำ ---
    { thai: "กิน", target: "먹다", reading: "ม็อกตา", lang: "ko-KR" },
    { thai: "ดื่ม", target: "마시다", reading: "มาชีดา", lang: "ko-KR" },
    { thai: "นอน", target: "자다", reading: "ชาดา", lang: "ko-KR" },
    { thai: "วิ่ง", target: "달리다", reading: "ทัลลีดา", lang: "ko-KR" },
    { thai: "เดิน", target: "걷다", reading: "ก็อดตา", lang: "ko-KR" },
    { thai: "กระโดด", target: "뛰다", reading: "ตวีดา", lang: "ko-KR" },
    { thai: "อ่าน", target: "읽다", reading: "อิกตา", lang: "ko-KR" },
    { thai: "เขียน", target: "쓰다", reading: "ซือดา", lang: "ko-KR" },
    { thai: "ฟัง", target: "듣다", reading: "ทึดตา", lang: "ko-KR" },
    { thai: "พูด", target: "말하다", reading: "มัลฮาดา", lang: "ko-KR" },
    { thai: "ดู / มอง", target: "보다", reading: "โพดา", lang: "ko-KR" },
    { thai: "คิด", target: "생각하다", reading: "แซงกักฮาดา", lang: "ko-KR" },
    { thai: "ทำงาน", target: "일하다", reading: "อิลฮาดา", lang: "ko-KR" },
    { thai: "เรียน", target: "배우다 / 공부하다", reading: "แพอูดา / คงบูฮาดา", lang: "ko-KR" },
    { thai: "สอน", target: "가르치다", reading: "คารือชีดา", lang: "ko-KR" },
    { thai: "ซื้อ", target: "사다", reading: "ซาดา", lang: "ko-KR" },
    { thai: "ขาย", target: "팔다", reading: "พัลดา", lang: "ko-KR" },
    { thai: "ทำ / สร้าง", target: "만들다", reading: "มันดึลดา", lang: "ko-KR" },
    { thai: "ให้", target: "주다", reading: "ชูดา", lang: "ko-KR" },
    { thai: "รับ", target: "받다", reading: "พัดตา", lang: "ko-KR" },
    { thai: "ถือ / จับ", target: "잡다", reading: "ชับตา", lang: "ko-KR" },
    { thai: "เปิด", target: "열다", reading: "ย็อลดา", lang: "ko-KR" },
    { thai: "ปิด", target: "닫다", reading: "ทัดตา", lang: "ko-KR" },
    { thai: "ขับรถ", target: "운전하다", reading: "อุนจอนฮาดา", lang: "ko-KR" },
    { thai: "ขี่ / ปั่น", target: "타다", reading: "ทาดา", lang: "ko-KR" },
    { thai: "ว่ายน้ำ", target: "수영하다", reading: "ซูยองฮาดา", lang: "ko-KR" },
    { thai: "บิน", target: "날다", reading: "นัลดา", lang: "ko-KR" },
    { thai: "หัวเราะ", target: "웃다", reading: "อุดตา", lang: "ko-KR" },
    { thai: "ร้องไห้", target: "울다", reading: "อุลดา", lang: "ko-KR" },
    { thai: "ยิ้ม", target: "미소 짓다", reading: "มีโซ จิดตา", lang: "ko-KR" },
    { thai: "รอ", target: "기다리다", reading: "คีดารีดา", lang: "ko-KR" },
    { thai: "หยุด", target: "멈추다", reading: "ม็อมชูดา", lang: "ko-KR" },
    { thai: "ช่วย", target: "돕다", reading: "ทบตา", lang: "ko-KR" },
    { thai: "เล่น", target: "놀다", reading: "นลดา", lang: "ko-KR" },
    { thai: "ร้องเพลง", target: "노래하다", reading: "โนแรฮาดา", lang: "ko-KR" },

    // --- 7. หมวดสีสัน (Colors) - 15 คำ ---
    { thai: "สีแดง", target: "빨간색", reading: "ปัลกันแซ็ก", lang: "ko-KR" },
    { thai: "สีน้ำเงิน", target: "파란색", reading: "พารันแซ็ก", lang: "ko-KR" },
    { thai: "สีเขียว", target: "초록색", reading: "โชรกแซ็ก", lang: "ko-KR" },
    { thai: "สีเหลือง", target: "노란색", reading: "โนรันแซ็ก", lang: "ko-KR" },
    { thai: "สีดำ", target: "검은색", reading: "คอมึนแซ็ก", lang: "ko-KR" },
    { thai: "สีขาว", target: "흰색", reading: "ฮึนแซ็ก", lang: "ko-KR" },
    { thai: "สีส้ม", target: "주황색", reading: "ชูฮวังแซ็ก", lang: "ko-KR" },
    { thai: "สีชมพู", target: "분홍색", reading: "บุนฮงแซ็ก", lang: "ko-KR" },
    { thai: "สีม่วง", target: "보라색", reading: "โบราแซ็ก", lang: "ko-KR" },
    { thai: "สีน้ำตาล", target: "갈색", reading: "คัลแซ็ก", lang: "ko-KR" },
    { thai: "สีเทา", target: "회색", reading: "ฮเวแซ็ก", lang: "ko-KR" },
    { thai: "สีทอง", target: "금색", reading: "คึมแซ็ก", lang: "ko-KR" },
    { thai: "สีเงิน", target: "은색", reading: "อึนแซ็ก", lang: "ko-KR" },
    { thai: "สีสัน", target: "색깔", reading: "แซ็กกัล", lang: "ko-KR" },
    { thai: "สว่าง", target: "밝은", reading: "พัลกึน", lang: "ko-KR" },

    // --- 8. หมวดสิ่งของรอบตัวและในบ้าน (House & Objects) - 30 คำ ---
    { thai: "บ้าน", target: "집", reading: "ชิบ", lang: "ko-KR" },
    { thai: "ห้อง", target: "방", reading: "พัง", lang: "ko-KR" },
    { thai: "ประตู", target: "문", reading: "มุน", lang: "ko-KR" },
    { thai: "หน้าต่าง", target: "창문", reading: "ชังมุน", lang: "ko-KR" },
    { thai: "โต๊ะ", target: "책상 / 탁자", reading: "แช็กซัง / ทักจา", lang: "ko-KR" },
    { thai: "เก้าอี้", target: "의자", reading: "อึยจา", lang: "ko-KR" },
    { thai: "เตียง", target: "침대", reading: "ชิมแด", lang: "ko-KR" },
    { thai: "หมอน", target: "베개", reading: "เพแก", lang: "ko-KR" },
    { thai: "ผ้าห่ม", target: "담요", reading: "ทัมโย", lang: "ko-KR" },
    { thai: "โทรศัพท์", target: "전화기", reading: "ชอนฮวากี", lang: "ko-KR" },
    { thai: "คอมพิวเตอร์", target: "컴퓨터", reading: "คอมพยูดอ", lang: "ko-KR" },
    { thai: "หนังสือ", target: "책", reading: "แช็ก", lang: "ko-KR" },
    { thai: "ปากกา", target: "펜", reading: "เพน", lang: "ko-KR" },
    { thai: "กระดาษ", target: "종이", reading: "ชงงี", lang: "ko-KR" },
    { thai: "กระเป๋า", target: "가방", reading: "คาบัง", lang: "ko-KR" },
    { thai: "กุญแจ", target: "열쇠", reading: "ย็อลซเว", lang: "ko-KR" },
    { thai: "เงิน", target: "돈", reading: "ทน", lang: "ko-KR" },
    { thai: "แก้วน้ำ", target: "유리잔 / 컵", reading: "ยูรีจัน / ค็อบ", lang: "ko-KR" },
    { thai: "จาน", target: "접시", reading: "ช็อบชี", lang: "ko-KR" },
    { thai: "ช้อน", target: "숟가락", reading: "ซุดการัก", lang: "ko-KR" },
    { thai: "ส้อม", target: "포크", reading: "โพคือ", lang: "ko-KR" },
    { thai: "รถยนต์", target: "자동차", reading: "ชาดงชา", lang: "ko-KR" },
    { thai: "จักรยาน", target: "자전거", reading: "ชาจ็อนกอ", lang: "ko-KR" },
    { thai: "นาฬิกา", target: "시계", reading: "ชีคเย", lang: "ko-KR" },
    { thai: "เสื้อผ้า", target: "옷", reading: "อด", lang: "ko-KR" },
    { thai: "รองเท้า", target: "신발", reading: "ชินบัล", lang: "ko-KR" },
    { thai: "แว่นตา", target: "안경", reading: "อันกยอง", lang: "ko-KR" },
    { thai: "ไฟ / หลอดไฟ", target: "전등 / 불", reading: "ช็อนดึง / พุล", lang: "ko-KR" },
    { thai: "พัดลม", target: "선풍기", reading: "ซ็อนพุงกี", lang: "ko-KR" },
    { thai: "กล่อง", target: "상자", reading: "ซังจา", lang: "ko-KR" },

    // --- 9. หมวดอาหารและเครื่องดื่ม (Food & Drink) - 20 คำ ---
    { thai: "ข้าว", target: "밥", reading: "พับ", lang: "ko-KR" },
    { thai: "ขนมปัง", target: "빵", reading: "ปัง", lang: "ko-KR" },
    { thai: "เนื้อสัตว์", target: "고기", reading: "โคงี", lang: "ko-KR" },
    { thai: "ไก่", target: "닭고기", reading: "ทักโกงี", lang: "ko-KR" },
    { thai: "ไข่", target: "계란", reading: "คเยรัน", lang: "ko-KR" },
    { thai: "ผัก", target: "채소", reading: "แชโซ", lang: "ko-KR" },
    { thai: "ผลไม้", target: "과일", reading: "ควาอิล", lang: "ko-KR" },
    { thai: "นม", target: "우유", reading: "อูยู", lang: "ko-KR" },
    { thai: "น้ำเปล่า", target: "물", reading: "มุล", lang: "ko-KR" },
    { thai: "กาแฟ", target: "커피", reading: "คอพี", lang: "ko-KR" },
    { thai: "ชา", target: "차", reading: "ชา", lang: "ko-KR" },
    { thai: "น้ำตาล", target: "설탕", reading: "ซ็อลทัง", lang: "ko-KR" },
    { thai: "เกลือ", target: "소금", reading: "โซกึม", lang: "ko-KR" },
    { thai: "เผ็ด", target: "맵다", reading: "แม็บตา", lang: "ko-KR" },
    { thai: "หวาน", target: "달다", reading: "ทัลดา", lang: "ko-KR" },
    { thai: "เปรี้ยว", target: "시다", reading: "ชีดา", lang: "ko-KR" },
    { thai: "เค็ม", target: "짜다", reading: "จาดา", lang: "ko-KR" },
    { thai: "ขม", target: "쓰다", reading: "ซือดา", lang: "ko-KR" },
    { thai: "ร้อน", target: "뜨겁다", reading: "ตือกอบตา", lang: "ko-KR" },
    { thai: "เย็น", target: "차갑다", reading: "ชากับตา", lang: "ko-KR" },

    // --- 10. หมวดสถานที่และอาคาร (Places & Buildings) - 30 คำ ---
    { thai: "โรงเรียน", target: "학교", reading: "ฮักกโย", lang: "ko-KR" },
    { thai: "โรงพยาบาล", target: "병원", reading: "พยองวอน", lang: "ko-KR" },
    { thai: "ธนาคาร", target: "은행", reading: "อึนแฮง", lang: "ko-KR" },
    { thai: "ร้านอาหาร", target: "식당", reading: "ชิกดัง", lang: "ko-KR" },
    { thai: "โรงแรม", target: "호텔", reading: "โฮเทล", lang: "ko-KR" },
    { thai: "ตลาด", target: "시장", reading: "ชีจัง", lang: "ko-KR" },
    { thai: "สำนักงาน / ออฟฟิศ", target: "사무실", reading: "ซามูชิล", lang: "ko-KR" },
    { thai: "ร้านค้า", target: "가게", reading: "คาเก", lang: "ko-KR" },
    { thai: "ห้างสรรพสินค้า", target: "백화점", reading: "แพ็กฮวาจ็อม", lang: "ko-KR" },
    { thai: "สนามบิน", target: "공항", reading: "คงฮัง", lang: "ko-KR" },
    { thai: "สถานี", target: "역", reading: "ย็อก", lang: "ko-KR" },
    { thai: "สวนสาธารณะ", target: "공원", reading: "คงวอน", lang: "ko-KR" },
    { thai: "ห้องสมุด", target: "도서관", reading: "โทซอกวัน", lang: "ko-KR" },
    { thai: "วัด", target: "절", reading: "ช็อล", lang: "ko-KR" },
    { thai: "เมือง", target: "도시", reading: "โทชี", lang: "ko-KR" },
    { thai: "หมู่บ้าน", target: "마을", reading: "มาอึล", lang: "ko-KR" },
    { thai: "ประเทศ", target: "나라", reading: "นารา", lang: "ko-KR" },
    { thai: "ถนน", target: "길 / 도로", reading: "คิล / โทโร", lang: "ko-KR" },
    { thai: "ทางแยก", target: "교차로", reading: "คโยชาโร", lang: "ko-KR" },
    { thai: "สะพาน", target: "다리", reading: "ทารี", lang: "ko-KR" },
    { thai: "ฟาร์ม", target: "농장", reading: "นงจัง", lang: "ko-KR" },
    { thai: "โรงงาน", target: "공장", reading: "คงจัง", lang: "ko-KR" },
    { thai: "สวน", target: "정원", reading: "ชองวอน", lang: "ko-KR" },
    { thai: "ห้องน้ำ", target: "화장실", reading: "ฮวาจังชิล", lang: "ko-KR" },
    { thai: "ห้องครัว", target: "부엌", reading: "พูอ็อก", lang: "ko-KR" },
    { thai: "ห้องนอน", target: "침실", reading: "ชิมชิล", lang: "ko-KR" },
    { thai: "ชั้นบน", target: "위층", reading: "วีชึง", lang: "ko-KR" },
    { thai: "ชั้นล่าง", target: "아래층", reading: "อาแรชึง", lang: "ko-KR" },
    { thai: "มุม", target: "모퉁이", reading: "โมทุงงี", lang: "ko-KR" },
    { thai: "ใจกลางเมือง", target: "시내", reading: "ชีแน", lang: "ko-KR" },
	, // --- 11. หมวดการเดินทางและยานพาหนะ (Travel & Vehicles) - 20 คำ ---
    { thai: "เครื่องบิน", target: "비행기", reading: "พีแฮ็งกี", lang: "ko-KR" },
    { thai: "เรือ", target: "배", reading: "แพ", lang: "ko-KR" },
    { thai: "รถไฟ", target: "기차", reading: "คีชา", lang: "ko-KR" },
    { thai: "รถเมล์ / รถบัส", target: "버스", reading: "พอซือ", lang: "ko-KR" },
    { thai: "มอเตอร์ไซค์", target: "오토바이", reading: "โอโทบาอี", lang: "ko-KR" },
    { thai: "ตั๋ว", target: "표", reading: "พโย", lang: "ko-KR" },
    { thai: "แผนที่", target: "지도", reading: "ชีโด", lang: "ko-KR" },
    { thai: "สัมภาระ / กระเป๋าเดินทาง", target: "수하물 / 짐", reading: "ซูฮามุล / ชิม", lang: "ko-KR" },
    { thai: "พาสปอร์ต", target: "여권", reading: "ยอกวอน", lang: "ko-KR" },
    { thai: "เที่ยวบิน", target: "항공편", reading: "ฮังกงพยอน", lang: "ko-KR" },
    { thai: "โรงแรม", target: "호텔", reading: "โฮเทล", lang: "ko-KR" },
    { thai: "ท่องเที่ยว", target: "관광", reading: "ควันกวัง", lang: "ko-KR" },
    { thai: "ทิศทาง", target: "방향", reading: "พังฮยัง", lang: "ko-KR" },
    { thai: "ทางเหนือ", target: "북쪽", reading: "พุกจก", lang: "ko-KR" },
    { thai: "ทางใต้", target: "남쪽", reading: "นัมจก", lang: "ko-KR" },
    { thai: "ทางตะวันออก", target: "동쪽", reading: "ทงจก", lang: "ko-KR" },
    { thai: "ทางตะวันตก", target: "서쪽", reading: "ซอจก", lang: "ko-KR" },
    { thai: "ตรงไป", target: "직진", reading: "ชิกจิน", lang: "ko-KR" },
    { thai: "เลี้ยว", target: "돌다", reading: "ทลดา", lang: "ko-KR" },
    { thai: "มาถึง", target: "도착하다", reading: "โทชักฮาดา", lang: "ko-KR" },

    // --- 12. หมวดคำคุณศัพท์พื้นฐาน (Basic Adjectives) - 50 คำ ---
    { thai: "ใหญ่", target: "크다", reading: "คือดา", lang: "ko-KR" },
    { thai: "เล็ก", target: "작다", reading: "ชักตา", lang: "ko-KR" },
    { thai: "สูง", target: "높다", reading: "นพตา", lang: "ko-KR" },
    { thai: "ต่ำ", target: "낮다", reading: "นัดตา", lang: "ko-KR" },
    { thai: "ยาว", target: "길다", reading: "คิลดา", lang: "ko-KR" },
    { thai: "สั้น", target: "짧다", reading: "จัลตา", lang: "ko-KR" },
    { thai: "กว้าง", target: "넓다", reading: "น็อลตา", lang: "ko-KR" },
    { thai: "แคบ", target: "좁다", reading: "ชบตา", lang: "ko-KR" },
    { thai: "หนา", target: "두껍다", reading: "ทูก็อบตา", lang: "ko-KR" },
    { thai: "บาง", target: "얇다", reading: "ยัลตา", lang: "ko-KR" },
    { thai: "หนัก", target: "무겁다", reading: "มูก็อบตา", lang: "ko-KR" },
    { thai: "เบา", target: "가볍다", reading: "คาบย็อบตา", lang: "ko-KR" },
    { thai: "ยาก", target: "어렵다", reading: "ออรย็อบตา", lang: "ko-KR" },
    { thai: "ง่าย", target: "쉽다", reading: "ชวิบตา", lang: "ko-KR" },
    { thai: "ดี", target: "좋다", reading: "โชทา", lang: "ko-KR" },
    { thai: "แย่", target: "나쁘다", reading: "นาปือดา", lang: "ko-KR" },
    { thai: "สวย", target: "아름답다", reading: "อารึมดับตา", lang: "ko-KR" },
    { thai: "น่าเกลียด", target: "못생기다", reading: "มดแซ็งกีดา", lang: "ko-KR" },
    { thai: "ร้อน", target: "덥다", reading: "ท็อบตา", lang: "ko-KR" },
    { thai: "หนาว", target: "춥다", reading: "ชุบตา", lang: "ko-KR" },
    { thai: "เร็ว", target: "빠르다", reading: "ปารึดา", lang: "ko-KR" },
    { thai: "ช้า", target: "느리다", reading: "นือรีดา", lang: "ko-KR" },
    { thai: "ใหม่", target: "새롭다", reading: "แซรบตา", lang: "ko-KR" },
    { thai: "เก่า / แก่", target: "오래되다", reading: "โอแรดเวดา", lang: "ko-KR" },
    { thai: "แพง", target: "비싸다", reading: "พีซาดา", lang: "ko-KR" },
    { thai: "ถูก", target: "싸다", reading: "ซาดา", lang: "ko-KR" },
    { thai: "รวย", target: "부유하다", reading: "พูยูฮาดา", lang: "ko-KR" },
    { thai: "จน", target: "가난하다", reading: "คานันฮาดา", lang: "ko-KR" },
    { thai: "สะอาด", target: "깨끗하다", reading: "แกกึดฮาดา", lang: "ko-KR" },
    { thai: "สกปรก", target: "더럽다", reading: "ทอร็อบตา", lang: "ko-KR" },
    { thai: "เต็ม", target: "가득하다", reading: "คาดึกฮาดา", lang: "ko-KR" },
    { thai: "ว่างเปล่า", target: "비어 있다", reading: "พีออ อิดตา", lang: "ko-KR" },
    { thai: "ดัง", target: "시끄럽다", reading: "ชีกือร็อบตา", lang: "ko-KR" },
    { thai: "เงียบ", target: "조용하다", reading: "โชยงฮาดา", lang: "ko-KR" },
    { thai: "มีความสุข", target: "행복하다", reading: "แฮ็งบกฮาดา", lang: "ko-KR" },
    { thai: "เศร้า", target: "슬프다", reading: "ซึลพือดา", lang: "ko-KR" },
    { thai: "โกรธ", target: "화나다", reading: "ฮวานาดา", lang: "ko-KR" },
    { thai: "หิว", target: "배고프다", reading: "แพโกพือดา", lang: "ko-KR" },
    { thai: "กระหายน้ำ", target: "목마르다", reading: "มกมารึดา", lang: "ko-KR" },
    { thai: "เหนื่อย", target: "피곤하다", reading: "พีกนฮาดา", lang: "ko-KR" },
    { thai: "ป่วย", target: "아프다", reading: "อาพือดา", lang: "ko-KR" },
    { thai: "แข็งแรง", target: "강하다", reading: "คังฮาดา", lang: "ko-KR" },
    { thai: "อ่อนแอ", target: "약하다", reading: "ยักฮาดา", lang: "ko-KR" },
    { thai: "ฉลาด", target: "똑똑하다", reading: "ตกตกฮาดา", lang: "ko-KR" },
    { thai: "โง่", target: "어리석다", reading: "ออรีซ็อกตา", lang: "ko-KR" },
    { thai: "ปลอดภัย", target: "안전하다", reading: "อันจ็อนฮาดา", lang: "ko-KR" },
    { thai: "อันตราย", target: "위험하다", reading: "วีฮอมฮาดา", lang: "ko-KR" },
    { thai: "น่าสนใจ", target: "흥미롭다", reading: "ฮึงมีรบตา", lang: "ko-KR" },
    { thai: "น่าเบื่อ", target: "지루하다", reading: "ชีรูฮาดา", lang: "ko-KR" },
    { thai: "สำคัญ", target: "중요하다", reading: "ชุงโยฮาดา", lang: "ko-KR" },

    // --- 13. หมวดอาชีพ (Occupations) - 25 คำ ---
    { thai: "พนักงาน", target: "직원", reading: "ชิกวอน", lang: "ko-KR" },
    { thai: "นายจ้าง / หัวหน้า", target: "사장", reading: "ซาจัง", lang: "ko-KR" },
    { thai: "ผู้จัดการ", target: "매니저", reading: "แมนีจอ", lang: "ko-KR" },
    { thai: "พนักงานขาย", target: "판매원", reading: "พันแมวอน", lang: "ko-KR" },
    { thai: "วิศวกร", target: "엔지니어", reading: "เอนจีนีออ", lang: "ko-KR" },
    { thai: "หมอ", target: "의사", reading: "อึยซา", lang: "ko-KR" },
    { thai: "พยาบาล", target: "간호사", reading: "คันโฮซา", lang: "ko-KR" },
    { thai: "ครู", target: "선생님", reading: "ซ็อนแซ็งนิม", lang: "ko-KR" },
    { thai: "ตำรวจ", target: "경찰", reading: "คยองชัล", lang: "ko-KR" },
    { thai: "ทหาร", target: "군인", reading: "คุนิน", lang: "ko-KR" },
    { thai: "นักบิน", target: "조종사", reading: "โชจงซา", lang: "ko-KR" },
    { thai: "พ่อครัว", target: "요리사", reading: "โยรีซา", lang: "ko-KR" },
    { thai: "พนักงานเสิร์ฟ", target: "종업원", reading: "ชงงอบวอน", lang: "ko-KR" },
    { thai: "คนขับรถ", target: "운전사", reading: "อุนจ็อนซา", lang: "ko-KR" },
    { thai: "นักเขียน", target: "작가", reading: "ชักกา", lang: "ko-KR" },
    { thai: "ศิลปิน", target: "예술가", reading: "เยซุลกา", lang: "ko-KR" },
    { thai: "นักธุรกิจ", target: "사업가", reading: "ซาออบกา", lang: "ko-KR" },
    { thai: "เลขานุการ", target: "비서", reading: "พีซอ", lang: "ko-KR" },
    { thai: "ช่างภาพ", target: "사진작가", reading: "ซาจินชักกา", lang: "ko-KR" },
    { thai: "นักออกแบบ", target: "디자이너", reading: "ทีจาอีเนอ", lang: "ko-KR" },
    { thai: "ชาวนา / เกษตรกร", target: "농부", reading: "นงบู", lang: "ko-KR" },
    { thai: "นักแสดง", target: "배우", reading: "แพอู", lang: "ko-KR" },
    { thai: "นักดนตรี", target: "음악가", reading: "อึมมักกา", lang: "ko-KR" },
    { thai: "อาชีพ", target: "직업", reading: "ชีกอบ", lang: "ko-KR" },
    { thai: "งาน", target: "일", reading: "อิล", lang: "ko-KR" },

    // --- 14. หมวดธุรกิจและการตลาด (Business & Marketing) - 40 คำ ---
    { thai: "บริษัท", target: "회사", reading: "ฮเวซา", lang: "ko-KR" },
    { thai: "ธุรกิจ", target: "비즈니스", reading: "พีจือนีซือ", lang: "ko-KR" },
    { thai: "ลูกค้า", target: "고객", reading: "โคแก็ก", lang: "ko-KR" },
    { thai: "บริการ", target: "서비스", reading: "ซอบีซือ", lang: "ko-KR" },
    { thai: "ผลิตภัณฑ์ / สินค้า", target: "제품", reading: "เชพุม", lang: "ko-KR" },
    { thai: "แบรนด์ / ยี่ห้อ", target: "브랜드", reading: "พือแรนดือ", lang: "ko-KR" },
    { thai: "ราคา", target: "가격", reading: "คากย็อก", lang: "ko-KR" },
    { thai: "ส่วนลด", target: "할인", reading: "ฮาริน", lang: "ko-KR" },
    { thai: "โฆษณา", target: "광고", reading: "ควันโก", lang: "ko-KR" },
    { thai: "ยอดขาย", target: "판매량", reading: "พันแมรยัง", lang: "ko-KR" },
    { thai: "การตลาด", target: "마케팅", reading: "มาเคทิง", lang: "ko-KR" },
    { thai: "กำไร", target: "이익", reading: "อีอิก", lang: "ko-KR" },
    { thai: "ขาดทุน", target: "손실", reading: "ซนชิล", lang: "ko-KR" },
    { thai: "คู่แข่ง", target: "경쟁자", reading: "คยองแจ็งจา", lang: "ko-KR" },
    { thai: "กลยุทธ์", target: "전략", reading: "ช็อลลยัก", lang: "ko-KR" },
    { thai: "โอกาส", target: "기회", reading: "คีฮเว", lang: "ko-KR" },
    { thai: "สัญญา", target: "계약", reading: "คเยยัก", lang: "ko-KR" },
    { thai: "ข้อตกลง", target: "합의", reading: "ฮาบึย", lang: "ko-KR" },
    { thai: "หุ้น", target: "주식", reading: "ชูชิก", lang: "ko-KR" },
    { thai: "การลงทุน", target: "투자", reading: "ทูจา", lang: "ko-KR" },
    { thai: "เป้าหมาย", target: "목표", reading: "มกพโย", lang: "ko-KR" },
    { thai: "ความสำเร็จ", target: "성공", reading: "ซ็องกง", lang: "ko-KR" },
    { thai: "ล้มเหลว", target: "실패", reading: "ชิลแพ", lang: "ko-KR" },
    { thai: "การเติบโต", target: "성장", reading: "ซ็องจัง", lang: "ko-KR" },
    { thai: "คุณภาพ", target: "품질", reading: "พุมจิล", lang: "ko-KR" },
    { thai: "ปริมาณ", target: "수량", reading: "ซูรยัง", lang: "ko-KR" },
    { thai: "ภาษี", target: "세금", reading: "เซกึม", lang: "ko-KR" },
    { thai: "ใบแจ้งหนี้", target: "송장", reading: "ซงจัง", lang: "ko-KR" },
    { thai: "ใบเสร็จ", target: "영수증", reading: "ยองซูจึง", lang: "ko-KR" },
    { thai: "ธนาคาร", target: "은행", reading: "อึนแฮง", lang: "ko-KR" },
    { thai: "บัญชี", target: "계좌", reading: "คเยจวา", lang: "ko-KR" },
    { thai: "บัตรเครดิต", target: "신용카드", reading: "ชินยงคาดือ", lang: "ko-KR" },
    { thai: "เงินสด", target: "현금", reading: "ฮย็อนกึม", lang: "ko-KR" },
    { thai: "ค่าใช้จ่าย", target: "비용", reading: "พียง", lang: "ko-KR" },
    { thai: "งบประมาณ", target: "예산", reading: "เยซาน", lang: "ko-KR" },
    { thai: "หนี้", target: "빚", reading: "พิด", lang: "ko-KR" },
    { thai: "ความมั่งคั่ง", target: "부", reading: "พู", lang: "ko-KR" },
    { thai: "เศรษฐกิจ", target: "경제", reading: "คยองเจ", lang: "ko-KR" },
    { thai: "ตลาด", target: "시장", reading: "ชีจัง", lang: "ko-KR" },
    { thai: "อุตสาหกรรม", target: "산업", reading: "ซานอบ", lang: "ko-KR" },

    // --- 15. หมวดการสื่อสารและอุปกรณ์ในออฟฟิศ (Office & Communication) - 35 คำ ---
    { thai: "การประชุม", target: "회의", reading: "ฮเวอึย", lang: "ko-KR" },
    { thai: "การนำเสนอ", target: "발표", reading: "พัลพโย", lang: "ko-KR" },
    { thai: "รายงาน", target: "보고서", reading: "โพโกซอ", lang: "ko-KR" },
    { thai: "โครงการ", target: "프로젝트", reading: "พือโรเจ็กทือ", lang: "ko-KR" },
    { thai: "กำหนดส่ง", target: "마감일", reading: "มากามิล", lang: "ko-KR" },
    { thai: "ตารางเวลา", target: "일정", reading: "อิลจอง", lang: "ko-KR" },
    { thai: "ข้อมูล", target: "정보", reading: "ชองโบ", lang: "ko-KR" },
    { thai: "อีเมล", target: "이메일", reading: "อีเมอิล", lang: "ko-KR" },
    { thai: "ข้อความ", target: "메시지", reading: "เมชีจี", lang: "ko-KR" },
    { thai: "โทรศัพท์", target: "전화", reading: "ช็อนฮวา", lang: "ko-KR" },
    { thai: "แล็ปท็อป", target: "노트북", reading: "โนทือบุก", lang: "ko-KR" },
    { thai: "เครื่องพิมพ์", target: "프린터", reading: "พือรินทอ", lang: "ko-KR" },
    { thai: "เอกสาร", target: "문서", reading: "มุนซอ", lang: "ko-KR" },
    { thai: "ไฟล์ / แฟ้ม", target: "파일", reading: "พาอิล", lang: "ko-KR" },
    { thai: "อินเทอร์เน็ต", target: "인터넷", reading: "อินทอเน็ต", lang: "ko-KR" },
    { thai: "รหัสผ่าน", target: "비밀번호", reading: "พีมิลบอนโฮ", lang: "ko-KR" },
    { thai: "หน้าจอ", target: "화면", reading: "ฮวามยอน", lang: "ko-KR" },
    { thai: "แป้นพิมพ์", target: "키보드", reading: "คีโบดือ", lang: "ko-KR" },
    { thai: "เมาส์", target: "마우스", reading: "มาอูซือ", lang: "ko-KR" },
    { thai: "ซอฟต์แวร์", target: "소프트웨어", reading: "โซพือทือแวออ", lang: "ko-KR" },
    { thai: "ฮาร์ดแวร์", target: "하드웨어", reading: "ฮาดือแวออ", lang: "ko-KR" },
    { thai: "การสื่อสาร", target: "의사소통", reading: "อึยซาโซทง", lang: "ko-KR" },
    { thai: "เครือข่าย", target: "네트워크", reading: "เนทือวอกือ", lang: "ko-KR" },
    { thai: "ทีม", target: "팀", reading: "ทิม", lang: "ko-KR" },
    { thai: "ความร่วมมือ", target: "협력", reading: "ฮย็อมนย็อก", lang: "ko-KR" },
    { thai: "ความคิดเห็น", target: "피드백", reading: "พีดือแบ็ก", lang: "ko-KR" },
    { thai: "การตัดสินใจ", target: "결정", reading: "คย็อลจอง", lang: "ko-KR" },
    { thai: "ปัญหา", target: "문제", reading: "มุนเจ", lang: "ko-KR" },
    { thai: "วิธีแก้ปัญหา", target: "해결책", reading: "แฮกย็อลแช็ก", lang: "ko-KR" },
    { thai: "นวัตกรรม", target: "혁신", reading: "ฮย็อกชิน", lang: "ko-KR" },
    { thai: "ความคิดสร้างสรรค์", target: "창의력", reading: "ชางอึยรย็อก", lang: "ko-KR" },
    { thai: "ทักษะ", target: "기술", reading: "คีซุล", lang: "ko-KR" },
    { thai: "ประสบการณ์", target: "경험", reading: "คยองฮอม", lang: "ko-KR" },
    { thai: "ความรู้", target: "지식", reading: "ชีชิก", lang: "ko-KR" },
    { thai: "เป้าหมาย", target: "목표", reading: "มกพโย", lang: "ko-KR" },

    // --- 16. หมวดเทคโนโลยีและฮาร์ดแวร์ (Technology & Hardware) - 25 คำ ---
    { thai: "เทคโนโลยี", target: "기술", reading: "คีซุล", lang: "ko-KR" },
    { thai: "อุปกรณ์", target: "기기", reading: "คีกี", lang: "ko-KR" },
    { thai: "มือถือ", target: "모바일", reading: "โมบาอิล", lang: "ko-KR" },
    { thai: "เซิร์ฟเวอร์", target: "서버", reading: "ซอบอ", lang: "ko-KR" },
    { thai: "หน้าจอ", target: "스크린", reading: "ซือคือริน", lang: "ko-KR" },
    { thai: "แบตเตอรี่", target: "배터리", reading: "แพทอรี", lang: "ko-KR" },
    { thai: "สายเคเบิล", target: "케이블", reading: "เคอีบึล", lang: "ko-KR" },
    { thai: "ไร้สาย", target: "무선", reading: "มูซอน", lang: "ko-KR" },
    { thai: "บลูทูธ", target: "블루투스", reading: "พึลลูทูซือ", lang: "ko-KR" },
    { thai: "เราเตอร์", target: "라우터", reading: "ราอูทอ", lang: "ko-KR" },
    { thai: "สวิตช์", target: "스위치", reading: "ซือวีชี", lang: "ko-KR" },
    { thai: "หน่วยความจำ", target: "메모리", reading: "เมโมรี", lang: "ko-KR" },
    { thai: "ตัวประมวลผล", target: "프로세서", reading: "พือโรเซซอ", lang: "ko-KR" },
    { thai: "ที่เก็บข้อมูล", target: "저장소", reading: "ชอจังโซ", lang: "ko-KR" },
    { thai: "ระบบคลาวด์", target: "클라우드", reading: "คึลลาอูดือ", lang: "ko-KR" },
    { thai: "เบราว์เซอร์", target: "브라우저", reading: "พือราอูจอ", lang: "ko-KR" },
    { thai: "แอปพลิเคชัน", target: "애플리케이션", reading: "แอพึลลีเคอีชอน", lang: "ko-KR" },
    { thai: "ดาวน์โหลด", target: "다운로드", reading: "ทาอุลโลดือ", lang: "ko-KR" },
    { thai: "อัปโหลด", target: "업로드", reading: "ออมโนดือ", lang: "ko-KR" },
    { thai: "ติดตั้ง", target: "설치", reading: "ซอลชี", lang: "ko-KR" },
    { thai: "อัปเดต", target: "업데이트", reading: "ออบเดอีทือ", lang: "ko-KR" },
    { thai: "อัปเกรด", target: "업그레이드", reading: "ออบกือเรอีดือ", lang: "ko-KR" },
    { thai: "เวอร์ชัน", target: "버전", reading: "พอจอน", lang: "ko-KR" },
    { thai: "ระบบ", target: "시스템", reading: "ชีซือเท็ม", lang: "ko-KR" },
    { thai: "แพลตฟอร์ม", target: "플랫폼", reading: "พึลแล็ดพม", lang: "ko-KR" },

    // --- 17. หมวดการพัฒนาเว็บและโปรแกรมมิ่ง (Web Development & Programming) - 40 คำ ---
    { thai: "โค้ด / รหัส", target: "코드", reading: "โคดือ", lang: "ko-KR" },
    { thai: "โปรแกรม", target: "프로그램", reading: "พือโรกือแรม", lang: "ko-KR" },
    { thai: "นักพัฒนา", target: "개발자", reading: "แคบัลจา", lang: "ko-KR" },
    { thai: "ฟังก์ชัน", target: "함수", reading: "ฮัมซู", lang: "ko-KR" },
    { thai: "ตัวแปร", target: "변수", reading: "พย็อนซู", lang: "ko-KR" },
    { thai: "อาเรย์ / ชุดข้อมูล", target: "배열", reading: "แพย็อล", lang: "ko-KR" },
    { thai: "อ็อบเจกต์", target: "객체", reading: "แค็กเช", lang: "ko-KR" },
    { thai: "ข้อความ (สตริง)", target: "문자열", reading: "มุนจาย็อล", lang: "ko-KR" },
    { thai: "จำนวนเต็ม", target: "정수", reading: "ชองซู", lang: "ko-KR" },
    { thai: "บูลีน (ตรรกะ)", target: "부울", reading: "พูอุล", lang: "ko-KR" },
    { thai: "วนลูป", target: "루프", reading: "รูพือ", lang: "ko-KR" },
    { thai: "เงื่อนไข", target: "조건", reading: "โชกอน", lang: "ko-KR" },
    { thai: "คำสั่ง", target: "구문", reading: "คุมุน", lang: "ko-KR" },
    { thai: "ข้อผิดพลาด", target: "오류", reading: "โอรยู", lang: "ko-KR" },
    { thai: "บั๊ก / จุดบกพร่อง", target: "버그", reading: "พอกือ", lang: "ko-KR" },
    { thai: "แก้บั๊ก", target: "디버그", reading: "ทีบอกือ", lang: "ko-KR" },
    { thai: "สคริปต์", target: "스크립트", reading: "ซือคือริบทือ", lang: "ko-KR" },
    { thai: "ระบบหน้าบ้าน", target: "프론트엔드", reading: "พือรนทือเอนดือ", lang: "ko-KR" },
    { thai: "ระบบหลังบ้าน", target: "백엔드", reading: "แพ็กเอนดือ", lang: "ko-KR" },
    { thai: "ฐานข้อมูล", target: "데이터베이스", reading: "เดอีทอเบอีซือ", lang: "ko-KR" },
    { thai: "คำสืบค้น", target: "쿼리", reading: "ควอรี", lang: "ko-KR" },
    { thai: "เอพีไอ", target: "API", reading: "에이피아이 (เออีพีอาอี)", lang: "ko-KR" },
    { thai: "เฟรมเวิร์ก", target: "프레임워크", reading: "พือเรอิมวอกือ", lang: "ko-KR" },
    { thai: "ไลบรารี", target: "라이브러리", reading: "ราอีบือรอรี", lang: "ko-KR" },
    { thai: "คลังเก็บโค้ด", target: "저장소", reading: "ชอจังโซ", lang: "ko-KR" },
    { thai: "บันทึกการเปลี่ยน", target: "커밋", reading: "คอมิด", lang: "ko-KR" },
    { thai: "ดันโค้ด", target: "푸시", reading: "พูชี", lang: "ko-KR" },
    { thai: "ดึงโค้ด", target: "풀", reading: "พุล", lang: "ko-KR" },
    { thai: "สาขา (โค้ด)", target: "브랜치", reading: "พือแรนชี", lang: "ko-KR" },
    { thai: "รวม (โค้ด)", target: "병합", reading: "พยองฮับ", lang: "ko-KR" },
    { thai: "ไวยากรณ์ (โค้ด)", target: "문법", reading: "มุนบ็อบ", lang: "ko-KR" },
    { thai: "แท็ก", target: "태그", reading: "แทกือ", lang: "ko-KR" },
    { thai: "คุณลักษณะ", target: "속성", reading: "ซกซอง", lang: "ko-KR" },
    { thai: "องค์ประกอบ", target: "요소", reading: "โยโซ", lang: "ko-KR" },
    { thai: "ปลั๊กอิน", target: "플러그인", reading: "พึลลอกืออิน", lang: "ko-KR" },
    { thai: "โมดูล", target: "모듈", reading: "โมดยุล", lang: "ko-KR" },
    { thai: "ส่วนประกอบ", target: "컴포넌트", reading: "คอมโพนอนทือ", lang: "ko-KR" },
    { thai: "แม่แบบ", target: "템플릿", reading: "เท็มพึลลิด", lang: "ko-KR" },
    { thai: "โฮสต์", target: "호스트", reading: "โฮซือทือ", lang: "ko-KR" },
    { thai: "โดเมน", target: "도메인", reading: "โทเมอิน", lang: "ko-KR" },

    // --- 18. หมวดข้อมูล, UI/UX และตรรกะ (Data, UI/UX & Logic) - 35 คำ ---
    { thai: "ข้อมูล", target: "데이터", reading: "เดอีทอ", lang: "ko-KR" },
    { thai: "ตรรกะ", target: "논리", reading: "นลลี", lang: "ko-KR" },
    { thai: "อินเทอร์เฟส / หน้าจอ", target: "인터페이스", reading: "อินทอเพอีซือ", lang: "ko-KR" },
    { thai: "ผู้ใช้", target: "사용자", reading: "ซายงจา", lang: "ko-KR" },
    { thai: "การออกแบบ", target: "디자인", reading: "ทีจาอิน", lang: "ko-KR" },
    { thai: "โครงร่าง / เค้าโครง", target: "레이아웃", reading: "เรอีอาอุด", lang: "ko-KR" },
    { thai: "การนำทาง", target: "네비게이션", reading: "เนบีเกอีชอน", lang: "ko-KR" },
    { thai: "ปุ่ม", target: "버튼", reading: "พอทึน", lang: "ko-KR" },
    { thai: "ลิงก์ / จุดเชื่อมโยง", target: "링크", reading: "ลิงคือ", lang: "ko-KR" },
    { thai: "ไอคอน", target: "아이콘", reading: "อาอีคน", lang: "ko-KR" },
    { thai: "เมนู", target: "메뉴", reading: "เมนู", lang: "ko-KR" },
    { thai: "ค้นหา", target: "검색", reading: "คอมแซ็ก", lang: "ko-KR" },
    { thai: "กรอง", target: "필터", reading: "พิลทอ", lang: "ko-KR" },
    { thai: "เรียงลำดับ", target: "정렬", reading: "ชองนย็อล", lang: "ko-KR" },
    { thai: "นำเข้า / ข้อมูลเข้า", target: "입력", reading: "อิมนย็อก", lang: "ko-KR" },
    { thai: "ส่งออก / ผลลัพธ์", target: "출력", reading: "ชุลลย็อก", lang: "ko-KR" },
    { thai: "คลิก", target: "클릭", reading: "คึลลิก", lang: "ko-KR" },
    { thai: "เลื่อน (จอ)", target: "스크롤", reading: "ซือคือรล", lang: "ko-KR" },
    { thai: "ปัด (หน้าจอ)", target: "스와이프", reading: "ซือวาอีพือ", lang: "ko-KR" },
    { thai: "วางเมาส์เหนือ", target: "호버", reading: "โฮบอ", lang: "ko-KR" },
    { thai: "โฟกัส", target: "포커스", reading: "โพคอซือ", lang: "ko-KR" },
    { thai: "ใช้งานอยู่", target: "활성", reading: "ฮวัลซอง", lang: "ko-KR" },
    { thai: "ค่าเริ่มต้น", target: "기본값", reading: "คีบนกัป", lang: "ko-KR" },
    { thai: "การตั้งค่า", target: "설정", reading: "ซอลจอง", lang: "ko-KR" },
    { thai: "โปรไฟล์", target: "프로필", reading: "พือโรพิล", lang: "ko-KR" },
    { thai: "บัญชี", target: "계정", reading: "คเยจอง", lang: "ko-KR" },
    { thai: "เข้าสู่ระบบ", target: "로그인", reading: "รอกืออิน", lang: "ko-KR" },
    { thai: "ออกจากระบบ", target: "로그아웃", reading: "รอกืออาอุด", lang: "ko-KR" },
    { thai: "สมัครสมาชิก", target: "가입", reading: "คาอิบ", lang: "ko-KR" },
    { thai: "ความปลอดภัย", target: "보안", reading: "โพอัน", lang: "ko-KR" },
    { thai: "ความเป็นส่วนตัว", target: "개인정보", reading: "แคอินจองโบ", lang: "ko-KR" },
    { thai: "การเข้าถึง", target: "접근", reading: "ช็อบกึน", lang: "ko-KR" },
    { thai: "โทเคน (รหัส)", target: "토큰", reading: "โทคึน", lang: "ko-KR" },
    { thai: "เซสชัน", target: "세션", reading: "เซชอน", lang: "ko-KR" },
    { thai: "คุกกี้ (ข้อมูล)", target: "쿠키", reading: "คูคี", lang: "ko-KR" },
	, // --- 19. หมวดสุขภาพ โภชนาการ และการดูแลร่างกาย (Health & Nutrition) - 30 คำ ---
    { thai: "สุขภาพ", target: "건강", reading: "กอนกัง", lang: "ko-KR" },
    { thai: "สุขภาพดี", target: "건강한", reading: "กอน강ฮัน", lang: "ko-KR" },
    { thai: "โภชนาการ", target: "영양", reading: "ยองยัง", lang: "ko-KR" },
    { thai: "ระบบเผาผลาญ", target: "신진대사", reading: "ชินจินแดซา", lang: "ko-KR" },
    { thai: "แคลอรี", target: "칼로리", reading: "คัลโลรี", lang: "ko-KR" },
    { thai: "โปรตีน", target: "단백질", reading: "ทันแบ็กจิล", lang: "ko-KR" },
    { thai: "วิตามิน", target: "비타민", reading: "พีทามิน", lang: "ko-KR" },
    { thai: "แร่ธาตุ", target: "미네랄", reading: "มีเนรัล", lang: "ko-KR" },
    { thai: "ไขมัน", target: "지방", reading: "ชีบัง", lang: "ko-KR" },
    { thai: "คาร์โบไฮเดรต", target: "탄수화물", reading: "ทันซูฮวามุล", lang: "ko-KR" },
    { thai: "เส้นใยอาหาร", target: "섬유질", reading: "ซอมยูจิล", lang: "ko-KR" },
    { thai: "กล้ามเนื้อ", target: "근육", reading: "คือนยุก", lang: "ko-KR" },
    { thai: "น้ำหนัก", target: "체중 / 몸무게", reading: "เชจุง / มมมูเก", lang: "ko-KR" },
    { thai: "ส่วนสูง", target: "키", reading: "คี", lang: "ko-KR" },
    { thai: "ความสมบูรณ์ของร่างกาย", target: "체력 / 피트니스", reading: "เชรย็อก / พีทือนีซือ", lang: "ko-KR" },
    { thai: "โรงยิม", target: "체육관 / 헬스장", reading: "เชยุกกวัน / เฮลซือจัง", lang: "ko-KR" },
    { thai: "ออกกำลังกาย (หนัก)", target: "운동", reading: "อุนดง", lang: "ko-KR" },
    { thai: "เหงื่อ", target: "땀", reading: "ตัม", lang: "ko-KR" },
    { thai: "การพักผ่อน", target: "휴식", reading: "ฮยูชิก", lang: "ko-KR" },
    { thai: "การฟื้นฟู", target: "회복", reading: "ฮเวบก", lang: "ko-KR" },
    { thai: "โรคภัย", target: "질병", reading: "ชิลบยอง", lang: "ko-KR" },
    { thai: "ยารักษาโรค", target: "약", reading: "ยัก", lang: "ko-KR" },
    { thai: "คลินิก", target: "의원 / 클리닉", reading: "อึยวอน / คึลลีนิก", lang: "ko-KR" },
    { thai: "การบำบัด", target: "치료", reading: "ชีรโย", lang: "ko-KR" },
    { thai: "อาหารเสริม", target: "보충제", reading: "โพชุงเจ", lang: "ko-KR" },
    { thai: "การย่อยอาหาร", target: "소화", reading: "โซฮวา", lang: "ko-KR" },
    { thai: "ภูมิคุ้มกัน", target: "면역", reading: "มยอนย็อก", lang: "ko-KR" },
    { thai: "ออกซิเจน", target: "산소", reading: "ซันโซ", lang: "ko-KR" },
    { thai: "โยเกิร์ต", target: "요구르트", reading: "โยกูรือทือ", lang: "ko-KR" },
    { thai: "เมล็ดพืช", target: "씨앗", reading: "ชีอัด", lang: "ko-KR" },

    // --- 20. หมวดการเงิน การลงทุน และสินทรัพย์ (Finance & Investment) - 40 คำ ---
    { thai: "การเงิน", target: "금융", reading: "คึมยุง", lang: "ko-KR" },
    { thai: "สินทรัพย์", target: "자산", reading: "ชาซาน", lang: "ko-KR" },
    { thai: "หนี้สิน", target: "부채", reading: "พูแช", lang: "ko-KR" },
    { thai: "กองทุน", target: "펀드", reading: "พ็อนดือ", lang: "ko-KR" },
    { thai: "กองทุนรวม", target: "뮤추얼 펀드", reading: "มยูชูออล พ็อนดือ", lang: "ko-KR" },
    { thai: "คริปโตเคอร์เรนซี", target: "암호화폐", reading: "อัมโฮฮวาพเย", lang: "ko-KR" },
    { thai: "บิตคอยน์", target: "비트코인", reading: "พีทือโคอิน", lang: "ko-KR" },
    { thai: "เงินปันผล", target: "배당금", reading: "แพ당กึม", lang: "ko-KR" },
    { thai: "ดอกเบี้ย", target: "이자", reading: "อีจา", lang: "ko-KR" },
    { thai: "อัตรา", target: "비율", reading: "พียุล", lang: "ko-KR" },
    { thai: "เงินเฟ้อ", target: "인플레이션", reading: "อินพึลเลอีชอน", lang: "ko-KR" },
    { thai: "พอร์ตการลงทุน", target: "포트폴리오", reading: "โพทือพลลีโอ", lang: "ko-KR" },
    { thai: "กระจายความเสี่ยง", target: "분산 투자", reading: "พุนซาน ทูจา", lang: "ko-KR" },
    { thai: "ผลตอบแทน", target: "수익", reading: "ซูอิก", lang: "ko-KR" },
    { thai: "ทุน / เงินทุน", target: "자본", reading: "ชาบน", lang: "ko-KR" },
    { thai: "การเทรด / ซื้อขาย", target: "거래", reading: "คอแร", lang: "ko-KR" },
    { thai: "ค่าเฉลี่ย", target: "평균", reading: "พยองกยุน", lang: "ko-KR" },
    { thai: "การเกษียณอายุ", target: "은퇴", reading: "อึนทเว", lang: "ko-KR" },
    { thai: "เงินบำนาญ", target: "연금", reading: "ยอนกึม", lang: "ko-KR" },
    { thai: "เก็บออม", target: "저축", reading: "ชอชุก", lang: "ko-KR" },
    { thai: "รายได้ (เข้า)", target: "수입", reading: "ซูอิบ", lang: "ko-KR" },
    { thai: "รายจ่าย", target: "지출", reading: "ชีชุล", lang: "ko-KR" },
    { thai: "สกุลเงิน", target: "통화", reading: "ทงฮวา", lang: "ko-KR" },
    { thai: "เหรียญ", target: "동전", reading: "ทงจอน", lang: "ko-KR" },
    { thai: "ตลาดกระทิง (ขาขึ้น)", target: "강세장", reading: "คังเซจัง", lang: "ko-KR" },
    { thai: "ตลาดหมี (ขาลง)", target: "약세장", reading: "ยักเซจัง", lang: "ko-KR" },
    { thai: "หุ้นส่วน", target: "파트너", reading: "พาทือนอ", lang: "ko-KR" },
    { thai: "เจ้าของ", target: "소유자", reading: "โซยูจา", lang: "ko-KR" },
    { thai: "นักลงทุน", target: "투자자", reading: "ทูจาจา", lang: "ko-KR" },
    { thai: "มูลค่า", target: "가치", reading: "คาชี", lang: "ko-KR" },
    { thai: "ราคา", target: "가격", reading: "คากย็อก", lang: "ko-KR" },
    { thai: "โบรกเกอร์ (นายหน้า)", target: "중개인", reading: "ชุงแกอิน", lang: "ko-KR" },
    { thai: "ค่าธรรมเนียม", target: "수수료", reading: "ซูซูรโย", lang: "ko-KR" },
    { thai: "ความผันผวน", target: "변동성", reading: "พยอนดงซอง", lang: "ko-KR" },
    { thai: "ส่วนแบ่ง / หุ้น", target: "지분 / 주식", reading: "ชีบุน / ชูชิก", lang: "ko-KR" },
    { thai: "สภาพคล่อง", target: "유동성", reading: "ยูดงซอง", lang: "ko-KR" },
    { thai: "ดัชนี", target: "지수", reading: "ชีซู", lang: "ko-KR" },
    { thai: "แนวโน้ม", target: "추세", reading: "ชูเซ", lang: "ko-KR" },
    { thai: "ความมั่งคั่ง", target: "부", reading: "พู", lang: "ko-KR" },
    { thai: "ความเสี่ยง", target: "위험", reading: "วีฮอม", lang: "ko-KR" },

    // --- 21. หมวดกลยุทธ์ การแข่งขัน และเกมมิ่ง (Strategy & Gaming) - 30 คำ ---
    { thai: "กลยุทธ์", target: "전략", reading: "ช็อลลยัก", lang: "ko-KR" },
    { thai: "ยุทธวิธี", target: "전술", reading: "ช็อนซุล", lang: "ko-KR" },
    { thai: "เกม", target: "게임", reading: "เคอิม", lang: "ko-KR" },
    { thai: "การแข่งขัน", target: "경기 / 시합", reading: "คยองกี / ชีฮับ", lang: "ko-KR" },
    { thai: "การต่อสู้", target: "전투", reading: "ช็อนทู", lang: "ko-KR" },
    { thai: "คู่แข่ง / ศัตรู", target: "적", reading: "ช็อก", lang: "ko-KR" },
    { thai: "คู่ปรับ", target: "라이벌", reading: "ราอีบ็อล", lang: "ko-KR" },
    { thai: "ตัวละคร", target: "캐릭터", reading: "แคริกทอ", lang: "ko-KR" },
    { thai: "ระดับ / เลเวล", target: "레벨", reading: "เรเบล", lang: "ko-KR" },
    { thai: "สถิติ / ค่าพลัง", target: "능력치", reading: "นึงนย็อกชี", lang: "ko-KR" },
    { thai: "พลังชีวิต (HP)", target: "체력", reading: "เชรย็อก", lang: "ko-KR" },
    { thai: "โจมตี", target: "공격", reading: "คงกย็อก", lang: "ko-KR" },
    { thai: "ป้องกัน", target: "방어", reading: "พังงอ", lang: "ko-KR" },
    { thai: "ความเร็ว", target: "속도", reading: "ซกโด", lang: "ko-KR" },
    { thai: "ไอเทม / สิ่งของ", target: "아이템", reading: "อาอีเท็ม", lang: "ko-KR" },
    { thai: "สวมใส่", target: "장착하다", reading: "ชังชักฮาดา", lang: "ko-KR" },
    { thai: "วิวัฒนาการ", target: "진화", reading: "ชินฮวา", lang: "ko-KR" },
    { thai: "เพาะพันธุ์", target: "번식", reading: "พ็อนชิก", lang: "ko-KR" },
    { thai: "ธรรมชาติ / นิสัย", target: "성격", reading: "ซองกย็อก", lang: "ko-KR" },
    { thai: "ความสามารถ", target: "능력", reading: "นึงนย็อก", lang: "ko-KR" },
    { thai: "ท่าต่อสู้ / การเคลื่อนไหว", target: "기술", reading: "คีซุล", lang: "ko-KR" },
    { thai: "ตา / รอบ (การเล่น)", target: "턴", reading: "ท็อน", lang: "ko-KR" },
    { thai: "ชนะ", target: "이기다", reading: "อีกีดา", lang: "ko-KR" },
    { thai: "แพ้", target: "지다", reading: "ชีดา", lang: "ko-KR" },
    { thai: "เสมอ", target: "무승부", reading: "มูซึงบู", lang: "ko-KR" },
    { thai: "การฝึกฝน", target: "훈련", reading: "ฮุลลย็อน", lang: "ko-KR" },
    { thai: "คะแนน", target: "점수", reading: "ช็อมซู", lang: "ko-KR" },
    { thai: "แชมป์", target: "챔피언", reading: "แชมพีออน", lang: "ko-KR" },
    { thai: "ทัวร์นาเมนต์", target: "토너먼트", reading: "โทนอม็อนทือ", lang: "ko-KR" },
    { thai: "ความเสียหาย", target: "데미지 / 피해", reading: "เทมีจี / พีแฮ", lang: "ko-KR" },

    // --- 22. หมวดอารมณ์และความรู้สึก (Emotions & Feelings) - 20 คำ ---
    { thai: "ความรัก", target: "사랑", reading: "ซารัง", lang: "ko-KR" },
    { thai: "ความเกลียดชัง", target: "증오", reading: "ชึงโอ", lang: "ko-KR" },
    { thai: "ความกลัว", target: "공포 / 두려움", reading: "คงโพ / ทูรยออุม", lang: "ko-KR" },
    { thai: "ความประหลาดใจ", target: "놀람", reading: "นลลัม", lang: "ko-KR" },
    { thai: "ความตกใจ", target: "충격", reading: "ชุงกย็อก", lang: "ko-KR" },
    { thai: "ความตื่นเต้น", target: "흥분", reading: "ฮึงบุน", lang: "ko-KR" },
    { thai: "ความเบื่อหน่าย", target: "지루함", reading: "ชีรูฮัม", lang: "ko-KR" },
    { thai: "ความสับสน", target: "혼란", reading: "ฮลลัน", lang: "ko-KR" },
    { thai: "ความหวัง", target: "희망", reading: "ฮีมัง", lang: "ko-KR" },
    { thai: "ความสุข / ความปีติ", target: "기쁨", reading: "คีปึม", lang: "ko-KR" },
    { thai: "ความเศร้า", target: "슬픔", reading: "ซึลพึม", lang: "ko-KR" },
    { thai: "ความเครียด", target: "스트레스", reading: "ซือทือเรซือ", lang: "ko-KR" },
    { thai: "ผ่อนคลาย", target: "편안함", reading: "พยอนันฮัม", lang: "ko-KR" },
    { thai: "ความกังวล", target: "걱정", reading: "ค็อกจอง", lang: "ko-KR" },
    { thai: "ความภาคภูมิใจ", target: "자부심", reading: "ชาบูชิม", lang: "ko-KR" },
    { thai: "ความอิจฉา", target: "질투", reading: "ชิลทู", lang: "ko-KR" },
    { thai: "ความเห็นอกเห็นใจ", target: "동정", reading: "ทงจอง", lang: "ko-KR" },
    { thai: "ความรู้สึกผิด", target: "죄책감", reading: "ชเวแช็กกัม", lang: "ko-KR" },
    { thai: "ความมั่นใจ", target: "자신감", reading: "ชาชินกัม", lang: "ko-KR" },
    { thai: "ความสงสัย", target: "의심", reading: "อึยชิม", lang: "ko-KR" },

    // --- 23. หมวดสภาพอากาศและฤดูกาล (Weather & Seasons) - 20 คำ ---
    { thai: "สภาพอากาศ", target: "날씨", reading: "นัลชี", lang: "ko-KR" },
    { thai: "ฤดูกาล", target: "계절", reading: "คเยจ็อล", lang: "ko-KR" },
    { thai: "ฤดูร้อน", target: "여름", reading: "ยอรึม", lang: "ko-KR" },
    { thai: "ฤดูหนาว", target: "겨울", reading: "คยออุล", lang: "ko-KR" },
    { thai: "ฤดูใบไม้ผลิ", target: "봄", reading: "พม", lang: "ko-KR" },
    { thai: "ฤดูใบไม้ร่วง", target: "가을", reading: "คาอึล", lang: "ko-KR" },
    { thai: "อุณหภูมิ", target: "온도", reading: "อนโด", lang: "ko-KR" },
    { thai: "องศา", target: "도", reading: "โท", lang: "ko-KR" },
    { thai: "แดดออก", target: "화창한", reading: "ฮวาชังฮัน", lang: "ko-KR" },
    { thai: "มีเมฆมาก", target: "흐린", reading: "ฮือริน", lang: "ko-KR" },
    { thai: "ฝนตก", target: "비가 오는", reading: "พีกา โอนึน", lang: "ko-KR" },
    { thai: "พายุ", target: "폭풍", reading: "พกพุง", lang: "ko-KR" },
    { thai: "ฟ้าแลบ", target: "번개", reading: "พ็อนแก", lang: "ko-KR" },
    { thai: "ฟ้าร้อง", target: "천둥", reading: "ช็อนดุง", lang: "ko-KR" },
    { thai: "มีหมอก", target: "안개가 낀", reading: "อันแกกา กิน", lang: "ko-KR" },
    { thai: "น้ำแข็ง", target: "얼음", reading: "ออรึม", lang: "ko-KR" },
    { thai: "ละลาย", target: "녹다", reading: "นกตา", lang: "ko-KR" },
    { thai: "แช่แข็ง", target: "얼다", reading: "ออลดา", lang: "ko-KR" },
    { thai: "พยากรณ์", target: "예보", reading: "เยโบ", lang: "ko-KR" },
    { thai: "ร่ม", target: "우산", reading: "อูซาน", lang: "ko-KR" },

    // --- 24. หมวดงานอดิเรกและความบันเทิง (Hobbies & Entertainment) - 30 คำ ---
    { thai: "งานอดิเรก", target: "취미", reading: "ชวีมี", lang: "ko-KR" },
    { thai: "ดนตรี", target: "음악", reading: "อึมมัก", lang: "ko-KR" },
    { thai: "เพลง", target: "노래", reading: "โนแร", lang: "ko-KR" },
    { thai: "ภาพยนตร์", target: "영화", reading: "ยองฮวา", lang: "ko-KR" },
    { thai: "โรงภาพยนตร์", target: "영화관", reading: "ยองฮวากวัน", lang: "ko-KR" },
    { thai: "ศิลปะ", target: "예술", reading: "เยซุล", lang: "ko-KR" },
    { thai: "การวาดภาพ (เส้น)", target: "소묘 / 그리기", reading: "โซมโย / คือรีกี", lang: "ko-KR" },
    { thai: "การทาสี / ภาพจิตรกรรม", target: "그림", reading: "คือริม", lang: "ko-KR" },
    { thai: "การเต้น", target: "춤", reading: "ชุม", lang: "ko-KR" },
    { thai: "การถ่ายภาพ", target: "사진 촬영", reading: "ซาจิน ชวัลยอง", lang: "ko-KR" },
    { thai: "กล้อง", target: "카메라", reading: "คาเมรา", lang: "ko-KR" },
    { thai: "กีฬา", target: "스포츠", reading: "ซือโพชือ", lang: "ko-KR" },
    { thai: "ฟุตบอล", target: "축구", reading: "ชุกกู", lang: "ko-KR" },
    { thai: "บาสเกตบอล", target: "농구", reading: "นงกู", lang: "ko-KR" },
    { thai: "ว่ายน้ำ", target: "수영", reading: "ซูยอง", lang: "ko-KR" },
    { thai: "วิ่ง", target: "달리기", reading: "ทัลลีกี", lang: "ko-KR" },
    { thai: "การอ่าน", target: "독서", reading: "ทกซอ", lang: "ko-KR" },
    { thai: "นวนิยาย", target: "소설", reading: "โซซ็อล", lang: "ko-KR" },
    { thai: "หนังสือการ์ตูน", target: "만화", reading: "มันฮวา", lang: "ko-KR" },
    { thai: "เกม", target: "게임", reading: "เคอิม", lang: "ko-KR" },
    { thai: "เครื่องเล่นเกม", target: "게임기", reading: "เคอิมกี", lang: "ko-KR" },
    { thai: "ปริศนา", target: "퍼즐", reading: "พอจึล", lang: "ko-KR" },
    { thai: "ของเล่น", target: "장난감", reading: "ชังนันกัม", lang: "ko-KR" },
    { thai: "ปาร์ตี้ / งานเลี้ยง", target: "파티", reading: "พาที", lang: "ko-KR" },
    { thai: "เทศกาล", target: "축제", reading: "ชุกเจ", lang: "ko-KR" },
    { thai: "คอนเสิร์ต", target: "콘서트", reading: "คนซอทือ", lang: "ko-KR" },
    { thai: "ตั๋ว", target: "표 / 티켓", reading: "พโย / ทีเค็ด", lang: "ko-KR" },
    { thai: "มายากล / เวทมนตร์", target: "마술", reading: "มาซุล", lang: "ko-KR" },
    { thai: "ของสะสม", target: "수집품", reading: "ซูจิบพุม", lang: "ko-KR" },
    { thai: "กีตาร์", target: "기타", reading: "คีทา", lang: "ko-KR" },

    // --- 25. หมวดแนวคิดนามธรรมและทิศทาง (Abstract Concepts & Directions) - 30 คำ ---
    { thai: "ความคิด / ไอเดีย", target: "생각 / 아이디어", reading: "แซงกัก / อาอีดีออ", lang: "ko-KR" },
    { thai: "ความจริง", target: "진실", reading: "ชินชิล", lang: "ko-KR" },
    { thai: "คำโกหก", target: "거짓말", reading: "คอจินมัล", lang: "ko-KR" },
    { thai: "เหตุผล", target: "이유", reading: "อียู", lang: "ko-KR" },
    { thai: "จุดประสงค์", target: "목적", reading: "มกจ็อก", lang: "ko-KR" },
    { thai: "วิธีการ", target: "방법", reading: "พังบ็อบ", lang: "ko-KR" },
    { thai: "ผลลัพธ์", target: "결과", reading: "คย็อลกวา", lang: "ko-KR" },
    { thai: "ผลกระทบ", target: "영향", reading: "ยองฮยัง", lang: "ko-KR" },
    { thai: "สาเหตุ", target: "원인", reading: "วอนิน", lang: "ko-KR" },
    { thai: "ประวัติศาสตร์", target: "역사", reading: "ย็อกซา", lang: "ko-KR" },
    { thai: "กฎ / กติกา", target: "규칙", reading: "คยูชิก", lang: "ko-KR" },
    { thai: "กฎหมาย", target: "법", reading: "พ็อบ", lang: "ko-KR" },
    { thai: "ความยุติธรรม", target: "정의", reading: "ชองอึย", lang: "ko-KR" },
    { thai: "อิสรภาพ", target: "자유", reading: "ชายู", lang: "ko-KR" },
    { thai: "สัญลักษณ์", target: "상징", reading: "ซังจิง", lang: "ko-KR" },
    { thai: "รูปร่าง", target: "모양", reading: "โมยัง", lang: "ko-KR" },
    { thai: "วงกลม", target: "원", reading: "วอน", lang: "ko-KR" },
    { thai: "สี่เหลี่ยม", target: "정사각형", reading: "ชองซากักฮยอง", lang: "ko-KR" },
    { thai: "สามเหลี่ยม", target: "삼각형", reading: "ซัมกักฮยอง", lang: "ko-KR" },
    { thai: "ขนาด", target: "크기", reading: "คือกี", lang: "ko-KR" },
    { thai: "พื้นที่ว่าง / อวกาศ", target: "공간 / 우주", reading: "คงกัน / อูจู", lang: "ko-KR" },
    { thai: "ระยะทาง", target: "거리", reading: "คอรี", lang: "ko-KR" },
    { thai: "พื้นที่ (ตาราง)", target: "면적", reading: "มย็อนจ็อก", lang: "ko-KR" },
    { thai: "ทิศทาง", target: "방향", reading: "พังฮยัง", lang: "ko-KR" },
    { thai: "ตำแหน่ง", target: "위치", reading: "วีชี", lang: "ko-KR" },
    { thai: "ด้านบน", target: "위", reading: "วี", lang: "ko-KR" },
    { thai: "ด้านล่าง", target: "아래", reading: "อาแร", lang: "ko-KR" },
    { thai: "ตรงกลาง", target: "중간", reading: "ชุงกัน", lang: "ko-KR" },
    { thai: "ด้านหน้า", target: "앞", reading: "อับ", lang: "ko-KR" },
    { thai: "ด้านหลัง", target: "뒤", reading: "ทวี", lang: "ko-KR" },
	, // --- 26. หมวดสัตว์ (Animals) - 30 คำ ---
    { thai: "สิงโต", target: "사자", reading: "ซาจา", lang: "ko-KR" },
    { thai: "เสือ", target: "호랑이", reading: "โฮรังงี", lang: "ko-KR" },
    { thai: "ช้าง", target: "코끼리", reading: "โคกีรี", lang: "ko-KR" },
    { thai: "หมี", target: "곰", reading: "คม", lang: "ko-KR" },
    { thai: "ลิง", target: "원숭이", reading: "วอนซุงงี", lang: "ko-KR" },
    { thai: "งู", target: "뱀", reading: "แพม", lang: "ko-KR" },
    { thai: "ม้า", target: "말", reading: "มัล", lang: "ko-KR" },
    { thai: "วัว", target: "소", reading: "โซ", lang: "ko-KR" },
    { thai: "หมู", target: "돼지", reading: "ทแวจี", lang: "ko-KR" },
    { thai: "แกะ", target: "양", reading: "ยัง", lang: "ko-KR" },
    { thai: "แพะ", target: "염소", reading: "ย็อมโซ", lang: "ko-KR" },
    { thai: "เป็ด", target: "오리", reading: "โอรี", lang: "ko-KR" },
    { thai: "หนู", target: "쥐", reading: "ชวี", lang: "ko-KR" },
    { thai: "กระต่าย", target: "토끼", reading: "โทกี", lang: "ko-KR" },
    { thai: "เต่า", target: "거북이", reading: "คอบูกี", lang: "ko-KR" },
    { thai: "กบ", target: "개구리", reading: "แคกูรี", lang: "ko-KR" },
    { thai: "แมงมุม", target: "거미", reading: "คอมี", lang: "ko-KR" },
    { thai: "แมลง", target: "곤충", reading: "คนชุง", lang: "ko-KR" },
    { thai: "ผึ้ง", target: "벌", reading: "พ็อล", lang: "ko-KR" },
    { thai: "ผีเสื้อ", target: "나비", reading: "นาบี", lang: "ko-KR" },
    { thai: "มด", target: "개미", reading: "แคมี", lang: "ko-KR" },
    { thai: "แมลงวัน", target: "파리", reading: "พารี", lang: "ko-KR" },
    { thai: "ยุง", target: "모기", reading: "โมกี", lang: "ko-KR" },
    { thai: "โลมา", target: "돌고래", reading: "ทลโกแร", lang: "ko-KR" },
    { thai: "วาฬ", target: "고래", reading: "โคแร", lang: "ko-KR" },
    { thai: "ฉลาม", target: "상어", reading: "ซังงอ", lang: "ko-KR" },
    { thai: "เพนกวิน", target: "펭귄", reading: "เพ็งกวิน", lang: "ko-KR" },
    { thai: "จิงโจ้", target: "캥거루", reading: "แค็งกอรู", lang: "ko-KR" },
    { thai: "หมาป่า", target: "늑대", reading: "นึกแด", lang: "ko-KR" },
    { thai: "จระเข้", target: "악어", reading: "อากอ", lang: "ko-KR" },

    // --- 27. หมวดเครื่องแต่งกายและเครื่องประดับ (Clothing & Accessories) - 30 คำ ---
    { thai: "เสื้อเชิ้ต", target: "셔츠", reading: "ชยอชือ", lang: "ko-KR" },
    { thai: "เสื้อยืด", target: "티셔츠", reading: "ทีชยอชือ", lang: "ko-KR" },
    { thai: "กางเกงขายาว", target: "바지", reading: "พาจี", lang: "ko-KR" },
    { thai: "กางเกงยีนส์", target: "청바지", reading: "ชองบาจี", lang: "ko-KR" },
    { thai: "กางเกงขาสั้น", target: "반바지", reading: "พัน바จี", lang: "ko-KR" },
    { thai: "กระโปรง", target: "치마", reading: "ชีมา", lang: "ko-KR" },
    { thai: "ชุดเดรส", target: "원피스", reading: "วอนพีซือ", lang: "ko-KR" },
    { thai: "ชุดสูท", target: "정장", reading: "ชองจัง", lang: "ko-KR" },
    { thai: "เสื้อแจ็คเก็ต", target: "재킷", reading: "แจคิต", lang: "ko-KR" },
    { thai: "เสื้อโค้ต", target: "코트", reading: "โคทือ", lang: "ko-KR" },
    { thai: "เสื้อกันหนาว", target: "스웨터", reading: "ซือเวทอ", lang: "ko-KR" },
    { thai: "หมวก (มีปีกรอบ)", target: "모자", reading: "โมจา", lang: "ko-KR" },
    { thai: "หมวกแก๊ป", target: "캡", reading: "แค็บ", lang: "ko-KR" },
    { thai: "ถุงเท้า", target: "양말", reading: "ยังมัล", lang: "ko-KR" },
    { thai: "รองเท้าบูท", target: "부츠", reading: "พูชือ", lang: "ko-KR" },
    { thai: "รองเท้าผ้าใบ", target: "운동화", reading: "อุนดงฮวา", lang: "ko-KR" },
    { thai: "เข็มขัด", target: "벨트", reading: "เพลทือ", lang: "ko-KR" },
    { thai: "เนคไท", target: "넥타이", reading: "เน็กทาอี", lang: "ko-KR" },
    { thai: "ผ้าพันคอ", target: "스카프", reading: "ซือ카พือ", lang: "ko-KR" },
    { thai: "ถุงมือ", target: "장갑", reading: "ชังกับ", lang: "ko-KR" },
    { thai: "ชุดชั้นใน", target: "속옷", reading: "ซกอด", lang: "ko-KR" },
    { thai: "แหวน", target: "반지", reading: "พันจี", lang: "ko-KR" },
    { thai: "สร้อยคอ", target: "목걸이", reading: "มกกอลี", lang: "ko-KR" },
    { thai: "สร้อยข้อมือ", target: "팔찌", reading: "พัลจี", lang: "ko-KR" },
    { thai: "ต่างหู", target: "귀걸이", reading: "ควีกอลี", lang: "ko-KR" },
    { thai: "กระเป๋าสตางค์", target: "지갑", reading: "ชี갑", lang: "ko-KR" },
    { thai: "กระเป๋าถือ (ผู้หญิง)", target: "핸드백", reading: "แฮนดือแบ็ก", lang: "ko-KR" },
    { thai: "กระเป๋าเป้", target: "배낭", reading: "แพนัง", lang: "ko-KR" },
    { thai: "เครื่องแบบ", target: "유니폼", reading: "ยู니폼", lang: "ko-KR" },
    { thai: "กระเป๋าเสื้อ/กางเกง", target: "주머니", reading: "ชูมอนี", lang: "ko-KR" },

    // --- 28. หมวดการศึกษาและโรงเรียน (Education & School) - 40 คำ ---
    { thai: "การศึกษา", target: "교육", reading: "คโยยุก", lang: "ko-KR" },
    { thai: "มหาวิทยาลัย", target: "대학교", reading: "แทฮักกโย", lang: "ko-KR" },
    { thai: "วิทยาลัย", target: "대학", reading: "แทฮัก", lang: "ko-KR" },
    { thai: "นักเรียน / นักศึกษา", target: "학생", reading: "ฮักแซง", lang: "ko-KR" },
    { thai: "ชั้นเรียน", target: "반 / 수업", reading: "พัน / ซูออบ", lang: "ko-KR" },
    { thai: "ห้องเรียน", target: "교실", reading: "คโยชิล", lang: "ko-KR" },
    { thai: "วิชา", target: "과목", reading: "ความก", lang: "ko-KR" },
    { thai: "คณิตศาสตร์", target: "수학", reading: "ซูฮัก", lang: "ko-KR" },
    { thai: "วิทยาศาสตร์", target: "과학", reading: "ควาฮัก", lang: "ko-KR" },
    { thai: "ภูมิศาสตร์", target: "지리학", reading: "ชีรีฮัก", lang: "ko-KR" },
    { thai: "ภาษา", target: "언어", reading: "ออนอ", lang: "ko-KR" },
    { thai: "ภาษาอังกฤษ", target: "영어", reading: "ยองออ", lang: "ko-KR" },
    { thai: "การทดสอบ", target: "테스트", reading: "เทซือทือ", lang: "ko-KR" },
    { thai: "การสอบ (ทางการ)", target: "시험", reading: "ชีฮอม", lang: "ko-KR" },
    { thai: "แบบทดสอบย่อย", target: "퀴즈", reading: "ควิจือ", lang: "ko-KR" },
    { thai: "การบ้าน", target: "숙제", reading: "ซุกเจ", lang: "ko-KR" },
    { thai: "ระดับชั้น / เกรด", target: "학년 / 성적", reading: "ฮักนยอน / ซองจ็อก", lang: "ko-KR" },
    { thai: "ปริญญา", target: "학위", reading: "ฮากวี", lang: "ko-KR" },
    { thai: "ผู้สำเร็จการศึกษา", target: "졸업생", reading: "ชลลอบแซง", lang: "ko-KR" },
    { thai: "ประกาศนียบัตร", target: "졸업장", reading: "ชลลอบ장", lang: "ko-KR" },
    { thai: "ทุนการศึกษา", target: "장학금", reading: "ชังฮักกึม", lang: "ko-KR" },
    { thai: "บทเรียน", target: "수업 / 교훈", reading: "ซูออบ / คโยฮุน", lang: "ko-KR" },
    { thai: "บท", target: "장", reading: "ชัง", lang: "ko-KR" },
    { thai: "หน้า (หนังสือ)", target: "페이지", reading: "เพอีจี", lang: "ko-KR" },
    { thai: "คำถาม", target: "질문", reading: "ชิลมุน", lang: "ko-KR" },
    { thai: "คำตอบ", target: "대답", reading: "แทดับ", lang: "ko-KR" },
    { thai: "ตัวอย่าง", target: "예 / 예시", reading: "เย / เยชี", lang: "ko-KR" },
    { thai: "พจนานุกรม", target: "사전", reading: "ซาจอน", lang: "ko-KR" },
    { thai: "คำศัพท์", target: "어휘", reading: "ออฮวี", lang: "ko-KR" },
    { thai: "ไวยากรณ์", target: "문법", reading: "มุนบ็อบ", lang: "ko-KR" },
    { thai: "ดินสอ", target: "연필", reading: "ยอนพิล", lang: "ko-KR" },
    { thai: "ยางลบ", target: "지우개", reading: "ชีอูแก", lang: "ko-KR" },
    { thai: "ไม้บรรทัด", target: "자", reading: "จา", lang: "ko-KR" },
    { thai: "กระดานดำ", target: "칠판", reading: "ชิลพัน", lang: "ko-KR" },
    { thai: "กระดานไวท์บอร์ด", target: "화이트보드", reading: "ฮวาอีทือ보드", lang: "ko-KR" },
    { thai: "สมุดจด", target: "공책", reading: "คงแช็ก", lang: "ko-KR" },
    { thai: "โต๊ะเรียน", target: "책상", reading: "แช็กซัง", lang: "ko-KR" },
    { thai: "ภาคเรียน", target: "학기", reading: "ฮักกี", lang: "ko-KR" },
    { thai: "ภาคการศึกษา", target: "학기", reading: "ฮักกี", lang: "ko-KR" },
    { thai: "เวลาพัก", 초target: "쉬는 시간", reading: "ชวีนึน ชีกัน", lang: "ko-KR" },

    // --- 29. หมวดการเดินทางในเมืองและสถานที่สาธารณะ (City Life & Commute) - 30 คำ ---
    { thai: "ถนน", target: "거리 / 길", reading: "คอรี / คิล", lang: "ko-KR" },
    { thai: "ถนนใหญ่ / อเวนิว", target: "대로", reading: "대로", lang: "ko-KR" },
    { thai: "ทางหลวง", target: "고속도로", reading: "โคซกด도로", lang: "ko-KR" },
    { thai: "การจราจร", target: "교통", reading: "คโยทง", lang: "ko-KR" },
    { thai: "ไฟจราจร", target: "신호등", reading: "ชินโฮดึง", lang: "ko-KR" },
    { thai: "ทางเท้า", target: "인도", reading: "อินโด", lang: "ko-KR" },
    { thai: "ทางม้าลาย", target: "횡단보도", reading: "ฮเวงดันโบโด", lang: "ko-KR" },
    { thai: "รถไฟใต้ดิน", target: "지하철", reading: "ชีฮาชอล", lang: "ko-KR" },
    { thai: "ชานชาลา", target: "승강장", reading: "ซึงกังจัง", lang: "ko-KR" },
    { thai: "ผู้โดยสาร", target: "승객", reading: "ซึงแก็ก", lang: "ko-KR" },
    { thai: "การเดินทาง (ระยะไกล)", target: "여행", reading: "ยอแฮง", lang: "ko-KR" },
    { thai: "การเดินทาง (ระยะสั้น)", target: "여정", reading: "ยอจอง", lang: "ko-KR" },
    { thai: "การท่องเที่ยว", target: "관광", reading: "ควันกวัง", lang: "ko-KR" },
    { thai: "คนนำทาง / มัคคุเทศก์", target: "가이드", reading: "คาอีดือ", lang: "ko-KR" },
    { thai: "เส้นทาง", target: "경로", reading: "คยองโร", lang: "ko-KR" },
    { thai: "ค่าโดยสาร", target: "요금", reading: "โยกึม", lang: "ko-KR" },
    { thai: "คิว / แถว", target: "줄", reading: "จุล", lang: "ko-KR" },
    { thai: "ความล่าช้า", target: "지연", reading: "ชียอน", lang: "ko-KR" },
    { thai: "อุบัติเหตุ", target: "사고", reading: "ซาโก", lang: "ko-KR" },
    { thai: "อันตราย (คำนาม)", target: "위험", reading: "วีฮอม", lang: "ko-KR" },
    { thai: "ความปลอดภัย", target: "안전", reading: "อันจอน", lang: "ko-KR" },
    { thai: "ฝูงชน", target: "군중", reading: "คุนจุง", lang: "ko-KR" },
    { thai: "อาคาร", target: "건물", reading: "กอนมุล", lang: "ko-KR" },
    { thai: "ตึกระฟ้า", target: "마천루", reading: "มาชอนรู", lang: "ko-KR" },
    { thai: "อพาร์ตเมนต์", target: "아파트", reading: "อาพาทือ", lang: "ko-KR" },
    { thai: "ละแวกบ้าน", target: "이웃 / 동네", reading: "อีอุด / ทงเน", lang: "ko-KR" },
    { thai: "เมืองหลวง", target: "수도", reading: "ซูโด", lang: "ko-KR" },
    { thai: "อนุสาวรีย์", target: "기념비", reading: "คีนยอมบี", lang: "ko-KR" },
    { thai: "พิพิธภัณฑ์", target: "박물관", reading: "พังมุลกวัน", lang: "ko-KR" },
    { thai: "สวนสัตว์", target: "동물원", reading: "ทงมูรวอน", lang: "ko-KR" },

    // --- 30. หมวดเครื่องมือ วัสดุ และคุณลักษณะทางกายภาพ (Tools, Materials & Shapes) - 35 คำ ---
    { thai: "เครื่องมือ", target: "도구", reading: "โทกู", lang: "ko-KR" },
    { thai: "ค้อน", target: "망치", reading: "มังชี", lang: "ko-KR" },
    { thai: "ตะปู", target: "못", 초reading: "มด", lang: "ko-KR" },
    { thai: "สกรู", target: "나사", reading: "นาซา", lang: "ko-KR" },
    { thai: "ประแจ", target: "렌치", reading: "เรนชี", lang: "ko-KR" },
    { thai: "กรรไกร", target: "가위", reading: "คาวี", lang: "ko-KR" },
    { thai: "มีด", target: "칼", reading: "คัล", lang: "ko-KR" },
    { thai: "ใบมีด", target: "칼날", reading: "คัลนัล", lang: "ko-KR" },
    { thai: "เครื่องจักร", target: "기계", reading: "คีคเย", lang: "ko-KR" },
    { thai: "เครื่องยนต์", target: "엔진", reading: "เอนจิน", lang: "ko-KR" },
    { thai: "มอเตอร์", target: "모터", reading: "โมทอ", lang: "ko-KR" },
    { thai: "วัสดุ", target: "재료", reading: "แชรโย", lang: "ko-KR" },
    { thai: "ไม้", target: "나무 / 목재", reading: "นามู / มกแจ", lang: "ko-KR" },
    { thai: "โลหะ", target: "금속", reading: "คึมซก", lang: "ko-KR" },
    { thai: "เหล็ก", target: "철", reading: "ชอล", lang: "ko-KR" },
    { thai: "เหล็กกล้า", target: "강철", reading: "คังชอล", lang: "ko-KR" },
    { thai: "ทองแดง", target: "구리", reading: "คูรี", lang: "ko-KR" },
    { thai: "พลาสติก", target: "플라스틱", reading: "พึลลาซือทิก", lang: "ko-KR" },
    { thai: "ยาง", target: "고무", reading: "โคมู", lang: "ko-KR" },
    { thai: "ฝ้าย", target: "면", reading: "มยอน", lang: "ko-KR" },
    { thai: "หนัง (วัสดุ)", target: "가죽", reading: "คาจุก", lang: "ko-KR" },
    { thai: "กระดาษแข็ง", target: "판지 / 골판지", reading: "พันจี / คล판จี", lang: "ko-KR" },
    { thai: "เชือกหนา", target: "밧줄", reading: "พัดจุล", lang: "ko-KR" },
    { thai: "ลวด / สายไฟ", target: "전선 / 철사", reading: "ชอนซอน / ชอลซา", lang: "ko-KR" },
    { thai: "เส้น", target: "선", reading: "ซอน", lang: "ko-KR" },
    { thai: "ส่วนโค้ง", target: "곡선", reading: "คกซอน", lang: "ko-KR" },
    { thai: "มุม", target: "각도", reading: "คักโด", lang: "ko-KR" },
    { thai: "กลม", target: "둥근", reading: "ทุงกึน", lang: "ko-KR" },
    { thai: "แบน", target: "납작한", reading: "นับจักฮัน", lang: "ko-KR" },
    { thai: "แหลม / คม", target: "날카로운", reading: "นัลคา로운", lang: "ko-KR" },
    { thai: "เรียบ / ลื่น", target: "매끄러운", reading: "แมกือ로운", lang: "ko-KR" },
    { thai: "ขรุขระ", target: "거친", reading: "คอชิน", lang: "ko-KR" },
    { thai: "นุ่ม", target: "부드러운", reading: "พูดือ로운", lang: "ko-KR" },
    { thai: "แข็ง (วัสดุ)", target: "단단한", reading: "ทัน단ฮัน", lang: "ko-KR" },
    { thai: "ของแข็ง", target: "고체", reading: "โคเช", lang: "ko-KR" },

    // --- 31. หมวดสังคม การปกครอง และกระบวนการยุติธรรม (Society, Government & Justice) - 35 คำ ---
    { thai: "สังคม", target: "사회", reading: "ซาฮเว", lang: "ko-KR" },
    { thai: "วัฒนธรรม", target: "문화", reading: "มุนฮวา", lang: "ko-KR" },
    { thai: "ประเพณี", target: "전통", reading: "ชอนทง", lang: "ko-KR" },
    { thai: "รัฐบาล", target: "정부", reading: "ชองบู", lang: "ko-KR" },
    { thai: "การเมือง", target: "정치", reading: "ชองชี", lang: "ko-KR" },
    { thai: "การเลือกตั้ง", target: "선거", reading: "ซอนกอ", lang: "ko-KR" },
    { thai: "ลงคะแนนเสียง", target: "투표", reading: "ทูพโย", lang: "ko-KR" },
    { thai: "ประธานาธิบดี / ประธาน", target: "대통령", reading: "แททงนยอง", lang: "ko-KR" },
    { thai: "ผู้นำ", target: "지도자", reading: "ชีโดจา", lang: "ko-KR" },
    { thai: "พลเมือง", target: "시민", reading: "시มิน", lang: "ko-KR" },
    { thai: "ชาติ / ประเทศ", target: "국가 / 나라", reading: "กุกกา / นารา", lang: "ko-KR" },
    { thai: "ชุมชน", target: "지역사회", reading: "ชียอกซาฮเว", lang: "ko-KR" },
    { thai: "นโยบาย", target: "정책", reading: "ชองแช็ก", lang: "ko-KR" },
    { thai: "ข้อบังคับ / ระเบียบ", target: "규정 / 규칙", reading: "คยูจอง / คยูชิก", lang: "ko-KR" },
    { thai: "สิทธิ", target: "권리", reading: "ควอลลี", lang: "ko-KR" },
    { thai: "หน้าที่", target: "의무", reading: "อึยมู", lang: "ko-KR" },
    { thai: "ศาล", target: "법원", reading: "พอบวอน", lang: "ko-KR" },
    { thai: "ผู้พิพากษา", target: "판사", reading: "พันซา", lang: "ko-KR" },
    { thai: "ทนายความ", target: "변호사", reading: "พยอนโฮซา", lang: "ko-KR" },
    { thai: "เจ้าหน้าที่", target: "경찰관", reading: "คยองชัลกวัน", lang: "ko-KR" },
    { thai: "อาชญากรรม", target: "범죄", reading: "พอมจเว", lang: "ko-KR" },
    { thai: "อาชญากร", target: "범죄자", reading: "พอมจเวจา", lang: "ko-KR" },
    { thai: "คุก / เรือนจำ", target: "감옥", reading: "คามก", lang: "ko-KR" },
    { thai: "ขโมย (คน)", target: "도둑", reading: "โทดุก", lang: "ko-KR" },
    { thai: "การป้องกัน", target: "보호", reading: "โพโฮ", lang: "ko-KR" },
    { thai: "สันติภาพ", target: "평화", reading: "พยองฮวา", lang: "ko-KR" },
    { thai: "สงคราม", target: "전쟁", reading: "ชอนแจง", lang: "ko-KR" },
    { thai: "กองทัพบก", target: "군대", reading: "คุนแด", lang: "ko-KR" },
    { thai: "อาวุธ", target: "무기", reading: "มูกี", lang: "ko-KR" },
    { thai: "ปืน", target: "총", reading: "ชง", lang: "ko-KR" },
    { thai: "ประชากร", target: "인구", reading: "อินกู", lang: "ko-KR" },
    { thai: "ชายแดน", target: "국경", reading: "กุกกยอง", lang: "ko-KR" },
    { thai: "ธง", target: "국기", reading: "กุกกี", lang: "ko-KR" },
    { thai: "สาธารณะ", target: "공공의", reading: "คงกง의", lang: "ko-KR" },
    { thai: "ส่วนตัว", target: "개인의", reading: "캐อิน의", lang: "ko-KR" },

    // --- 32. หมวดคำบุพบทและคำเชื่อมประโยค (Prepositions & Conjunctions) - 30 คำ ---
    { thai: "ใน / ข้างใน", target: "안에", reading: "อาเน", lang: "ko-KR" },
    { thai: "บน / ข้างบน", target: "위에", reading: "วีเอ", lang: "ko-KR" },
    { thai: "ที่", target: "에 / 에서", reading: "เอ / เอซอ", lang: "ko-KR" },
    { thai: "โดย / ด้วย", target: "의해 / 로", reading: "อึยแฮ / 로", lang: "ko-KR" },
    { thai: "สำหรับ / เพื่อ", target: "위해", reading: "วีแฮ", lang: "ko-KR" },
    { thai: "กับ / ด้วย", target: "와 / 과 / 함께", reading: "วา / กวา / ฮัมเก", lang: "ko-KR" },
    { thai: "เกี่ยวกับ", target: "대해", reading: "แทแฮ", lang: "ko-KR" },
    { thai: "ต่อต้าน / แข่งกับ", target: "반대하여", reading: "พันแดฮายอ", lang: "ko-KR" },
    { thai: "ระหว่าง (สองสิ่ง)", target: "사이에", reading: "ซาอีเอ", lang: "ko-KR" },
    { thai: "เข้าไปใน", target: "안으로", reading: "อานือโร", lang: "ko-KR" },
    { thai: "ทะลุผ่าน", target: "통해", reading: "ทงแฮ", lang: "ko-KR" },
    { thai: "ระหว่าง (เวลา)", target: "동안", reading: "ทงอัน", lang: "ko-KR" },
    { thai: "ก่อน", target: "전에", reading: "ชอเน", lang: "ko-KR" },
    { thai: "หลังจาก", target: "후에", reading: "ฮูเอ", lang: "ko-KR" },
    { thai: "เหนือ / สูงกว่า", target: "위에", reading: "วีเอ", lang: "ko-KR" },
    { thai: "ใต้ / ต่ำกว่า", target: "아래에", reading: "อา래เอ", lang: "ko-KR" },
    { thai: "จาก", target: "부터 / 에서", reading: "พูทอ / เอซอ", lang: "ko-KR" },
    { thai: "ขึ้น", target: "위로", reading: "วีโร", lang: "ko-KR" },
    { thai: "ลง", target: "아래로", reading: "아래โร", lang: "ko-KR" },
    { thai: "ออก / ข้างนอก", target: "밖으로", reading: "พากือโร", lang: "ko-KR" },
    { thai: "และ", target: "그리고", reading: "คือรีโก", lang: "ko-KR" },
    { thai: "แต่", target: "하지만", reading: "ฮาจีมัน", lang: "ko-KR" },
    { thai: "หรือ", target: "또는", reading: "โตนึน", lang: "ko-KR" },
    { thai: "เพราะว่า", target: "왜냐하면", reading: "แวนยาฮามยอน", lang: "ko-KR" },
    { thai: "ถ้า / หาก", target: "만약", reading: "มานยัก", lang: "ko-KR" },
    { thai: "ดังนั้น", target: "그래서", reading: "คือ래ซอ", lang: "ko-KR" },
    { thai: "แม้ว่า", target: "비록 ~일지라도", reading: "พีรก ~อิลจีราโด", lang: "ko-KR" },
    { thai: "จนกระทั่ง", target: "까지", reading: "กาจี", lang: "ko-KR" },
    { thai: "เว้นแต่ว่า", target: "않는 한", reading: "อันนึน ฮัน", lang: "ko-KR" },
    { thai: "ตั้งแต่ / เนื่องจาก", target: "이후로", reading: "อีฮูโร", lang: "ko-KR" },

    // --- 33. หมวดคำวิเศษณ์บอกเวลา สถานที่ และความถี่ (Common Adverbs) - 30 คำ ---
    { thai: "เสมอ / ตลอด", target: "항상", reading: "ฮังซัง", lang: "ko-KR" },
    { thai: "มักจะ / เป็นประจำ", target: "보통", reading: "โพทง", lang: "ko-KR" },
    { thai: "บ่อยๆ", target: "자주", reading: "ชาจู", lang: "ko-KR" },
    { thai: "บางครั้ง", target: "가끔", reading: "คากึม", lang: "ko-KR" },
    { thai: "ไม่เคย", target: "결코 ~않다", reading: "คยอลโค ~อันทา", lang: "ko-KR" },
    { thai: "มาก", target: "매우 / 아주", reading: "แมอู / อาจู", lang: "ko-KR" },
    { thai: "เกินไป / ก็ด้วย", target: "너무 / 또한", reading: "นอมู / โตฮัน", lang: "ko-KR" },
    { thai: "ค่อนข้าง", target: "꽤", reading: "กแว", lang: "ko-KR" },
    { thai: "จริงๆ / อย่างแท้จริง", target: "정말로", reading: "ชองมัล로", lang: "ko-KR" },
    { thai: "อย่างแน่นอน / เป๊ะ", target: "정확히", reading: "ชองฮวักฮี", lang: "ko-KR" },
    { thai: "เกือบจะ", target: "거의", reading: "คออึย", lang: "ko-KR" },
    { thai: "เรียบร้อยแล้ว", target: "이미", reading: "อีมี", lang: "ko-KR" },
    { thai: "ยังคง", target: "여전히", reading: "ยอจอนฮี", lang: "ko-KR" },
    { thai: "ยัง (รูปปฏิเสธ/คำถาม)", target: "아직", reading: "아직", lang: "ko-KR" },
    { thai: "เพิ่งจะ / แค่", target: "방금 / 단지", reading: "พังกึม / ทันจี", lang: "ko-KR" },
    { thai: "เท่านั้น / เพียงแค่", target: "오직", reading: "오직", lang: "ko-KR" },
    { thai: "บางที", target: "아마도", reading: "아마도", lang: "ko-KR" },
    { thai: "อาจจะ", target: "어쩌면", reading: "ออจอมยอน", lang: "ko-KR" },
    { thai: "ทันทีทันใด", target: "갑자기", reading: "คับจ지", lang: "ko-KR" },
    { thai: "อย่างรวดเร็ว", target: "빨리", reading: "ปัลลี", lang: "ko-KR" },
    { thai: "อย่างช้าๆ", target: "천천히", reading: "ชอนชอนฮี", lang: "ko-KR" },
    { thai: "อย่างระมัดระวัง", target: "조심스럽게", reading: "โชชิมซือรอบเก", lang: "ko-KR" },
    { thai: "อย่างง่ายดาย", target: "쉽게", reading: "ชวิบ게", lang: "ko-KR" },
    { thai: "ดี (คำวิเศษณ์)", target: "잘", reading: "ชัล", lang: "ko-KR" },
    { thai: "ที่นี่", target: "여기", reading: "ยอกี", lang: "ko-KR" },
    { thai: "ที่นั่น", target: "거기", reading: "คอกี", lang: "ko-KR" },
    { thai: "ทุกที่", target: "모든 곳", reading: "모든 곳", lang: "ko-KR" },
    { thai: "บางที่", target: "어딘가", reading: "ออดินกา", lang: "ko-KR" },
    { thai: "ไม่มีที่ไหน", target: "아무데도", reading: "อามู데도", lang: "ko-KR" },
    { thai: "ที่ไหนก็ได้", target: "어디든", reading: "어디든", lang: "ko-KR" },

    // --- 34. หมวดปริมาณ ขนาด และการวัด (Quantities & Measurements) - 25 คำ ---
    { thai: "ทั้งหมด", target: "모두", reading: "모두", lang: "ko-KR" },
    { thai: "บ้าง / บางส่วน", target: "약간 / 일부", reading: "ยักกัน / อิลบู", lang: "ko-KR" },
    { thai: "บ้าง (รูปปฏิเสธ/คำถาม)", target: "어떤", reading: "ออตอน", lang: "ko-KR" },
    { thai: "มาก (นับได้)", target: "많은", reading: "มานึน", lang: "ko-KR" },
    { thai: "มาก (นับไม่ได้)", target: "많은", reading: "มานึน", lang: "ko-KR" },
    { thai: "น้อย (นับได้)", target: "적은", reading: "ชอกึน", lang: "ko-KR" },
    { thai: "น้อย (นับไม่ได้)", target: "거의 없는", reading: "คออึย 없는", lang: "ko-KR" },
    { thai: "ชิ้น", target: "조각 / 개", reading: "โชกัก / 개", lang: "ko-KR" },
    { thai: "แผ่น / ชิ้นบางๆ", target: "얇은 조각", reading: "ยัลบึน โชกัก", lang: "ko-KR" },
    { thai: "หยด", target: "방울", reading: "พางุล", lang: "ko-KR" },
    { thai: "ปอนด์ (น้ำหนัก)", target: "파운드", reading: "파운드", lang: "ko-KR" },
    { thai: "กิโลกรัม", target: "킬로그램", reading: "คิล로그램", lang: "ko-KR" },
    { thai: "เมตร", target: "미터", reading: "มีทอ", lang: "ko-KR" },
    { thai: "ลิตร", target: "리터", reading: "리터", lang: "ko-KR" },
    { thai: "โหล (12 ชิ้น)", target: "다스", reading: "다스", lang: "ko-KR" },
    { thai: "ครึ่ง", target: "절반", reading: "ชอล반", lang: "ko-KR" },
    { thai: "หนึ่งในสี่", target: "4분의 1", reading: "사분의 일", lang: "ko-KR" },
    { thai: "ยอดรวม", target: "총계 / 합계", reading: "ชงคเย / ฮับคเย", lang: "ko-KR" },
    { thai: "จำนวน / ปริมาณ (นับไม่ได้)", target: "양", reading: "ยัง", lang: "ko-KR" },
    { thai: "ตัวเลข / จำนวน (นับได้)", target: "숫자 / 수", reading: "ซุดจา / ซู", lang: "ko-KR" },
    { thai: "น้ำหนัก", target: "무게", reading: "มูเก", lang: "ko-KR" },
    { thai: "ความยาว", target: "길이", reading: "คิล리", lang: "ko-KR" },
    { thai: "ความสูง", target: "높이", reading: "โน피", lang: "ko-KR" },
    { thai: "ความลึก", target: "깊이", reading: "คี피", lang: "ko-KR" },
    { thai: "ความกว้าง", target: "너비", reading: "너비", lang: "ko-KR" },

    // --- 35. หมวดจักรวาล วิทยาศาสตร์ และธรรมชาติ (Universe & Basic Science) - 15 คำ ---
    { thai: "จักรวาล", target: "우주", reading: "อู주", lang: "ko-KR" },
    { thai: "ดาราจักร / กาแล็กซี", target: "은하", reading: "อึนฮา", lang: "ko-KR" },
    { thai: "ดาวเคราะห์", target: "행성", reading: "แฮงซอง", lang: "ko-KR" },
    { thai: "อวกาศ / พื้นที่ว่าง", target: "우주 공간", reading: "อู주 คงกัน", lang: "ko-KR" },
    { thai: "อะตอม", target: "원자", reading: "วอนจา", lang: "ko-KR" },
    { thai: "พลังงาน", target: "에너지", reading: "에너지", lang: "ko-KR" },
    { thai: "แรงโน้มถ่วง", target: "중력", reading: "중력", lang: "ko-KR" },
    { thai: "ฟิสิกส์", target: "물리학", reading: "มุลลีฮัก", lang: "ko-KR" },
    { thai: "เคมี", target: "화학", reading: "ฮวาฮัก", lang: "ko-KR" },
    { thai: "ชีววิทยา", target: "생물학", reading: "생물학", lang: "ko-KR" },
    { thai: "เซลล์", target: "세포", reading: "เซโพ", lang: "ko-KR" },
    { thai: "ธรรมชาติ", target: "자연", reading: "ชายอน", lang: "ko-KR" },
    { thai: "ก๊าซ", target: "가스 / 기체", reading: "카스 / คีเช", lang: "ko-KR" },
    { thai: "ของเหลว", target: "액체", reading: "액체", lang: "ko-KR" },
    { thai: "การทดลอง", target: "실험", reading: "ชิลฮอม", lang: "ko-KR" }
]; // สิ้นสุดอาเรย์ ตัวแปร wordsKR สมบูรณ์ 1,000 คำ